#!/bin/sh
####################################################################
## activateVAP
##
## This script is used to activate a VAP that was created earlier.
## Activation involves bringing the interface up, associating with
## a bridge, and configuring the security mode.  The VAP MUST EXIST
## prior to calling the activate script.
##
## The form of the command is
##
## activateVAP <vap> <BR> <Security> <SEC Args> <WSC>  <VAP_TIE>
##
## Where
##      vap:    Vap ID (e.g. ath0)
##       BR:    Bridge to join (or - if not bridged)
## Security:    Security mode (WEP,WPA,WSC,NONE)
## Sec Args:    File containing security configuration.  For WPA this is the hostapd
##              conf file.  For WEP this is a list of iwconfig commands setting the
##              keys.
##
## Examples:
##   Open Access Point
##      activateVAP ath0 br0 NONE
##   WPA Access Point
##      activateVAP ath1 br0 WPA wpa2-psk.conf
##   WEP Station
##      activateVAP ath0 br0 WEP wep.conf
##
###################################################################


#+++ Alphanetworks: hendry. 
. /etc/ath/apcfg_alpha
#--- Alphanetworks: hendry. 

if [ "${1}" = "" ]; then
    echo "activateVAP usage"
    echo "activateVAP VAPid:Radio bridge Security Security_file"
    echo
    echo "vapid: e.g. ath0"
    echo "bridge:  Name of bridge to add to,(typically br0)"
    echo "Security: [ WPA | WEP | WSC | NONE ]"
    echo "Security_file: Name of file in /etc/ath containing security config"
    echo
    exit
fi

BRIDGE=$2
SECMODE=$3
SECFILE=$4
WSCMODE=$5
VAPTIE=$6

APNAME=`echo $1 | cut -d ':' -f 1`
RADIO=`echo $1 | cut -d ':' -f 2`

if [ "$RADIO" = "" ]; then
    RADIO="0"
fi

KVER=`uname -r | cut -f 1 -d '-'`
MODULE_PATH=/lib/modules/$KVER/net
MODE=`iwconfig ${APNAME} | grep "Mode:Master"`
HOSTAPD_VER=`hostapd -v 2>&1|grep hostapd|cut -f2 -d' '`

if [ "${HOSTAPD_VER}" != "v0.5.9" ]; then
    if [ "${SECMODE}" = "WEP" -a "${WSCMODE}" != "0" ]; then
        echo "*** WARNING: WPS is enabled in WEP mode!! ***"
        echo "*** WARNING: WPS is disabled  ***"
        WSCMODE=0
    fi

    if [ "${SECMODE}" = "WPA" -a "${WSCMODE}" != "0" ]; then
        if [ "${AP_CYPHER}" = "TKIP" ]; then
            echo "*** WARNING: AP_SSID - WPS is enabled in TKIP only mode!! ***"
            echo "*** WARNING: WPS has been disabled  ***"
            WSCMODE=0
        fi

        i=2
        while [ $i -le 15 ]
        do
            istkip=`eval expr match '$'AP_CYPHER_$i 'TKIP$' 2>/dev/null`
            istkip=${istkip:="0"}
            isssid=`eval expr length '$'AP_SSID_$i 2>/dev/null`
            isssid=${isssid:="0"}
            if [ "${isssid}" != "0" -a "${istkip}" != "0" ]; then
                echo "*** WARNING: AP_SSID_$i - WPS is enabled in TKIP only mode!! ***"
                echo "*** WARNING: WPS has been disabled  ***"
                WSCMODE=0
            fi
            i=`expr $i + 1`
        done
    fi
fi

if [ "${WSCMODE}" = "1" -o "${WSCMODE}" = "2" ]; then
    if [ "${SECMODE}" != "WPA" ]; then
        echo "*** WARNING: WPS is enabled with No/Incorrect Security settings !! ***"
    fi
fi

if [ "${AP_HIDESSID}" = "1" ]; then
    echo "*** WARNING: invalid config WPS is enabled with hidden ssid !! ***"
    echo "*** WARNING: WPS is disabled  ***"
    WSCMODE=0
fi

AP_MODE=`echo $AP_STARTMODE  | cut -f 1 -d '-'`

##
## Create an AP index, based on the VAP (ath) number
##

APINDEX=`echo ${APNAME}| cut -b 4-4`

if [ "$APINDEX" != "0" ]; then
    APINDEX=`expr ${APINDEX} + 1`
fi

##
## First, let us see if the indicated VAP exists.  If not, it must be created
##

#VAPLIST=`iwconfig | grep ${APNAME} | cut -b 1-4`

#if [ "${VAPLIST}" = "" ]; then
#    echo "VAP ${APNAME} must be created first!! (use makeVAP)"
#    exit
#fi

##
## Must determine if the scan modules need to be loaded.  Remember, only once!
## This is in station mode if the MODE value is blank
##

STATIONSCAN=`lsmod | grep wlan_scan_sta`

if [ "${MODE}" = "" -a "${STATIONSCAN}" = "" ]; then
    
    #
    # Check for a specific MAC address that is specified.  Only valid for stations
    #

    if [ "${AP_REQ_MAC}" != "" ]; then
        iwconfig $APNAME ap $AP_REQ_MAC
    fi
fi

#
# Bring the interface up at this point!!
# configure bridge, or set an IP address for the WLAN interface
#

if [ "${BRIDGE}" != "none" -a "${BRIDGE}" != "-" ]; then
    ifconfig ${APNAME} up
    brctl addif ${BRIDGE} ${APNAME}
    
    #+++ Alphanetworks: hendry
    #echo -e "\tinterface ${APNAME}" >> /tmp/${BRIDGE}
    #--- Alphanetworks: hendry    
    
    #
    # Add the arping command to ensure all nodes are updated on the network!
    #
    
    #+++ Alphanetworks: hendry
    #arping -U -c 1 -I ${BRIDGE} $AP_IPADDR
	#--- Alphanetworks: hendry    

else
    ifconfig ${APNAME} up ${WAN_IPADDR}
fi
