#!/bin/sh
##
## Compatability scripts for older versions
##
. /etc/ath/apcfg

if [ "${ICM_ENABLE}" -eq "1" ]; then
    killall icm
fi

WPS_LED_OFF=1
echo $WPS_LED_OFF  > /proc/simple_config/simple_config_led  

KER_VER_31=`set | uname -a | grep -c "2.6.31"`
if [ "${KER_VER_31}" = 1 ]; then
    pktlogconf -d
fi


killVAP all
#Finally, unload all modules
sleep 3
if [ "${AP_CONF_ACFG}"  -eq "1" ]; then
	prepareACFG unload
fi
/etc/rc.d/rc.wlan down

export WAN_IF=eth0
export LAN_IF=eth1

ifconfig $WAN_IF up
ifconfig $LAN_IF up
/etc/rc.d/rc.network
/etc/rc.d/rc.bridge

rm -f /tmp/.apup
