{
	// Menu
	"Home": "Home",
	"Settings": "Settings",
	"Advanced": "Advanced",
	"Management": "Management",
	"Internet(WAN)": "Internet",
	"Wireless(Wi-Fi)": "Wireless",
	"Network(LAN)": "Network",
	"SharePort": "SharePort",
	"mydlink": "mydlink",
	"Firewall Setting": "Firewall Setting",
	"Virtual Server": "Virtual Server",
	"Port Forwarding": "Port Forwarding",
	"Website Filter": "Website Filter",
	"Static Route": "Static Route",
	"Disabled": "Disabled",
	"Enabled": "Enabled",
	
	// Genernal
	"There is unsaved data on this page. Do you want to abandon it?": "There is unsaved data on this page. Do you want to abandon it?",
	"Remaining": "Remaining",
	
	// Login
	"Model Name": "Model Name",
	"Hardware Version": "Hardware Version",
	"Firmware Version": "Firmware Version",
	"Language": "Language",
	"Admin Password": "Admin Password",
	"Log In": "Log In",
	"To access your storage with SharePort Web Access,": "To access your storage with SharePort Web Access,",
	"click here.": "click here.",
	"The Private Browsing feature of Safari is incompatible with this device's interface. You will need to disable Private Browsing to log in.": "The Private Browsing feature of Safari is incompatible with this device's interface. You will need to disable Private Browsing to log in.",
	"Invalid password, please try again.": "Invalid password, please try again.",
	
	// Home
	"Current Status": "Current Status",
	"Click on any item in the diagram for more information.": "Click on any item in the diagram for more information.",
	"Setup Wizard": "Setup Wizard",
	"Router": "Router",
	"Internet": "Internet",
	"LAN": "LAN",
	"Router IP Address": "Router IP Address",
	"MAC Address": "MAC Address",
	"Wi-Fi 2.4GHz": "Wi-Fi 2.4GHz",
	"Wi-Fi 5GHz": "Wi-Fi 5GHz",
	"Guest Zone 2.4GHz": "Guest Zone 2.4GHz",
	"Guest Zone 5GHz": "Guest Zone 5GHz",
	"IP Address": "IP Address",
	"Subnet Mask": "Subnet Mask",
	"Default Gateway": "Default Gateway",
	"Available Space": "Available Space",
	"Total Space": "Total Space",
	"Service Name": "Service Name",
	"Ethernet Device": "Ethernet Device",
	"Wi-Fi Clients": "Wi-Fi Clients",
	"USB Device": "USB Device",
	"USB Name": "USB Name",
	"Status": "Status",
	"Wi-Fi Name (SSID)": "Wi-Fi Name (SSID)",
	"Password": "Password",
	"IPv6 Connection Type": "IPv6 Connection Type",
	"WAN IPv6 Address": "WAN IPv6 Address",
	"Primary IPv6 DNS Server": "Primary IPv6 DNS Server",
	"Secondary IPv6 DNS Address": "Secondary IPv6 DNS Address",
	"LAN IPv6 Link-Local Address": "LAN IPv6 Link-Local Address",
	"DHCP-PD": "DHCP-PD",
	"IPv6 Network Assigned by DHCP-PD": "IPv6 Network Assigned by DHCP-PD",
	"LAN IPv6 Address": "LAN IPv6 Address",
	"Guest Zone": "Guest Zone",
	"Connection Type": "Connection Type",
	"Network Status": "Network Status",
	"Connection Up Time": "Connection Up Time",
	"Primary DNS Server": "Primary DNS Server",
	"Secondary DNS Server": "Secondary DNS Server",
	"SharePort": "SharePort",
	"Release": "Release",
	"Renew": "Renew",
	"Disconnect": "Disconnect",
	"Connect": "Connect",
	"Ignore": "Ignore",
	"Connected": "Connected",
	"Connecting": "Connecting",
	"Disconnected": "Disconnected",
	"DHCP": "Dynamic IP (DHCP)",
	"Static": "Static IP (Static)",
	"DHCPPPPoE": "Dynamic IP (PPPoE)",
	"StaticPPPoE": "Static IP (PPPoE)",
	"DynamicPPTP": "Dynamic IP (PPTP)",
	"StaticPPTP": "Static IP (PPTP)",
	"DynamicL2TP": "Dynamic IP (L2TP)",
	"StaticL2TP": "Static IP (L2TP)",
	"A new firmware is available! Do you want to download and upgrade the firmware?": "A new firmware is available! Do you want to download and upgrade the firmware?",
	"Your changes are being saved, and the device will need to reboot.": "Your changes are being saved, and the device will need to reboot.",
	"The Wi-Fi connection is not secure.": "The Wi-Fi connection is not secure.",
	"Secure your network.": "Secure your network.",
	
	// Wizard
	"Welcome": "Welcome",
	"This wizard will guide you through a step-by-step process to configure your new D-Link device.": "This wizard will guide you through a step-by-step process to configure your new D-Link device.",
	"Step1: Install your device": "Step1: Install your device",
	"Step2: Configure your Network and Wi-Fi settings": "Step2: Configure your Network and Wi-Fi settings",
	"Step3: Set your router password": "Step3: Set your router password",
	"Step4: Set mydlink service": "Step4: Set mydlink service",
	"Your Device": "Your Device",
	"Cable/xDSL Broadband Modem": "Cable/xDSL Broadband Modem",
	"DHCP Connection (Dynamic IP Address)": "DHCP Connection (Dynamic IP Address)",
	"Choose this if your Internet connection automatically provides you with an IP Address. Most Cable Modems use this type of connection.": "Choose this if your Internet connection automatically provides you with an IP Address. Most Cable Modems use this type of connection.",
	"Username/Password Connection (PPPoE)": "Username/Password Connection (PPPoE)",
	"Choose this option if your Internet connection reguires a username and passowrd to get online. Most DSL modems use this connection type of connection.": "Choose this option if your Internet connection reguires a username and passowrd to get online. Most DSL modems use this connection type of connection.",
	"Static IP Address Connection": "Static IP Address Connection",
	"Choose this option if your Internet Setup Provider provided you with IP Address information that has to be manually configured.": "Choose this option if your Internet Setup Provider provided you with IP Address information that has to be manually configured.",
	"Username": "Username",
	"Gateway Address": "Gateway Address",
	"Primary DNS Address": "Primary DNS Address",
	"Secondary DNS Address": "Secondary DNS Address",
	"2.4GHz Wi-Fi Network Name": "2.4GHz Wi-Fi Network Name",
	"5GHz Wi-Fi Network Name": "5GHz Wi-Fi Network Name",
	"The Wi-Fi Network Name is up to 32 characters. You will need to join your Wi-Fi network using this Network Name (SSID).": "The Wi-Fi Network Name is up to 32 characters. You will need to join your Wi-Fi network using this Network Name (SSID).",
	"Wi-Fi Password": "Wi-Fi Password",
	"Copy to 5GHz": "Copy to 5GHz",
	"2.4GHz Wi-Fi Password": "2.4GHz Wi-Fi Password",
	"5GHz Wi-Fi Password": "5GHz Wi-Fi Password",
	"The password must contain at least 8 characters. You will need to join your Wi-Fi network using this password.": "The password must contain at least 8 characters. You will need to join your Wi-Fi network using this password.",
	"Device Admin Password": "Device Admin Password",
	"This device is mydlink-enabled, which allows you to remotely monitor and manage your network through the mydlink.com website, or through the mydlink mobile app.": "This device is mydlink-enabled, which allows you to remotely monitor and manage your network through the mydlink.com website, or through the mydlink mobile app.",
	"You can register this device with your existing mydlink account. If you do not have one, you can create one now.": "You can register this device with your existing mydlink account. If you do not have one, you can create one now.",
	"Do you have an existing mydlink account": "Do you have an existing mydlink account",
	"Yes, I have a mydlink account": "Yes, I have a mydlink account",
	"No, I want to create a new mydlink account": "No, I want to create a new mydlink account",
	"E-mail Address (Account Name)": "E-mail Address (Account Name)",
	"First Name": "First Name",
	"Last Name": "Last Name",
	"I accept the mydlink": "I accept the mydlink",
	"terms and conditions.": "terms and conditions.",
	"Connect to the Wi-Fi network from your mobile device or PC": "Connect to the Wi-Fi network from your mobile device or PC",
	"1.Please go to Settings > Wi-fi, and choose": "1.Please go to Settings > Wi-fi, and choose",
	"from the list of Wi-Fi network services.": "from the list of Wi-Fi network services.",
	"2.Enter the password you just setup when prompted.": "2.Enter the password you just setup when prompted.",
	"Checking Internet connectivity": "Checking Internet connectivity",
	"Wi-Fi Client": "Wi-Fi Client",
	"Save": "Save",
	"Please wait": "Please wait",
	"Configure Your Internet Connection": "Configure Your Internet Connection",
	"Detecting Internet connection": "Detecting Internet connection",
	"Install": "Install",
	"Please plug one end of the Ethernet cable included with your device into the port labeled INTERNET on your device. Plug the other end of this cable into the Ethernet port on yourDSL or cable broadband modem, and power cycle the modem.": "Please plug one end of the Ethernet cable included with your device into the port labeled INTERNET on your device. Plug the other end of this cable into the Ethernet port on yourDSL or cable broadband modem, and power cycle the modem.",
	"Please select your Internet connection type below": "Please select your Internet connection type below:",
	"PPPoE": "PPPoE",
	"To setup this Internet connection, you will need to have a User Name from your InternetService Provider. If you do not have this information, please contact your ISP.": "To setup this Internet connection, you will need to have a User Name from your InternetService Provider. If you do not have this information, please contact your ISP.",
	"Static IP": "Static IP",
	"Dynamic IP (DHCP)": "Dynamic IP (DHCP)",
	"To set up this conncetion you will need to have a complete list of IP information by your Internet Service Provider. If you have a Static IP connection and do not have this information, please contact your ISP.": "To set up this conncetion you will need to have a complete list of IP information by your Internet Service Provider. If you have a Static IP connection and do not have this information, please contact your ISP.",
	"Wi-Fi Settings": "Wi-Fi Settings",
	"To setup a Wi-Fi Network you will need to give your Wi-Fi Nerwork a Name(SSID) and Password.": "To setup a Wi-Fi Network you will need to give your Wi-Fi Nerwork a Name(SSID) and Password.",
	"By default, your new D-Link device does not have a password configured for administrator access to the Web-based configuration utility. To secure your new device, please create a password below.": "By default, your new D-Link device does not have a password configured for administrator access to the Web-based configuration utility. To secure your new device, please create a password below.",
	"Setup Complete": "Setup Complete",
	"Below is a summary of your Wi-Fi security and device password settings.Please take a note of your settings and save your configuration.": "Below is a summary of your Wi-Fi security and device password settings.Please take a note of your settings and save your configuration.",
	"Checking Your Internet connectivity": "Checking Your Internet connectivity",
	"Checking Internet connectivity": "Checking Internet connectivity",
	"mydlink Regristration": "mydlink Regristration",
	"Congratulations": "Congratulations",
	"Congratulations,your device has been configured. You can now connect to your Wi-Fi network by using the new Wi-Fi Network Name and Password you created.": "Congratulations,your device has been configured. You can now connect to your Wi-Fi network by using the new Wi-Fi Network Name and Password you created.",
	"Back": "Back",
	"Next": "Next",
	"Skip": "Skip",
	"Finish": "Finish",
	"Registered": "Registered",
	"Unregistered": "Unregistered",
	
	// Ethernet, Wireless, Wireless_Guest
	"Wi-Fi Clients (Guest Zone)": "Wi-Fi Clients (Guest Zone)",
	"Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.",
	"Here, you can see a list of all devices connected through Wi-Fi. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Here, you can see a list of all devices connected through Wi-Fi. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.",
	"Vendor": "Vendor",
	"Reserve IP": "Reserve IP",
	"Access": "Access",
	"Allowed": "Allowed",
	"Blocked": "Blocked",
	
	// Internet > IPv4
	"Use this section to configure your Internet Connection type. There are several connection types to choose from Static IP, DHCP, PPPoE, PPTP, L2TP, and DS-Lite. If you are unsure of your connection method, please contact your Internet Service Provider. Note:  If using the PPPoE option, you will need to remove or disable any PPPoE client software on your computers.": "Use this section to configure your Internet Connection type. There are several connection types to choose from Static IP, DHCP, PPPoE, PPTP, L2TP, and DS-Lite. If you are unsure of your connection method, please contact your Internet Service Provider. Note:  If using the PPPoE option, you will need to remove or disable any PPPoE client software on your computers.",
	"My Internet Connection is": "My Internet Connection is",
	"Host Name": "Host Name",
	"Mac Address Clone": "Mac Address Clone",
	"PPTP IP Address": "PPTP IP Address",
	"PPTP Server IP Address": "PPTP Server IP Address",
	"PPTP Subnet Mask": "PPTP Subnet Mask",
	"PPTP Gateway IP Address": "PPTP Gateway IP Address",
	"L2TP IP Address": "L2TP IP Address",
	"L2TP Server IP Address": "L2TP Server IP Address",
	"L2TP Subnet Mask": "L2TP Subnet Mask",
	"L2TP Gateway IP Address": "L2TP Gateway IP Address",
	"MTU": "MTU",
	"Address Mode": "Address Mode",
	"Reconnect Mode": "Reconnect Mode",
	"Maximum Idle Time": "Maximum Idle Time",
	"DS-Lite Configuration": "DS-Lite Configuration",
	"DS-Lite DHCPv6 Option": "DS-Lite DHCPv6 Option",
	"Manual Configuration": "Manual Configuration",
	"AFTR IPv6 Address": "AFTR IPv6 Address",
	"B4 IPv4 Address": "B4 IPv4 Address",
	"WAN IPv6 Address": "WAN IPv6 Address",
	"IPv6 WAN Default Gateway": "IPv6 WAN Default Gateway",
	"Advanced Settings": "Advanced Settings",
	"Manual": "Manual",
	"Always on": "Always on",
	"On demand": "On demand",
	"Dynamic IP": "Dynamic IP",
	
	// Internet > IPv6
	"All of your IPv6 Internet and network connection details are displayed on this page.": "All of your IPv6 Internet and network connection details are displayed on this page.",
	"Auto Detection": "Auto Detection",
	"Static IPv6": "Static IPv6",
	"Auto Configuration (SLAAC/DHCPv6)": "Auto Configuration (SLAAC/DHCPv6)",
	"IPv6 in IPv4 Tunnel": "IPv6 in IPv4 Tunnel",
	"6to4": "6to4",
	"Local Connectivity Only": "Local Connectivity Only",
	"Use Link-Local Address": "Use Link-Local Address",
	"Subnet Prefix Length": "Subnet Prefix Length",
	"PPPoE Session": "PPPoE Session",
	"Remote IPv4 Address": "Remote IPv4 Address",
	"Remote IPv6 Address": "Remote IPv6 Address",
	"Local IPv4 Address": "Local IPv4 Address",
	"Local IPv6 Address": "Local IPv6 Address",
	"6to4 Address": "6to4 Address",
	"6to4 Relay": "6to4 Relay",
	"Assign IPv6 Prefix": "Assign IPv6 Prefix",
	"LAN IPv6 Link-Local Address": "LAN IPv6 Link-Local Address",
	"IPv6 DNS SETTINGS": "IPv6 DNS SETTINGS",
	"LAN IPv6 ADDRESS SETTINGS": "LAN IPv6 ADDRESS SETTINGS",
	"LAN IPv6 Address": "LAN IPv6 Address",
	"ADDRESS AUTOCONFIGURATION SETTINGS": "ADDRESS AUTOCONFIGURATION SETTINGS",
	"Enable Automatic IPv6 Address Assignment": "Enable Automatic IPv6 Address Assignment",
	"Enable Automatic DHCP-PD in LAN": "Enable Automatic DHCP-PD in LAN",
	"Autoconfiguration Type": "Autoconfiguration Type",
	"Enable DHCP-PD": "Enable DHCP-PD",
	"6RD MANUAL CONFIGURATION": "6RD MANUAL CONFIGURATION",
	"Enable Hub and Spoke Mode": "Enable Hub and Spoke Mode",
	"6rd Configuration": "6rd Configuration",
	"6rd IPv6 Prefix": "6rd IPv6 Prefix",
	"6rd Border Relay IPv4 Address": "6rd Border Relay IPv4 Address",
	"IPv6 ULA SETTINGS": "IPv6 ULA SETTINGS",
	"Enable ULA": "Enable ULA",
	"Use Default ULA Prefix": "Use Default ULA Prefix",
	"ULA Prefix": "ULA Prefix",
	"CURRENT IPv6 ULA SETTINGS": "CURRENT IPv6 ULA SETTINGS",
	"Current ULA Prefix": "Current ULA Prefix",
	"LAN IPv6 ULA": "LAN IPv6 ULA",
	"minutes": "minutes",
	"DNS Type": "DNS Type",
	"Obtain a DNS server address automatically": "Obtain a DNS server address automatically",
	"Use the following DNS address": "Use the following DNS address",
	"SLAAC+Stateless DHCP": "SLAAC+Stateless DHCP",
	"Stateful DHCPv6": "Stateful DHCPv6",
	"6rd DHCPv4 Option": "6rd DHCPv4 Option",
	"Share with IPv4": "Share with IPv4",
	"Create a new session": "Create a new session",
	"bytes": "bytes",
	"Router Advertisement Lifetime": "Router Advertisement Lifetime",
	"IPv6 Address Range (Start)": "IPv6 Address Range (Start)",
	"IPv6 Address Range (End)": "IPv6 Address Range (End)",
	"IPv6 Address Lifetime": "IPv6 Address Lifetime",
	
	// WiFi & Guest Zone
	"Security Mode": "Security Mode",
	"None": "None",
	"WPA-Personal": "WPA-Personal",
	"Auto": "Auto",
	"High": "High",
	"Low": "Low",
	"802.11 Mode": "802.11 Mode",
	"Wi-Fi Channel": "Wi-Fi Channel",
	"Transmission Power": "Transmission Power",
	"Channel Width": "Channel Width",
	"Visibility Status": "Visibility Status",
	"Visible": "Visible",
	"Invisible": "Invisible",
	"Mixed 802.11b/g": "Mixed 802.11b/g",
	"Mixed 802.11g/n": "Mixed 802.11g/n",
	"Mixed 802.11b/g/n": "Mixed 802.11b/g/n",
	"Auto 20/40 MHz": "Auto 20/40 MHz",
	"Mixed 802.11a and 802.11n": "Mixed 802.11a/n",
	"Use this section to configure the wireless settings for your D-Link Router. Please note that changes made on this section may also need to be duplicated on your Wireless Client.": "Use this section to configure the wireless settings for your D-Link Router. Please note that changes made on this section may also need to be duplicated on your Wireless Client.",
	"This page lets you configure a Wi-Fi Guest Zone. Wi-Fi Guest Zones are Wi-Fi networks that are separate from your normal ones, and use different Wi-Fi Network Names and passwords. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless the Access Local Service option is enabled. Guest Zones are useful to give guests Internet access without allowing them to access your own devices on your network.": "This page lets you configure a Wi-Fi Guest Zone. Wi-Fi Guest Zones are Wi-Fi networks that are separate from your normal ones, and use different Wi-Fi Network Names and passwords. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless the Access Local Service option is enabled. Guest Zones are useful to give guests Internet access without allowing them to access your own devices on your network.",
	"Internet Access Only": "Internet Access Only",
	"Routing Between Zones": "Routing Between Zones",
	"Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.": "Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.",
	"Your changes are being saved.": "Your changes are being saved.",
	
	// Network
	"Network": "Network",
	"Network Settings": "Network Settings",
	"DHCP Server": "DHCP Server",
	"Use this page to configure the local network settings for your router, including the IP address you use to access this configuration interface. Please note that if you change this IP address, you will need to use the new IP to access this interface.": "Use this page to configure the local network settings for your router, including the IP address you use to access this configuration interface. Please note that if you change this IP address, you will need to use the new IP to access this interface.",
	"LAN IP Address": "LAN IP Address",
	"Device Name": "Device Name",
	"Local Domain Name": "Local Domain Name",
	"Enable DNS Relay": "Enable DNS Relay",
	"DHCP IP Address Range": "DHCP IP Address Range",
	"DHCP Lease Time": "DHCP Lease Time",
	"Always Broadcast": "Always Broadcast",
	"compatibility for some DHCP Clients": "(compatibility for some DHCP Clients)",
	"If you changed the IP address of the router you will need to change the IP address in your browser before accessing the configuration website again.": "If you changed the IP address of the router you will need to change the IP address in your browser before accessing the configuration website again.",
	"The new settings have been saved.": "The new settings have been saved.",
	"to": "to",
	
	// Advanced Network
	"Advanced Network": "Advanced Network",
	"Advanced Network settings allow you to configure some of the more advanced features of your router. It is recommended that you only change these settings if you are  familiar with them, or if you are specifically instructed to do so.": "Advanced Network settings allow you to configure some of the more advanced features of your router. It is recommended that you only change these settings if you are  familiar with them, or if you are specifically instructed to do so.",
	"UPnP": "UPnP",
	"WAN Port Speed": "WAN Port Speed",
	"IPv4 Multicast Streams": "IPv4 Multicast Streams",
	"IPv6 Multicast Streams": "IPv6 Multicast Streams",
	"Auto (10/100/1000 Mbps)": "Auto (10/100/1000 Mbps)",
	
	// SharePort
	"SharePort": "SharePort",
	"DLNA (Digital Living Network Alliance) is the standard for the interoperability of Network Media Devices (NMDs). The user can enjoy multi-media applications (music, pictures and videos) on your network connected PC or media devices. Web File Access allows you to use a web browser to remotely access files stored on an SD card or USB storage drive plugged into the router.": "DLNA (Digital Living Network Alliance) is the standard for the interoperability of Network Media Devices (NMDs). The user can enjoy multi-media applications (music, pictures and videos) on your network connected PC or media devices. Web File Access allows you to use a web browser to remotely access files stored on an SD card or USB storage drive plugged into the router.",
	"DLNA Media Server Configuration": "DLNA Media Server Configuration",
	"DLNA Media Server": "DLNA Media Server",
	"Web File Access": "Web File Access",
	"Remote Access Port": "Remote Access Port",
	"Remote HTTPS Port": "Remote HTTPS Port",
	"Enable Storage Remote Access": "Enable Storage Remote Access",
	"Direct Links": "Direct Links",
	"Local Access": "Local Access",
	"SharePort Web Access": "SharePort Web Access",
	
	// SharePort CreateUser
	"\"Create User\" manage access to your storage devices or use the Guest account (guest/guest) to access the Guest Folder. After plugging in an SD card or USB storage drive, the new device will appear in the list with a link to it. You can then use this link to connect the drive and login with a user account.": "\"Create User\" manage access to your storage devices or use the Guest account (guest/guest) to access the Guest Folder. After plugging in an SD card or USB storage drive, the new device will appear in the list with a link to it. You can then use this link to connect the drive and login with a user account.",
	"Remote Access": "Remote Access",
	"Create User": "Create User",
	"User Name": "User Name",
	"Access Path": "Access Path",
	"Permission": "Permission",
	"Edit": "Edit",
	"Delete": "Delete",
	"Browse": "Browse",
	"OK": "OK",
	"Create User": "Create User",
	"Create New User": "Create New User",
	"Edit User Profile": "Edit User Profile",
	"Folder": "Folder",
	"Select Folder": "Select Folder",
	"USB Device Name": "USB Device Name",
	"Number of Device": "Number of Device",
	
	// mydlink
	"Setting and registering your router with mydlink will allow you to use its mydlink cloud services features, including online access and management of your router through the mydlink portal website.": "Setting and registering your router with mydlink will allow you to use its mydlink cloud services features, including online access and management of your router through the mydlink portal website.",
	"mydlink Registration": "mydlink Registration",
	"Sign Up": "Sign Up",
	"Sign In": "Sign In",
	"Please enter your e-mail address and mydlink password.": "Please enter your e-mail address and mydlink password.",
	"You must accept the terms and conditions to continue.": "You must accept the terms and conditions to continue.",
	
	// QoS Engine
	"QoS Engine": "QoS Engine",
	"QoS prioritizes your network traffic so you can decide what devices should have priority over other devices. For example, you could set a computer that is downloading files to have lower priority than a laptop that is streaming movies to ensure that you can stream movies smoothly without downloads taking up all of your bandwidth.": "QoS prioritizes your network traffic so you can decide what devices should have priority over other devices. For example, you could set a computer that is downloading files to have lower priority than a laptop that is streaming movies to ensure that you can stream movies smoothly without downloads taking up all of your bandwidth.",
	"All Devices": "All Devices",
	"Drag the device cards above to the Prioity boxes below.": "Drag the device cards above to the Prioity boxes below.",
	"Highest": "Highest",
	"Medium": "Medium",
	
	// Firewall
	"Firewall Settings": "Firewall Settings",
	"Here, you can set up various firewall features to protect your network from attacks. You can click on the DMZ, IPv4 Rules, and IPv6 Rules buttons to see the settings for that feature.": "Here, you can set up various firewall features to protect your network from attacks. You can click on the DMZ, IPv4 Rules, and IPv6 Rules buttons to see the settings for that feature.",
	"Application Level Gateway (ALG) Configuration": "Application Level Gateway (ALG) Configuration",
	"Enable SPI IPv4": "Enable SPI IPv4",
	"Enable Anti-spoof Checking": "Enable Anti-spoof Checking",
	"IPv6 Simple Security": "IPv6 Simple Security",
	"PPTP": "PPTP",
	"IPSec (VPN)": "IPSec (VPN)",
	"RTSP": "RTSP",
	"SIP": "SIP",
	"IPv4 Rules": "IPv4 Rules",
	"IPv6 Rules": "IPv6 Rules",
	"Firewall": "Firewall",
	"Enable DMZ Host": "Enable DMZ",
	"DMZ IP Address": "DMZ IP Address",
	"Security Check": "Security Check",
	
	// Firewall IPv4, IPv6
	"The IPv4 rule section is an advance feature used to deny or allow traffic from passing through the device.": "The IPv4 rule section is an advance feature used to deny or allow traffic from passing through the device.",
	"The IPv6 rule section is an advance feature used to deny or allow traffic from passing through the device.": "The IPv6 rule section is an advance feature used to deny or allow traffic from passing through the device.",
	"Add Rules": "Add Rules",
	"Name": "Name",
	"Schedule": "Schedule",
	"Create New Rule": "Create New Rule",
	"Source IP Address Range": "Source IP Address Range",
	"Destination IP Address Range": "Destination IP Address Range",
	"Port Range": "Port Range",
	"Turn IPv4 Filtering OFF": "Turn IPv4 Filtering OFF",
	"Turn IPv4 Filtering ON and ALLOW rules listed": "Turn IPv4 Filtering ON and ALLOW rules listed",
	"Turn IPv4 Filtering ON and DENY rules listed": "Turn IPv4 Filtering ON and DENY rules listed",
	"Turn IPv6 Filtering OFF": "Turn IPv6 Filtering OFF",
	"Turn IPv6 Filtering ON and ALLOW rules listed": "Turn IPv6 Filtering ON and ALLOW rules listed",
	"Turn IPv6 Filtering ON and DENY rules listed": "Turn IPv6 Filtering ON and DENY rules listed",
	
	// Port Forwarding
	"Port Forwarding is used to open ports in your router and to redirect traffic to those ports to a specific device on your network. This may be needed for specific applications, games, or services. You can enter individual ports (80, 68, 888), port ranges (100-150), or in a mixed format (1020-5000, 689).": "Port Forwarding is used to open ports in your router and to redirect traffic to those ports to a specific device on your network. This may be needed for specific applications, games, or services. You can enter individual ports (80, 68, 888), port ranges (100-150), or in a mixed format (1020-5000, 689).",
	"Local IP": "Local IP",
	"TCP Port": "TCP Port",
	"UDP Port": "UDP Port",
	
	// Virtual Server
	"The Virtual Server option allows you to define a single public port on your router for redirection to an internal LAN IP Address and Private LAN port if required. This feature is useful for hosting online services such as FTP or Web Servers.": "The Virtual Server option allows you to define a single public port on your router for redirection to an internal LAN IP Address and Private LAN port if required. This feature is useful for hosting online services such as FTP or Web Servers.",
	"Protocol": "Protocol",
	"External Port": "External Port",
	"Internal Port": "Internal Port",
	"Protocol Number": "Protocol Number",
	
	// Website Filter
	"The Website Filter option allows you to set up a list of Web sites you would like to allow or deny through your network. To use this feature, you must also select the \"Apply Web Filter\" checkbox in the Access Control section.": "The Website Filter option allows you to set up a list of Web sites you would like to allow or deny through your network. To use this feature, you must also select the \"Apply Web Filter\" checkbox in the Access Control section.",
	"DENY computers access to ONLY these sites": "DENY computers access to ONLY these sites",
	"ALLOW computers access to ONLY these sites": "ALLOW computers access to ONLY these sites",
	"Website URL/Domain": "Website URL/Domain",
	
	// StaticRouter, StaticRouterIPv6
	"Static Routes": "Static Routes",
	"This page allows you to define custom routes to define how data traffic is moved around your network.": "This page allows you to define custom routes to define how data traffic is moved around your network.",
	"Destination IP": "Destination IP",
	"Netmask": "Netmask",
	"Gateway": "Gateway",
	"Matrix": "Matrix",
	"Interface": "Interface",
	"DestNetwork": "DestNetwork",
	"PrefixLen": "PrefixLen",
	
	// DynamicDNS
   	"Dynamic DNS (DDNS) allows you to use an easy to remember domain name such as www.[YourDomainName].com to reach your router\'s dynamically assigned IP address. This is useful when hosting a web, FTP, or game server, and allows you to reach your server no matter what your IP address has changed to. D-Link offers a free DDNS service that you can use through www.DLinkDDNS.com.": "Dynamic DNS (DDNS) allows you to use an easy to remember domain name such as www.[YourDomainName].com to reach your router\'s dynamically assigned IP address. This is useful when hosting a web, FTP, or game server, and allows you to reach your server no matter what your IP address has changed to. D-Link offers a free DDNS service that you can use through www.DLinkDDNS.com.",
	"Server Address": "Server Address",
	"Dynamic DNS": "Dynamic DNS",
	"Enable Dynamic DNS": "Enable Dynamic DNS",
	"Select Server Name": "Select Server Name",
	"Time Out": "Time Out",
	"IPv6 Address": "IPv6 Address",
	"hours": "hours",
	
	// Time
	"Time & Schedule": "Time & Schedule",
	"Time": "Time",
	"Time Confuguration": "Time Confuguration",
	"Automatic Time Confuguration": "Automatic Time Confuguration",
	"Manual Time Confuguration": "Manual Time Confuguration",
	"Date": "Date",
	"This page allows you to set the router\'s internal system clock. You can set the time manually, or automatically through a time server.": "This page allows you to set the router\'s internal system clock. You can set the time manually, or automatically through a time server.",
	"System Time": "System Time",
	"Time Zone": "Time Zone",
	"Enable Daylight Saving": "Enable Daylight Saving",
	"Update Time Using an NTP Serevr": "Update Time Using an NTP Serevr",
	"Year/ Month/ Day": "(Year/ Month/ Day)",
	"Hour/ Minute": "(Hour/ Minute)",
	"Day": "Day",
	"Hour": "Hour",
	"Min": "Min",
	"Sec": "Sec",
	
	// Schedule
	"The Schedule configuration option is used to manage schedule rules for various firewall and parental control features.": "The Schedule configuration option is used to manage schedule rules for various firewall and parental control features.",
	"Monday": "Monday",
	"Tuesday": "Tuesday",
	"Wednesday": "Wednesday",
	"Thursday": "Thursday",
	"Friday": "Friday",
	"Saturday": "Saturday",
	"Sunday": "Sunday",
	"All Day": "All Day",
	"All Week": "All Week",
	"Always": "Always Enable",
	
	// System Log
	"System Log": "System Log",
	"SysLog Settings": "SysLog Settings",
	"This page allows you to enable logging of system events to a SysLog server, or to e-mail the log to you according to a schedule or when the log is full.": "This page allows you to enable logging of system events to a SysLog server, or to e-mail the log to you according to a schedule or when the log is full.",
	"SysLog Server IP Address": "SysLog Server IP Address",
	"Enable Logging to Syslog Server": "Enable Logging to Syslog Server",
	"E-mail Settings": "E-mail Settings",
	"E-mail Log When Full or On Schedule": "E-mail Log When Full or On Schedule",
	"Enable E-mail Notification": "Enable E-mail Notification",
	"From E-mail Address": "From E-mail Address",
	"To E-mail Address": "To E-mail Address",
	"SMTP Server Address": "SMTP Server Address",
	"SMTP Server Port": "SMTP Server Port",
	"Enable Authentication": "Enable Authentication",
	"Account Name": "Account Name",
	"On Log Full": "On Log Full",
	"On Schedule": "On Schedule",
	
	// System
	"System": "System",
	"Save Configuration": "Save Configuration",
	"Restore Configuration From File": "Restore Configuration From File",
	"Restore Factory Default": "Restore Factory Default",
	"Reboot": "Reboot",
	"This page lets you save your router\'s current settings to a file, restore your settings from a file, restore your router to factory default settings, or reboot the device. Please note that restoring the settings to the factory defaults will erase all settings, including any rules you have created.": "This page lets you save your router\'s current settings to a file, restore your settings from a file, restore your router to factory default settings, or reboot the device. Please note that restoring the settings to the factory defaults will erase all settings, including any rules you have created.",
	"Save Settings To Local Hard Drive": "Save Settings To Local Hard Drive",
	"Load Settings From Local Hard Drive": "Load Settings From Local Hard Drive",
	"Restore To Factory Default Settings": "Restore To Factory Default Settings",
	"Reboot The Device": "Reboot The Device",
	"Cancel": "Cancel",
	"Are you sure you want to restore configuration file?": "Are you sure you want to restore configuration file?",
	"Do not close the page or power off the service until the restore configuration file is complete!": "Do not close the page or power off the service until the restore configuration file is complete!",
	"Restore configuration file failed!": "Restore configuration file failed!",
	"Restore configuration file success!": "Restore configuration file success!",
	"Are you sure you want to reset the device?": "Are you sure you want to reset the device?",
	"Rebooting": "Rebooting",
	"Reboot success!": "Reboot success!",
	"Are you sure you want to reset the device to its factory default settings? This will cause current settings to be lost.": "Are you sure you want to reset the device to its factory default settings? This will cause current settings to be lost.",
	"Restore to factory default success!": "Restore to factory default success!",
	"Select File": "Select File",
	"Restore": "Restore",
	"Restore Factory Default": "Restore Factory Default",
	
	// Admin
	"Admin": "Admin",
	"Admin Password": "Admin Password",
	"Administration": "Administration",
	"Use HTTPS": "Use HTTPS",
	"The admin has read/write access and can change passwords, while the user has read-only access. By default there is no password configured. It is highly recommended that you create a password to keep your router secure.": "The admin has read/write access and can change passwords, while the user has read-only access. By default there is no password configured. It is highly recommended that you create a password to keep your router secure.",
	"Enable Graphical Authentication (CAPTCHA)": "Enable Graphical Authentication (CAPTCHA)",
	"Enable HTTPS Server": "Enable HTTPS Server",
	"Enable Remote Management": "Enable Remote Management",
	"Remote Admin Port": "Remote Admin Port",
	"Remote Admin Inbound Filter": "Remote Admin Inbound Filter",
	
	// Update Firmware
	"Upgrade Firmware": "Upgrade Firmware",
	"This page shows you your current firmware version and language pack, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below. If you are using a language pack, we recommend that you also get the latest version of the language pack when upgrading the firmware to ensure that any changes in the interface are shown correctly.": "This page shows you your current firmware version and language pack, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below. If you are using a language pack, we recommend that you also get the latest version of the language pack when upgrading the firmware to ensure that any changes in the interface are shown correctly.",
	"Current Firmware Version": "Current Firmware Version",
	"Current Firmware Date": "Current Firmware Date",
	"Current Language Pack": "Current Language Pack",
	"Download New Firmware": "Download New Firmware",
	"Upgrade Firmware": "Upgrade Firmware",
	"Add a Language Pack": "Add a Language Pack",
	"Upload": "Upload",
	"Upgrade": "Upgrade",
	"Upgrading": "Upgrading",
	"Do you want to upgrade Firmware?": "Do you want to upgrade Firmware?",
	"Do not power off the device until the Firmware Upgrade is complete!": "Do not power off the device until the Firmware Upgrade is complete!",
	"Firmware Uploading": "Firmware Uploading",
	"Firmware Upgrade failed!": "Firmware Upgrade failed!",
	"Firmware Upgrade success!": "Firmware Upgrade success!",
	"Firmware Imformation": "Firmware Imformation",
	"New Firmware Version": "New Firmware Version",
	"New Firmware Date": "New Firmware Date",
	"Check for New Firmware": "Check for New Firmware",
	"Language Pack Imformation": "Language Pack Imformation",
	"Current Language Pack": "Current Language Pack",
	"Remove": "Remove",
	"Upgrade Manually": "Upgrade Manually",
	"Add a Language Pack": "Add a Language Pack",
	"Checking": "Checking",
	"Retry": "Retry",
	"This firmware is the latest version.": "This firmware is the latest version.",
	"Downloading": "Downloading",
	"Please do not close the browser while the firmware is being downloaded!": "Please do not close the browser while the firmware is being downloaded!",
	
	// Statistic
	"Statistics": "Statistics",
	"This page gives you various statistics about data transmitted and received by your router through the Internet, on your wired network (LAN), and through your wireless networks.": "This page gives you various statistics about data transmitted and received by your router through the Internet, on your wired network (LAN), and through your wireless networks.",
	"Clear": "Clear",
	"Information: Your browser is not support HTML5, please upgrade your browser.": "Information: Your browser is not support HTML5, please upgrade your browser.",
	"Sent (Tx)": "Sent (Tx)",
	"Received (Rx)": "Received (Rx)",
	"Total Packets": "Total Packets",
	"Total Byte(s)": "Total Byte(s)",
	"Total Kbit(s)": "Total Kbit(s)",
	"Kbits/sec": "Kbits/sec",
	"Session": "Session",

	//DAP1320B
	//general
	"Extended Wi-Fi" : "Extended Wi-Fi",
	"SCAN": "SCAN",
	"Uplink Router": "Uplink Router",
	"Wireless Mode": "Wireless Mode",
	"Scanning":"Scanning",
	"Connect to another uplink router":"Connect to another uplink router",
	"Select":"Select",
	"Repeater":"Repeater",
	"Password Length":"Password Length",
	"Authentication":"Authentication",
	"DNS Server":"DNS Server",
	"Network Settings": "Network Settings",
	"Network Status":"Network Status",
	"Connection Up Time":"Connection Up Time",
	"Subnet Prefix Length":"Subnet Prefix Length",
	"The device is not connected to an uplink router, click &quot;Next&quot; to find available Wi-Fi networks.":"The device is not connected to an uplink router, click &quot;Next&quot; to find available Wi-Fi networks.",
	//page
	"Use this section to configure the Wi-Fi Network you would like your DAP-1320b to connect to. Use Site Survey to scan available Wi-Fi networks and select the Wi-Fi Network you would like your DAP-1320b to connect to. Enter the Password of the Wi-Fi Network you selected and click Save.": "Use this section to configure the Wi-Fi Network you would like your DAP-1320b to connect to. Use Site Survey to scan available Wi-Fi networks and select the Wi-Fi Network you would like your DAP-1320b to connect to. Enter the Password of the Wi-Fi Network you selected and click Save.",
	"Use this section to configure the wireless settings for your D-Link Extender. Please note that changes made on this section may also need to be duplicated on your Wireless Client.":"Use this section to configure the wireless settings for your D-Link Extender. Please note that changes made on this section may also need to be duplicated on your Wireless Client.",
	"Use this section to configure the internal network settings of your Extender. Device Name allows you to configure this device more easily when your network using TCP/IP protocol. You can enter the device name of the Extender into your web browser to access the instead of IP address for configuration. Recommend to change the device name if there're more than one D-Link devices within the subnet.":"Use this section to configure the internal network settings of your Extender. Device Name allows you to configure this device more easily when your network using TCP/IP protocol. You can enter the device name of the Extender into your web browser to access the instead of IP address for configuration. Recommend to change the device name if there're more than one D-Link devices within the subnet.",
	"The admin password is used to log in to this configuration interface. It is highly recommended that you create a password to keep your router secure.":"The admin password is used to log in to this configuration interface. It is highly recommended that you create a password to keep your router secure.",
	"This page shows you your current firmware version, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below.":"This page shows you your current firmware version, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below.",



	"This page gives you various statistics about data transmitted and received by your AP through the internet, and through your wireless networks.":"This page gives you various statistics about data transmitted and received by your AP through the internet, and through your wireless networks.",
	//Wizard
	//wizard title
	"WI-FI CONNECTION SETUP WIZARD":"WI-FI CONNECTION SETUP WIZARD",
	"SELECT CONFIGURATION METHOD":"SELECT CONFIGURATION METHOD",
	"SELECT WI-FI NETWORK":"SELECT WI-FI NETWORK",
	"ENTER WIFI PASSWORD":"ENTER WIFI PASSWORD",
	"PLEASE ENTER THE SETTINGS FOR THE EXTENDED NETWORK":"PLEASE ENTER THE SETTINGS FOR THE EXTENDED NETWORK",
	"SETUP COMPLETE":"SETUP COMPLETE",
	
	
	
	"Wi-Fi Password" :"Wi-Fi Password",
	"Wi-Fi Network Name":"Wi-Fi Network Name",
	"Extended Wi-Fi Network Name":"Extended Wi-Fi Network Name",
	"Extended Wi-Fi Password":"Extended Wi-Fi Password",
	"This wizard is designed to assist you in your Wi-Fi network setup. It will guide you through step-by step instructions on how to set up your Wi-Fi network and how to make it secure.":"This wizard is designed to assist you in your Wi-Fi network setup. It will guide you through step-by step instructions on how to set up your Wi-Fi network and how to make it secure.",
	"Select this option if your wireless device supports WPS(Wi-Fi Protected Setup)": "Select this option if your wireless device supports WPS(Wi-Fi Protected Setup)",
	"Select this option if you want to setup your network manually":"Select this option if you want to setup your network manually",
	"Please enter Wi-Fi Password to establish wireless connection" : "Please enter Wi-Fi Password to establish wireless connection",
	"Between 8 and 63 characters": "Between 8 and 63 characters",
	"Give Your Extended Wi-Fi Network(SSID) a Name":"Give Your Extended Wi-Fi Network(SSID) a Name",
	"Give Your Extended Wi-Fi Network a Password":"Give Your Extended Wi-Fi Network a Password",
	"Using up to 32 characters":"Using up to 32 characters",
	"Use the same Wi-Fi Network Name for the Extended Network.":"Use the same Wi-Fi Network Name for the Extended Network.",
	"Please Take a note of the following summary of your Wi-Fi Security setting for furture reference":"Please Take a note of the following summary of your Wi-Fi Security setting for furture reference",
	//network setting ipv6
	"IPv4 Device Management Interface":"IPv4 Device Management Interface",
	"Choose a IPv4 provisioning mechanism to be used by the device.":"Choose a IPv4 provisioning mechanism to be used by the device.",
	"IPv6 Device Management Interface":"IPv6 Device Management Interface",
	"Choose a IPv6 provisioning mechanism to be used by the device.":"Choose a IPv6 provisioning mechanism to be used by the device.",
	"Obtain a DNS server address automatically or enter a specific DNS server address.":"Obtain a DNS server address automatically or enter a specific DNS server address.",
	"Autoconfiguration (SLAAC/DHCPv6)":"Autoconfiguration (SLAAC/DHCPv6)",
	"Obtain IPV6 Servers automatically.":"Obtain IPV6 Servers automatically.",
	"Use the following IPv6 DNS Servers.":"Use the following IPv6 DNS Servers.",
	"My IPv6 Connection is":"My IPv6 Connection is",
	"My LAN Connection is":"My LAN Connection is",
	"The LAN IPv6 Link-Local Address is the IPv6 Address that you use to access the Web-based management interface.":"The LAN IPv6 Link-Local Address is the IPv6 Address that you use to access the Web-based management interface.",
	"LAN IPv6 Link-Local Address":"LAN IPv6 Link-Local Address",
	"Enter the IPv6 address information that you would like to use to access the Web-based management interface.":"Enter the IPv6 address information that you would like to use to access the Web-based management interface."
	
	
	
	
	
	}