{
	// Menu
	"Home": "Inicio",
	"Settings": "Configuración",
	"Advanced": "Avanzado",
	"Management": "Gestión",
	"Internet(WAN)": "Internet",
	"Wireless(Wi-Fi)": "Inalámbrico",
	"Network(LAN)": "Red",
	"SharePort": "SharePort",
	"mydlink": "mydlink",
	"Firewall Setting": "Parámetro del cortafuegos",
	"Virtual Server": "Servidor virtual",
	"Port Forwarding": "Direccionamiento de puertos",
	"Website Filter": "Filtro de sitio web",
	"Static Route": "Ruta estática",
	"Disbled": "Desactivado",
	"Enabled": "Activado",
	
	// Genernal
    "There is unsaved data on this page. Do you want to abandon it?": "There is unsaved data on this page. Do you want to abandon it?",
    "Remaining": "Remaining",
	
	// Login
	"Model Name": "Nombre del modelo",
	"Hardware Version": "Versión de hardware",
	"Firmware Version": "Versión del firmware",
	"Language": "Idioma",
	"Admin Password": "Contraseña de administrador",
	"Log In": "Inicio de sesión",
	"To access your storage with SharePort Web Access,": "Para acceder al almacenamiento con Acceso web SharePort,",
	"click here.": "haga clic aquí.",
	"Invalid password, please try again.": "Contraseña no válida, inténtelo de nuevo.",
	"The Private Browsing feature of Safari is incompatible with this device's interface. You will need to disable Private Browsing to log in.": "The Private Browsing feature of Safari is incompatible with this device's interface. You will need to disable Private Browsing to log in.",
	
	// Home
    "Current Status": "Estado actual",
	"Click on any item in the diagram for more information.": "Haga clic en cualquier elemento del diagrama para obtener más información.",
    "Setup Wizard": "Asistente de configuración",
	"Router": "Router",
	"Internet": "Internet",
	"LAN": "LAN",
	"Router IP Address": "Dirección IP del router",
	"MAC Address": "Dirección MAC",
	"Wi-Fi 2.4GHz": "Wi-Fi de 2,4 GHz",
	"Wi-Fi 5GHz": "Wi-Fi de 5 GHz",
	"Guest Zone 2.4GHz": "Zona de invitados de 2,4 GHz",
	"Guest Zone 5GHz": "Zona de invitados de 5 GHz",
	"IP Address": "Dirección IP",
	"Subnet Mask": "Máscara de subred",
	"Default Gateway": "Puerta de enlace predeterminada",
	"Available Space": "Espacio disponible",
	"Total Space": "Espacio total",
	"Service Name": "Nombre del servicio",
	"Ethernet Device": "Dispositivo Ethernet",
	"Wi-Fi Clients": "Clientes Wi-Fi",
	"USB Device": "Dispositivo USB",
	"USB Name": "Nombre de USB",
	"Status": "Estado",
	"Wi-Fi Name (SSID)": "Nombre de Wi-Fi (SSID)",
	"Password": "Contraseña",
	"IPv6 Connection Type": "Tipo de conexión IPv6",
	"WAN IPv6 Address": "Dirección IPv6 de WAN",
	"Primary IPv6 DNS Server": "Servidor DNS IPv6 primario",
	"Secondary IPv6 DNS Address": "Dirección de DNS IPv6 secundario",
	"LAN IPv6 Link-Local Address": "Dirección de enlace local IPv6 de LAN",
	"DHCP-PD": "DHCP-PD",
	"IPv6 Network Assigned by DHCP-PD": "Red IPv6 asignada por DHCP-PD",
	"LAN IPv6 Address": "Dirección IPv6 de LAN",
	"Guest Zone": "Zona de invitados",
	"Connection Type": "Tipo de conexión",
	"Network Status": "Estado de red",
	"Connection Up Time": "Tiempo de conexión",
	"Primary DNS Server": "Servidor DNS primario",
	"Secondary DNS Server": "Servidor DNS secundario",
	"SharePort": "SharePort",
	"Release": "Liberar",
	"Renew": "Renovar",
	"Disconnect": "Desconectar",
	"Connect": "Conectar",
	"Ignore": "Ignore",
	"Connected": "Connected",
	"Connecting": "Connecting",
	"Disconnected": "Disconnected",
	"DHCP": "Dynamic IP (DHCP)",
	"Static": "Static IP (Static)",
	"DHCPPPPoE": "Dynamic IP (PPPoE)",
	"StaticPPPoE": "Static IP (PPPoE)",
	"DynamicPPTP": "Dynamic IP (PPTP)",
	"StaticPPTP": "Static IP (PPTP)",
	"DynamicL2TP": "Dynamic IP (L2TP)",
	"StaticL2TP": "Static IP (L2TP)",
	"A new firmware is available! Do you want to download and upgrade the firmware?": "A new firmware is available! Do you want to download and upgrade the firmware?",
    "Your changes are being saved, and the device will need to reboot.": "Your changes are being saved, and the device will need to reboot.",
    "The Wi-Fi connection is not secure.": "The Wi-Fi connection is not secure.",
	"Secure your network.": "Secure your network.",
	
	// Wizard
	"Welcome": "Bienvenido",
	"This wizard will guide you through a step-by-step process to configure your new D-Link device.": "Este asistente le guiará a través de un proceso paso a paso para configurar su nuevo dispositivo D-Link.",
	"Step1: Install your device": "Paso 1: Instalar el dispositivo",
	"Step2: Configure your Network and Wi-Fi settings": "Paso 2: Configurar los parámetros de red y Wi-Fi",
	"Step3: Set your router password": "Paso 3: Establecer la contraseña del router",
	"Step4: Set mydlink service": "Paso 4: Establecer el servicio mydlink",
	"Your Device": "Su dispositivo",
	"Cable/xDSL Broadband Modem": "Módem de banda ancha por cable/xDSL",
	"DHCP Connection (Dynamic IP Address)": "Conexión DHCP (dirección IP dinámica)",
	"Choose this if your Internet connection automatically provides you with an IP Address. Most Cable Modems use this type of connection.": "Elija esta opción si su conexión a Internet le proporciona automáticamente una dirección IP. La mayoría de los módems por cable utilizan este tipo de conexión.",
	"Username/Password Connection (PPPoE)": "Conexión con nombre de usuario / contraseña (PPPoE)",
	"Choose this option if your Internet connection reguires a username and passowrd to get online. Most DSL modems use this connection type of connection.": "Elija esta opción si su conexión a Internet requiere un nombre de usuario y una contraseña para navegar por la red. La mayoría de los módems DSL utilizan este tipo de conexión.",
	"Static IP Address Connection": "Conexión de dirección IP estática",
	"Choose this option if your Internet Setup Provider provided you with IP Address information that has to be manually configured.": "Elija esta opción si su proveedor de servicios de Internet le facilitó información de dirección IP que se debe configurar manualmente.",
	"Username": "Nombre de usuario",
	"Gateway Address": "Dirección de puerta de enlace",
	"Primary DNS Address": "Dirección DNS primaria",
	"Secondary DNS Address": "Dirección DNS secundaria",
	"2.4GHz Wi-Fi Network Name": "Nombre de red Wi-Fi de 2,4 GHz",
	"5GHz Wi-Fi Network Name": "Nombre de red Wi-Fi de 5 GHz",
	"The Wi-Fi Network Name is up to 32 characters. You will need to join your Wi-Fi network using this Network Name (SSID).": "El nombre de la red Wi-Fi tiene un máximo de 32 caracteres. Necesitará unirse a la red Wi-Fi utilizando este nombre de red (SSID).",
	"Wi-Fi Password": "Contraseña de Wi-Fi",
	"Copy to 5GHz": "Copiar a 5 GHz",
	"2.4GHz Wi-Fi Password": "Contraseña de Wi-Fi de 2,4 GHz",
	"5GHz Wi-Fi Password": "Contraseña de Wi-Fi de 5 GHz",
	"The password must contain at least 8 characters. You will need to join your Wi-Fi network using this password.": "La contraseña debe contener 8 caracteres como mínimo. Necesitará unirse a la red Wi-Fi utilizando esta contraseña.",
	"Device Admin Password": "Contraseña de administrador del dispositivo",
	"This device is mydlink-enabled, which allows you to remotely monitor and manage your network through the mydlink.com website, or through the mydlink mobile app.": "Este dispositivo está habilitado para mydlink, que permite supervisar y gestionar la red de forma remota a través del sitio web mydlink.com o a través de la aplicación móvil de mydlink.",
	"You can register this device with your existing mydlink account. If you do not have one, you can create one now.": "Puede registrar este dispositivo con su cuenta de mydlink existente. Si no tiene una, puede crearla ahora.",
	"Do you have an existing mydlink account": "¿Tiene una cuenta de mydlink existente?",
	"Yes, I have a mydlink account": "Sí, tengo una cuenta de mydlink",
	"No, I want to create a new mydlink account": "No, deseo crear una nueva cuenta de mydlink",
	"E-mail Address (Account Name)": "Dirección de correo electrónico (nombre de cuenta)",
	"First Name": "Nombre",
	"Last Name": "Apellido",
	"I accept the mydlink": "Acepto las condiciones",
	"terms and conditions.": "de mydlink.",
	"Connect to the Wi-Fi network from your mobile device or PC": "Conéctese a la red Wi-Fi desde su dispositivo móvil o PC",
	"1.Please go to Settings > Wi-fi, and choose": "1. Vaya a Configuración > Wi-Fi y seleccione",
	"from the list of Wi-Fi network services.": "de la lista de servicios de red Wi-Fi.",
	"2.Enter the password you just setup when prompted.": "2. Cuando se le indique, introduzca la contraseña que acaba de establecer.",
	"Checking Internet connectivity": "Comprobando la conectividad a Internet",
	"Wi-Fi Client": "Cliente Wi-Fi",
	"Save": "Guardar",
	"Please wait": "Espere",
	"Configure Your Internet Connection": "Configurar su conexión a Internet",
	"Detecting Internet connection": "Detectando la conexión a Internet",
	"Install": "Instalar",
	"Please plug one end of the Ethernet cable included with your device into the port labeled INTERNET on your device. Plug the other end of this cable into the Ethernet port on yourDSL or cable broadband modem, and power cycle the modem.": "Conecte un extremo del cable Ethernet suministrado con el dispositivo al puerto que lleva la etiqueta INTERNET en el dispositivo. Enchufe el otro extremo de este cable al puerto Ethernet de su módem de banda ancha DSL o por cable.",
	"Please select your Internet connection type below": "Seleccione su tipo de conexión a Internet a continuación",
	"PPPoE": "PPPoE",
	"To setup this Internet connection, you will need to have a User Name from your InternetService Provider. If you do not have this information, please contact your ISP.": "Para establecer esta conexión a Internet, necesitará disponer de un nombre de usuario de su proveedor de servicios de Internet. Si no tiene esta información, póngase en contacto con su ISP.",
	"Static IP": "IP estática",
	"Dynamic IP (DHCP)": "IP dinámica (DHCP)",
	"To set up this conncetion you will need to have a complete list of IP information by your Internet Service Provider. If you have a Static IP connection and do not have this information, please contact your ISP.": "Para establecer esta conexión necesitará disponer de una lista completa de la información IP facilitada por su proveedor de servicios de Internet. Si tiene una conexión IP estática y no tiene esta información, póngase en contacto con su ISP.",
	"Wi-Fi Settings": "Parámetros de Wi-Fi",
	"To setup a Wi-Fi Network you will need to give your Wi-Fi Nerwork a Name(SSID) and Password.": "Para configurar una red Wi-Fi, necesitará asignar un nombre (SSID) y una contraseña a la red Wi-Fi.",
	"By default, your new D-Link device does not have a password configured for administrator access to the Web-based configuration utility. To secure your new device, please create a password below.": "De forma predeterminada, el nuevo dispositivo D-Link no tiene configurada una contraseña para el acceso de administrador a la utilidad de configuración basada en la web. Para asegurar su nuevo dispositivo, cree una contraseña a continuación.",
	"Setup Complete": "Config. completa",
	"Below is a summary of your Wi-Fi security and device password settings.Please take a note of your settings and save your configuration.": "A continuación se muestra un resumen de los parámetros de seguridad Wi-Fi y de contraseña del dispositivo. Tome nota de sus parámetros y guarde la configuración.",
	"Checking Your Internet connectivity": "Comprobando la conectividad a Internet",
	"Checking Internet connectivity": "Comprobando la conectividad a Internet",
	"mydlink Regristration": "Registro mydlink",
	"Congratulations": "¡Felicidades!",
	"Congratulations,your device has been configured. You can now connect to your Wi-Fi network by using the new Wi-Fi Network Name and Password you created.": "Enhorabuena, se ha configurado el dispositivo. Ahora puede conectarse a su red Wi-Fi utilizando el nuevo nombre de red Wi-Fi y la contraseña que ha creado.",
	"Back": "Atrás",
	"Next": "Siguiente",
	"Skip": "Omitir",
	"Finish": "Finalizar",
	"Registered": "Registered",
	"Unregistered": "Unregistered",
	
	// Ethernet, Wireless, Wireless_Guest
	"Wi-Fi Clients (Guest Zone)": "Clientes Wi-Fi (zona de invitados)",
	"Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.",
	"Here, you can see a list of all devices connected through Wi-Fi. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Aquí puede ver una lista de todos los dispositivo conectados a través de Wi-Fi. Haga clic en un dispositivo para obtener más información acerca del mismo o haga clic en el icono del lápiz para asignar un nombre al dispositivo para facilitar su identificación. Puede bloquear siempre el acceso de un dispositivo a la red o de acuerdo con un programa utilizando la casilla desplegable Bloquear.",
	"Vendor": "Proveedor",
	"Reserve IP": "Reservar IP",
	"Access": "Acceder",
	"Allowed": "Permitido",
	"Blocked": "Bloqueado",
	
	// Internet > IPv4
	"Use this section to configure your Internet Connection type. There are several connection types to choose from Static IP, DHCP, PPPoE, PPTP, L2TP, and DS-Lite. If you are unsure of your connection method, please contact your Internet Service Provider. Note:  If using the PPPoE option, you will need to remove or disable any PPPoE client software on your computers.": "Utilice esta sección para configurar su tipo de conexión a Internet. Existen varios tipos de conexión entre los que elegir, IP estática, DHCP, PPPoE, PPTP, L2TP y DS-Lite. Si no está seguro del método de conexión, póngase en contacto con su proveedor de servicios de Internet. Nota:  si está utilizando la opción PPPoE, necesitará eliminar o desactivar cualquier software cliente PPPoE en sus ordenadores.",
	"My Internet Connection is": "Mi conexión a Internet es",
	"Host Name": "Nombre de host",
	"Mac Address Clone": "Clon de la dirección MAC",
	"PPTP IP Address": "Dirección IP de PPTP",
	"PPTP Server IP Address": "Dirección IP del servidor PPTP",
	"PPTP Subnet Mask": "Máscara de subred PPTP",
	"PPTP Gateway IP Address": "Dirección IP de puerta de enlace PPTP",
	"L2TP IP Address": "Dirección IP L2TP",
	"L2TP Server IP Address": "Dirección IP del servidor L2TP",
	"L2TP Subnet Mask": "Máscara de subred L2TP",
	"L2TP Gateway IP Address": "Dirección IP de puerta de enlace L2TP",
	"MTU": "MTU",
	"Address Mode": "Modo de dirección",
	"Reconnect Mode": "Modo de reconexión",
	"Maximum Idle Time": "Tiempo de inactividad máximo",
	"DS-Lite Configuration": "Configuración de DS-Lite",
	"DS-Lite DHCPv6 Option": "Opción DHCPv6 de DS-Lite",
	"Manual Configuration": "Configuración manual",
	"AFTR IPv6 Address": "Dirección IPv6 de AFTR",
	"B4 IPv4 Address": "Dirección IPv4 B4",
	"WAN IPv6 Address": "Dirección IPv6 de WAN",
	"IPv6 WAN Default Gateway": "Puerta de enlace predeterminada de WAN IPv6",
	"Advanced Settings": "Parámetros avanzados",
	"Manual": "Manual",
	"Always on": "Siempre activado",
	"On demand": "A petición",
	"Dynamic IP": "Dynamic IP",
	
	// Internet > IPv6
    "All of your IPv6 Internet and network connection details are displayed on this page.": "Todos los detalles sobre la conexión a Internet IPv6 y de red se muestran en esta página.",
	"Auto Detection": "Detección automática",
	"Static IPv6": "IPv6 estática",
	"Auto Configuration (SLAAC/DHCPv6)": "Configuración automática (SLAAC/DHCPv6)",
	"IPv6 in IPv4 Tunnel": "Túnel IPv6 en IPv4",
	"6to4": "6 a 4",
	"Local Connectivity Only": "Solo conectividad local",
	"Use Link-Local Address": "Usar dirección de enlace local",
	"Subnet Prefix Length": "Longitud del prefijo de subred",
	"PPPoE Session": "Sesión PPPoE",
	"Remote IPv4 Address": "Dirección IPv4 remota",
	"Remote IPv6 Address": "Dirección IPv6 remota",
	"Local IPv4 Address": "Dirección IPv4 local",
	"Local IPv6 Address": "Dirección IPv6 local",
	"6to4 Address": "Dirección 6 a 4",
	"6to4 Relay": "Relé 6 a 4",
	"Assign IPv6 Prefix": "Asignar prefijo IPv6",
	"LAN IPv6 Link-Local Address": "Dirección de enlace local IPv6 de LAN",
	"IPv6 DNS SETTINGS": "PARÁMETROS DE DNS IPv6",
	"LAN IPv6 ADDRESS SETTINGS": "CONFIGURACIÓN DE LA DIRECCIÓN IPv6 DE LAN",
	"LAN IPv6 Address": "Dirección IPv6 de LAN",
	"ADDRESS AUTOCONFIGURATION SETTINGS": "PARÁMETROS DE CONFIGURACIÓN AUTOMÁTICA DE LA DIRECCIÓN",
	"Enable Automatic IPv6 Address Assignment": "Activar la asignación automática de direcciones IPv6",
	"Enable Automatic DHCP-PD in LAN": "Activar DHCP-PD automática en la LAN",
	"Autoconfiguration Type": "Tipo de configuración automática",
	"Enable DHCP-PD": "Activar DHCP-PD",
	"6RD MANUAL CONFIGURATION": "CONFIGURACIÓN MANUAL DE 6RD",
	"Enable Hub and Spoke Mode": "Activar concentrador y el modo Hablar",
	"6rd Configuration": "Configuración 6rd",
	"6rd IPv6 Prefix": "Prefijo de IPv6 6rd",
	"6rd Border Relay IPv4 Address": "Dirección IPv4 de relé 6rd de borde",
	"IPv6 ULA SETTINGS": "PARÁMETROS ULA IPv6",
	"Enable ULA": "Activar ULA",
	"Use Default ULA Prefix": "Utilizar el prefijo ULA predeterminado",
	"ULA Prefix": "Prefijo ULA",
	"CURRENT IPv6 ULA SETTINGS": "PARÁMETROS ULA IPv6 ACTUALES",
	"Current ULA Prefix": "Prefijo ULA actual",
	"LAN IPv6 ULA": "ULA IPv6 de LAN",
	"minutes": "minutos",
	"DNS Type": "Tipo de DNS",
	"Obtain a DNS server address automatically": "Obtenga automáticamente la dirección de un servidor DNS",
	"Use the following DNS address": "Utilice la siguiente dirección de DNS",
	"SLAAC+Stateless DHCP": "SLAAC+DHCP sin estado",
	"Stateful DHCPv6": "DHCPv6 con estado",
	"6rd DHCPv4 Option": "Opción DHCPv4 6rd",
	"Share with IPv4": "Compartir con IPv4",
	"Create a new session": "Crear una nueva sesión",
	"bytes": "bytes",
	"Router Advertisement Lifetime": "Router Advertisement Lifetime",
	"IPv6 Address Range (Start)": "IPv6 Address Range (Start)",
	"IPv6 Address Range (End)": "IPv6 Address Range (End)",
	"IPv6 Address Lifetime": "IPv6 Address Lifetime",
	
	// WiFi & Guest Zone
	"Security Mode": "Modo de seguridad",
	"None": "Ninguna",
	"WPA-Personal": "WPA-Personal",
	"Auto": "Automático",
	"High": "Alta",
	"Low": "Baja",
	"802.11 Mode": "Modo 802.11",
	"Wi-Fi Channel": "Canal Wi-Fi",
	"Transmission Power": "Potencia de transmisión",
	"Channel Width": "Anchura de canal",
	"Visibility Status": "Estado de visibilidad",
	"Visible": "Visible",
	"Invisible": "Invisible",
	"Mixed 802.11b/g": "Mezcla de 802.11b/g",
	"Mixed 802.11g/n": "Mezcla de 802.11g/n",
	"Mixed 802.11b/g/n": "Mezcla de 802.11b/g/n",
	"Auto 20/40 MHz": "Automático 20/40 MHz",
	"Mixed 802.11a and 802.11n": "Mezcla de 802,11a y 802.11n",
	"Use this section to configure the wireless settings for your D-Link Router. Please note that changes made on this section may also need to be duplicated on your Wireless Client.": "Utilice esta sección para configurar los parámetros inalámbricos para su router D-Link. Tenga en cuenta que también será necesario duplicar los cambios realizados en esta sección en su cliente inalámbrico.",
	"This page lets you configure a Wi-Fi Guest Zone. Wi-Fi Guest Zones are Wi-Fi networks that are separate from your normal ones, and use different Wi-Fi Network Names and passwords. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless the Access Local Service option is enabled. Guest Zones are useful to give guests Internet access without allowing them to access your own devices on your network.": "Esta página permite configurar una zona de invitados Wi-Fi. Las zonas de invitados Wi-Fi son redes Wi-Fi independientes de las redes normales, que utilizan nombres y contraseñas de red Wi-Fi diferentes. Los usuarios conectados a una zona de invitados no se pueden comunicar o detectar dispositivos en la red normal a menos que esté activada la opción de acceso al servicio local. Las zonas de invitados resultan útiles para otorgar acceso a Internet a los invitados sin permitirles acceder a sus propios dispositivos en la red.",
	"Internet Access Only": "Solo acceso a Internet",
	"Routing Between Zones": "Enrutamiento entre zonas",
	"Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.": "Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.",
	"Your changes are being saved.": "Your changes are being saved.",
	
	// Network
	"Network": "Red",
	"Network Settings": "Parámetros de red",
	"DHCP Server": "Servidor DHCP",
	"Use this page to configure the local network settings for your router, including the IP address you use to access this configuration interface. Please note that if you change this IP address, you will need to use the new IP to access this interface.": "Utilice esta página para configurar los parámetros de red local del router, incluida la dirección IP que utiliza para acceder a esta interfaz de configuración. Tenga en cuenta que, si cambia esta dirección IP, necesitará utilizar la nueva IP para acceder a esta interfaz.",
	"LAN IP Address": "Dirección IP de LAN",
	"Device Name": "Nombre del dispositivo",
	"Local Domain Name": "Nombre de dominio local",
	"Enable DNS Relay": "Activar relé DNS",
	"DHCP IP Address Range": "Intervalo de dirección IP de DHCP",
	"DHCP Lease Time": "Tiempo de validez de DHCP",
	"Always Broadcast": "Difusión siempre",
	"compatibility for some DHCP Clients": "compatibilidad para algunos clientes DHCP",
	"If you changed the IP address of the router you will need to change the IP address in your browser before accessing the configuration website again.": "Si ha cambiado la dirección IP del router, necesitará cambiar la dirección IP en el explorador antes de acceder de nuevo al sitio web de configuración.",
	"The new settings have been saved.": "Se han guardado los nuevos parámetros.",
	"to": "to",
	
	// Advanced Network
	"Advanced Network": "Red avanzada",
	"Advanced Network settings allow you to configure some of the more advanced features of your router. It is recommended that you only change these settings if you are  familiar with them, or if you are specifically instructed to do so.": "Los parámetros de opciones avanzadas de red permiten configurar algunas de las opciones más avanzadas del router. Se recomienda que solo cambie estos parámetros si está familiarizado con ellos o si se le indica específicamente que lo haga.",
	"UPnP": "UPnP",
	"WAN Port Speed": "Velocidad de puerto WAN",
	"IPv4 Multicast Streams": "Secuencias de multidifusión IPv4",
	"IPv6 Multicast Streams": "Secuencias de multidifusión IPv6",
	"Auto (10/100/1000 Mbps)": "Automático (10/100/1000 Mbps)",
	
	// SharePort
	"SharePort": "SharePort",
	"DLNA (Digital Living Network Alliance) is the standard for the interoperability of Network Media Devices (NMDs). The user can enjoy multi-media applications (music, pictures and videos) on your network connected PC or media devices. Web File Access allows you to use a web browser to remotely access files stored on an SD card or USB storage drive plugged into the router.": "DLNA (Digital Living Network Alliance) es la norma correspondiente a la interoperabilidad de los dispositivos multimedia de red (NMD). Los usuarios pueden disfrutar de aplicaciones multimedia (música, imágenes y vídeos) desde los dispositivos o los PC conectados a la red. El acceso a archivos web permite utilizar un explorador web para acceder de forma remota a los archivos almacenados en una tarjeta SD o un dispositivo de almacenamiento USB conectado al router.",
	"DLNA Media Server Configuration": "DLNA Media Server Configuration",
	"DLNA Media Server": "Servidor multimedia DLNA",
	"Web File Access": "Acceso a archivos web",
	"Remote Access Port": "Puerto de acceso remoto",
	"Remote HTTPS Port": "Puerto HTTPS remoto",
	"Enable Storage Remote Access": "Activar acceso remoto a almacenamiento",
	"Direct Links": "Enlaces directos",
	"Local Access": "Acceso local",
	"SharePort Web Access": "Acceso a la web SharePort",
    
    // SharePort CreateUser
    "\"Create User\" manage access to your storage devices or use the Guest account (guest/guest) to access the Guest Folder. After plugging in an SD card or USB storage drive, the new device will appear in the list with a link to it. You can then use this link to connect the drive and login with a user account.": "\"Crear usuario\" gestiona el acceso a los dispositivos de almacenamiento o utiliza la cuenta de invitado (invitado/invitado) para acceder a la carpeta Invitado. Después de enchufar una tarjeta SD o una unidad de almacenamiento USB, aparecerá el nuevo dispositivo en la lista con el enlace al mismo. Podrá utilizar este enlace para conectar la unidad e iniciar sesión con una cuenta de usuario.",
	"Remote Access": "Acceso remoto",
	"Create User": "Crear usuario",
	"User Name": "Nombre de usuario",
	"Access Path": "Ruta de acceso",
	"Permission": "Permiso",
	"Edit": "Editar",
	"Delete": "Eliminar",
	"Browse": "Examinar",
	"OK": "Aceptar",
	"Create User": "Crear usuario",
	"Create New User": "Crear usuario nuevo",
	"Edit User Profile": "Editar perfil de usuario",
	"Folder": "Carpeta",
	"Select Folder": "Seleccionar carpeta",
	"USB Device Name": "Nombre del dispositivo USB",
	"Number of Device": "Número del dispositivo",
	
	// mydlink
	"Setting and registering your router with mydlink will allow you to use its mydlink cloud services features, including online access and management of your router through the mydlink portal website.": "Configurar y registrar su router con mydlink le permitirá utilizar las características de los servicios de mydlink Cloud, incluido el acceso y la gestión en línea del router a través del sitio web del portal de mydlink.",
	"mydlink Registration": "Registro mydlink",
	"Sign Up": "Registrarse",
	"Sign In": "Iniciar Sesión",
	"Please enter your e-mail address and mydlink password.": "Introduzca su dirección de correo electrónico y la contraseña de mydlink.",
	"You must accept the terms and conditions to continue.": "Para continuar, debe aceptar las condiciones.",
	
	// QoS Engine
	"QoS Engine": "QoS",
	"QoS prioritizes your network traffic so you can decide what devices should have priority over other devices. For example, you could set a computer that is downloading files to have lower priority than a laptop that is streaming movies to ensure that you can stream movies smoothly without downloads taking up all of your bandwidth.": "La calidad de servicio da prioridad al tráfico de red, de modo que pueda decidir los dispositivos que deben tener prioridad sobre el resto de los dispositivos. Por ejemplo, puede establecer que un ordenador que está descargando archivos tenga una prioridad inferior que un portátil que está transfiriendo películas, para garantizar que puede transferir las películas sin problemas sin que las descargas ocupen todo el ancho de banda.",
	"All Devices": "Todos los dispositivos",
	"Drag the device cards above to the Prioity boxes below.": "Arrastre las tarjetas de dispositivo por encima de las casillas de prioridad que aparecen a continuación.",
	"Highest": "Más alta",
	"Medium": "Media",
	
	// Firewall
	"Firewall Settings": "Parámetros del cortafuegos",
	"Here, you can set up various firewall features to protect your network from attacks. You can click on the DMZ, IPv4 Rules, and IPv6 Rules buttons to see the settings for that feature.": "Aquí puede establecer diversas características de cortafuegos para proteger la red frente a los ataques. Puede hacer clic en los botones DMZ, Reglas de IPv4 y Reglas de IPv6 para ver los parámetros para esa característica.",
	"Application Level Gateway (ALG) Configuration": "Configuración de puerta de enlace a nivel de aplicación (ALG, Application Level Gateway)",
	"Enable SPI IPv4": "Activar SPI IPv4",
	"Enable Anti-spoof Checking": "Activar comprobación para prevenir suplantaciones",
	"IPv6 Simple Security": "Seguridad sencilla IPv6",
	"PPTP": "PPTP",
	"IPSec (VPN)": "IPSec (VPN)",
	"RTSP": "RTSP",
	"SIP": "SIP",
	"IPv4 Rules": "Reglas de IPv4",
	"IPv6 Rules": "Reglas de IPv6",
	"Firewall": "Cortafuegos",
	"Enable DMZ Host": "Activar host DMZ",
	"DMZ IP Address": "Dirección IP de DMZ",
	"Security Check": "Comprobación de seguridad",
	
	// Firewall IPv4, IPv6
	"The IPv4 rule section is an advance feature used to deny or allow traffic from passing through the device.": "La sección de reglas de IPv4 es una característica avanzada que se utiliza para denegar o permitir que el tráfico pase a través del dispositivo.",
	"The IPv6 rule section is an advance feature used to deny or allow traffic from passing through the device.": "La sección de reglas de IPv6 es una característica avanzada que se utiliza para denegar o permitir que el tráfico pase a través del dispositivo.",
	"Add Rules": "Añadir reglas",
	"Name": "Nombre",
	"Schedule": "Programación",
	"Create New Rule": "Crear nueva regla",
	"Source IP Address Range": "Rango de la dirección IP de origen",
	"Destination IP Address Range": "Rango de la dirección IP de destino",
	"Port Range": "Rango de puertos",
	"Turn IPv4 Filtering OFF": "DESACTIVE el filtrado IPv4",
	"Turn IPv4 Filtering ON and ALLOW rules listed": "ENCIENDA el filtrado IPv4 y PERMITA las reglas enumeradas",
	"Turn IPv4 Filtering ON and DENY rules listed": "ENCIENDA el filtrado IPv4 y DENIEGUE las reglas enumeradas",
	"Turn IPv6 Filtering OFF": "DESACTIVE el filtrado IPv6",
	"Turn IPv6 Filtering ON and ALLOW rules listed": "ENCIENDA el filtrado IPv6 y PERMITA las reglas enumeradas",
	"Turn IPv6 Filtering ON and DENY rules listed": "ENCIENDA el filtrado IPv6 y DENIEGUE las reglas enumeradas",
	
	// Port Forwarding
	"Port Forwarding is used to open ports in your router and to redirect traffic to those ports to a specific device on your network. This may be needed for specific applications, games, or services. You can enter individual ports (80, 68, 888), port ranges (100-150), or in a mixed format (1020-5000, 689).": "El direccionamiento de puertos se utiliza para abrir puertos en el router y redirigir el tráfico a dichos puertos en un dispositivo específico en la red. Puede que sea necesario para aplicaciones, juegos o servicios específicos. Puede introducir puertos individuales (80, 68, 888), rangos de puertos (100-150) o en formato mezclado (1020-5000, 689).",
	"Local IP": "IP local",
	"TCP Port": "Puerto TCP",
	"UDP Port": "Puerto UDP",
	
	// Virtual Server
	"The Virtual Server option allows you to define a single public port on your router for redirection to an internal LAN IP Address and Private LAN port if required. This feature is useful for hosting online services such as FTP or Web Servers.": "La opción Servidor virtual le permite definir un único puerto público en su router para la redirección a una Dirección IP de LAN interna y a un puerto LAN privado si fuera necesario. Esta característica resulta útil para alojar servicios en línea como servidores FTP o web.",
	"Protocol": "Protocolo",
	"External Port": "Puerto externo",
	"Internal Port": "Puerto interno",
	"Protocol Number": "Protocol Number",
	
	// Website Filter
	"The Website Filter option allows you to set up a list of Web sites you would like to allow or deny through your network. To use this feature, you must also select the \"Apply Web Filter\" checkbox in the Access Control section.": "La opción Filtro del sitio web permite establecer una lista de sitios web que desee permitir o denegar en su red. Para utilizar esta característica, debe marcar además la casilla \"Aplicar filtro web\" en la sección Control de acceso.",
	"DENY computers access to ONLY these sites": "DENEGAR el acceso de los ordenadores SÓLO a estos sitios",
	"ALLOW computers access to ONLY these sites": "PERMITIR el acceso de los ordenadores SÓLO a estos sitios",
	"Website URL/Domain": "URL/Dominio de sitio web",
	
	// StaticRouter, StaticRouterIPv6
	"Static Routes": "Rutas estáticas",
	"This page allows you to define custom routes to define how data traffic is moved around your network.": "Esta página permite definir rutas personalizadas para determinar la forma en que se mueven los datos por la red.",
	"Destination IP": "IP de destino",
	"Netmask": "Máscara de red",
	"Gateway": "Puerta de enlace",
	"Matrix": "Matriz",
	"Interface": "Interfaz",
	"DestNetwork": "Red de destino",
	"PrefixLen": "Longitud del prefijo",
	
	// DynamicDNS
   	"Dynamic DNS (DDNS) allows you to use an easy to remember domain name such as www.[YourDomainName].com to reach your router\'s dynamically assigned IP address. This is useful when hosting a web, FTP, or game server, and allows you to reach your server no matter what your IP address has changed to. D-Link offers a free DDNS service that you can use through www.DLinkDDNS.com.": "DNS dinámico (DDNS) permite utilizar un nombre de dominio fácil de recordar como, por ejemplo, www.[sunombrededominio].com para llegar a la dirección IP del router asignada dinámicamente. Esto resulta útil al alojar un servidor web, FTP o de juegos y permite alcanzar el servidor independientemente de los cambios que se hayan producido en la dirección IP. D-Link ofrece un servicio DDNS gratuito que puede utilizar a través de www.DLinkDDNS.com.",
	"Server Address": "Dirección del servidor",
	"Dynamic DNS": "DNS dinámico",
	"Enable Dynamic DNS": "Activar DNS dinámico",
	"Select Server Name": "Seleccionar nombre del servidor",
	"Time Out": "Tiempo de espera",
	"IPv6 Address": "Dirección IPv6",
	"hours": "horas",
	
	// Time
	"Time & Schedule": "Hora y programación",
	"Time": "Hora",
	"Time Confuguration": "Configuración de la hora",
	"Automatic Time Confuguration": "Configuración automática de la hora",
	"Manual Time Confuguration": "Configuración manual de la hora",
	"Date": "Fecha",
	"This page allows you to set the router\'s internal system clock. You can set the time manually, or automatically through a time server.": "Esta página permite establecer el reloj interno del sistema del router. Puede establecer la hora de forma manual, o bien, de forma automática a través de un servidor de hora.",
	"System Time": "Hora del sistema",
	"Time Zone": "Zona horaria",
	"Enable Daylight Saving": "Activar el horario de verano",
	"Update Time Using an NTP Serevr": "Actualizar la hora utilizando un servidor NTP",
	"Year/ Month/ Day": "Año/ mes/ día",
	"Hour/ Minute": "Hora/ minuto",
	"Day": "Día",
	"Hour": "Hora",
	"Min": "Min.",
	"Sec": "S",
	
	// Schedule
	"The Schedule configuration option is used to manage schedule rules for various firewall and parental control features.": "La opción de configuración de programa se utiliza para gestionar las reglas de programa para diversas características de cortafuegos y control paterno.",
	"Monday": "Monday",
	"Tuesday": "Tuesday",
	"Wednesday": "Wednesday",
	"Thursday": "Thursday",
	"Friday": "Friday",
	"Saturday": "Saturday",
	"Sunday": "Sunday",
	"All Day": "All Day",
	"All Week": "All Week",
	"Always": "Always Enable",
	
	// System Log
	"System Log": "Registro del sistema",
	"SysLog Settings": "Parámetros de SysLog",
	"This page allows you to enable logging of system events to a SysLog server, or to e-mail the log to you according to a schedule or when the log is full.": "Esta página permite activar el registro de los eventos del sistema en un servidor SysLog o enviar por correo electrónico el registro a su dirección de acuerdo con una programación o cuando el registro está lleno.",
	"SysLog Server IP Address": "Dirección IP del servidor Syslog",
	"Enable Logging to Syslog Server": "Activar inicio de sesión en el servidor Syslog",
	"E-mail Settings": "Parámetros de correo electrónico",
	"E-mail Log When Full or On Schedule": "Enviar el registro por correo electrónico cuando esté completo o según programación",
	"Enable E-mail Notification": "Activar notificación por correo electrónico",
	"From E-mail Address": "Dirección de correo electrónico del remitente",
	"To E-mail Address": "Dirección de correo electrónico del destinatario",
	"SMTP Server Address": "Dirección del servidor SMTP",
	"SMTP Server Port": "Puerto del servidor SMTP",
	"Enable Authentication": "Activar autenticación",
	"Account Name": "Nombre de cuenta",
	"On Log Full": "Activar registro lleno",
	"On Schedule": "Según programación",
	
	// System
	"System": "Sistema",
	"Save Configuration": "Guardar configuración",
	"Restore Configuration From File": "Restablecer la configuración del archivo",
	"Restore Factory Default": "Restablecer valor predeterminado de fábrica",
	"Reboot": "Reiniciar",
	"This page lets you save your router\'s current settings to a file, restore your settings from a file, restore your router to factory default settings, or reboot the device. Please note that restoring the settings to the factory defaults will erase all settings, including any rules you have created.": "Esta página permite guardar en un archivo los parámetros actuales del router, restablecer la configuración desde un archivo, restaurar el router en los parámetros predeterminados de fábrica o reiniciar el dispositivo. Tenga en cuenta que al restaurar los valores predeterminados de fábrica se borrarán todos los parámetros, incluidas las reglas que haya creado.",
	"Save Settings To Local Hard Drive": "Guardar parámetros en la unidad de disco duro local",
	"Load Settings From Local Hard Drive": "Cargar parámetros de la unidad de disco duro local",
	"Restore To Factory Default Settings": "Restablecer los parámetros predeterminados de fábrica",
	"Reboot The Device": "Reiniciar el dispositivo",
	"Cancel": "Cancelar",
	"Are you sure you want to restore configuration file?": "¿Está seguro de que desea restablecer el archivo de configuración?",
	"Do not close the page or power off the service until the restore configuration file is complete!": "No cierre la página ni apague el servicio hasta que se haya completado la restauración del archivo de configuración.",
	"Restore configuration file failed!": "Error al restablecer el archivo de configuración.",
	"Restore configuration file success!": "Archivo de configuración restablecido correctamente.",
	"Are you sure you want to reset the device?": "¿Está seguro de que desea restablecer el dispositivo?",
	"Rebooting": "Reiniciando",
	"Reboot success!": "Reinicio correcto.",
	"Are you sure you want to reset the device to its factory default settings? This will cause current settings to be lost.": "¿Está seguro de que desea restablecer el dispositivo a sus valores predeterminados de fábrica? Esta acción causará la pérdida de los parámetros actuales.",
	"Restore to factory default success!": "Restablecido correctamente en los valores predeterminados de fábrica.",
	"Select File": "Seleccionar archivo",
	"Restore": "Restablecer",
	"Restore Factory Default": "Restablecer valor predeterminado de fábrica",
	
	// Admin
	"Admin": "Admin",
	"Admin Password": "Contraseña de administrador",
	"Administration": "Administración",
	"Use HTTPS": "Utilice HTTPS",
	"The admin has read/write access and can change passwords, while the user has read-only access. By default there is no password configured. It is highly recommended that you create a password to keep your router secure.": "El administrador tiene derecho de lectura/escritura y puede cambiar las contraseñas, mientras que el usuario tiene acceso de sólo lectura. De forma predeterminada no existe contraseña configurada. Se recomienda encarecidamente crear una contraseña para mantener seguro el router.",
	"Enable Graphical Authentication (CAPTCHA)": "Activar autenticación gráfica (CAPTCHA)",
	"Enable HTTPS Server": "Activar el servidor HTTPS",
	"Enable Remote Management": "Activar gestión remota",
	"Remote Admin Port": "Puerto de administración remoto",
	"Remote Admin Inbound Filter": "Filtro de entrada de administración remota",
    
    // Update Firmware
    "Upgrade Firmware": "Actualizar firmware",
	"This page shows you your current firmware version and language pack, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below. If you are using a language pack, we recommend that you also get the latest version of the language pack when upgrading the firmware to ensure that any changes in the interface are shown correctly.": "Esta página muestra la versión de firmware actual y el paquete de idioma y permite comprobar y descargar nuevo firmware. Después de descargar el firmware, puede actualizarlo utilizando los botones que aparecen a continuación. Si está utilizando un paquete de idioma, se recomienda obtener también la última versión del paquete de idioma al actualizar el firmware para asegurarse de que se muestran correctamente todos los cambios de la interfaz.",
	"Current Firmware Version": "Versión del firmware actual",
	"Current Firmware Date": "Fecha actual del firmware",
	"Current Language Pack": "Paquete de idioma actual",
	"Download New Firmware": "Descargar nuevo firmware",
	"Upgrade Firmware": "Actualizar firmware",
	"Add a Language Pack": "Añadir un paquete de idioma",
	"Upload": "Cargar",
	"Upgrade": "Actualizar",
    "Upgrading": "Upgrading",
	"Do you want to upgrade Firmware?": "¿Desea actualizar el firmware?",
	"Do not power off the device until the Firmware Upgrade is complete!": "No cierre la página ni apague el servicio hasta que se haya completado la actualización del firmware.",
	"Firmware Uploading": "Carga de firmware",
	"Firmware Upgrade failed!": "Error de actualización de firmware.",
	"Firmware Upgrade success!": "Actualización de firmware correcta.",
	"Firmware Imformation": "Información del firmware",
	"New Firmware Version": "Nueva versión del firmware",
	"New Firmware Date": "Fecha del nuevo firmware",
	"Check for New Firmware": "Comprobar el nuevo firmware",
	"Language Pack Imformation": "Información del paquete de idioma",
	"Current Language Pack": "Paquete de idioma actual",
	"Remove": "Eliminar",
	"Upgrade Manually": "Actualizar manualmente",
	"Add a Language Pack": "Añadir un paquete de idioma",
	"Checking": "Comprobando",
	"Retry": "Reintentar",
	"This firmware is the latest version.": "This firmware is the latest version.",
	"Downloading": "Downloading",
	"Please do not close the browser while the firmware is being downloaded!": "Please do not close the browser while the firmware is being downloaded!",
	
	// Statistic
	"Statistics": "Estadísticas",
	"This page gives you various statistics about data transmitted and received by your router through the Internet, on your wired network (LAN), and through your wireless networks.": "Esta página le ofrece diversas estadísticas acerca de los datos transmitidos y recibidos por el router a través de Internet, en la red con cables (LAN) y a través de las redes inalámbricas.",
	"Clear": "Borrar",
	"Information: Your browser is not support HTML5, please upgrade your browser.": "Información: El explorador no admite HTML5, actualice el explorador.",
	"Sent (Tx)": "Enviado (transmisión)",
	"Received (Rx)": "Recibido (recepción)",
	"Total Packets": "Total Packets",
	"Total Byte(s)": "Total Byte(s)",
	"Total Kbit(s)": "Total Kbit(s)",
	"Kbits/sec": "Kbits/sec",
	"Session": "Session"
}