{
	// Menu
	"Home": "Accueil",
	"Settings": "Paramètres",
	"Advanced": "Avancé",
	"Management": "Gestion",
	"Internet(WAN)": "Réseau étendu",
	"Wireless(Wi-Fi)": "Sans fil",
	"Network(LAN)": "Réseau",
	"SharePort": "SharePort",
	"mydlink": "mydlink",
	"Firewall Setting": "Paramètres du pare-feu",
	"Virtual Server": "Serveur virtuel",
	"Port Forwarding": "Redirection de port",
	"Website Filter": "Filtre de sites Web",
	"Static Route": "Route statique",
	"Disabled": "Désactivé",
	"Enabled": "Activé",
	
	// Genernal
	"There is unsaved data on this page. Do you want to abandon it?": "There is unsaved data on this page. Do you want to abandon it?",
	"Remaining": "Remaining",
	
	// Login
	"Model Name": "Nom du modèle",
	"Hardware Version": "Version matérielle",
	"Firmware Version": "Version du microprogramme",
	"Language": "Langue",
	"Admin Password": "Mot de passe d'administration",
	"Log In": "Connexion",
	"To access your storage with SharePort Web Access,": "Pour accéder à votre stockage avec l'accès Web à SharePort,",
	"click here.": "cliquez ici.",
	"Invalid password, please try again.": "Mot de passe incorrect, veuillez réessayer.",
	"The Private Browsing feature of Safari is incompatible with this device's interface. You will need to disable Private Browsing to log in.": "La fonction Private Browsing de Safari est incompatible avec l'interface de ce périphérique. Vous devrez désactiver Private Browsing pour vous connecter.",
	
	// Home
	"Current Status": "État actuel",
	"Click on any item in the diagram for more information.": "Cliquez sur un élément du schéma pour plus d'informations.",
	"Setup Wizard": "Assistant de configuration",
	"Router": "Routeur",
	"Internet": "Internet",
	"LAN": "Réseau local",
	"Router IP Address": "Adresse IP du routeur",
	"MAC Address": "Adresse MAC",
	"Wi-Fi 2.4GHz": "Wi-Fi 2.4GHz",
	"Wi-Fi 5GHz": "Wi-Fi 5GHz",
	"Guest Zone 2.4GHz": "Zone invité 2.4GHz",
	"Guest Zone 5GHz": "Zone invité 5GHz",
	"IP Address": "Adresse IP",
	"Subnet Mask": "Masque de sous-réseau",
	"Default Gateway": "Passerelle par défaut",
	"Available Space": "Espace libre",
	"Total Space": "Espace total",
	"Service Name": "Nom du service",
	"Ethernet Device": "Périphérique Ethernet",
	"Wi-Fi Clients": "Clients Wi-Fi",
	"USB Device": "Périphérique USB",
	"USB Name": "Nom USB",
	"Status": "État",
	"Wi-Fi Name (SSID)": "Nom Wi-Fi (SSID)",
	"Password": "Mot de passe",
	"IPv6 Connection Type": "Type de connexion IPv6",
	"WAN IPv6 Address": "Adresse IPv6 du réseau étendu",
	"Primary IPv6 DNS Server": "Serveur DNS IPv6 principal",
	"Secondary IPv6 DNS Address": "Adresse DNS IPv6 secondaire",
	"LAN IPv6 Link-Local Address": "Adresse lien-local du réseau local IPv6",
	"DHCP-PD": "DHCP-PD",
	"IPv6 Network Assigned by DHCP-PD": "Réseau IPv6 attribué par DHCP-PD",
	"LAN IPv6 Address": "Adresse IPv6 du réseau local",
	"Guest Zone": "Zone invité",
	"Connection Type": "Type de connexion",
	"Network Status": "État du réseau",
	"Connection Up Time": "Durée d'activation de la connexion",
	"Primary DNS Server": "Serveur DNS principal",
	"Secondary DNS Server": "Serveur DNS secondaire",
	"SharePort": "SharePort",
	"Release": "Version",
	"Renew": "Renouveler",
	"Disconnect": "Déconnexion",
	"Connect": "Connexion",
	"Ignore": "Ignore",
	"Connected": "Connected",
	"Connecting": "Connecting",
	"Disconnected": "Disconnected",
	"DHCP": "Dynamic IP (DHCP)",
	"Static": "Static IP (Static)",
	"DHCPPPPoE": "Dynamic IP (PPPoE)",
	"StaticPPPoE": "Static IP (PPPoE)",
	"DynamicPPTP": "Dynamic IP (PPTP)",
	"StaticPPTP": "Static IP (PPTP)",
	"DynamicL2TP": "Dynamic IP (L2TP)",
	"StaticL2TP": "Static IP (L2TP)",
	"A new firmware is available! Do you want to download and upgrade the firmware?": "A new firmware is available! Do you want to download and upgrade the firmware?",
	"Your changes are being saved, and the device will need to reboot.": "Your changes are being saved, and the device will need to reboot.",
	"The Wi-Fi connection is not secure.": "The Wi-Fi connection is not secure.",
	"Secure your network.": "Secure your network.",
	
	// Wizard
	"Welcome": "Bienvenue",
	"This wizard will guide you through a step-by-step process to configure your new D-Link device.": "Cet assistant vous guidera étape par étape pour configurer votre nouveau périphérique D-Link.",
	"Step1: Install your device": "Étape 1 : Installez votre périphérique",
	"Step2: Configure your Network and Wi-Fi settings": "Étape 2 : Configurez votre réseau et vos paramètres Wi-Fi",
	"Step3: Set your router password": "Étape 3: Définissez le mot de passe de votre routeur",
	"Step4: Set mydlink service": "Étape 4 : Configurez le service mydlink",
	"Your Device": "Votre périphérique",
	"Cable/xDSL Broadband Modem": "Modem haut-débit câble/xDSL",
	"DHCP Connection (Dynamic IP Address)": "Connexion DHCP (adresse IP dynamique)",
	"Choose this if your Internet connection automatically provides you with an IP Address. Most Cable Modems use this type of connection.": "Choisissez cette option si votre connexion Internet vous fournit automatiquement une adresse IP. La plupart des modems câblés utilisent ce type de connexion.",
	"Username/Password Connection (PPPoE)": "Connexion par nom d'utilisateur/mot de passe (PPPoE)",
	"Choose this option if your Internet connection reguires a username and passowrd to get online. Most DSL modems use this connection type of connection.": "Choisissez cette option si votre connexion Internet requiert un nom d'utilisateur et un mot de passe. La plupart des modems DSL utilisent ce type de connexion.",
	"Static IP Address Connection": "Adresse IP statique de connexion",
	"Choose this option if your Internet Setup Provider provided you with IP Address information that has to be manually configured.": "Choisissez cette option si votre fournisseur d'accès Internet vous a fourni des informations relatives à l'adresse IP à configurer manuellement.",
	"Username": "Nom d'utilisateur",
	"Gateway Address": "Adresse de passerelle",
	"Primary DNS Address": "Adresse DNS principale",
	"Secondary DNS Address": "Adresse DNS secondaire",
	"2.4GHz Wi-Fi Network Name": "Nom du réseau Wi-Fi 2.4GHz",
	"5GHz Wi-Fi Network Name": "Nom du réseau Wi-Fi 5GHz",
	"The Wi-Fi Network Name is up to 32 characters. You will need to join your Wi-Fi network using this Network Name (SSID).": "Le nom du réseau Wi-Fi peut comporter jusqu'à 32 caractères. Vous devez rejoindre votre réseau Wi-Fi en utilisant ce nom de réseau (SSID).",
	"Wi-Fi Password": "Mot de passe Wi-Fi",
	"Copy to 5GHz": "Copier à  5GHz",
	"2.4GHz Wi-Fi Password": "Mot de passe Wi-Fi 2.4GHz",
	"5GHz Wi-Fi Password": "Mot de passe Wi-Fi 5GHz",
	"The password must contain at least 8 characters. You will need to join your Wi-Fi network using this password.": "Le mot de passe doit comporter au moins 8 caractères. Vous devrez utiliser ce mot de passe pour rejoindre votre réseau Wi-Fi.",
	"Device Admin Password": "Mot de passe admin du périphérique",
	"This device is mydlink-enabled, which allows you to remotely monitor and manage your network through the mydlink.com website, or through the mydlink mobile app.": "Ce périphérique est compatible mydlink, ce qui vous permet de surveiller et de gérer à distance votre réseau via le site web mydlink.com ou via l'app. mobile mydlink.",
	"You can register this device with your existing mydlink account. If you do not have one, you can create one now.": "Vous pouvez enregistrer cet appareil sur votre compte mydlink existant. Si vous n'en avez pas, vous pouvez en créer un maintenant.",
	"Do you have an existing mydlink account": "Avez-vous déjà un compte mydlink ?",
	"Yes, I have a mydlink account": "Oui, j'ai un compte mydlink",
	"No, I want to create a new mydlink account": "Non, je veux créer un nouveau compte mydlink",
	"E-mail Address (Account Name)": "Adresse électronique (nom du compte)",
	"First Name": "Prénom",
	"Last Name": "Nom",
	"I accept the mydlink": "J'accepte les conditions générales",
	"terms and conditions.": "mydlink.",
	"Connect to the Wi-Fi network from your mobile device or PC": "Connectez-vous au réseau Wi -Fi à partir de votre appareil mobile ou de votre PC",
	"1.Please go to Settings > Wi-fi, and choose": "1.Accédez à Settings > Wi-fi, et choisissez",
	"from the list of Wi-Fi network services.": "dans la liste des services réseau Wi-Fi.",
	"2.Enter the password you just setup when prompted.": "2.Saisissez à l'invite le mot de passe que vous venez de configurer.",
	"Checking Internet connectivity": "Contrôle de la connectivité Internet",
	"Wi-Fi Client": "Client Wi-Fi",
	"Save": "Enregistrer",
	"Please wait": "Veuillez patienter",
	"Configure Your Internet Connection": "Configurez votre connexion Internet",
	"Detecting Internet connection": "Détection d'une connexion Internet",
	"Install": "Installer",
	"Please plug one end of the Ethernet cable included with your device into the port labeled INTERNET on your device. Plug the other end of this cable into the Ethernet port on yourDSL or cable broadband modem, and power cycle the modem.": "Branchez une extrémité du câble Ethernet joint au périphérique dans le port étiqueté INTERNET du périphérique. Branchez l'autre extrémité de ce câble dans le port Ethernet sur votre modem haut débit câble ou DSL.",
	"Please select your Internet connection type below": "Sélectionnez votre type de connexion Internet ci-dessous",
	"PPPoE": "PPPoE",
	"To setup this Internet connection, you will need to have a User Name from your InternetService Provider. If you do not have this information, please contact your ISP.": "Pour configurer cette connexion Internet, vous devez disposer d'un nom d'utilisateur fourni par votre fournisseur d'accès Internet. Si vous ne disposez pas de ces informations, contactez votre fournisseur d'accès Internet.",
	"Static IP": "Adresse IP statique",
	"Dynamic IP (DHCP)": "Adresse IP dynamique (DHCP)",
	"To set up this conncetion you will need to have a complete list of IP information by your Internet Service Provider. If you have a Static IP connection and do not have this information, please contact your ISP.": "Pour configurer cette connexion, vous devez disposer d'une liste complète des informations IP qui doit vous être fournie par votre fournisseur d'accès Internet. Si vous possédez une connexion par adresse IP statique, mais que vous n'avez pas ces informations, contactez votre FAI.",
	"Wi-Fi Settings": "Paramètres Wi-Fi",
	"To setup a Wi-Fi Network you will need to give your Wi-Fi Nerwork a Name(SSID) and Password.": "Pour configurer un réseau Wi-Fi, vous devez indiquer à votre réseau Wi-Fi un nom (SSID) et un mot de passe.",
	"By default, your new D-Link device does not have a password configured for administrator access to the Web-based configuration utility. To secure your new device, please create a password below.": "Par défaut, votre nouveau périphérique D-Link ne possède aucun mot de passe configuré pour l'accès administrateur à l'utilitaire de configuration Web. Pour sécuriser votre nouveau périphérique, créez un mot de passe ci-dessous.",
	"Setup Complete": "Configuration terminée",
	"Below is a summary of your Wi-Fi security and device password settings.Please take a note of your settings and save your configuration.": "Voici un résumé de vos paramètres de sécurité Wi-Fi et de mot de passe périphérique. Veuillez noter ces paramètres et enregistrer votre configuration.",
	"Checking Your Internet connectivity": "Contrôle de votre connectivité Internet",
	"Checking Internet connectivity": "Contrôle de la connectivité Internet",
	"mydlink Regristration": "Enregistrement mydlink",
	"Congratulations": "Félicitations",
	"Congratulations,your device has been configured. You can now connect to your Wi-Fi network by using the new Wi-Fi Network Name and Password you created.": "Félicitations, votre périphérique a été configuré. Vous pouvez maintenant vous connecter à votre réseau Wi-Fi à l'aide du nouveau nom de réseau et mot de passe Wi-Fi que vous avez créés.",
	"Back": "Retour",
	"Next": "Suivant",
	"Skip": "Ignorer",
	"Finish": "Terminer",
	"Registered": "Registered",
	"Unregistered": "Unregistered",
	
	// Ethernet, Wireless, Wireless_Guest
	"Wi-Fi Clients (Guest Zone)": "Clients Wi-Fi (Zone invité)",
	"Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.",
	"Here, you can see a list of all devices connected through Wi-Fi. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Cet espace affiche la liste de tous les périphériques connectés en Wi-Fi. Cliquez sur un périphérique pour afficher des informations supplémentaires, ou cliquez sur l'icône crayon pour donner un nom au périphérique pour qu'il soit plus facile à identifier. Vous pouvez bloquer l'accès d'un périphérique à votre réseau de façon permanente ou selon un calendrier en utilisant la liste déroulante de blocage.",
	"Vendor": "Fournisseur",
	"Reserve IP": "Reservation d'adresses IP",
	"Access": "Accès",
	"Allowed": "Autorisé",
	"Blocked": "Bloqué",
	
	// Internet > IPv4
	"Use this section to configure your Internet Connection type. There are several connection types to choose from Static IP, DHCP, PPPoE, PPTP, L2TP, and DS-Lite. If you are unsure of your connection method, please contact your Internet Service Provider. Note:  If using the PPPoE option, you will need to remove or disable any PPPoE client software on your computers.": "Utilisez cette section pour configurer votre type de connexion Internet. Vous pouvez choisir entre plusieurs types de connexion : IP statique, DHCP, PPPoE, PPTP, L2TP et DS-Lite. Si vous n'êtes pas sûr(e) de votre méthode de connexion, contactez votre fournisseur d'accès Internet. Remarque :  Si vous utilisez l'option PPPoE, vous devez supprimer ou désactiver le logiciel PPPoE client de vos ordinateurs.",
	"My Internet Connection is": "Ma connexion Internet est",
	"Host Name": "Nom d'hôte",
	"Mac Address Clone": "Clone d'adresse Mac",
	"PPTP IP Address": "Adresse IP de PPTP",
	"PPTP Server IP Address": "Adresse IP du serveur PPTP",
	"PPTP Subnet Mask": "Masque de sous-réseau PPTP",
	"PPTP Gateway IP Address": "Adresse IP d'une passerelle PPTP",
	"L2TP IP Address": "Adresse IP de L2TP",
	"L2TP Server IP Address": "Adresse IP du serveur L2TP",
	"L2TP Subnet Mask": "Masque du sous-réseau L2TP",
	"L2TP Gateway IP Address": "Adresse IP de la passerelle L2TP",
	"MTU": "MTU",
	"Address Mode": "Mode adresse",
	"Reconnect Mode": "Mode de reconnexion",
	"Maximum Idle Time": "Temps d'inactivité maximum",
	"DS-Lite Configuration": "Configuration de DS-Lite",
	"DS-Lite DHCPv6 Option": "Option DHCPv6 de DS-Lite",
	"Manual Configuration": "Configuration manuelle",
	"AFTR IPv6 Address": "Adresse IPv6 en AFTR",
	"B4 IPv4 Address": "Adresse IPv4 en B4",
	"WAN IPv6 Address": "Adresse IPv6 du réseau étendu",
	"IPv6 WAN Default Gateway": "Passerelle IPv6 par défaut du réseau étendu",
	"Advanced Settings": "Paramètres avancés",
	"Manual": "Manuel",
	"Always on": "Toujours activée",
	"On demand": "À la demande",
	"Dynamic IP": "Dynamic IP",
	
	// Internet > IPv6
	"All of your IPv6 Internet and network connection details are displayed on this page.": "Tous les détails de votre connexion réseau et Internet IPv6 sont affichés sur cette page.",
	"Auto Detection": "Détection automatique",
	"Static IPv6": "IPv6 statique",
	"Auto Configuration (SLAAC/DHCPv6)": "Autoconfiguration (SLAAC/DHCPv6)",
	"IPv6 in IPv4 Tunnel": "Tunnel IPv6 en IPv4",
	"6to4": "6to4",
	"Local Connectivity Only": "Connectivité locale uniquement",
	"Use Link-Local Address": "Utiliser l'adresse lien-local",
	"Subnet Prefix Length": "Longueur du préfixe de sous-réseau",
	"PPPoE Session": "Session PPPoE",
	"Remote IPv4 Address": "Adresse IPv4 distante",
	"Remote IPv6 Address": "Adresse IPv6 distante",
	"Local IPv4 Address": "Adresse IPv4 locale",
	"Local IPv6 Address": "Adresse IPv6 locale",
	"6to4 Address": "Adresse 6to4",
	"6to4 Relay": "Relais 6to4",
	"Assign IPv6 Prefix": "Attribuer un préfixe IPv6",
	"LAN IPv6 Link-Local Address": "Adresse lien-local du réseau local IPv6",
	"IPv6 DNS SETTINGS": "PARAMÈTRES DNS IPv6",
	"LAN IPv6 ADDRESS SETTINGS": "PARAMÈTRES DE L'ADRESSE IPV6 DU RÉSEAU LOCAL",
	"LAN IPv6 Address": "Adresse IPv6 du réseau local",
	"ADDRESS AUTOCONFIGURATION SETTINGS": "PARAMÈTRES D'AUTOCONFIGURATION D'ADRESSE",
	"Enable Automatic IPv6 Address Assignment": "Activer l'affectation automatique d'adresse IPv6",
	"Enable Automatic DHCP-PD in LAN": "Activer le DHCP-PD automatique sur le réseau local",
	"Autoconfiguration Type": "Type d'autoconfiguration",
	"Enable DHCP-PD": "Activer le DHCP-PD",
	"6RD MANUAL CONFIGURATION": "CONFIGURATION MANUELLE 6RD",
	"Enable Hub and Spoke Mode": "Activez le mode Système et réseau en étoile",
	"6rd Configuration": "Configuration 6rd",
	"6rd IPv6 Prefix": "Préfixe IPv6 en 6rd",
	"6rd Border Relay IPv4 Address": "Adresse IPv4 du relais 6rd en bordure du réseau",
	"IPv6 ULA SETTINGS": "PARAMÈTRES ULA IPv6",
	"Enable ULA": "Activer ULA",
	"Use Default ULA Prefix": "Utiliser le préfixe ULA par défaut",
	"ULA Prefix": "Préfixe ULA",
	"CURRENT IPv6 ULA SETTINGS": "PARAMÈTRES ULA IPv6 ACTUELS",
	"Current ULA Prefix": "Préfixe ULA actuel",
	"LAN IPv6 ULA": "ULA IPv6 du réseau local",
	"minutes": "minutes",
	"DNS Type": "Type DNS",
	"Obtain a DNS server address automatically": "Obtenir automatiquement une adresse de serveur DNS",
	"Use the following DNS address": "Utiliser l'adresse DNS suivante",
	"SLAAC+Stateless DHCP": "SLAAC+DHCP sans état",
	"Stateful DHCPv6": "DHCPv6 à état",
	"6rd DHCPv4 Option": "Option DHCPv4 en 6rd",
	"Share with IPv4": "Partager avec IPv4",
	"Create a new session": "Créer une nouvelle session",
	"bytes": "bytes",
	"Router Advertisement Lifetime": "Router Advertisement Lifetime",
	"IPv6 Address Range (Start)": "IPv6 Address Range (Start)",
	"IPv6 Address Range (End)": "IPv6 Address Range (End)",
	"IPv6 Address Lifetime": "IPv6 Address Lifetime",
	
	// WiFi & Guest Zone
	"Security Mode": "Mode de sécurité",
	"None": "Aucune",
	"WPA-Personal": "WPA personnel",
	"Auto": "Auto",
	"High": "Élevée",
	"Low": "Basse",
	"802.11 Mode": "Mode 802.11",
	"Wi-Fi Channel": "Canal Wi-Fi",
	"Transmission Power": "Puissance de transmission",
	"Channel Width": "Largeur de canal",
	"Visibility Status": "État de visibilité",
	"Visible": "Visible",
	"Invisible": "Invisible",
	"Mixed 802.11b/g": "Mode mixte 802.11b/g",
	"Mixed 802.11g/n": "Mode mixte 802.11g/n",
	"Mixed 802.11b/g/n": "Mode mixte 802.11b/g/n",
	"Auto 20/40 MHz": "Mode auto 20/40 MHz",
	"Mixed 802.11a and 802.11n": "Mode mixte 802.11a et 802.11n",
	"Use this section to configure the wireless settings for your D-Link Router. Please note that changes made on this section may also need to be duplicated on your Wireless Client.": "Cette section vous permet de configurer les paramètres sans fil de votre routeur D-Link. Notez que les éventuelles modifications réalisées dans cette section doivent également être apportées à votre client sans fil.",
	"This page lets you configure a Wi-Fi Guest Zone. Wi-Fi Guest Zones are Wi-Fi networks that are separate from your normal ones, and use different Wi-Fi Network Names and passwords. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless the Access Local Service option is enabled. Guest Zones are useful to give guests Internet access without allowing them to access your own devices on your network.": "Cette page vous permet de configurer une zone invité Wi-Fi. Les zones invité Wi-Fi sont des réseaux Wi-Fi distincts de vos réseaux normaux et utilisent différents noms et mots de passe de réseau Wi-Fi. Les utilisateurs connectés à une zone invité ne peuvent pas communiquer ou détecter des périphériques sur votre réseau normal sauf si vous avez activé l'option Access Local Service (Service d'accès local). Les zones invité sont utiles pour fournir aux invités un accès Internet sans leur permettre d'accéder à vos propres périphériques sur votre réseau.",
	"Internet Access Only": "Accès Internet uniquement",
	"Routing Between Zones": "Acheminement entre zones",
	"Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.": "Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.",
	"Your changes are being saved.": "Your changes are being saved.",
	
	// Network
	"Network": "Réseau",
	"Network Settings": "Paramètres réseau",
	"DHCP Server": "Serveur DHCP",
	"Use this page to configure the local network settings for your router, including the IP address you use to access this configuration interface. Please note that if you change this IP address, you will need to use the new IP to access this interface.": "Utilisez cette page pour configurer les paramètres du réseau local de votre routeur, y compris l'adresse IP que vous voulez utiliser pour accéder à cette interface de configuration. Veuillez noter que si vous modifiez cette adresse IP, vous devrez utiliser la nouvelle adresse IP pour accéder à cette interface.",
	"LAN IP Address": "Adresse IP du réseau local",
	"Device Name": "Nom du périphérique",
	"Local Domain Name": "Nom de domaine local",
	"Enable DNS Relay": "Activer le relais DNS",
	"DHCP IP Address Range": "Plage d'adresses IP DHCP",
	"DHCP Lease Time": "Durée de la concession DHCP",
	"Always Broadcast": "Toujours diffuser",
	"compatibility for some DHCP Clients": "compatibilité de certains clients DHCP",
	"If you changed the IP address of the router you will need to change the IP address in your browser before accessing the configuration website again.": "Si vous avez modifié l'adresse IP du routeur, vous devrez modifier l'adresse IP dans votre navigateur avant d'accéder de nouveau au site web de configuration.",
	"The new settings have been saved.": "Les nouveaux paramètres ont été enregistrés.",
	"to": "to",
	
	// Advanced Network
	"Advanced Network": "Réseau avancé",
	"Advanced Network settings allow you to configure some of the more advanced features of your router. It is recommended that you only change these settings if you are  familiar with them, or if you are specifically instructed to do so.": "Les paramètres Réseau avancé vous permettent de configurer certaines des fonctions les plus avancées de votre routeur. Il est recommandé de ne changer ces paramètres que si vous les connaissez bien ou si vous avez reçu des instructions spécifiques pour le faire.",
	"UPnP": "UPnP",
	"WAN Port Speed": "Vitesse du port du réseau étendu",
	"IPv4 Multicast Streams": "Flux de multidiffusion IPv4",
	"IPv6 Multicast Streams": "Flux de multidiffusion IPv6",
	"Auto (10/100/1000 Mbps)": "Auto (10/100/1000 Mbps)",
	
	// SharePort
	"SharePort": "SharePort",
	"DLNA (Digital Living Network Alliance) is the standard for the interoperability of Network Media Devices (NMDs). The user can enjoy multi-media applications (music, pictures and videos) on your network connected PC or media devices. Web File Access allows you to use a web browser to remotely access files stored on an SD card or USB storage drive plugged into the router.": "La norme DLNA (Digital Living Network Alliance) est la norme d'interopérabilité des appareils réseaux multiples (Network Media Devices ou NMD). L'utilisateur peut profiter des applications multimédias (musique, photos et vidéos) sur les PC et les périphériques connectés au réseau. Web File Access vous permet d'utiliser un navigateur web pour accéder à distance aux fichiers stockés sur une carte SD ou un disque de stockage USB connecté au routeur.",
	"DLNA Media Server Configuration": "Configuration du Serveur multimédia DLNA",
	"DLNA Media Server": "Serveur multimédia DLNA",
	"Web File Access": "Web File Access",
	"Remote Access Port": "Port d'accès distant",
	"Remote HTTPS Port": "Port HTTPS distant",
	"Enable Storage Remote Access": "Activer l'accès distant au stockage",
	"Direct Links": "Liens directs",
	"Local Access": "Accès local",
	"SharePort Web Access": "Accès Web à SharePort",
	
	// SharePort CreateUser
	"\"Create User\" manage access to your storage devices or use the Guest account (guest/guest) to access the Guest Folder. After plugging in an SD card or USB storage drive, the new device will appear in the list with a link to it. You can then use this link to connect the drive and login with a user account.": "\"Create User\" gère l'accès à vos périphériques de stockage ou utilise le compte Invité (invité/invité) pour accéder au dossier invité. Après le branchement d'une carte SD ou d'un disque de stockage USB, le nouveau périphérique apparaîtra dans la liste avec un lien associé. Vous pouvez ensuite utiliser ce lien pour connecter le disque et vous connecter avec un compte utilisateur.",
	"Remote Access": "Accès distant",
	"Create User": "Créer un utilisateur",
	"User Name": "Nom d’utilisateur",
	"Access Path": "Chemin d'accès",
	"Permission": "Permission",
	"Edit": "Modifier",
	"Delete": "Supprimer",
	"Browse": "Parcourir",
	"OK": "OK",
	"Create User": "Créer un utilisateur",
	"Create New User": "Créer un nouvel utilisateur",
	"Edit User Profile": "Modifier le profil utilisateur",
	"Folder": "Dossier",
	"Select Folder": "Dossier choisi",
	"USB Device Name": "Nom du périphérique USB",
	"Number of Device": "Numéro du périphérique",
	
	// mydlink
	"Setting and registering your router with mydlink will allow you to use its mydlink cloud services features, including online access and management of your router through the mydlink portal website.": "La configuration et l'enregistrement de votre routeur sur mydlink vous permet d'utiliser les fonctions de cloud mydlink, notamment l'accès en ligne et la gestion de votre routeur via le portail Web mydlink.",
	"mydlink Registration": "Inscription sur mydlink",
	"Sign Up": "Connexion",
	"Sign In": "Connexion",
	"Please enter your e-mail address and mydlink password.": "Veuillez saisir votre adresse électronique et votre mot de passe de connexion à mydlink.",
	"You must accept the terms and conditions to continue.": "Vous devez accepter les conditions générales pour continuer.",
	
	// QoS Engine
	"QoS Engine": "Moteur QoS",
	"QoS prioritizes your network traffic so you can decide what devices should have priority over other devices. For example, you could set a computer that is downloading files to have lower priority than a laptop that is streaming movies to ensure that you can stream movies smoothly without downloads taking up all of your bandwidth.": "Le moteur QoS gère les priorités de votre trafic réseau pour que vous puissez choisir des périphériques qui ont prioritté sur les autres. Par exemple, vous pouvez configurer un ordinateur qui télécharge des fichiers pour qu'il ait une priorité inférieure à un ordinateur portable qui diffuse des films ; vous êtes ainsi certain(e) de diffuser les films en toute tranquillité sans que les téléchargements ne prennent toute votre bande passante.",
	"All Devices": "Tous les périphériques",
	"Drag the device cards above to the Prioity boxes below.": "Faites glisser les cartes des périphériques sur les cases Priorité ci-dessous.",
	"Highest": "Maximale",
	"Medium": "Moyenne",
	
	// Firewall
	"Firewall Settings": "Paramètres du pare-feu",
	"Here, you can set up various firewall features to protect your network from attacks. You can click on the DMZ, IPv4 Rules, and IPv6 Rules buttons to see the settings for that feature.": "Ici, vous pouvez configurer plusieurs fonctions de pare-feu pour protéger votre réseau d'attaques. Vous pouvez cliquer sur les boutons DMZ, règles IPv4 et règles IPv6 pour voir les paramètres de cette fonction.",
	"Application Level Gateway (ALG) Configuration": "Configuration de la passerelle de niveau application (ALG)",
	"Enable SPI IPv4": "Activer SPI IPv4",
	"Enable Anti-spoof Checking": "Activer le contrôle anti-usurpation",
	"IPv6 Simple Security": "Sécurité simple IPv6",
	"PPTP": "PPTP",
	"IPSec (VPN)": "IPSec (VPN)",
	"RTSP": "RTSP",
	"SIP": "SIP",
	"IPv4 Rules": "Règles IPv4",
	"IPv6 Rules": "Règles IPv6",
	"Firewall": "Pare-feu",
	"Enable DMZ Host": "Activer l'hôte DMZ",
	"DMZ IP Address": "Adresse IP de la DMZ",
	"Security Check": "Contrôle de sécurité",
	
	// Firewall IPv4, IPv6
	"The IPv4 rule section is an advance feature used to deny or allow traffic from passing through the device.": "La section des règles IPv4 est une fonction avancée servant à refuser ou à autoriser le passage du trafic par le périphérique.",
	"The IPv6 rule section is an advance feature used to deny or allow traffic from passing through the device.": "La section de la règle IPv6 est une fonction avancée servant à refuser ou à autoriser le passage du trafic par le périphérique.",
	"Add Rules": "Ajouter des règles",
	"Name": "Nom",
	"Schedule": "Calendrier",
	"Create New Rule": "Créer une nouvelle règle",
	"Source IP Address Range": "Plage d'adresses IP source",
	"Destination IP Address Range": "Plage d'adresses IP de destination",
	"Port Range": "Plage de ports",
	"Turn IPv4 Filtering OFF": "DÉSACTIVER le filtrage IPV4",
	"Turn IPv4 Filtering ON and ALLOW rules listed": "ACTIVER le filtrage IPv4 et AUTORISER les règles énumérées",
	"Turn IPv4 Filtering ON and DENY rules listed": "ACTIVER le filtrage IPv4 et REFUSER les règles énumérées",
	"Turn IPv6 Filtering OFF": "DÉSACTIVER le filtrage IPv6",
	"Turn IPv6 Filtering ON and ALLOW rules listed": "ACTIVER le filtrage IPv6 et AUTORISER les règles énumérées",
	"Turn IPv6 Filtering ON and DENY rules listed": "ACTIVER le filtrage IPv6 et REFUSER les règles énumérées",
	
	// Port Forwarding
	"Port Forwarding is used to open ports in your router and to redirect traffic to those ports to a specific device on your network. This may be needed for specific applications, games, or services. You can enter individual ports (80, 68, 888), port ranges (100-150), or in a mixed format (1020-5000, 689).": "La redirection de port sert à ouvrir les ports dans votre routeur et à rediriger le trafic sur ces ports vers un périphérique spécifique sur votre réseau. Ceci peut être nécessaire pour des applications, des jeux ou des services spécifiques. Vous pouvez entrer des ports individuels (80, 68, 888), des plages de port (100-150) ou un format mixte (1020-5000, 689).",
	"Local IP": "IP locale",
	"TCP Port": "Port TCP",
	"UDP Port": "Port UDP",
	
	// Virtual Server
	"The Virtual Server option allows you to define a single public port on your router for redirection to an internal LAN IP Address and Private LAN port if required. This feature is useful for hosting online services such as FTP or Web Servers.": "L'option Serveur virtuel vous permet de définir un seul port public sur votre routeur, qui sera redirigé vers une adresse IP interne et un port privé du réseau local, si nécessaire. Cette option est utile pour héberger les services en ligne, comme les serveurs FTP ou Web.",
	"Protocol": "Protocole",
	"External Port": "Port externe",
	"Internal Port": "Port interne",
	"Protocol Number": "Protocol Number",
	
	// Website Filter
	"The Website Filter option allows you to set up a list of Web sites you would like to allow or deny through your network. To use this feature, you must also select the \"Apply Web Filter\" checkbox in the Access Control section.": "L'option Filtre des sites Web vous permet de configurer une liste de sites Web auxquels vous souhaitez autoriser ou refuser l'accès à travers votre réseau. Pour utiliser cette fonction, vous devez également cocher la case \"Appliquer le filtre Web\" dans la section Contrôle d'accès.",
	"DENY computers access to ONLY these sites": "REFUSER l’accès des ordinateurs à ces sites UNIQUEMENT",
	"ALLOW computers access to ONLY these sites": "AUTORISER l’accès des ordinateurs à ces sites UNIQUEMENT",
	"Website URL/Domain": "URL/domaine du site Web",
	
	// StaticRouter, StaticRouterIPv6
	"Static Routes": "Routes statiques",
	"This page allows you to define custom routes to define how data traffic is moved around your network.": "Cette page vous permet de définir des voies personnalisées qui déterminent la manière dont les données sont transférées autour de votre réseau.",
	"Destination IP": "IP cible",
	"Netmask": "Masque de réseau",
	"Gateway": "Passerelle",
	"Matrix": "Matrice",
	"Interface": "Interface",
	"DestNetwork": "DestNetwork",
	"PrefixLen": "PrefixLen",
	
	// DynamicDNS
   	"Dynamic DNS (DDNS) allows you to use an easy to remember domain name such as www.[YourDomainName].com to reach your router\'s dynamically assigned IP address. This is useful when hosting a web, FTP, or game server, and allows you to reach your server no matter what your IP address has changed to. D-Link offers a free DDNS service that you can use through www.DLinkDDNS.com.": "Dynamic DNS (DDNS) vous permet d'utiliser un nom de domaine facile à retenir comme www.[YourDomainName].com pour atteindre l'adresse IP dynamiquement affectée à votre routeur. Cette option est utile lorsque vous hébergez un web, un FTP ou un serveur de jeux et vous permet d'atteindre votre serveur quelle que soit la nouvelle adresse IP. D-Link offre un service DDNS gratuit que vous pouvez utiliser via www.DLinkDDNS.com.",
	"Server Address": "Adresse du serveur",
	"Dynamic DNS": "DNS dynamique",
	"Enable Dynamic DNS": "Activer le DNS dynamique",
	"Select Server Name": "Sélectionner le nom du serveur",
	"Time Out": "Expiration du délai",
	"IPv6 Address": "Adresse IPv6",
	"hours": "heures",
	
	// Time
	"Time & Schedule": "Calendrier",
	"Time": "Heure",
	"Time Confuguration": "Configuration de l'heure",
	"Automatic Time Confuguration": "Configuration automatique de l'heure",
	"Manual Time Confuguration": "Configuration manuelle de l'heure",
	"Date": "Date",
	"This page allows you to set the router\'s internal system clock. You can set the time manually, or automatically through a time server.": "Cette page vous permet de configurer l'horloge système interne du routeur. Vous pouvez régler l'heure manuellement ou automatiquement via un serveur de temps.",
	"System Time": "Heure du système",
	"Time Zone": "Fuseau horaire",
	"Enable Daylight Saving": "Activer l'heure d'été",
	"Update Time Using an NTP Serevr": "Mettre à jour l'heure avec un serveur NTP",
	"Year/ Month/ Day": "Année/ Mois/ Jour",
	"Hour/ Minute": "Heure/ Minute",
	"Day": "Jour",
	"Hour": "Heure",
	"Min": "Min",
	"Sec": "Sec",
	
	// Schedule
	"The Schedule configuration option is used to manage schedule rules for various firewall and parental control features.": "L'option de configuration des calendriers permet de gérer des règles de calendrier pour diverses fonctions du pare-feu et de contrôle parental.",
	"Monday": "Monday",
	"Tuesday": "Tuesday",
	"Wednesday": "Wednesday",
	"Thursday": "Thursday",
	"Friday": "Friday",
	"Saturday": "Saturday",
	"Sunday": "Sunday",
	"All Day": "All Day",
	"All Week": "All Week",
	"Always": "Always Enable",
	
	// System Log
	"System Log": "Journal système",
	"SysLog Settings": "Paramètres de SysLog",
	"This page allows you to enable logging of system events to a SysLog server, or to e-mail the log to you according to a schedule or when the log is full.": "Cette page vous permet d'activer la journalisation des événements système vers un serveur SysLog ou de vous envoyer par courrier électronique le journal selon un calendrier ou lorsqu'il est plein.",
	"SysLog Server IP Address": "Adresse IP du serveur SysLog",
	"Enable Logging to Syslog Server": "Activer la journalisation sur un serveur SysLog",
	"E-mail Settings": "Paramètres de messagerie",
	"E-mail Log When Full or On Schedule": "Envoyer le journal par courrier électronique lorsqu'il est plein ou selon un calendrier",
	"Enable E-mail Notification": "Activer la notification par courrier électronique",
	"From E-mail Address": "Adresse de courrier électronique De",
	"To E-mail Address": "Adresse de courrier électronique À",
	"SMTP Server Address": "Adresse du serveur SMTP",
	"SMTP Server Port": "Port du serveur SMTP",
	"Enable Authentication": "Activer l'authentification",
	"Account Name": "Nom du compte",
	"On Log Full": "Quand le journal est plein",
	"On Schedule": "Selon calendrier",
	
	// System
	"System": "Système",
	"Save Configuration": "Enregistrer la configuration",
	"Restore Configuration From File": "Restaurer la configuration à partir d'un fichier",
	"Restore Factory Default": "Restaurer le paramètre par défaut",
	"Reboot": "Réinitialiser",
	"This page lets you save your router\'s current settings to a file, restore your settings from a file, restore your router to factory default settings, or reboot the device. Please note that restoring the settings to the factory defaults will erase all settings, including any rules you have created.": "Cette page vous permet d'enregistrer les paramètres actuels de votre routeur sur un fichier, de restaurer vos paramètres à partir d'un fichier, de restaurer votre routeur aux paramètres usine par défaut ou de relancer le périphérique. La restauration des paramètres par défaut efface tous vos paramètres, y compris toutes les règles que vous avez créées.",
	"Save Settings To Local Hard Drive": "Enregistrer les paramètres sur le disque dur local",
	"Load Settings From Local Hard Drive": "Charger les paramètres depuis le disque dur local",
	"Restore To Factory Default Settings": "Restaurer les paramètres par défaut",
	"Reboot The Device": "Réinitialiser le périphérique",
	"Cancel": "Annuler",
	"Are you sure you want to restore configuration file?": "Voulez-vous vraiment restaurer le fichier de configuration ?",
	"Do not close the page or power off the service until the restore configuration file is complete!": "Ne fermez pas la page ou n'interrompez pas le service tant que la configuration du fichier de configuration n'est pas terminée !",
	"Restore configuration file failed!": "La restauration du fichier de configuration a échoué !",
	"Restore configuration file success!": "La restauration du fichier de configuration a réussi !",
	"Are you sure you want to reset the device?": "Voulez-vous vraiment réinitialiser le périphérique ?",
	"Rebooting": "Réinitialisation",
	"Reboot success!": "Réinitialisation réussie !",
	"Are you sure you want to reset the device to its factory default settings? This will cause current settings to be lost.": "Voulez-vous vraiment réinitialiser le périphérique aux paramètres d'usine par défaut ? Vous perdrez vos paramètres actuels.",
	"Restore to factory default success!": "La restauration des paramètres par défaut a réussi !",
	"Select File": "Sélectionner un fichier",
	"Restore": "Restaurer",
	"Restore Factory Default": "Restaurer le paramètre par défaut",
	
	// Admin
	"Admin": "Administrateur",
	"Admin Password": "Mot de passe d'administration",
	"Administration": "Administration",
	"Use HTTPS": "Utiliser HTTPS",
	"The admin has read/write access and can change passwords, while the user has read-only access. By default there is no password configured. It is highly recommended that you create a password to keep your router secure.": "L’admin possède un accès de lecture/écriture et peut modifier les mots de passe, alors que l’utilisateur possède un accès en lecture seule. Par défaut, aucun mot de passe n'est configuré. Il est vivement recommandé de créer un mot de passe pour que votre routeur reste sécurisé.",
	"Enable Graphical Authentication (CAPTCHA)": "Activer l'authentification graphique (CAPTCHA)",
	"Enable HTTPS Server": "Activer le serveur HTTPS",
	"Enable Remote Management": "Activer la gestion à distance",
	"Remote Admin Port": "Port d’administration à distance",
	"Remote Admin Inbound Filter": "Filtre entrant d'administration à distance",
	
	// Update Firmware
	"Upgrade Firmware": "Mises à jour du microprogramme",
	"This page shows you your current firmware version and language pack, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below. If you are using a language pack, we recommend that you also get the latest version of the language pack when upgrading the firmware to ensure that any changes in the interface are shown correctly.": "Cette page affiche la version actuelle de votre microprogramme et de votre pack linguistique. Elle permet également de rechercher de nouveaux microprogrammes et de les télécharger. Une fois ces derniers téléchargés, vous pouvez les mettre à jour à l'aide des boutons ci-dessous. Si vous utilisez un pack linguistique, nous vous recommandons d'obtenir aussi la toute dernière version du pack linguistique lorsque vous mettez à niveau le microprogramme pour être sûr(e) que toute modification dans l'interface s'affichera correctement.",
	"Current Firmware Version": "Version actuelle du microprogramme",
	"Current Firmware Date": "Date du microprogramme actuel",
	"Current Language Pack": "Pack linguistique actuel",
	"Download New Firmware": "Télécharger le nouveau microprogramme",
	"Upgrade Firmware": "Mises à jour du microprogramme",
	"Add a Language Pack": "Ajouter un pack linguistique",
	"Upload": "Charger",
	"Upgrade": "Mettre à jour",
	"Upgrading": "Upgrading",
	"Do you want to upgrade Firmware?": "Voulez-vous mettre à jour le microprogramme ?",
	"Do not power off the device until the Firmware Upgrade is complete!": "Ne fermez pas la page ou n'interrompez pas le service tant que la mise à niveau du progiciel n'est pas terminée !",
	"Firmware Uploading": "Chargement du microprogramme",
	"Firmware Upgrade failed!": "Échec de la mise à jour du microprogramme !",
	"Firmware Upgrade success!": "Réussite de la mise à jour du programme !",
	"Firmware Imformation": "Informations concernant le microprogramme",
	"New Firmware Version": "Nouvelle version du microprogramme",
	"New Firmware Date": "Nouvelle date du microprogramme",
	"Check for New Firmware": "Vérifier s'il existe un nouveau microprogramme",
	"Language Pack Imformation": "Informations sur le pack linguistique",
	"Current Language Pack": "Pack linguistique actuel",
	"Remove": "Supprimer",
	"Upgrade Manually": "Mettre à jour manuellement",
	"Add a Language Pack": "Ajouter un pack linguistique",
	"Checking": "Contrôle en cours",
	"Retry": "Réessayer",
	"This firmware is the latest version.": "This firmware is the latest version.",
	"Downloading": "Downloading",
	"Please do not close the browser while the firmware is being downloaded!": "Please do not close the browser while the firmware is being downloaded!",
	
	// Statistic
	"Statistics": "Statistiques",
	"This page gives you various statistics about data transmitted and received by your router through the Internet, on your wired network (LAN), and through your wireless networks.": "Cette page affiche diverses statistiques sur les données envoyées et reçues par votre routeur sur Internet, sur votre réseau local et via vos réseaux sans fil.",
	"Clear": "Effacer",
	"Information: Your browser is not support HTML5, please upgrade your browser.": "Informations : Votre navigateur ne prend pas en charge HTML5, veuillez mettre à niveau votre navigateur.",
	"Sent (Tx)": "Envoyés (Tx)",
	"Received (Rx)": "Reçus (RX)",
	"Total Packets": "Total Packets",
	"Total Byte(s)": "Total Byte(s)",
	"Total Kbit(s)": "Total Kbit(s)",
	"Kbits/sec": "Kbits/sec",
	"Session": "Session"
}