{
	// Menu
	"Home": "Home",
	"Settings": "Impostazioni",
	"Advanced": "Avanzata",
	"Management": "Gestione",
	"Internet(WAN)": "Internet",
	"Wireless(Wi-Fi)": "Wireless",
	"Network(LAN)": "Rete",
	"SharePort": "SharePort",
	"mydlink": "mydlink",
	"Firewall Setting": "Impostazione firewall",
	"Virtual Server": "Server virtuale",
	"Port Forwarding": "Inoltro porte",
	"Website Filter": "Filtro siti Web",
	"Static Route": "Route statica",
	"Disabled": "Disabilitato",
	"Enabled": "Abilitato",
	
	// Genernal
	"There is unsaved data on this page. Do you want to abandon it?": "There is unsaved data on this page. Do you want to abandon it?",
	"Remaining": "Remaining",
	
	// Login
	"Model Name": "Nome modello",
	"Hardware Version": "Versione hardware",
	"Firmware Version": "Versione firmware",
	"Language": "Lingua",
	"Admin Password": "Password amministratore",
	"Log In": "Accesso",
	"To access your storage with SharePort Web Access,": "Per accedere allo spazio di archiviazione con Accesso Web SharePort,",
	"click here.": "fare clic qui.",
	"Invalid password, please try again.": "Password non valida. Riprovare.",
	"The Private Browsing feature of Safari is incompatible with this device's interface. You will need to disable Private Browsing to log in.": "The Private Browsing feature of Safari is incompatible with this device's interface. You will need to disable Private Browsing to log in.",
	
	// Home
	"Current Status": "Stato corrente",
	"Click on any item in the diagram for more information.": "Per ulteriori informazioni, fare clic su una voce qualsiasi del diagramma.",
	"Setup Wizard": "Installazione guidata",
	"Router": "Router",
	"Internet": "Internet",
	"LAN": "LAN",
	"Router IP Address": "Indirizzo IP router",
	"MAC Address": "Indirizzo MAC",
	"Wi-Fi 2.4GHz": "Wi-Fi 2,4 GHz",
	"Wi-Fi 5GHz": "Wi-Fi 5 GHz",
	"Guest Zone 2.4GHz": "Zona guest 2,4 GHz",
	"Guest Zone 5GHz": "Zona guest 5 GHz",
	"IP Address": "Indirizzo IP",
	"Subnet Mask": "Subnet mask",
	"Default Gateway": "Gateway predefinito",
	"Available Space": "Spazio disponibile",
	"Total Space": "Spazio totale",
	"Service Name": "Nome servizio",
	"Ethernet Device": "Dispositivo Ethernet",
	"Wi-Fi Clients": "Client Wi-Fi",
	"USB Device": "Dispositivo USB",
	"USB Name": "Nome USB",
	"Status": "Stato",
	"Wi-Fi Name (SSID)": "Nome Wi-Fi (SSID)",
	"Password": "Password",
	"IPv6 Connection Type": "Tipo di connessione IPv6",
	"WAN IPv6 Address": "Indirizzo IPv6 WAN",
	"Primary IPv6 DNS Server": "Server DNS IPv6 primario",
	"Secondary IPv6 DNS Address": "Indirizzo DNS IPv6 secondario",
	"LAN IPv6 Link-Local Address": "Indirizzo Link-Local IPv6 LAN",
	"DHCP-PD": "DHCP-PD",
	"IPv6 Network Assigned by DHCP-PD": "Rete IPv6 assegnata da DHCP-PD",
	"LAN IPv6 Address": "Indirizzo IPv6 LAN",
	"Guest Zone": "Zona guest",
	"Connection Type": "Tipo di connessione",
	"Network Status": "Stato della rete",
	"Connection Up Time": "Durata connessione",
	"Primary DNS Server": "Server DNS primario",
	"Secondary DNS Server": "Server DNS secondario",
	"SharePort": "SharePort",
	"Release": "Rilascia",
	"Renew": "Rinnova",
	"Disconnect": "Disconnetti",
	"Connect": "Connetti",
	"Ignore": "Ignore",
	"Connected": "Connected",
	"Connecting": "Connecting",
	"Disconnected": "Disconnected",
	"DHCP": "Dynamic IP (DHCP)",
	"Static": "Static IP (Static)",
	"DHCPPPPoE": "Dynamic IP (PPPoE)",
	"StaticPPPoE": "Static IP (PPPoE)",
	"DynamicPPTP": "Dynamic IP (PPTP)",
	"StaticPPTP": "Static IP (PPTP)",
	"DynamicL2TP": "Dynamic IP (L2TP)",
	"StaticL2TP": "Static IP (L2TP)",
	"A new firmware is available! Do you want to download and upgrade the firmware?": "A new firmware is available! Do you want to download and upgrade the firmware?",
	"Your changes are being saved, and the device will need to reboot.": "Your changes are being saved, and the device will need to reboot.",
	"The Wi-Fi connection is not secure.": "The Wi-Fi connection is not secure.",
	"Secure your network.": "Secure your network.",
	
	// Wizard
	"Welcome": "Benvenuta/o",
	"This wizard will guide you through a step-by-step process to configure your new D-Link device.": "Questa procedura guidata assiste l'utente nelle varie fasi della configurazione di un nuovo dispositivo D-Link.",
	"Step1: Install your device": "Passo 1: Installazione del dispositivo",
	"Step2: Configure your Network and Wi-Fi settings": "Passo 2: Configurazione delle impostazioni Wi-Fi e della rete",
	"Step3: Set your router password": "Passo 3: Impostazione della password del router",
	"Step4: Set mydlink service": "Passo 4: Impostazione del servizio mydlink",
	"Your Device": "Dispositivo in uso",
	"Cable/xDSL Broadband Modem": "Modem a banda larga xDSL/cavo",
	"DHCP Connection (Dynamic IP Address)": "Connessione DHCP (indirizzo IP dinamico)",
	"Choose this if your Internet connection automatically provides you with an IP Address. Most Cable Modems use this type of connection.": "Scegliere questa opzione se la connessione Internet fornisce automaticamente l'indirizzo IP. Questo tipo di connessione viene utilizzata con la maggior parte dei modem cavo.",
	"Username/Password Connection (PPPoE)": "Connessione con nome utente/password (PPPoE)",
	"Choose this option if your Internet connection reguires a username and passowrd to get online. Most DSL modems use this connection type of connection.": "Selezionare questa opzione se per connettersi a Internet è necessario immettere un nome utente e una password. Questo tipo di connessione viene utilizzato con la maggior parte dei modem DSL.",
	"Static IP Address Connection": "Connessione con indirizzo IP statico",
	"Choose this option if your Internet Setup Provider provided you with IP Address information that has to be manually configured.": "Scegliere questa opzione se il provider di servizi Internet ha fornito le informazioni sugli indirizzi IP da configurare manualmente.",
	"Username": "Nome utente",
	"Gateway Address": "Indirizzo gateway",
	"Primary DNS Address": "Indirizzo DNS primario",
	"Secondary DNS Address": "Indirizzo DNS secondario",
	"2.4GHz Wi-Fi Network Name": "Nome della rete Wi-Fi 2,4 GHz",
	"5GHz Wi-Fi Network Name": "Nome della rete Wi-Fi 5 GHz",
	"The Wi-Fi Network Name is up to 32 characters. You will need to join your Wi-Fi network using this Network Name (SSID).": "Per il nome della rete Wi-Fi è possibile utilizzare fino a un massimo di 32 caratteri. Tale nome (SSID) sarà necessario per accedere alla rete Wi-Fi.",
	"Wi-Fi Password": "Password Wi-Fi",
	"Copy to 5GHz": "Copia in 5 GHz",
	"2.4GHz Wi-Fi Password": "Password della rete Wi-Fi 2,4 GHz",
	"5GHz Wi-Fi Password": "Password della rete Wi-Fi 5 GHz",
	"The password must contain at least 8 characters. You will need to join your Wi-Fi network using this password.": "La password deve essere composta da almeno 8 caratteri. Tale password sarà necessaria per accedere alla rete Wi-Fi.",
	"Device Admin Password": "Password amministratore del dispositivo",
	"This device is mydlink-enabled, which allows you to remotely monitor and manage your network through the mydlink.com website, or through the mydlink mobile app.": "Questo dispositivo è abilitato per mydlink. È quindi possibile monitorare e gestire in remoto la rete tramite il sito Web mydlink.com oppure tramite l'app mydlink mobile.",
	"You can register this device with your existing mydlink account. If you do not have one, you can create one now.": "È possibile registrare questo dispositivo con l'account mydlink esistente. Se non si dispone di un account, è possibile crearne uno ora.",
	"Do you have an existing mydlink account": "Si dispone già di un account mydlink?",
	"Yes, I have a mydlink account": "Sì, dispongo di un account mydlink.",
	"No, I want to create a new mydlink account": "No, desidero creare un nuovo account mydlink.",
	"E-mail Address (Account Name)": "Indirizzo e-mail (nome account)",
	"First Name": "Nome",
	"Last Name": "Cognome",
	"I accept the mydlink": "Accetto",
	"terms and conditions.": "termini e condizioni di mydlink.",
	"Connect to the Wi-Fi network from your mobile device or PC": "Connessione alla rete Wi-Fi da dispositivo mobile o PC",
	"1.Please go to Settings > Wi-fi, and choose": "1. Passare a Impostazioni > Wi-Fi e scegliere",
	"from the list of Wi-Fi network services.": "nell'elenco dei servizi di rete Wi-Fi.",
	"2.Enter the password you just setup when prompted.": "2. Quando richiesto, immettere la password appena configurata.",
	"Checking Internet connectivity": "Verifica della connessione a Internet",
	"Wi-Fi Client": "Client Wi-Fi",
	"Save": "Salva",
	"Please wait": "Attendere",
	"Configure Your Internet Connection": "Configurazione della connessione Internet",
	"Detecting Internet connection": "Rilevamento della connessione Internet",
	"Install": "Installa",
	"Please plug one end of the Ethernet cable included with your device into the port labeled INTERNET on your device. Plug the other end of this cable into the Ethernet port on yourDSL or cable broadband modem, and power cycle the modem.": "Collegare un'estremità del cavo Ethernet fornito con il dispositivo alla porta INTERNET del dispositivo. Collegare l'altra estremità del cavo alla porta Ethernet del modem a banda larga DSL o via cavo.",
	"Please select your Internet connection type below": "Selezionare un tipo di connessione Internet tra quelli seguenti.",
	"PPPoE": "PPPoE",
	"To setup this Internet connection, you will need to have a User Name from your InternetService Provider. If you do not have this information, please contact your ISP.": "Per configurare la connessione a Internet, è necessario disporre del nome utente fornito dal provider di servizi Internet (ISP). Se non si dispone di queste informazioni, contattare l'ISP.",
	"Static IP": "IP statico",
	"Dynamic IP (DHCP)": "IP dinamico (DHCP)",
	"To set up this conncetion you will need to have a complete list of IP information by your Internet Service Provider. If you have a Static IP connection and do not have this information, please contact your ISP.": "Per configurare la connessione, è necessario disporre di un elenco completo di indirizzi IP fornito dall'ISP (Internet Service Provider). Se la connessione è di tipo IP statico e non si dispone di queste informazioni, contattare l'ISP.",
	"Wi-Fi Settings": "Impostazioni Wi-Fi",
	"To setup a Wi-Fi Network you will need to give your Wi-Fi Nerwork a Name(SSID) and Password.": "Per configurare una rete Wi-Fi, è necessario assegnare un nome (SSID) e una password alla rete.",
	"By default, your new D-Link device does not have a password configured for administrator access to the Web-based configuration utility. To secure your new device, please create a password below.": "Per impostazione predefinita, il nuovo dispositivo D-Link non dispone di una password configurata per l'accesso amministratore all'utilità di configurazione basata sul Web. Per proteggere il nuovo dispositivo, creare una password di seguito.",
	"Setup Complete": "Configurazione completata",
	"Below is a summary of your Wi-Fi security and device password settings.Please take a note of your settings and save your configuration.": "Di seguito è riportato un riepilogo relativo alle impostazioni di protezione Wi-Fi e alla password del dispositivo. Prendere nota delle impostazioni e salvare la configurazione.",
	"Checking Your Internet connectivity": "Verifica della connessione a Internet",
	"Checking Internet connectivity": "Verifica della connessione a Internet",
	"mydlink Regristration": "Registrazione a mydlink",
	"Congratulations": "Congratulazioni",
	"Congratulations,your device has been configured. You can now connect to your Wi-Fi network by using the new Wi-Fi Network Name and Password you created.": "Il dispositivo è stato configurato. È ora possibile connettersi alla rete Wi-Fi utilizzando il nome e la password della rete Wi-Fi creati.",
	"Back": "Indietro",
	"Next": "Avanti",
	"Skip": "Ignora",
	"Finish": "Fine",
	"Registered": "Registered",
	"Unregistered": "Unregistered",
	
	// Ethernet, Wireless, Wireless_Guest
	"Wi-Fi Clients (Guest Zone)": "Client Wi-Fi (zona guest)",
	"Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.",
	"Here, you can see a list of all devices connected through Wi-Fi. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Questo è un elenco di tutti i dispositivi connessi tramite Wi-Fi. Fare clic su un dispositivo per visualizzare ulteriori informazioni oppure fare clic sull'icona della matita per assegnare un nome al dispositivo e facilitarne l'identificazione. Le opzioni della casella di riepilogo Blocca consentono di bloccare l'accesso del dispositivo alla rete in qualsiasi orario oppure in base a una pianificazione.",
	"Vendor": "Fornitore",
	"Reserve IP": "IP riservato",
	"Access": "Accesso",
	"Allowed": "Consentito",
	"Blocked": "Bloccato",
	
	// Internet > IPv4
	"Use this section to configure your Internet Connection type. There are several connection types to choose from Static IP, DHCP, PPPoE, PPTP, L2TP, and DS-Lite. If you are unsure of your connection method, please contact your Internet Service Provider. Note:  If using the PPPoE option, you will need to remove or disable any PPPoE client software on your computers.": "In questa sezione è possibile configurare il tipo di connessione Internet. È possibile scegliere tra diversi tipi di connessione: IP statico, DHCP, PPPoE, PPTP, L2TP e DS-Lite. Se non si è certi del metodo di connessione, contattare l'ISP (Internet Service Provider). Nota:  se si utilizza l'opzione PPPoE, sarà necessario rimuovere o disabilitare eventuale software client PPPoE installato nei computer in uso.",
	"My Internet Connection is": "La connessione Internet è",
	"Host Name": "Nome host",
	"Mac Address Clone": "Duplicazione indirizzi MAC",
	"PPTP IP Address": "Indirizzo IP PPTP",
	"PPTP Server IP Address": "Indirizzo IP server PPTP",
	"PPTP Subnet Mask": "Subnet mask PPTP",
	"PPTP Gateway IP Address": "Indirizzo IP gateway PPTP",
	"L2TP IP Address": "Indirizzo IP L2TP",
	"L2TP Server IP Address": "Indirizzo IP server L2TP",
	"L2TP Subnet Mask": "Subnet mask L2TP",
	"L2TP Gateway IP Address": "Indirizzo IP gateway L2TP",
	"MTU": "MTU",
	"Address Mode": "Modalità indirizzo",
	"Reconnect Mode": "Modalità di riconnessione",
	"Maximum Idle Time": "Tempo massimo di inattività",
	"DS-Lite Configuration": "Configurazione DS-Lite",
	"DS-Lite DHCPv6 Option": "Opzione DHCPv6 DS-Lite",
	"Manual Configuration": "Configurazione manuale",
	"AFTR IPv6 Address": "Indirizzo IPv6 AFTR",
	"B4 IPv4 Address": "Indirizzo IPv4 B4",
	"WAN IPv6 Address": "Indirizzo IPv6 WAN",
	"IPv6 WAN Default Gateway": "Gateway predefinito WAN IPv6",
	"Advanced Settings": "Impostazioni avanzate",
	"Manual": "Manuale",
	"Always on": "Sempre attiva",
	"On demand": "A richiesta",
	"Dynamic IP": "Dynamic IP",
	
	// Internet > IPv6
	"All of your IPv6 Internet and network connection details are displayed on this page.": "In questa pagina sono visualizzati tutti i dettagli sulla connessione Internet IPv6 e di rete.",
	"Auto Detection": "Rilevamento automatico",
	"Static IPv6": "IPv6 statico",
	"Auto Configuration (SLAAC/DHCPv6)": "Configurazione automatica (SLAAC/DHCPv6)",
	"IPv6 in IPv4 Tunnel": "Tunnel IPv6 in IPv4",
	"6to4": "6to4",
	"Local Connectivity Only": "Solo connettività locale",
	"Use Link-Local Address": "Usa indirizzo Link-Local",
	"Subnet Prefix Length": "Lunghezza prefisso subnet",
	"PPPoE Session": "Sessione PPPoE",
	"Remote IPv4 Address": "Indirizzo IPv4 remoto",
	"Remote IPv6 Address": "Indirizzo IPv6 remoto",
	"Local IPv4 Address": "Indirizzo IPv4 locale",
	"Local IPv6 Address": "Indirizzo IPv6 locale",
	"6to4 Address": "Indirizzo 6to4",
	"6to4 Relay": "Relay 6to4",
	"Assign IPv6 Prefix": "Assegna prefisso IPv6",
	"LAN IPv6 Link-Local Address": "Indirizzo Link-Local IPv6 LAN",
	"IPv6 DNS SETTINGS": "IMPOSTAZIONI DNS IPv6",
	"LAN IPv6 ADDRESS SETTINGS": "IMPOSTAZIONI INDIRIZZO IPv6 LAN",
	"LAN IPv6 Address": "Indirizzo IPv6 LAN",
	"ADDRESS AUTOCONFIGURATION SETTINGS": "IMPOSTAZIONI CONFIGURAZIONE AUTOMATICA INDIRIZZI",
	"Enable Automatic IPv6 Address Assignment": "Abilita assegnazione automatica degli indirizzi IPv6",
	"Enable Automatic DHCP-PD in LAN": "Abilita DHCP-PD automatico nella rete LAN",
	"Autoconfiguration Type": "Tipo configurazione automatica",
	"Enable DHCP-PD": "Abilita DHCP-PD",
	"6RD MANUAL CONFIGURATION": "CONFIGURAZIONE MANUALE 6RD",
	"Enable Hub and Spoke Mode": "Abilita modalità Hub and spoke",
	"6rd Configuration": "Configurazione 6rd",
	"6rd IPv6 Prefix": "Prefisso IPv6 6rd",
	"6rd Border Relay IPv4 Address": "Indirizzo IPv4 Relay 6rd Border",
	"IPv6 ULA SETTINGS": "IMPOSTAZIONI ULA IPv6",
	"Enable ULA": "Abilita ULA",
	"Use Default ULA Prefix": "Utilizza prefisso ULA predefinito",
	"ULA Prefix": "Prefisso ULA",
	"CURRENT IPv6 ULA SETTINGS": "IMPOSTAZIONI ULA IPv6 CORRENTI",
	"Current ULA Prefix": "Prefisso ULA corrente",
	"LAN IPv6 ULA": "ULA IPv6 LAN",
	"minutes": "minuti",
	"DNS Type": "Tipo DNS",
	"Obtain a DNS server address automatically": "Ottieni automaticamente l'indirizzo del server DNS",
	"Use the following DNS address": "Usa il seguente indirizzo DNS",
	"SLAAC+Stateless DHCP": "SLAAC+DHCP senza stato",
	"Stateful DHCPv6": "DHCPv6 con stato",
	"6rd DHCPv4 Option": "Opzione DHCPv4 6rd",
	"Share with IPv4": "Condividi con IPv4",
	"Create a new session": "Crea una nuova sessione",
	"bytes": "bytes",
	"Router Advertisement Lifetime": "Router Advertisement Lifetime",
	"IPv6 Address Range (Start)": "IPv6 Address Range (Start)",
	"IPv6 Address Range (End)": "IPv6 Address Range (End)",
	"IPv6 Address Lifetime": "IPv6 Address Lifetime",
	
	// WiFi & Guest Zone
	"Security Mode": "Modalità protezione",
	"None": "Nessuna",
	"WPA-Personal": "WPA personale",
	"Auto": "Automatico",
	"High": "Alta",
	"Low": "Bassa",
	"802.11 Mode": "Modalità 802.11",
	"Wi-Fi Channel": "Canale Wi-Fi",
	"Transmission Power": "Potenza di trasmissione",
	"Channel Width": "Ampiezza canale",
	"Visibility Status": "Stato visibilità",
	"Visible": "Visibile",
	"Invisible": "Invisibile",
	"Mixed 802.11b/g": "Combinazione 802.11b/g",
	"Mixed 802.11g/n": "Combinazione 802.11g/n",
	"Mixed 802.11b/g/n": "Combinazione 802.11b/g/n",
	"Auto 20/40 MHz": "20/40 MHz automatico",
	"Mixed 802.11a and 802.11n": "Combinazione di 802.11a e 802.11n",
	"Use this section to configure the wireless settings for your D-Link Router. Please note that changes made on this section may also need to be duplicated on your Wireless Client.": "In questa sezione è possibile configurare le impostazioni wireless per il router D-Link. Si noti che potrebbe essere necessario duplicare le modifiche apportate in questa sezione anche nel client wireless.",
	"This page lets you configure a Wi-Fi Guest Zone. Wi-Fi Guest Zones are Wi-Fi networks that are separate from your normal ones, and use different Wi-Fi Network Names and passwords. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless the Access Local Service option is enabled. Guest Zones are useful to give guests Internet access without allowing them to access your own devices on your network.": "In questa pagina è possibile configurare una zona guest Wi-Fi. Le zone guest Wi-Fi sono reti Wi-Fi distinte da quelle normali e utilizzano nomi e password di rete Wi-Fi diversi. Gli utenti connessi a una zona guest non possono comunicare o rilevare dispositivi sulla rete normale a meno che non sia abilitata l'opzione per l'accesso al servizio locale. Le zone guest sono utili per offrire agli ospiti accesso Internet senza consentire l'accesso ai dispositivi disponibili in rete.",
	"Internet Access Only": "Solo accesso Internet",
	"Routing Between Zones": "Routing tra le zone",
	"Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.": "Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.",
	"Your changes are being saved.": "Your changes are being saved.",
	
	// Network
	"Network": "Rete",
	"Network Settings": "Impostazioni di rete",
	"DHCP Server": "Server DHCP",
	"Use this page to configure the local network settings for your router, including the IP address you use to access this configuration interface. Please note that if you change this IP address, you will need to use the new IP to access this interface.": "In questa pagina è possibile configurare le impostazioni della rete locale per il router, incluso l'indirizzo IP utilizzato per accedere all'interfaccia di configurazione. Si noti che modificando questo indirizzo IP sarà necessario utilizzare il nuovo IP per accedere a questa interfaccia.",
	"LAN IP Address": "Indirizzo IP LAN",
	"Device Name": "Nome dispositivo",
	"Local Domain Name": "Nome di dominio locale",
	"Enable DNS Relay": "Abilita relay DNS",
	"DHCP IP Address Range": "Intervallo di indirizzi IP DHCP",
	"DHCP Lease Time": "Tempo di validità DHCP",
	"Always Broadcast": "Esegui sempre broadcast",
	"compatibility for some DHCP Clients": "(compatibilità per alcuni client DHCP)",
	"If you changed the IP address of the router you will need to change the IP address in your browser before accessing the configuration website again.": "Se si modifica l'indirizzo IP del router è necessario riportare la modifica nel browser per poter accedere nuovamente al sito Web di configurazione.",
	"The new settings have been saved.": "Le nuove impostazioni sono state salvate.",
	"to": "to",
	
	// Advanced Network
	"Advanced Network": "Impostazioni di rete avanzate",
	"Advanced Network settings allow you to configure some of the more advanced features of your router. It is recommended that you only change these settings if you are  familiar with them, or if you are specifically instructed to do so.": "Le impostazioni di rete avanzate consentono di configurare alcune delle funzionalità più avanzate del router. Si consiglia di modificare tali impostazioni solo se si conoscono o se è stato specificamente richiesto.",
	"UPnP": "UPnP",
	"WAN Port Speed": "Velocità porte WAN",
	"IPv4 Multicast Streams": "Flussi multicast IPv4",
	"IPv6 Multicast Streams": "Flussi multicast IPv6",
	"Auto (10/100/1000 Mbps)": "Automatico (10/100/1000 Mbps)",
	
	// SharePort
	"SharePort": "SharePort",
	"DLNA (Digital Living Network Alliance) is the standard for the interoperability of Network Media Devices (NMDs). The user can enjoy multi-media applications (music, pictures and videos) on your network connected PC or media devices. Web File Access allows you to use a web browser to remotely access files stored on an SD card or USB storage drive plugged into the router.": "DLNA (Digital Living Network Alliance) è lo standard per l'interoperatività dei dispositivi NMD (Network Media Device). L'utente può utilizzare applicazioni multimediali (musica, immagini e video) da PC o dispositivi multimediali collegati in rete. L'accesso ai file tramite Web consente di utilizzare un browser Web per accedere in remoto ai file memorizzati su una scheda SD o su un'unità di archiviazione USB collegate al router.",
	"DLNA Media Server Configuration": "Configurazione server multimediale DLNA",
	"DLNA Media Server": "Server multimediale DLNA",
	"Web File Access": "Accesso ai file tramite Web",
	"Remote Access Port": "Porta di accesso remoto",
	"Remote HTTPS Port": "Porta HTTPS remota",
	"Enable Storage Remote Access": "Abilita accesso remoto unità di archiviazione",
	"Direct Links": "Collegamenti diretti",
	"Local Access": "Accesso locale",
	"SharePort Web Access": "Accesso Web SharePort",
	
	// SharePort CreateUser
	"\"Create User\" manage access to your storage devices or use the Guest account (guest/guest) to access the Guest Folder. After plugging in an SD card or USB storage drive, the new device will appear in the list with a link to it. You can then use this link to connect the drive and login with a user account.": "\"Crea utente\" consente di gestire l'accesso ai dispositivi di archiviazione o utilizzare l'account Guest (guest/guest) per accedere alla cartella Guest. Dopo aver collegato una scheda SD o un'unità di archiviazione USB, il nuovo dispositivo viene visualizzato nell'elenco insieme al relativo collegamento. Quindi è possibile utilizzare questo collegamento per connettersi all'unità ed eseguire l'accesso con un account utente.",
	"Remote Access": "Accesso remoto",
	"Create User": "Crea utente",
	"User Name": "Nome utente",
	"Access Path": "Percorso di accesso",
	"Permission": "Autorizzazione",
	"Edit": "Modifica",
	"Delete": "Elimina",
	"Browse": "Sfoglia",
	"OK": "OK",
	"Create User": "Crea utente",
	"Create New User": "Crea nuovo utente",
	"Edit User Profile": "Modifica profilo utente",
	"Folder": "Cartella",
	"Select Folder": "Seleziona cartella",
	"USB Device Name": "Nome dispositivo USB",
	"Number of Device": "Numero del dispositivo",
	
	// mydlink
	"Setting and registering your router with mydlink will allow you to use its mydlink cloud services features, including online access and management of your router through the mydlink portal website.": "L'impostazione e la registrazione del router in mydlink consentono di utilizzarne le funzionalità dei servizi mydlink cloud, incluso l'accesso e la gestione online del router tramite il sito Web del portale mydlink.",
	"mydlink Registration": "Registrazione a mydlink",
	"Sign Up": "Effettua registrazione",
	"Sign In": "Accedi",
	"Please enter your e-mail address and mydlink password.": "Immettere l'indirizzo e-mail e la password di mydlink.",
	"You must accept the terms and conditions to continue.": "Per continuare, è necessario accettare i termini e le condizioni.",
	
	// QoS Engine
	"QoS Engine": "Motore QoS",
	"QoS prioritizes your network traffic so you can decide what devices should have priority over other devices. For example, you could set a computer that is downloading files to have lower priority than a laptop that is streaming movies to ensure that you can stream movies smoothly without downloads taking up all of your bandwidth.": "QoS consente di assegnare priorità al traffico di rete per stabilire quali dispositivi devono essere prioritari rispetto ad altri. Ad esempio, è possibile impostare una priorità inferiore per un computer che scarica file rispetto a un laptop che riproduce film in streaming in modo che da evitare che i download occupino tutta la larghezza di banda causando interruzioni durante la riproduzione dei film in streaming.",
	"All Devices": "Tutti i dispositivi",
	"Drag the device cards above to the Prioity boxes below.": "Trascinare le schede dei dispositivi sulle caselle di priorità.",
	"Highest": "Massima",
	"Medium": "Media",
	
	// Firewall
	"Firewall Settings": "Impostazioni firewall",
	"Here, you can set up various firewall features to protect your network from attacks. You can click on the DMZ, IPv4 Rules, and IPv6 Rules buttons to see the settings for that feature.": "In questa pagina è possibile impostare diverse funzionalità del firewall per proteggere la rete da attacchi. È possibile fare clic sui pulsanti DMZ, Regole IPv4 e Regole IPv6 per visualizzare le impostazioni relative alla funzionalità corrispondente.",
	"Application Level Gateway (ALG) Configuration": "Configurazione gateway ALG (Application Level Gateway)",
	"Enable SPI IPv4": "Abilita IPv4 SPI",
	"Enable Anti-spoof Checking": "Abilita controllo anti-spoofing",
	"IPv6 Simple Security": "IPv6 Simple Security",
	"PPTP": "PPTP",
	"IPSec (VPN)": "IPSec (VPN)",
	"RTSP": "RTSP",
	"SIP": "SIP",
	"IPv4 Rules": "Regole IPv4",
	"IPv6 Rules": "Regole IPv6",
	"Firewall": "Firewall",
	"Enable DMZ Host": "Abilita host DMZ",
	"DMZ IP Address": "Indirizzo IP DMZ",
	"Security Check": "Controllo di sicurezza",
	
	// Firewall IPv4, IPv6
	"The IPv4 rule section is an advance feature used to deny or allow traffic from passing through the device.": "La sezione delle regole IPv4 è una funzionalità avanzata per consentire o impedire il traffico trasmesso attraverso il dispositivo.",
	"The IPv6 rule section is an advance feature used to deny or allow traffic from passing through the device.": "La sezione delle regole IPv6 è una funzionalità avanzata per consentire o impedire il traffico trasmesso attraverso il dispositivo.",
	"Add Rules": "Aggiungi regole",
	"Name": "Nome",
	"Schedule": "Pianificazione",
	"Create New Rule": "Crea nuova regola",
	"Source IP Address Range": "Intervallo di indirizzi IP di origine",
	"Destination IP Address Range": "Intervallo di indirizzi IP di destinazione",
	"Port Range": "Intervallo porte",
	"Turn IPv4 Filtering OFF": "Disattiva filtro IPv4",
	"Turn IPv4 Filtering ON and ALLOW rules listed": "Attiva filtro IPv4 e CONSENTI regole elencate",
	"Turn IPv4 Filtering ON and DENY rules listed": "Attiva filtro IPv4 e NEGA regole elencate",
	"Turn IPv6 Filtering OFF": "Disattiva filtro IPv6",
	"Turn IPv6 Filtering ON and ALLOW rules listed": "Attiva filtro IPv6 e CONSENTI regole elencate",
	"Turn IPv6 Filtering ON and DENY rules listed": "Attiva filtro IPv6 e NEGA regole elencate",
	
	// Port Forwarding
	"Port Forwarding is used to open ports in your router and to redirect traffic to those ports to a specific device on your network. This may be needed for specific applications, games, or services. You can enter individual ports (80, 68, 888), port ranges (100-150), or in a mixed format (1020-5000, 689).": "Inoltro porte viene utilizzato per aprire le porte del router e reindirizzare il traffico di tali porte a un dispositivo specifico della rete. Tale funzionalità può essere necessaria per applicazioni, giochi o servizi specifici. È possibile immettere singole porte (80, 68, 888), intervalli di porte (100-150) o combinazioni di singole porte e intervalli (1020-5000, 689).",
	"Local IP": "IP locale",
	"TCP Port": "Porta TCP",
	"UDP Port": "Porta UDP",
	
	// Virtual Server
	"The Virtual Server option allows you to define a single public port on your router for redirection to an internal LAN IP Address and Private LAN port if required. This feature is useful for hosting online services such as FTP or Web Servers.": "L'opzione Server virtuale consente di definire una singola porta pubblica sul router per il reindirizzamento a un indirizzo IP LAN interno e se necessario a una porta LAN privata. Questa funzionalità è utile per l'hosting di servizi online quali server FTP o Web.",
	"Protocol": "Protocollo",
	"External Port": "Porta esterna",
	"Internal Port": "Porta interna",
	"Protocol Number": "Protocol Number",
	
	// Website Filter
	"The Website Filter option allows you to set up a list of Web sites you would like to allow or deny through your network. To use this feature, you must also select the \"Apply Web Filter\" checkbox in the Access Control section.": "L'opzione Filtro siti Web consente di configurare un elenco di siti Web ai quali concedere o meno l'accesso tramite la rete. Per utilizzare questa funzionalità, è inoltre necessario selezionare la casella di controllo \"Applica filtro Web\" nella sezione Controllo di accesso.",
	"DENY computers access to ONLY these sites": "NON CONSENTIRE ai computer l'accesso SOLO a questi siti",
	"ALLOW computers access to ONLY these sites": "CONSENTI ai computer di accedere SOLO a questi siti",
	"Website URL/Domain": "URL/Dominio sito Web",
	
	// StaticRouter, StaticRouterIPv6
	"Static Routes": "Route statiche",
	"This page allows you to define custom routes to define how data traffic is moved around your network.": "In questa pagina è possibile specificare route personalizzate che determinano la modalità di spostamento dei dati all'interno della rete.",
	"Destination IP": "Indirizzo IP di destinazione",
	"Netmask": "Netmask",
	"Gateway": "Gateway",
	"Matrix": "Matrice",
	"Interface": "Interfaccia",
	"DestNetwork": "ReteDest",
	"PrefixLen": "LunghPrefisso",
	
	// DynamicDNS
   	"Dynamic DNS (DDNS) allows you to use an easy to remember domain name such as www.[YourDomainName].com to reach your router\'s dynamically assigned IP address. This is useful when hosting a web, FTP, or game server, and allows you to reach your server no matter what your IP address has changed to. D-Link offers a free DDNS service that you can use through www.DLinkDDNS.com.": "DNS dinamico (DDNS) consente di utilizzare un nome di dominio facile da ricordare, ad esempio www.[NomeDominio].com per raggiungere l'indirizzo IP assegnato dinamicamente del router. Questa funzionalità è utile quando si ospita un server Web, FTP o di gioco e consente di raggiungere il server indipendentemente dall'indirizzo IP usato. D-Link offre un servizio DDNS gratuito utilizzabile tramite www.DLinkDDNS.com.",
	"Server Address": "Indirizzo server",
	"Dynamic DNS": "DNS dinamico",
	"Enable Dynamic DNS": "Abilita DNS dinamico",
	"Select Server Name": "Seleziona nome server",
	"Time Out": "Timeout",
	"IPv6 Address": "Indirizzo IPv6",
	"hours": "ore",
	
	// Time
	"Time & Schedule": "Ora e pianificazione",
	"Time": "Ora",
	"Time Confuguration": "Configurazione ora",
	"Automatic Time Confuguration": "Configurazione ora automatica",
	"Manual Time Confuguration": "Configurazione ora manuale",
	"Date": "Data",
	"This page allows you to set the router\'s internal system clock. You can set the time manually, or automatically through a time server.": "In questa pagina è possibile impostare l'orologio interno del router. L'ora può essere impostata manualmente o automaticamente tramite un server di riferimento orario NTP.",
	"System Time": "Ora di sistema",
	"Time Zone": "Fuso orario",
	"Enable Daylight Saving": "Abilita aggiornamento ora legale",
	"Update Time Using an NTP Serevr": "Aggiorna ora tramite server NTP",
	"Year/ Month/ Day": "Anno/Mese/Giorno",
	"Hour/ Minute": "Ora/Minuto",
	"Day": "Giorno",
	"Hour": "Ora",
	"Min": "Min",
	"Sec": "Sec",
	
	// Schedule
	"The Schedule configuration option is used to manage schedule rules for various firewall and parental control features.": "Utilizzare l'opzione di configurazione delle pianificazioni per gestire le regole di pianificazione per varie funzioni di firewall e controllo parentale.",
	"Monday": "Monday",
	"Tuesday": "Tuesday",
	"Wednesday": "Wednesday",
	"Thursday": "Thursday",
	"Friday": "Friday",
	"Saturday": "Saturday",
	"Sunday": "Sunday",
	"All Day": "All Day",
	"All Week": "All Week",
	"Always": "Always Enable",
	
	// System Log
	"System Log": "Log di sistema",
	"SysLog Settings": "Impostazioni SysLog",
	"This page allows you to enable logging of system events to a SysLog server, or to e-mail the log to you according to a schedule or when the log is full.": "In questa pagina è possibile impostare la registrazione di eventi del sistema su un server SysLog oppure inviare tramite posta elettronica il log quando è pieno oppure in base a una pianificazione.",
	"SysLog Server IP Address": "Indirizzo IP server SysLog",
	"Enable Logging to Syslog Server": "Abilita registrazione in server SysLog",
	"E-mail Settings": "Impostazioni e-mail",
	"E-mail Log When Full or On Schedule": "Log tramite e-mail quando pieno o se pianificato",
	"Enable E-mail Notification": "Abilita notifica e-mail",
	"From E-mail Address": "Indirizzo e-mail mittente",
	"To E-mail Address": "Indirizzo e-mail destinatario",
	"SMTP Server Address": "Indirizzo server SMTP",
	"SMTP Server Port": "Porta server SMTP",
	"Enable Authentication": "Abilita autenticazione",
	"Account Name": "Nome account",
	"On Log Full": "Per log pieno",
	"On Schedule": "Se pianificato",
	
	// System
	"System": "Sistema",
	"Save Configuration": "Salva configurazione",
	"Restore Configuration From File": "Ripristina configurazione da file",
	"Restore Factory Default": "Ripristina impostazioni predefinite",
	"Reboot": "Riavvia",
	"This page lets you save your router\'s current settings to a file, restore your settings from a file, restore your router to factory default settings, or reboot the device. Please note that restoring the settings to the factory defaults will erase all settings, including any rules you have created.": "In questa pagina è possibile salvare le impostazioni correnti del router in un file, ripristinarle da un file, ripristinare le impostazioni predefinite del router oppure riavviare il dispositivo. Tenere presente che il ripristino delle impostazioni predefinite comporta la cancellazione di tutte le impostazioni, incluse eventuali regole create dall'utente.",
	"Save Settings To Local Hard Drive": "Salva impostazioni su disco rigido locale",
	"Load Settings From Local Hard Drive": "Carica impostazioni da disco rigido locale",
	"Restore To Factory Default Settings": "Ripristina impostazioni di default",
	"Reboot The Device": "Riavvia il dispositivo",
	"Cancel": "Annulla",
	"Are you sure you want to restore configuration file?": "Ripristinare il file di configurazione?",
	"Do not close the page or power off the service until the restore configuration file is complete!": "Non chiudere la pagina o spegnere il servizio finché non viene completato il ripristino del file di configurazione.",
	"Restore configuration file failed!": "Ripristino del file di configurazione non riuscito.",
	"Restore configuration file success!": "Ripristino del file di configurazione riuscito.",
	"Are you sure you want to reset the device?": "Reimpostare il dispositivo?",
	"Rebooting": "Riavvio in corso",
	"Reboot success!": "Riavvio riuscito.",
	"Are you sure you want to reset the device to its factory default settings? This will cause current settings to be lost.": "Ripristinare le impostazioni di default del dispositivo? L'operazione comporterà la perdita delle impostazioni correnti.",
	"Restore to factory default success!": "Ripristino delle impostazioni predefinite riuscito.",
	"Select File": "Seleziona file",
	"Restore": "Ripristina",
	"Restore Factory Default": "Ripristina impostazioni predefinite",
	
	// Admin
	"Admin": "Amministratore",
	"Admin Password": "Password amministratore",
	"Administration": "Amministrazione",
	"Use HTTPS": "Usa HTTPS",
	"The admin has read/write access and can change passwords, while the user has read-only access. By default there is no password configured. It is highly recommended that you create a password to keep your router secure.": "Admin dispone di accesso in lettura/scrittura ed è autorizzato a modificare le password, mentre user dispone di accesso in sola lettura. Per impostazione predefinita, non è configurata nessuna password. Si consiglia vivamente di creare una password per garantire la protezione del router.",
	"Enable Graphical Authentication (CAPTCHA)": "Abilita autenticazione grafica (CAPTCHA)",
	"Enable HTTPS Server": "Abilita server HTTPS",
	"Enable Remote Management": "Abilita gestione remota",
	"Remote Admin Port": "Porta amministrazione remota",
	"Remote Admin Inbound Filter": "Filtro in ingresso amministrazione remota",
	
	// Update Firmware
	"Upgrade Firmware": "Aggiorna firmware",
	"This page shows you your current firmware version and language pack, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below. If you are using a language pack, we recommend that you also get the latest version of the language pack when upgrading the firmware to ensure that any changes in the interface are shown correctly.": "In questa pagina sono indicati la versione del firmware e il Language Pack correnti. È inoltre possibile verificare la disponibilità di nuovo firmware e scaricarlo. Dopo il download del firmware, è possibile aggiornarlo tramite i pulsanti seguenti. Se si utilizza un Language Pack, si consiglia anche di scaricare la versione più recente del Language Pack durante l'aggiornamento del firmware, in modo da garantire la corretta visualizzazione delle eventuali modifiche apportate all'interfaccia.",
	"Current Firmware Version": "Versione firmware corrente",
	"Current Firmware Date": "Data firmware corrente",
	"Current Language Pack": "Language Pack corrente",
	"Download New Firmware": "Scarica nuovo firmware",
	"Upgrade Firmware": "Aggiorna firmware",
	"Add a Language Pack": "Aggiungi Language Pack",
	"Upload": "Carica",
	"Upgrade": "Aggiorna",
	"Upgrading": "Upgrading",
	"Do you want to upgrade Firmware?": "Aggiornare il firmware?",
	"Do not power off the device until the Firmware Upgrade is complete!": "Non chiudere la pagina o spegnere il servizio finché non viene completato l'aggiornamento del firmware.",
	"Firmware Uploading": "Caricamento firmware",
	"Firmware Upgrade failed!": "Aggiornamento firmware non riuscito.",
	"Firmware Upgrade success!": "Firmware aggiornato.",
	"Firmware Imformation": "Informazioni sul firmware",
	"New Firmware Version": "Nuova versione firmware",
	"New Firmware Date": "Data nuovo firmware",
	"Check for New Firmware": "Verifica disponibilità nuovo firmware",
	"Language Pack Imformation": "Informazioni sul Language Pack",
	"Current Language Pack": "Language Pack corrente",
	"Remove": "Rimuovi",
	"Upgrade Manually": "Aggiorna manualmente",
	"Add a Language Pack": "Aggiungi Language Pack",
	"Checking": "Verifica in corso",
	"Retry": "Riprova",
	"This firmware is the latest version.": "This firmware is the latest version.",
	"Downloading": "Downloading",
	"Please do not close the browser while the firmware is being downloaded!": "Please do not close the browser while the firmware is being downloaded!",
	
	// Statistic
	"Statistics": "Statistiche",
	"This page gives you various statistics about data transmitted and received by your router through the Internet, on your wired network (LAN), and through your wireless networks.": "In questa pagina sono visualizzate diverse statistiche sui dati trasmessi e ricevuti dal router tramite Internet, nonché tramite le reti cablate (LAN) e wireless.",
	"Clear": "Cancella",
	"Information: Your browser is not support HTML5, please upgrade your browser.": "Informazioni: Il browser in uso non supporta HTML5. Aggiornare il browser.",
	"Sent (Tx)": "Inviati (TX)",
	"Received (Rx)": "Ricevuti (RX)",
	"Total Packets": "Total Packets",
	"Total Byte(s)": "Total Byte(s)",
	"Total Kbit(s)": "Total Kbit(s)",
	"Kbits/sec": "Kbits/sec",
	"Session": "Session"
}