{
	// Menu
	"Home": "홈",
	"Settings": "설정",
	"Advanced": "고급",
	"Management": "관리",
	"Internet(WAN)": "인터넷",
	"Wireless(Wi-Fi)": "무선",
	"Network(LAN)": "네트워크",
	"SharePort": "SharePort",
	"mydlink": "mydlink",
	"Firewall Setting": "방화벽 설정",
	"Virtual Server": "가상 서버",
	"Port Forwarding": "포트 포워딩",
	"Website Filter": "웹 필터",
	"Static Route": "고정 경로",
	"Disabled": "비활성화",
	"Enabled": "활성화",
	
	// Genernal
	"There is unsaved data on this page. Do you want to abandon it?": "There is unsaved data on this page. Do you want to abandon it?",
	"Remaining": "Remaining",
	
	// Login
	"Model Name": "모델명",
	"Hardware Version": "하드웨어 버전",
	"Firmware Version": "펌웨어 버전",
	"Language": "언어",
	"Admin Password": "관리자 암호",
	"Log In": "로그인",
	"To access your storage with SharePort Web Access,": "SharePort 웹액세스로 스토리지에 접속하려면,",
	"click here.": "여기를 클릭하십시오.",
	"Invalid password, please try again.": "비밀번호가 잘못되었습니다 다시 시도하십시오.",
	"The Private Browsing feature of Safari is incompatible with this device's interface. You will need to disable Private Browsing to log in.": "사파리의 개인 정보 보호 브라우징 기능이 장치의 인터페이스와 호환되지 않습니다. 당신은 로그인 할 개인 정보 보호 브라우징을 비활성화 해야합니다.",
	
	// Home
	"Current Status": "현재 상태",
	"Click on any item in the diagram for more information.": "자세한 내용은 다이어그램에서 해당 항목을 클릭합니다.",
	"Setup Wizard": "설치 마법사",
	"Router": "라우터",
	"Internet": "인터넷",
	"LAN": "LAN",
	"Router IP Address": "라우터의 IP 주소",
	"MAC Address": "MAC 주소",
	"Wi-Fi 2.4GHz": "Wi-Fi를 2.4 기가 헤르츠 고출력",
	"Wi-Fi 5GHz": "Wi-Fi (은) 5GHz의",
	"Guest Zone 2.4GHz": "2.4 기가 헤르츠 고출력 고객 영역",
	"Guest Zone 5GHz": "고객 영역 5GHz의",
	"IP Address": "IP 주소",
	"Subnet Mask": "서브넷 마스크",
	"Default Gateway": "기본 게이트웨이",
	"Available Space": "사용 가능 공간",
	"Total Space": "총 공간",
	"Service Name": "서비스 이름",
	"Ethernet Device": "이더넷 장치",
	"Wi-Fi Clients": "Wi-Fi (은) 클라이언트",
	"USB Device": "USB 장치",
	"USB Name": "USB 이름",
	"Status": "지위",
	"Wi-Fi Name (SSID)": "Wi-Fi (은) 이름 (SSID)",
	"Password": "암호",
	"IPv6 Connection Type": "IPv6의 연결 유형",
	"WAN IPv6 Address": "WAN IPv6 Address (IPv6 주소)",
	"Primary IPv6 DNS Server": "기본 IPv6의 DNS 서버",
	"Secondary IPv6 DNS Address": "차 IPv6의 DNS 주소",
	"LAN IPv6 Link-Local Address": "LAN IPv6를 링크 - 로컬 주소",
	"DHCP-PD": "DHCP-PD",
	"IPv6 Network Assigned by DHCP-PD": "DHCP-PD에 의해 할당 된 IPv6 네트워크",
	"LAN IPv6 Address": "LAN IPv6의 주소",
	"Guest Zone": "고객 영역",
	"Connection Type": "연결 유형",
	"Network Status": "네트워크 상태",
	"Connection Up Time": "시간 연결을",
	"Primary DNS Server": "기본 DNS 서버",
	"Secondary DNS Server": "보조 DNS 서버",
	"SharePort": "SharePort",
	"Release": "해제",
	"Renew": "갱신",
	"Disconnect": "분리",
	"Connect": "연결",
	"Ignore": "Ignore",
	"Connected": "Connected",
	"Connecting": "Connecting",
	"Disconnected": "Disconnected",
	"DHCP": "Dynamic IP (DHCP)",
	"Static": "Static IP (Static)",
	"DHCPPPPoE": "Dynamic IP (PPPoE)",
	"StaticPPPoE": "Static IP (PPPoE)",
	"DynamicPPTP": "Dynamic IP (PPTP)",
	"StaticPPTP": "Static IP (PPTP)",
	"DynamicL2TP": "Dynamic IP (L2TP)",
	"StaticL2TP": "Static IP (L2TP)",
	"A new firmware is available! Do you want to download and upgrade the firmware?": "A new firmware is available! Do you want to download and upgrade the firmware?",
	"Your changes are being saved, and the device will need to reboot.": "Your changes are being saved, and the device will need to reboot.",
	"The Wi-Fi connection is not secure.": "The Wi-Fi connection is not secure.",
	"Secure your network.": "Secure your network.",
	
	// Wizard
	"Welcome": "환영",
	"This wizard will guide you through a step-by-step process to configure your new D-Link device.": "이 마법사는 새로운 D-Link 장치를 구성하는 단계별 과정을 통해 여러분에게 안내 할 것입니다.",
	"Step1: Install your device": "1 단계 : 장치 설치",
	"Step2: Configure your Network and Wi-Fi settings": "2 단계 : 네트워크 및 Wi-Fi 설정 구성",
	"Step3: Set your router password": "3 단계 : 라우터 암호 설정",
	"Step4: Set mydlink service": "4 단계 : mydlink 서비스 설정",
	"Your Device": "장치",
	"Cable/xDSL Broadband Modem": "케이블 / XDSL 광대역 모뎀",
	"DHCP Connection (Dynamic IP Address)": "DHCP 연결 (동적 IP 주소)",
	"Choose this if your Internet connection automatically provides you with an IP Address. Most Cable Modems use this type of connection.": "인터넷 연결이 자동으로 IP 주소를 제공하는 경우이 옵션을 선택. 대부분의 케이블 모뎀의 연결 유형을 사용합니다.",
	"Username/Password Connection (PPPoE)": "아이디 / 패스워드 연결을 (PPPoE)",
	"Choose this option if your Internet connection reguires a username and passowrd to get online. Most DSL modems use this connection type of connection.": "인터넷 연결이 이름을 reguires 및 온라인을 passowrd 경우이 옵션을 선택합니다. 대부분의 DSL 모뎀은 Connection에이 연결 유형을 사용합니다.",
	"Static IP Address Connection": "고정 IP 주소 연결",
	"Choose this option if your Internet Setup Provider provided you with IP Address information that has to be manually configured.": "인터넷 설정 공급자를 수동으로 구성해야합니다 IP 주소 정보를 제공 한 경우이 옵션을 선택합니다.",
	"Username": "이름",
	"Gateway Address": "게이트웨이 주소",
	"Primary DNS Address": "기본 DNS 주소",
	"Secondary DNS Address": "보조 DNS 주소",
	"2.4GHz Wi-Fi Network Name": "2.4 기가 헤르츠 고출력 Wi-Fi 네트워크 이름",
	"5GHz Wi-Fi Network Name": "5GHz의 Wi-Fi 네트워크 이름",
	"The Wi-Fi Network Name is up to 32 characters. You will need to join your Wi-Fi network using this Network Name (SSID).": "Wi-Fi 네트워크 이름은 최대 32 자까지입니다. 이 네트워크 이름 (SSID)을 사용하여 Wi-Fi 네트워크에 연결해야합니다.",
	"Wi-Fi Password": "Wi-Fi (은) 비밀번호",
	"Copy to 5GHz": "5GHz의로 복사",
	"2.4GHz Wi-Fi Password": "2.4 기가 헤르츠 고출력 무선 인터넷 비밀번호",
	"5GHz Wi-Fi Password": "5GHz의 와이파이 비밀번호",
	"The password must contain at least 8 characters. You will need to join your Wi-Fi network using this password.": "암호는 8 자 이상 포함되어야합니다. 이 암호를 사용하여 Wi-Fi 네트워크에 연결해야합니다.",
	"Device Admin Password": "장치 관리자 암호",
	"This device is mydlink-enabled, which allows you to remotely monitor and manage your network through the mydlink.com website, or through the mydlink mobile app.": "이 장치는 원격 mydlink.com 웹 사이트를 통해, 또는 mydlink 모바일 응용 프로그램을 통해 네트워크를 모니터링하고 관리 할 수​​ 있습니다 mydlink 지원입니다.",
	"You can register this device with your existing mydlink account. If you do not have one, you can create one now.": "당신은 당신의 기존 mydlink 계정에이 장치를 등록 할 수 있습니다. 당신이 하나를 가지고 있지 않다면, 당신은 지금 하나를 만들 수 있습니다.",
	"Do you have an existing mydlink account": "기존 mydlink 계정을 가지고 있습니까",
	"Yes, I have a mydlink account": "네, mydlink 계정을 가지고",
	"No, I want to create a new mydlink account": "아니, 난 새로운 mydlink 계정을 만들려면",
	"E-mail Address (Account Name)": "E-메일 주소 (계정 이름)",
	"First Name": "이름",
	"Last Name": "성",
	"I accept the mydlink": "mydlink를 수용합니다.",
	"terms and conditions.": "조건.",
	"Connect to the Wi-Fi network from your mobile device or PC": "모바일 장치 또는 PC에서 Wi-Fi 네트워크에 연결",
	"1.Please go to Settings > Wi-fi, and choose": "1.Please는 설정> Wi-Fi (은)로 이동을 선택",
	"from the list of Wi-Fi network services.": "Wi-Fi 네트워크 서비스 목록에서.",
	"2.Enter the password you just setup when prompted.": "메시지가 표시되면 방금 설치 암호를 2.Enter.",
	"Checking Internet connectivity": "인터넷 연결 확인",
	"Wi-Fi Client": "Wi-Fi (은) 클라이언트",
	"Save": "저장",
	"Please wait": "잠시 기다려주세요",
	"Configure Your Internet Connection": "인터넷 연결 구성",
	"Detecting Internet connection": "인터넷 연결을 감지",
	"Install": "설치",
	"Please plug one end of the Ethernet cable included with your device into the port labeled INTERNET on your device. Plug the other end of this cable into the Ethernet port on yourDSL or cable broadband modem, and power cycle the modem.": "장치의 포트 레이블 인터넷에 당신의 장치와 함께 제공되는 이더넷 케이블의 한쪽 끝을하시기 바랍니다. yourDSL 또는 케이블 광대역 모뎀의 이더넷 포트에이 케이블의 다른 쪽 끝을 연결합니다.",
	"Please select your Internet connection type below": "인터넷 연결 유형 아래를 선택하세요",
	"PPPoE": "PPPoE를",
	"To setup this Internet connection, you will need to have a User Name from your InternetService Provider. If you do not have this information, please contact your ISP.": "이 인터넷 연결을 설정하려면, 당신은 당신의 InternetService 공급자에서 사용자 이름이 필요합니다. 이 정보가없는 경우, ISP에 문의하십시오.",
	"Static IP": "고정 IP",
	"Dynamic IP (DHCP)": "동적 IP (DHCP)",
	"To set up this conncetion you will need to have a complete list of IP information by your Internet Service Provider. If you have a Static IP connection and do not have this information, please contact your ISP.": "이 conncetion을 설정하려면 인터넷 서비스 공급자에 의해 IP 정보의 전체 목록이 필요합니다. 당신은 정적 IP 연결을 가지고 있으며이 정보가없는 경우, ISP에 문의하십시오.",
	"Wi-Fi Settings": "Wi-Fi를 설정",
	"To setup a Wi-Fi Network you will need to give your Wi-Fi Nerwork a Name(SSID) and Password.": "Wi-Fi 네트워크를 설정하려면 당신의 Wi-Fi를 Nerwork 이름 (SSID)과 암호를 제공해야합니다.",
	"By default, your new D-Link device does not have a password configured for administrator access to the Web-based configuration utility. To secure your new device, please create a password below.": "기본적으로, 새 D - 링크 장치는 웹 기반 구성 유틸리티에 대한 관리자 액세스에 대해 구성된 암호가 없습니다. 새 장치를 보호하려면, 아래의 암호를 생성하십시오.",
	"Setup Complete": "설치 완료",
	"Below is a summary of your Wi-Fi security and device password settings.Please take a note of your settings and save your configuration.": "아래는 Wi-Fi 인터넷 보안 및 장치 암호를 settings.Please이 설정의 주를 가지고 구성을 저장을 요약 한 것입니다.",
	"Checking Your Internet connectivity": "당신의 인터넷 연결을 확인",
	"Checking Internet connectivity": "인터넷 연결 확인",
	"mydlink Regristration": "mydlink Regristration",
	"Congratulations": "축하합니다.",
	"Congratulations,your device has been configured. You can now connect to your Wi-Fi network by using the new Wi-Fi Network Name and Password you created.": "축하합니다. 장치가 구성되었습니다. 이제 새로 만든 Wi-Fi 네트워크 이름과 암호를 사용하여 Wi-Fi 네트워크에 연결할 수 있습니다.",
	"Back": "뒤로",
	"Next": "다음",
	"Skip": "건너 뛰기",
	"Finish": "끝",
	"Registered": "Registered",
	"Unregistered": "Unregistered",
	
	// Ethernet, Wireless, Wireless_Guest
	"Wi-Fi Clients (Guest Zone)": "Wi-Fi (은) 클라이언트 (고객 지역)",
	"Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.",
	"Here, you can see a list of all devices connected through Wi-Fi. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "여기에서, 당신은 Wi-Fi를 통해 연결된 모든 장치의 목록을 볼 수 있습니다. 그것에 대해 더 많은 정보를 보려면, 또는 장치에게 쉽게 식별 할 수 있도록 이름을 지정하는 연필 아이콘을 클릭 장치를 클릭하십시오. 당신은 블록 드롭 다운 상자를 사용하여 항상 네트워크에 액세스하거나 일정에 따라에서 장치를 차단할 수 있습니다.",
	"Vendor": "공급 업체",
	"Reserve IP": "예약된 IP",
	"Access": "액세스",
	"Allowed": "허용",
	"Blocked": "거부",
	
	// Internet > IPv4
	"Use this section to configure your Internet Connection type. There are several connection types to choose from Static IP, DHCP, PPPoE, PPTP, L2TP, and DS-Lite. If you are unsure of your connection method, please contact your Internet Service Provider. Note:  If using the PPPoE option, you will need to remove or disable any PPPoE client software on your computers.": "인터넷 연결 유형을 구성하려면이 섹션을 사용합니다. 고정 IP, DHCP, PPPoE를, PPTP, L2TP 및 DS-라이트에서 선택할 수있는 몇 가지 연결 유형이 있습니다. 당신의 연결 방법을 모를 경우 인터넷 서비스 공급자에게 문의하십시오. 참고 : PPPoE를 옵션을 사용하는 경우, 당신은 당신의 컴퓨터에 어떤 PPPoE를 클라이언트 소프트웨어를 제거하거나 사용하지 않도록 설정해야합니다.",
	"My Internet Connection is": "내 인터넷 연결은",
	"Host Name": "호스트 이름",
	"Mac Address Clone": "MAC 주소 복제",
	"PPTP IP Address": "PPTP의 IP 주소",
	"PPTP Server IP Address": "PPTP 서버의 IP 주소",
	"PPTP Subnet Mask": "PPTP 서브넷 마스크",
	"PPTP Gateway IP Address": "PPTP 게이트웨이 IP 주소",
	"L2TP IP Address": "L2TP IP 주소",
	"L2TP Server IP Address": "L2TP 서버 IP 주소",
	"L2TP Subnet Mask": "L2TP 서브넷 마스크",
	"L2TP Gateway IP Address": "L2TP 게이트웨이 IP 주소",
	"MTU": "MTU",
	"Address Mode": "주소 모드",
	"Reconnect Mode": "모드를 다시 연결",
	"Maximum Idle Time": "최대 유휴 시간",
	"DS-Lite Configuration": "DS-라이트 구성",
	"DS-Lite DHCPv6 Option": "DS-라이트 DHCPv6을 옵션",
	"Manual Configuration": "수동 구성",
	"AFTR IPv6 Address": "AFTR의 IPv6 주소",
	"B4 IPv4 Address": "B4 IPv4 Address (IPv4 주소)",
	"WAN IPv6 Address": "WAN IPv6 Address (IPv6 주소)",
	"IPv6 WAN Default Gateway": "IPv6의 WAN 기본 게이트웨이",
	"Advanced Settings": "고급 설정",
	"Manual": "사용 설명서",
	"Always on": "항상 켜짐",
	"On demand": "수요",
	"Dynamic IP": "Dynamic IP",
	
	// Internet > IPv6
	"All of your IPv6 Internet and network connection details are displayed on this page.": "귀하의 IPv6 인터넷 및 네트워크 연결의 모든 상세한 부분은 모두이 페이지에 표시됩니다.",
	"Auto Detection": "자동 감지",
	"Static IPv6": "고정 IPv6",
	"Auto Configuration (SLAAC/DHCPv6)": "자동 구성 (SLAAC/DHCPv6)",
	"IPv6 in IPv4 Tunnel": "IPv4의 터널에서 IPv6",
	"6to4": "6to4를",
	"Local Connectivity Only": "로컬 연결 만",
	"Use Link-Local Address": "링크 - 로컬 주소를 사용",
	"Subnet Prefix Length": "서브넷 접두사 길이",
	"PPPoE Session": "PPPoE를 세션",
	"Remote IPv4 Address": "원격 IPv4 Address (IPv4 주소)",
	"Remote IPv6 Address": "원격 IPv6 Address (IPv6 주소)",
	"Local IPv4 Address": "로컬 IPv4 Address (IPv4 주소)",
	"Local IPv6 Address": "로컬 IPv6 주소",
	"6to4 Address": "6to4를 주소",
	"6to4 Relay": "6to4 릴레이",
	"Assign IPv6 Prefix": "IPv6 Prefix (IPv6 접두어)를 할당",
	"LAN IPv6 Link-Local Address": "LAN IPv6를 링크 - 로컬 주소",
	"IPv6 DNS SETTINGS": "IPv6의 DNS 설정",
	"LAN IPv6 ADDRESS SETTINGS": "LAN의 IPv6 주소 설정",
	"LAN IPv6 Address": "LAN IPv6의 주소",
	"ADDRESS AUTOCONFIGURATION SETTINGS": "주소 자동 설정",
	"Enable Automatic IPv6 Address Assignment": "자동 IPv6 주소 할당을 사용",
	"Enable Automatic DHCP-PD in LAN": "사용 LAN의 자동 DHCP-PD",
	"Autoconfiguration Type": "자동 유형",
	"Enable DHCP-PD": "DHCP-PD를 사용",
	"6RD MANUAL CONFIGURATION": "6RD 수동 구성",
	"Enable Hub and Spoke Mode": "허브를 사용하고 모드를 말했다",
	"6rd Configuration": "6RD 구성",
	"6rd IPv6 Prefix": "6RD IPv6 Prefix (IPv6 접두어)",
	"6rd Border Relay IPv4 Address": "6RD 국경 릴레이 IPv4의 주소",
	"IPv6 ULA SETTINGS": "IPv6를 ULA 설정",
	"Enable ULA": "ULA 사용",
	"Use Default ULA Prefix": "기본 ULA 접두어를 사용",
	"ULA Prefix": "ULA 접두사",
	"CURRENT IPv6 ULA SETTINGS": "현재 IPv6를 ULA 설정",
	"Current ULA Prefix": "현재 ULA 접두사",
	"LAN IPv6 ULA": "LAN IPv6를 ULA",
	"minutes": "분",
	"DNS Type": "DNS 유형",
	"Obtain a DNS server address automatically": "자동으로 DNS 서버 주소 받기",
	"Use the following DNS address": "다음 DNS 주소 사용",
	"SLAAC+Stateless DHCP": "SLAAC + 무국적 DHCP",
	"Stateful DHCPv6": "상태 DHCPv6을",
	"6rd DHCPv4 Option": "6RD DHCPv4를 옵션",
	"Share with IPv4": "IPv4의와 공유",
	"Create a new session": "새로운 세션을 생성",
	"bytes": "bytes",
	"Router Advertisement Lifetime": "Router Advertisement Lifetime",
	"IPv6 Address Range (Start)": "IPv6 Address Range (Start)",
	"IPv6 Address Range (End)": "IPv6 Address Range (End)",
	"IPv6 Address Lifetime": "IPv6 Address Lifetime",
	
	// WiFi & Guest Zone
	"Security Mode": "보안 모드",
	"None": "없음",
	"WPA-Personal": "WPA-개인",
	"Auto": "자동",
	"High": "높은",
	"Low": "낮은",
	"802.11 Mode": "802.11 모드",
	"Wi-Fi Channel": "Wi-Fi (은) 채널",
	"Transmission Power": "전송 전력",
	"Channel Width": "채널 폭",
	"Visibility Status": "가시성 상태",
	"Visible": "눈에 보이는",
	"Invisible": "눈에 보이지 않는",
	"Mixed 802.11b/g": "혼합 802.11 / g",
	"Mixed 802.11g/n": "혼합 802.11g에 / N",
	"Mixed 802.11b/g/n": "혼합 802.11b/g/n의",
	"Auto 20/40 MHz": "자동 20 / 40 MHz의",
	"Mixed 802.11a and 802.11n": "혼합 802.11a 및 802.11n",
	"Use this section to configure the wireless settings for your D-Link Router. Please note that changes made on this section may also need to be duplicated on your Wireless Client.": "당신의 D - 링크 라우터에 대한 무선 설정을 구성하려면이 섹션을 사용합니다. 이 부분에 대한 변경 사항은 또한 당신의 무선 클라이언트에 복제해야 할 수도 있습니다.",
	"This page lets you configure a Wi-Fi Guest Zone. Wi-Fi Guest Zones are Wi-Fi networks that are separate from your normal ones, and use different Wi-Fi Network Names and passwords. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless the Access Local Service option is enabled. Guest Zones are useful to give guests Internet access without allowing them to access your own devices on your network.": "This page lets you configure a Wi-Fi Guest Zone. Wi-Fi Guest Zones are Wi-Fi networks that are separate from your normal ones, and use different Wi-Fi Network Names and passwords. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless the Access Local Service option is enabled. Guest Zones are useful to give guests Internet access without allowing them to access your own devices on your network.",
	"Internet Access Only": "인터넷 접속용",
	"Routing Between Zones": "구역(Zone) 사이의 라우팅",
	"Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.": "Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.",
	"Your changes are being saved.": "Your changes are being saved.",
	
	// Network
	"Network": "네트워크",
	"Network Settings": "네트워크 설정",
	"DHCP Server": "DHCP 서버",
	"Use this page to configure the local network settings for your router, including the IP address you use to access this configuration interface. Please note that if you change this IP address, you will need to use the new IP to access this interface.": "이 구성 인터페이스에 액세스하는 데 사용하는 IP 주소를 포함하여 라우터의 로컬 네트워크 설정을 구성하려면이 페이지를 사용하십시오. 이 IP 주소를 변경하는 경우, 당신은이 인터페이스에 액세스하려면 새 IP를 사용해야합니다 유의하십시오.",
	"LAN IP Address": "LAN IP 주소",
	"Device Name": "장치 이름",
	"Local Domain Name": "로컬 도메인 이름",
	"Enable DNS Relay": "DNS 릴레이 사용",
	"DHCP IP Address Range": "DHCP IP 주소 범위",
	"DHCP Lease Time": "DHCP 임대 시간",
	"Always Broadcast": "항상 방송",
	"compatibility for some DHCP Clients": "(일부 DHCP 클라이언트에 대한 호환성)",
	"If you changed the IP address of the router you will need to change the IP address in your browser before accessing the configuration website again.": "당신은 라우터의 IP 주소를 변경 한 경우 다시 구성 웹 사이트를 액세스하기 전에 브라우저에 IP 주소를 변경해야합니다.",
	"The new settings have been saved.": "새 설정이 저장되었습니다.",
	"to": "to",
	
	// Advanced Network
	"Advanced Network": "고급 네트워크",
	"Advanced Network settings allow you to configure some of the more advanced features of your router. It is recommended that you only change these settings if you are  familiar with them, or if you are specifically instructed to do so.": "고급 네트워크 설정은 라우터의 고급 기능 중 일부를 구성 할 수 있습니다. 그것은 당신이 그들을 잘 알고있는 경우에만 이러한 설정을 변경하는 것이 좋습니다, ​​또는 당신이 특별히 지시하는 경우.",
	"UPnP": "UPnP",
	"WAN Port Speed": "WAN 포트 속도",
	"IPv4 Multicast Streams": "IPv4의 멀티 캐스트 스트림",
	"IPv6 Multicast Streams": "IPv6의 멀티 캐스트 스트림",
	"Auto (10/100/1000 Mbps)": "자동 (10/100/1000 Mbps)",
	
	// SharePort
	"SharePort": "SharePort",
	"DLNA (Digital Living Network Alliance) is the standard for the interoperability of Network Media Devices (NMDs). The user can enjoy multi-media applications (music, pictures and videos) on your network connected PC or media devices. Web File Access allows you to use a web browser to remotely access files stored on an SD card or USB storage drive plugged into the router.": "DLNA (디지털 리빙 네트워크 얼라이언스) 네트워크 미디어 디바이스 (NMDs)의 상호 운용성을위한 표준입니다.사용자가 네트워크에 연결된 PC 또는 미디어 장치에서 멀티미디어 응용 프로그램 (음악, 사진 및 비디오) 즐길 수 있습니다. 웹 파일 액세스는 원격으로 SD 카드 또는 라우터에 연결 USB 저장 드라이브에 저장된 파일을 액세스 할 웹 브라우저를 사용할 수 있습니다.",
	"DLNA Media Server Configuration": "DLNA 미디어 서버 구성",
	"DLNA Media Server": "DLNA 미디어 서버",
	"Web File Access": "웹 파일 액세스",
	"Remote Access Port": "원격 액세스 포트",
	"Remote HTTPS Port": "원격 HTTPS 포트",
	"Enable Storage Remote Access": "스토리지 원격 액세스 활성화",
	"Direct Links": "직접 링크",
	"Local Access": "로컬 액세스",
	"SharePort Web Access": "SharePort 웹 액세스",
	
	// SharePort CreateUser
	"\"Create User\" manage access to your storage devices or use the Guest account (guest/guest) to access the Guest Folder. After plugging in an SD card or USB storage drive, the new device will appear in the list with a link to it. You can then use this link to connect the drive and login with a user account.": "\"사용자 만들기 \"저장 장치에 대한 액세스를 관리하거나 게스트 폴더에 액세스하려면 게스트 계정 (게스트 / 게스트)를 사용합니다.SD 카드 또는 USB 저장 드라이브를 연결하면 새 장치에 대한 링크와 함께 목록에 나타납니다. 그런 다음 사용자 계정으로 드라이브 로그인 연결이 링크를 사용할 수 있습니다.",
	"Remote Access": "원격 액세스",
	"Create User": "사용자 만들기",
	"User Name": "사용자 이름",
	"Access Path": "액세스 경로",
	"Permission": "허가",
	"Edit": "편집",
	"Delete": "삭제",
	"Browse": "찾아보기",
	"OK": "OK",
	"Create User": "사용자 만들기",
	"Create New User": "새 사용자를 만듭니다",
	"Edit User Profile": "사용자 프로필 편집",
	"Folder": "폴더",
	"Select Folder": "폴더 선택",
	"USB Device Name": "USB 장치 이름",
	"Number of Device": "장치의 수",
	
	// mydlink
	"Setting and registering your router with mydlink will allow you to use its mydlink cloud services features, including online access and management of your router through the mydlink portal website.": "설정 및 mydlink하여 라우터를 등록하면 mydlink 포털 웹 사이트를 통해 온라인으로 액세스 및 라우터의 관리를 포함하여 mydlink 클라우드 서비스의 기능을 사용 할 수 있습니다.",
	"mydlink Registration": "mydlink 등록",
	"Sign Up": "가입하기",
	"Sign In": "로그인",
	"Please enter your e-mail address and mydlink password.": "전자 메일 주소와 mydlink 암호를 입력하십시오.",
	"You must accept the terms and conditions to continue.": "계속하려면 계약 조건에 동의해야합니다.",
	
	// QoS Engine
	"QoS Engine": "QoS 엔진",
	"QoS prioritizes your network traffic so you can decide what devices should have priority over other devices. For example, you could set a computer that is downloading files to have lower priority than a laptop that is streaming movies to ensure that you can stream movies smoothly without downloads taking up all of your bandwidth.": "당신이 장치를 다른 장치에 우선 순위를 가지고해야하는지 결정할 수 있도록 QoS 기능은 네트워크 트래픽의 우선 순위를 결정합니다. 예를 들어, 당신은 다운로드 대역폭을 모두 차지하지 않고 원활하게 동영상을 스트리밍 할 수 있도록 영화를 스트리밍 노트북보다 낮은 우선 순위를 가지고 파일을 다운로드하는 컴퓨터를 설정할 수 있습니다.",
	"All Devices": "모든 장치",
	"Drag the device cards above to the Prioity boxes below.": "아래의 Prioity 상자에 위의 장치 카드를 드래그합니다.",
	"Highest": "가장 높음",
	"Medium": "중간",
	
	// Firewall
	"Firewall Settings": "방화벽 설정",
	"Here, you can set up various firewall features to protect your network from attacks. You can click on the DMZ, IPv4 Rules, and IPv6 Rules buttons to see the settings for that feature.": "여기에서, 당신은 공격으로부터 네트워크를 보호하기 위해 다양한 방화벽 기능을 설정할 수 있습니다. 해당 기능에 대한 설정을 확인합니다 DMZ, IPv4의 규칙 및 IPv6 규칙 단추를 클릭 할 수 있습니다.",
	"Application Level Gateway (ALG) Configuration": "응용 프로그램 수준 게이트웨이 (ALG) 구성",
	"Enable SPI IPv4": "SPI IPv4 사용",
	"Enable Anti-spoof Checking": "Anti-spoof 검사 사용",
	"IPv6 Simple Security": "IPv6의 간단한 보안",
	"PPTP": "PPTP",
	"IPSec (VPN)": "IPSec을 (VPN)",
	"RTSP": "RTSP",
	"SIP": "SIP",
	"IPv4 Rules": "IPv4의 규칙",
	"IPv6 Rules": "IPv6의 규칙",
	"Firewall": "방화벽",
	"Enable DMZ Host": "DMZ 호스트 사용",
	"DMZ IP Address": "IP 주소를 DMZ",
	"Security Check": "보안 검색",
	
	// Firewall IPv4, IPv6
	"The IPv4 rule section is an advance feature used to deny or allow traffic from passing through the device.": "IPv4의 규칙 섹션은 장치를 통해 통과하는에서 트래픽을 거부하거나 허용하는 데 사용 사전 기능입니다.",
	"The IPv6 rule section is an advance feature used to deny or allow traffic from passing through the device.": "IPv6의 규칙 섹션은 장치를 통해 통과하는에서 트래픽을 거부하거나 허용하는 데 사용 사전 기능입니다.",
	"Add Rules": "규칙을 추가",
	"Name": "이름",
	"Schedule": "예정",
	"Create New Rule": "새 규칙 생성",
	"Source IP Address Range": "Source IP Address (소스 IP 주소) 범위",
	"Destination IP Address Range": "Destination IP Address (대상 IP 주소) 범위",
	"Port Range": "Port Range (포트 범위)",
	"Turn IPv4 Filtering OFF": "IPv4 필터링을 껍니다",
	"Turn IPv4 Filtering ON and ALLOW rules listed": "IPv4 필터링을 켜고 나열된 규칙을 ALLOW함",
	"Turn IPv4 Filtering ON and DENY rules listed": "IPv4 필터링을 켜고 나열된 규칙을 DENY함",
	"Turn IPv6 Filtering OFF": "IPv6 필터링을 껍니다",
	"Turn IPv6 Filtering ON and ALLOW rules listed": "IPv6 필터링을 켜고 나열된 규칙을 ALLOW함",
	"Turn IPv6 Filtering ON and DENY rules listed": "IPv6 필터링을 켜고 나열된 규칙을 DENY함",
	
	// Port Forwarding
	"Port Forwarding is used to open ports in your router and to redirect traffic to those ports to a specific device on your network. This may be needed for specific applications, games, or services. You can enter individual ports (80, 68, 888), port ranges (100-150), or in a mixed format (1020-5000, 689).": "포트 포워딩은 라우터에서 포트를 열고 사용자의 네트워크에 특정 장치에 해당 포트로 트래픽을 리디렉션하는 데 사용됩니다. 이것은 특정 응용 프로그램, 게임 또는 서비스에 필요할 수 있습니다. 당신은 개별 포트 (80, 68, 888), 포트 범위 (100 ~ 150), 또는 혼합 형식을 (1020-5000, 689)을 입력 할 수 있습니다.",
	"Local IP": "로컬 IP",
	"TCP Port": "TCP 포트",
	"UDP Port": "UDP 포트",
	
	// Virtual Server
	"The Virtual Server option allows you to define a single public port on your router for redirection to an internal LAN IP Address and Private LAN port if required. This feature is useful for hosting online services such as FTP or Web Servers.": "가상 서버 옵션이 필요한 경우는 내부 LAN IP 주소와 사설 LAN 포트에 리디렉션 라우터에서 하나의 공용 포트를 정의 할 수 있습니다. 이 기능은 FTP 나 웹 서버와 같은 온라인 서비스를 호스팅하는 데 유용합니다.",
	"Protocol": "프로토콜",
	"External Port": "외부 포트",
	"Internal Port": "내부 포트",
	"Protocol Number": "Protocol Number",
	
	// Website Filter
	"The Website Filter option allows you to set up a list of Web sites you would like to allow or deny through your network. To use this feature, you must also select the \"Apply Web Filter\" checkbox in the Access Control section.": "웹 사이트 필터 옵션을 사용하면 네트워크를 통해 허용 또는 거부하고 싶은 웹 사이트의 목록을 설정할 수 있습니다. 이 기능을 사용하려면, 당신은 또한 \가 액세스 제어 섹션에서 확인란을 \"웹 필터 \"\ 적용\"을 선택해야합니다.",
	"DENY computers access to ONLY these sites": "컴퓨터 만 이러한 사이트에 대한 액세스 거부",
	"ALLOW computers access to ONLY these sites": "컴퓨터에게 ONLY 이러한 사이트에 대한 액세스를 허용",
	"Website URL/Domain": "웹 사이트 URL / 도메인",
	
	// StaticRouter, StaticRouterIPv6
	"Static Routes": "고정 경로",
	"This page allows you to define custom routes to define how data traffic is moved around your network.": "이 페이지는 데이터 트래픽이 네트워크의 주위에 이동하는 방법을 정의하는 사용자 정의 경로를 정의 할 수 있습니다.",
	"Destination IP": "목적지 IP",
	"Netmask": "마스크",
	"Gateway": "게이트웨이",
	"Matrix": "매트릭스",
	"Interface": "인터페이스",
	"DestNetwork": "DestNetwork",
	"PrefixLen": "PrefixLen",
	
	// DynamicDNS
   	"Dynamic DNS (DDNS) allows you to use an easy to remember domain name such as www.[YourDomainName].com to reach your router\'s dynamically assigned IP address. This is useful when hosting a web, FTP, or game server, and allows you to reach your server no matter what your IP address has changed to. D-Link offers a free DDNS service that you can use through www.DLinkDDNS.com.": "동적 DNS (DDNS)는 같은 WWW 같은 도메인 이름을 기억하기 쉽게 사용할 수 있습니다. 라우터 \ '의 동적으로 할당 된 IP 주소를 도달하는 [YourDomainName]. com. 이 웹, FTP, 게임 서버를 호스팅 할 때 유용합니다, 당신은 서버의 IP 주소가 변경된 내용을 문제없이 도달 할 수 있습니다. D - 링크는 www.DLinkDDNS.com를 통해 사용할 수있는 무료 DDNS 서비스를 제공합니다.",
	"Server Address": "서버 주소",
	"Dynamic DNS": "동적 DNS",
	"Enable Dynamic DNS": "동적 DNS 사용",
	"Select Server Name": "서버 이름을 선택",
	"Time Out": "체크 아웃 시간",
	"IPv6 Address": "IPv6 Address (IPv6 주소)",
	"hours": "시간",
	
	// Time
	"Time & Schedule": "시간 및 일정",
	"Time": "시간",
	"Time Confuguration": "시간 Confuguration",
	"Automatic Time Confuguration": "자동 시간 Confuguration",
	"Manual Time Confuguration": "수동으로 시간 Confuguration",
	"Date": "날짜",
	"This page allows you to set the router\'s internal system clock. You can set the time manually, or automatically through a time server.": "이 페이지는 라우터 \ '의 내부 시스템 클럭을 설정할 수 있습니다. 당신은 시간 서버를 통해 수동 또는 자동으로 시간을 설정할 수 있습니다.",
	"System Time": "시스템 시간",
	"Time Zone": "시간대",
	"Enable Daylight Saving": "일광 절약 가능",
	"Update Time Using an NTP Serevr": "NTP Serevr를 사용하여 업데이트 시간",
	"Year/ Month/ Day": "년 / 월 / 일",
	"Hour/ Minute": "시간 / 분",
	"Day": "하루",
	"Hour": "시간",
	"Min": "최소",
	"Sec": "초",
	
	// Schedule
	"The Schedule configuration option is used to manage schedule rules for various firewall and parental control features.": "일정 구성 옵션은 다양한 방화벽 및 보호자 통제 기능에 대한 일정 규칙을 관리하는 데 사용됩니다.",
	"Monday": "Monday",
	"Tuesday": "Tuesday",
	"Wednesday": "Wednesday",
	"Thursday": "Thursday",
	"Friday": "Friday",
	"Saturday": "Saturday",
	"Sunday": "Sunday",
	"All Day": "All Day",
	"All Week": "All Week",
	"Always": "Always Enable",
	
	// System Log
	"System Log": "시스템 로그",
	"SysLog Settings": "시스템 로그 설정",
	"This page allows you to enable logging of system events to a SysLog server, or to e-mail the log to you according to a schedule or when the log is full.": "이 페이지는 일정하거나 로그가 꽉에 따라 당신에게 로그를 syslog 서버로 시스템 이벤트 로그 또는 전자 메일을 사용 할 수 있습니다.",
	"SysLog Server IP Address": "Syslog 서버의 IP 주소",
	"Enable Logging to Syslog Server": "Syslog 서버에 로깅 활성화",
	"E-mail Settings": "전자 메일 설정",
	"E-mail Log When Full or On Schedule": "이메일 로그인 할 때 전체 또는 일정",
	"Enable E-mail Notification": "이메일 알림을 활성화",
	"From E-mail Address": "이메일일 주소에서",
	"To E-mail Address": "이메일 주소",
	"SMTP Server Address": "SMTP 서버 주소",
	"SMTP Server Port": "SMTP 서버 포트",
	"Enable Authentication": "인증 사용",
	"Account Name": "계정 이름",
	"On Log Full": "전체 로그에",
	"On Schedule": "일정",
	
	// System
	"System": "체계",
	"Save Configuration": "구성을 저장",
	"Restore Configuration From File": "파일에서 복원 구성",
	"Restore Factory Default": "공장 출하시의 초기 설정으로 복원",
	"Reboot": "재부팅",
	"This page lets you save your router\'s current settings to a file, restore your settings from a file, restore your router to factory default settings, or reboot the device. Please note that restoring the settings to the factory defaults will erase all settings, including any rules you have created.": "이 페이지는, 파일에 라우터의 \ '의 현재 설정을 저장할 파일에서 설정을 복원, 공장 출하시 기본 설정으로 라우터를 복원하거나 장치를 재부팅 할 수 있습니다.공장 기본값으로 설정을 복원하면 사용자가 만든 모든 규칙을 포함한 모든 설정이 삭제된다는 점에 유의하시기 바랍니다.",
	"Save Settings To Local Hard Drive": "로컬 하드 드라이브에 설정 저장",
	"Load Settings From Local Hard Drive": "로컬 하드 드라이브에서 설정로드",
	"Restore To Factory Default Settings": "공장 출하시 기본 설정으로 복원",
	"Reboot The Device": "장치를 재부팅",
	"Cancel": "취소",
	"Are you sure you want to restore configuration file?": "당신은 구성 파일을 복원 하시겠습니까?",
	"Do not close the page or power off the service until the restore configuration file is complete!": "복원 구성 파일이 완료 될 때까지 서비스를 해제 페이지 또는 전원을 닫지 마십시오!",
	"Restore configuration file failed!": "구성 파일을 복원하지 못했습니다!",
	"Restore configuration file success!": "구성 파일의 성공을 복원!",
	"Are you sure you want to reset the device?": "당신은 장치를 재설정 하시겠습니까?",
	"Rebooting": "재부팅",
	"Reboot success!": "성공을 재부팅합니다!",
	"Are you sure you want to reset the device to its factory default settings? This will cause current settings to be lost.": "당신은 공장 출하시 기본 설정으로 장치를 재설정 하시겠습니까? 이 현재의 설정이 손실 될 수 있습니다.",
	"Restore to factory default success!": "공장 출하시의 성공으로 복원!",
	"Select File": "파일을 선택",
	"Restore": "복원",
	"Restore Factory Default": "공장 출하시의 초기 설정으로 복원",
	
	// Admin
	"Admin": "관리자",
	"Admin Password": "관리자 암호",
	"Administration": "관리",
	"Use HTTPS": "HTTPS를 사용하여",
	"The admin has read/write access and can change passwords, while the user has read-only access. By default there is no password configured. It is highly recommended that you create a password to keep your router secure.": "사용자는 읽기 전용 액세스를 가지고있는 반면 관리자는 읽기 / 쓰기 액세스 권한을 가지고 있으며, 암호를 변경할 수 있습니다. 기본적으로 구성 암호가 없습니다. 그것은 매우 당신이 라우터의 보안을 유지하려면 암호를 만드는 것이 좋습니다.",
	"Enable Graphical Authentication (CAPTCHA)": "그래픽 인증 (CAPTCHA)을 활성화",
	"Enable HTTPS Server": "HTTPS 서버 활성화",
	"Enable Remote Management": "원격 관리를 가능하게",
	"Remote Admin Port": "원격 관리 포트",
	"Remote Admin Inbound Filter": "원격 관리 인바운드 필터",
	
	// Update Firmware
	"Upgrade Firmware": "펌웨어 업그레이드",
	"This page shows you your current firmware version and language pack, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below. If you are using a language pack, we recommend that you also get the latest version of the language pack when upgrading the firmware to ensure that any changes in the interface are shown correctly.": "이 페이지는 당신에게 당신의 현재 펌웨어 버전과 언어 팩을 보여주고, 당신이 확인하고 새 펌웨어를 다운로드 할 수 있습니다.펌웨어를 다운로드 후, 당신은 그 아래의 버튼을 사용하여 업그레이드 할 수 있습니다. 당신은 언어 팩을 사용하는 경우, 우리는 인터페이스의 변경 사항이 올바르게 표시되도록 펌웨어를 업그레이드 할 때 당신은 또한 언어 팩의 최신 버전을 설치하는 것이 좋습니다.",
	"Current Firmware Version": "현재 펌웨어 버전",
	"Current Firmware Date": "현재 펌웨어 날짜",
	"Current Language Pack": "현재 언어 팩",
	"Download New Firmware": "새 펌웨어를 다운로드",
	"Upgrade Firmware": "펌웨어 업그레이드",
	"Add a Language Pack": "언어 팩 추가",
	"Upload": "업로드",
	"Upgrade": "업그레이드",
	"Upgrading": "Upgrading",
	"Do you want to upgrade Firmware?": "당신은 펌웨어를 업그레이드 하시겠습니까?",
	"Do not power off the device until the Firmware Upgrade is complete!": "펌웨어 업그레이드가 완료 될 때까지 서비스를 해제 페이지 또는 전원을 닫지 마십시오!",
	"Firmware Uploading": "펌웨어 업로드",
	"Firmware Upgrade failed!": "펌웨어 업그레이드 실패!",
	"Firmware Upgrade success!": "펌웨어 업그레이드 성공!",
	"Firmware Imformation": "펌웨어 IMFORMATION",
	"New Firmware Version": "새로운 펌웨어 버전",
	"New Firmware Date": "새 펌웨어 날짜",
	"Check for New Firmware": "새 펌웨어를 확인",
	"Language Pack Imformation": "언어 팩 IMFORMATION",
	"Current Language Pack": "현재 언어 팩",
	"Remove": "제거",
	"Upgrade Manually": "수동으로 업그레이드",
	"Add a Language Pack": "언어 팩 추가",
	"Checking": "검사",
	"Retry": "재시도",
	"This firmware is the latest version.": "This firmware is the latest version.",
	"Downloading": "Downloading",
	"Please do not close the browser while the firmware is being downloaded!": "Please do not close the browser while the firmware is being downloaded!",
	
	// Statistic
	"Statistics": "통계",
	"This page gives you various statistics about data transmitted and received by your router through the Internet, on your wired network (LAN), and through your wireless networks.": "이 페이지는 유선 네트워크 (LAN)에 인터넷을 통해 라우터에 의해 전송 및 수신 데이터에 대한 당신의 무선 네트워크를 통해 다양한 통계를 제공합니다.",
	"Clear": "취소",
	"Information: Your browser is not support HTML5, please upgrade your browser.": "정보 : 귀하의 브라우저가 HTML5를 지원하지 않습니다, ​​브라우저를 업그레이드 해주세요.",
	"Sent (Tx)": "전송 (TX)",
	"Received (Rx)": "수신 (RX)",
	"Total Packets": "Total Packets",
	"Total Byte(s)": "Total Byte(s)",
	"Total Kbit(s)": "Total Kbit(s)",
	"Kbits/sec": "Kbits/sec",
	"Session": "Session"
}