{
	// Menu
	"Home": "Início",
	"Settings": "Definições",
	"Advanced": "Avançadas",
	"Management": "Gestão",
	"Internet(WAN)": "Internet",
	"Wireless(Wi-Fi)": "Sem Fios",
	"Network(LAN)": "Rede",
	"SharePort": "SharePort",
	"mydlink": "mydlink",
	"Firewall Setting": "Definição de Firewall",
	"Virtual Server": "Servidor Virtual",
	"Port Forwarding": "Encaminhamento de Portas",
	"Website Filter": "Filtro de Sítios da Internet",
	"Static Route": "Encaminhamento Estático",
	"Disabled": "Desativado",
	"Enabled": "Ativado",
	
	// Genernal
	"There is unsaved data on this page. Do you want to abandon it?": "There is unsaved data on this page. Do you want to abandon it?",
	"Remaining": "Remaining",
	
	// Login
	"Model Name": "Nome do Modelo",
	"Hardware Version": "Versão de Hardware",
	"Firmware Version": "Versão de Firmware",
	"Language": "Idioma",
	"Admin Password": "Palavra-passe do Admin",
	"Log In": "Iniciar Sessão",
	"To access your storage with SharePort Web Access,": "Para aceder ao seu armazenamento com SharePort Web Access,",
	"click here.": "clique aqui.",
	"Invalid password, please try again.": "Palavra-passe inválida, tente novamente.",
	"The Private Browsing feature of Safari is incompatible with this device's interface. You will need to disable Private Browsing to log in.": "Desativar Navegação PrivadaA opção Navegação Privada do Safari é incompatível com a interface deste dispositivo. Terá de desativar a Navegação Privada antes de iniciar sessão.",
	
	// Home
	"Current Status": "Estado Atual",
	"Click on any item in the diagram for more information.": "Clique em qualquer item no diagrama para obter mais informações.",
	"Setup Wizard": "Assistente de Configuração",
	"Router": "Router",
	"Internet": "Internet",
	"LAN": "LAN",
	"Router IP Address": "Endereço IP do Router",
	"MAC Address": "Endereço MAC",
	"Wi-Fi 2.4GHz": "Wi-Fi 2,4GHz",
	"Wi-Fi 5GHz": "Wi-Fi 5 GHz",
	"Guest Zone 2.4GHz": "Zona de Convidados 2,4 GHz",
	"Guest Zone 5GHz": "Zona de Convidados 5GHz",
	"IP Address": "Endereço IP",
	"Subnet Mask": "Máscara Sub-rede",
	"Default Gateway": "Gateway Predefinida",
	"Available Space": "Espaço Disponível",
	"Total Space": "Espaço Total",
	"Service Name": "Nome do Serviço",
	"Ethernet Device": "Dispositivo Ethernet",
	"Wi-Fi Clients": "Clientes Wi-Fi",
	"USB Device": "Dispositivo USB",
	"USB Name": "Nome USB",
	"Status": "Estado",
	"Wi-Fi Name (SSID)": "Nome da Wi-Fi (SSID)",
	"Password": "Palavra-passe",
	"IPv6 Connection Type": "Tipo de Ligação IPv6",
	"WAN IPv6 Address": "Endereço IPv6 da WAN",
	"Primary IPv6 DNS Server": "Servidor de DNS IPv6 Preferido",
	"Secondary IPv6 DNS Address": "Servidor de DNS IPv6 Alternativo",
	"LAN IPv6 Link-Local Address": "Endereço de Ligação Local IPv6 LAN",
	"DHCP-PD": "DHCP-PD",
	"IPv6 Network Assigned by DHCP-PD": "Rede IPv6 atribuída por DHCP-PD",
	"LAN IPv6 Address": "Endereço IPv6 da LAN",
	"Guest Zone": "Zona de Convidados",
	"Connection Type": "Tipo de Ligação",
	"Network Status": "Estado da Rede",
	"Connection Up Time": "Tempo de Disponibilidade de Ligação",
	"Primary DNS Server": "Servidor de DNS Preferido",
	"Secondary DNS Server": "Servidor de DNS Alternativo",
	"SharePort": "SharePort",
	"Release": "Versão",
	"Renew": "Renovar",
	"Disconnect": "Desligar",
	"Connect": "Ligar",
	"Ignore": "Ignore",
	"Connected": "Connected",
	"Connecting": "Connecting",
	"Disconnected": "Disconnected",
	"DHCP": "Dynamic IP (DHCP)",
	"Static": "Static IP (Static)",
	"DHCPPPPoE": "Dynamic IP (PPPoE)",
	"StaticPPPoE": "Static IP (PPPoE)",
	"DynamicPPTP": "Dynamic IP (PPTP)",
	"StaticPPTP": "Static IP (PPTP)",
	"DynamicL2TP": "Dynamic IP (L2TP)",
	"StaticL2TP": "Static IP (L2TP)",
	"A new firmware is available! Do you want to download and upgrade the firmware?": "A new firmware is available! Do you want to download and upgrade the firmware?",
	"Your changes are being saved, and the device will need to reboot.": "Your changes are being saved, and the device will need to reboot.",
	"The Wi-Fi connection is not secure.": "The Wi-Fi connection is not secure.",
	"Secure your network.": "Secure your network.",
	
	// Wizard
	"Welcome": "Bem-vindo",
	"This wizard will guide you through a step-by-step process to configure your new D-Link device.": "Este assistente de configuração guiá-lo-á pelo processo passo-a-passo para configurar o seu novo dispositivo D-Link.",
	"Step1: Install your device": "Passo1: Instale o seu dispositivo",
	"Step2: Configure your Network and Wi-Fi settings": "Passo2: Configure a sua Rede e as suas definições Wi-Fi",
	"Step3: Set your router password": "Passo3: Defina a sua palavra-passe do router",
	"Step4: Set mydlink service": "Passo4: Defina o serviço mydlink",
	"Your Device": "O Seu Dispositivo",
	"Cable/xDSL Broadband Modem": "Modem de Banda Larga xDSL/Cabo",
	"DHCP Connection (Dynamic IP Address)": "Ligação DHCP (Endereço IP Dinâmico)",
	"Choose this if your Internet connection automatically provides you with an IP Address. Most Cable Modems use this type of connection.": "Escolha esta opção se a sua ligação à Internet fornece automaticamente um endereço IP. A maioria dos Modems por Cabo utiliza este tipo de ligação.",
	"Username/Password Connection (PPPoE)": "Ligação com Nome de utilizador/Palavra-passe (PPPoE)",
	"Choose this option if your Internet connection reguires a username and passowrd to get online. Most DSL modems use this connection type of connection.": "Escolha esta opção se a sua ligação à Internet necessita de um nome de utilizador e palavra-passe para ligar. A maioria dos modems DSL utiliza este tipo de ligação.",
	"Static IP Address Connection": "Ligação Endereço IP estático",
	"Choose this option if your Internet Setup Provider provided you with IP Address information that has to be manually configured.": "Selecione esta opção se o seu Fornecedor do Serviços de Internet lhe forneceu informações do Endereço IP que tenham de ser configuradas manualmente.",
	"Username": "Nome de utilizador",
	"Gateway Address": "Endereço da Gateway",
	"Primary DNS Address": "Endereço de DNS preferido",
	"Secondary DNS Address": "Endereço de DNS Alternativo",
	"2.4GHz Wi-Fi Network Name": "Nome de Rede Wi-Fi 2,4 GHz",
	"5GHz Wi-Fi Network Name": "Nome de Rede Wi-Fi 5 GHz",
	"The Wi-Fi Network Name is up to 32 characters. You will need to join your Wi-Fi network using this Network Name (SSID).": "O Nome da Rede Wi-Fi deve ter até 32 caracteres. Necessitará de se ligar à sua rede Wi-Fi utilizando este Nome de Rede (SSID).",
	"Wi-Fi Password": "Palavra-passe Wi-Fi",
	"Copy to 5GHz": "Copiar a 5 GHz",
	"2.4GHz Wi-Fi Password": "Palavra-passe Wi-Fi 2,4 GHz",
	"5GHz Wi-Fi Password": "Palavra-passe Wi-Fi 5 GHz",
	"The password must contain at least 8 characters. You will need to join your Wi-Fi network using this password.": "A palavra-passe tem de conter pelo menos 8 caracteres. Necessitará de se ligar à sua rede Wi-Fi utilizando esta palavra-passe.",
	"Device Admin Password": "Palavra-passe do Administrador do Dispositivo",
	"This device is mydlink-enabled, which allows you to remotely monitor and manage your network through the mydlink.com website, or through the mydlink mobile app.": "Este dispositivo tem suporte mydlink, o que lhe permite controlar e gerir remotamente a sua rede através do sítio da Internet mydlink.com ou através da aplicação móvel mydlink.",
	"You can register this device with your existing mydlink account. If you do not have one, you can create one now.": "Pode registar este dispositivo com a sua conta mydlink existente. Se não tiver, pode criar uma agora.",
	"Do you have an existing mydlink account": "Já tem uma conta mydlink",
	"Yes, I have a mydlink account": "Sim, tenho uma conta mydlink",
	"No, I want to create a new mydlink account": "Não, quero criar uma nova conta mydlink",
	"E-mail Address (Account Name)": "Endereço de Correio Eletrónico (Nome de Conta)",
	"First Name": "Primeiro Nome",
	"Last Name": "Apelido",
	"I accept the mydlink": "Aceito os termos e condições",
	"terms and conditions.": "de mydlink.",
	"Connect to the Wi-Fi network from your mobile device or PC": "Ligue-se à rede Wi-Fi a partir do seu dispositivo móvel ou PC",
	"1.Please go to Settings > Wi-fi, and choose": "1.Vá a Definições > Wi-fi, e escolha",
	"from the list of Wi-Fi network services.": "a partir da lista de serviços de rede Wi-Fi.",
	"2.Enter the password you just setup when prompted.": "2.Quando lhe for pedido, introduza a palavra-passe que acabou de configurar.",
	"Checking Internet connectivity": "A verificar ligação à Internet",
	"Wi-Fi Client": "Cliente Wi-Fi",
	"Save": "Guardar",
	"Please wait": "Aguarde",
	"Configure Your Internet Connection": "Configurar a Sua Ligação à Internet",
	"Detecting Internet connection": "A detetar ligação à Internet",
	"Install": "Instalar",
	"Please plug one end of the Ethernet cable included with your device into the port labeled INTERNET on your device. Plug the other end of this cable into the Ethernet port on yourDSL or cable broadband modem, and power cycle the modem.": "Ligue uma extremidade do cabo Ethernet fornecido com o seu dispositivo na porta INTERNET do seu dispositivo. Ligue a outra extremidade deste cabo à porta Ethernet do seu modem de banda larga DSL ou por cabo.",
	"Please select your Internet connection type below": "Selecione o seu tipo de ligação à Internet",
	"PPPoE": "PPPoE",
	"To setup this Internet connection, you will need to have a User Name from your InternetService Provider. If you do not have this information, please contact your ISP.": "Para configurar esta ligação à Internet, terá de ter um Nome de Utilizador do seu Fornecedor de Serviços de Internet. Se não tiver estas informações, por favor contacte o seu ISP (fornecedor de serviços Internet).",
	"Static IP": "IP Estático",
	"Dynamic IP (DHCP)": "IP Dinâmico (DHCP)",
	"To set up this conncetion you will need to have a complete list of IP information by your Internet Service Provider. If you have a Static IP connection and do not have this information, please contact your ISP.": "Para configurar esta ligação, deverá ter uma lista completa de informações do IP fornecida pelo seu Fornecedor do Serviço de Internet. Se tiver uma ligação com IP Estático e não tiver esta informação, contacte o seu ISP.",
	"Wi-Fi Settings": "Definições Wi-Fi",
	"To setup a Wi-Fi Network you will need to give your Wi-Fi Nerwork a Name(SSID) and Password.": "Para configurar uma Rede Wi-Fi, terá de lhe dar um Nome (SSID) e uma Palavra-passe.",
	"By default, your new D-Link device does not have a password configured for administrator access to the Web-based configuration utility. To secure your new device, please create a password below.": "Por defeito, o seu novo dispositivo D-Link não tem uma palavra-passe configurada para acesso de administrador ao utilitário de configuração baseado na Internet. Para tornar o seu novo dispositivo seguro, crie uma palavra-passe abaixo.",
	"Setup Complete": "Configuração Completa",
	"Below is a summary of your Wi-Fi security and device password settings.Please take a note of your settings and save your configuration.": "Abaixo está um resumo da configuração da sua segurança Wi-Fi e da palavra-passe do dispositivo. Tome nota das suas definições e guarde a sua configuração.",
	"Checking Your Internet connectivity": "A verificar a sua ligação à Internet",
	"Checking Internet connectivity": "A verificar ligação à Internet",
	"mydlink Regristration": "Registo mydlink",
	"Congratulations": "Parabéns",
	"Congratulations,your device has been configured. You can now connect to your Wi-Fi network by using the new Wi-Fi Network Name and Password you created.": "Parabéns, o seu dispositivo está configurado. Pode agora ligar à sua rede Wi-Fi utilizando o novo Nome de Rede Wi-Fi e a Palavra-passe que definiu.",
	"Back": "Voltar",
	"Next": "Seguinte",
	"Skip": "Avançar",
	"Finish": "Terminar",
	"Registered": "Registered",
	"Unregistered": "Unregistered",
	
	// Ethernet, Wireless, Wireless_Guest
	"Wi-Fi Clients (Guest Zone)": "Clientes Wi-Fi (Zona de Convidados)",
	"Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.",
	"Here, you can see a list of all devices connected through Wi-Fi. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Aqui pode ver uma lista de todos os dispositivos ligados através de Wi-Fi. Clique num dispositivo para ver mais informações sobre ele, ou clique no ícone lápis para dar um nome ao dispositivo para o tornar mais fácil de identificar. Pode bloquear o acesso de um dispositivo à sua rede de forma permanente ou de acordo com um agendamento, utilizando a caixa pendente de Bloqueio.",
	"Vendor": "Vendedor",
	"Reserve IP": "Reservar IP",
	"Access": "Acesso",
	"Allowed": "Permitido",
	"Blocked": "Bloqueado",
	
	// Internet > IPv4
	"Use this section to configure your Internet Connection type. There are several connection types to choose from Static IP, DHCP, PPPoE, PPTP, L2TP, and DS-Lite. If you are unsure of your connection method, please contact your Internet Service Provider. Note:  If using the PPPoE option, you will need to remove or disable any PPPoE client software on your computers.": "Utilize esta secção para configurar o tipo de ligação à Internet. Existem vários tipos de ligação que pode escolher: IP Estático, DHCP, PPPoE, PPTP, L2TP, e DS-Lite. Se não tiver a certeza do seu método de ligação, contacte o seu Fornecedor de Serviços de Internet. Nota:  Se estiver a utilizar a opção PPPoE, terá de remover ou desativar qualquer software de cliente PPPoE nos seus computadores.",
	"My Internet Connection is": "A minha ligação à Internet é",
	"Host Name": "Nome do Anfitrião",
	"Mac Address Clone": "Clone de Endereço Mac",
	"PPTP IP Address": "Endereço IP PPTP",
	"PPTP Server IP Address": "Endereço IP do Servidor PPTP",
	"PPTP Subnet Mask": "Máscara de Sub-rede PPTP",
	"PPTP Gateway IP Address": "Endereço IP Gateway PPTP",
	"L2TP IP Address": "Endereço IP L2TP",
	"L2TP Server IP Address": "Endereço IP do Servidor L2TP",
	"L2TP Subnet Mask": "Máscara de Sub-rede L2TP",
	"L2TP Gateway IP Address": "Endereço IP Gateway L2TP",
	"MTU": "MTU",
	"Address Mode": "Modo Endereço",
	"Reconnect Mode": "Modo Ligar Novamente",
	"Maximum Idle Time": "Tempo Máximo de Inatividade",
	"DS-Lite Configuration": "Configuração DS-Lite",
	"DS-Lite DHCPv6 Option": "Opção DS-Lite DHCPv6",
	"Manual Configuration": "Configuração Manual",
	"AFTR IPv6 Address": "Endereço AFTR IPv6",
	"B4 IPv4 Address": "Endereço B4 IPv4",
	"WAN IPv6 Address": "Endereço IPv6 da WAN",
	"IPv6 WAN Default Gateway": "Gateway Predefinida IPv6",
	"Advanced Settings": "Definições Avançadas",
	"Manual": "Manual",
	"Always on": "Sempre ligado",
	"On demand": "A pedido",
	"Dynamic IP": "Dynamic IP",
	
	// Internet > IPv6
	"All of your IPv6 Internet and network connection details are displayed on this page.": "Todos os detalhes da sua ligação à Internet IPv6 e à rede são exibidos nesta página.",
	"Auto Detection": "Deteção Automática",
	"Static IPv6": "IPv6 estático",
	"Auto Configuration (SLAAC/DHCPv6)": "Configuração automática (SLAAC/DHCPv6)",
	"IPv6 in IPv4 Tunnel": "IPv6 em Modo de Túnel IPv4",
	"6to4": "6to4",
	"Local Connectivity Only": "Apenas Ligação Local",
	"Use Link-Local Address": "Utilize o Endereço Local da Ligação",
	"Subnet Prefix Length": "Comprimento do Prefixo de Sub-rede",
	"PPPoE Session": "Sessão PPPoE",
	"Remote IPv4 Address": "Endereço IPv4 Remoto",
	"Remote IPv6 Address": "Endereço IPv6 Remotos",
	"Local IPv4 Address": "Endereço IPv4 Local",
	"Local IPv6 Address": "Endereço IPv6 Local",
	"6to4 Address": "Endereço 6to4",
	"6to4 Relay": "Relé 6to4",
	"Assign IPv6 Prefix": "Atribuir Prefixo IPv6",
	"LAN IPv6 Link-Local Address": "Endereço de Ligação Local IPv6 LAN",
	"IPv6 DNS SETTINGS": "DEFINIÇÕES IPv6 DNS",
	"LAN IPv6 ADDRESS SETTINGS": "DEFINIÇÕES DO ENDEREÇO IPv6 LAN",
	"LAN IPv6 Address": "Endereço IPv6 da LAN",
	"ADDRESS AUTOCONFIGURATION SETTINGS": "DEFINIÇÕES DE CONFIGURAÇÃO AUTOMÁTICA DE ENDEREÇO",
	"Enable Automatic IPv6 Address Assignment": "Ativar Atribuição Automática de Endereço IPv6",
	"Enable Automatic DHCP-PD in LAN": "Ativar DHCP-PD Automático na LAN",
	"Autoconfiguration Type": "Tipo de Configuração Automática",
	"Enable DHCP-PD": "Ativar DHCP-PD",
	"6RD MANUAL CONFIGURATION": "CONFIGURAÇÃO MANUAL 6RD",
	"Enable Hub and Spoke Mode": "Ativar Modo Hub and Spoke",
	"6rd Configuration": "Configuração 6rd",
	"6rd IPv6 Prefix": "Prefixo 6rd IPv6",
	"6rd Border Relay IPv4 Address": "Endereço IPv4 de Desvio de Fronteira 6rd",
	"IPv6 ULA SETTINGS": "DEFINIÇÕES ULA IPv6",
	"Enable ULA": "Ativar ULA",
	"Use Default ULA Prefix": "Utilizar Prefixo ULA Predefinido",
	"ULA Prefix": "Prefixo ULA",
	"CURRENT IPv6 ULA SETTINGS": "DEFINIÇÕES ULA IPv6 ATUAIS",
	"Current ULA Prefix": "Prefixo ULA Atual",
	"LAN IPv6 ULA": "LAN IPv6 ULA",
	"minutes": "minutos",
	"DNS Type": "Tipo DNS",
	"Obtain a DNS server address automatically": "Obter endereço do servidor de DNS automaticamente",
	"Use the following DNS address": "Utilize o endereço DNS seguinte",
	"SLAAC+Stateless DHCP": "SLAAC+DHCP Sem Estado",
	"Stateful DHCPv6": "DHCPv6 com Estado",
	"6rd DHCPv4 Option": "Opção DHCPv4 6rd",
	"Share with IPv4": "Partilhar com IPv4",
	"Create a new session": "Criar uma sessão nova",
	"bytes": "bytes",
	"Router Advertisement Lifetime": "Router Advertisement Lifetime",
	"IPv6 Address Range (Start)": "IPv6 Address Range (Start)",
	"IPv6 Address Range (End)": "IPv6 Address Range (End)",
	"IPv6 Address Lifetime": "IPv6 Address Lifetime",
	
	// WiFi & Guest Zone
	"Security Mode": "Modo de segurança",
	"None": "Nenhum",
	"WPA-Personal": "WPA-Personal",
	"Auto": "Auto",
	"High": "Alta",
	"Low": "Baixa",
	"802.11 Mode": "Modo 802.11",
	"Wi-Fi Channel": "Canal Wi-Fi",
	"Transmission Power": "Alimentação de Transmissão",
	"Channel Width": "Largura de Canal",
	"Visibility Status": "Estado da Visibilidade",
	"Visible": "Visível",
	"Invisible": "Invisível",
	"Mixed 802.11b/g": "Mista 802.11b/g",
	"Mixed 802.11g/n": "Mista 802.11g/n",
	"Mixed 802.11b/g/n": "Mista 802.11b/g/n",
	"Auto 20/40 MHz": "Auto 20/40 MHz",
	"Mixed 802.11a and 802.11n": "Mista 802.11a e 802.11n",
	"Use this section to configure the wireless settings for your D-Link Router. Please note that changes made on this section may also need to be duplicated on your Wireless Client.": "Utilize esta secção para configurar as definições sem fios do seu Router D-Link. Tenha em atenção que as alterações feitas nesta secção devem também ser duplicadas pelo seu cliente sem fios.",
	"This page lets you configure a Wi-Fi Guest Zone. Wi-Fi Guest Zones are Wi-Fi networks that are separate from your normal ones, and use different Wi-Fi Network Names and passwords. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless the Access Local Service option is enabled. Guest Zones are useful to give guests Internet access without allowing them to access your own devices on your network.": "Esta página permite-lhe configurar uma Zona de Convidados Wi-Fi. As Zonas de Convidados Wi-Fi são redes Wi-Fi separadas das suas redes normais, e utilizam Nomes e Palavras-passe Wi-Fi diferentes. Os utilizadores ligados a uma Zona de Convidados não podem detetar ou comunicar com os dispositivos que estão na sua rede normal, a não ser que a opção Aceder ao Serviço Local esteja ativada. As Zonas de Convidados são úteis para fornecer acesso à Internet aos seus convidados, sem lhes fornecer acesso aos seus dispositivos na sua rede.",
	"Internet Access Only": "Apenas Acesso à Internet",
	"Routing Between Zones": "Encaminhamento Entre Zonas",
	"Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.": "Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.",
	"Your changes are being saved.": "Your changes are being saved.",
	
	// Network
	"Network": "Rede",
	"Network Settings": "Definições de Rede",
	"DHCP Server": "Servidor DHCP",
	"Use this page to configure the local network settings for your router, including the IP address you use to access this configuration interface. Please note that if you change this IP address, you will need to use the new IP to access this interface.": "Utilize esta página para configurar as definições da rede local do seu router, incluindo o endereço IP que utiliza para aceder a esta interface de configuração. Tenha em atenção que se alterar este endereço IP terá de utilizar o novo IP para aceder a esta interface.",
	"LAN IP Address": "Endereço IP LAN",
	"Device Name": "Nome do Dispositivo",
	"Local Domain Name": "Nome do Domínio Local",
	"Enable DNS Relay": "Ativar Desvio DNS",
	"DHCP IP Address Range": "Intervalo de Endereços IP DHCP",
	"DHCP Lease Time": "Tempo de Reserva DHCP",
	"Always Broadcast": "Difundir Sempre",
	"compatibility for some DHCP Clients": "compatibilidade para alguns clientes DHCP",
	"If you changed the IP address of the router you will need to change the IP address in your browser before accessing the configuration website again.": "Se alterou o endereço IP do router, terá de mudar o endereço IP no seu explorador antes de aceder novamente à página da Internet de configuração.",
	"The new settings have been saved.": "As novas definições foram guardadas.",
	"to": "to",
	
	// Advanced Network
	"Advanced Network": "Rede Avançada",
	"Advanced Network settings allow you to configure some of the more advanced features of your router. It is recommended that you only change these settings if you are  familiar with them, or if you are specifically instructed to do so.": "As Definições Avançadas de Rede permitem-lhe configurar algumas das opções mais avançadas do seu router. Recomenda-se que apenas altere estas definições se estiver familiarizado com elas, ou se lhe pedirem especificamente para o fazer.",
	"UPnP": "UPnP",
	"WAN Port Speed": "Velocidade da Porta WAN",
	"IPv4 Multicast Streams": "Fluxos de Multidifusão IPv4",
	"IPv6 Multicast Streams": "Fluxos de Multidifusão IPv6",
	"Auto (10/100/1000 Mbps)": "Auto (10/100/1000 Mbps)",
	
	// SharePort
	"SharePort": "SharePort",
	"DLNA (Digital Living Network Alliance) is the standard for the interoperability of Network Media Devices (NMDs). The user can enjoy multi-media applications (music, pictures and videos) on your network connected PC or media devices. Web File Access allows you to use a web browser to remotely access files stored on an SD card or USB storage drive plugged into the router.": "DLNA (Digital Living Network Alliance) é o padrão para a interoperabilidade de Dispositivos Média de Rede (NMDs). O utilizador poderá usufruir de aplicações multimédia (música, imagens e vídeos) no seu PC ou dispositivos média ligados à rede. O Web File Access permite-lhe utilizar um explorador de Internet para aceder remotamente a ficheiros armazenados num cartão SD ou dispositivo USB ligado ao router.",
	"DLNA Media Server Configuration": "Configuração do Servidor Multimédia DLNA",
	"DLNA Media Server": "Servidor Multimédia DLNA",
	"Web File Access": "Web File Access",
	"Remote Access Port": "Porta de Acesso Remoto",
	"Remote HTTPS Port": "Porta HTTPS Remota",
	"Enable Storage Remote Access": "Ativar Acesso Remoto de Armazenamento",
	"Direct Links": "Ligações Diretas",
	"Local Access": "Acesso Local",
	"SharePort Web Access": "SharePort Web Access",
	
	// SharePort CreateUser
	"\"Create User\" manage access to your storage devices or use the Guest account (guest/guest) to access the Guest Folder. After plugging in an SD card or USB storage drive, the new device will appear in the list with a link to it. You can then use this link to connect the drive and login with a user account.": "\"Crie Utilizador\" para gerir o acesso aos seus dispositivos de armazenamento ou utilize a conta de Convidado (convidado/convidado) para aceder à pasta Convidado. Após ligar um cartão SD ou dispositivo de armazenamento USB, aparecerá um novo dispositivo na lista com uma ligação. Pode então utilizar essa ligação para ligar o dispositivo e iniciar sessão com a sua conta de utilizador.",
	"Remote Access": "Acesso Remoto",
	"Create User": "Criar Utilizador",
	"User Name": "Nome de utilizador",
	"Access Path": "Caminho de Acesso",
	"Permission": "Permissão",
	"Edit": "Editar",
	"Delete": "Eliminar",
	"Browse": "Procurar",
	"OK": "OK",
	"Create User": "Criar Utilizador",
	"Create New User": "Criar Novo Utilizador",
	"Edit User Profile": "Editar Perfil de Utilizador",
	"Folder": "Pasta",
	"Select Folder": "Selecionar a Pasta",
	"USB Device Name": "Nome de Dispositivo USB",
	"Number of Device": "Número de Dispositivo",
	
	// mydlink
	"Setting and registering your router with mydlink will allow you to use its mydlink cloud services features, including online access and management of your router through the mydlink portal website.": "Definir e registar o seu router em mydlink permitir-lhe-á utilizar as suas funções de serviços cloud com ativação mydlink, incluindo acesso e gestão on-line do seu router através do serviço mydlink.",
	"mydlink Registration": "registo no mydlink",
	"Sign Up": "Inscrever",
	"Sign In": "Iniciar Sessão",
	"Please enter your e-mail address and mydlink password.": "Introduza o seu endereço de correio eletrónico e a palavra-passe mydlink.",
	"You must accept the terms and conditions to continue.": "Tem de aceitar os termos e condições para continuar.",
	
	// QoS Engine
	"QoS Engine": "Motor QoS",
	"QoS prioritizes your network traffic so you can decide what devices should have priority over other devices. For example, you could set a computer that is downloading files to have lower priority than a laptop that is streaming movies to ensure that you can stream movies smoothly without downloads taking up all of your bandwidth.": "O QoS estabelece prioridades no seu tráfego de rede para que possa decidir quais dispositivos têm prioridade. Por exemplo, pode estabelecer que um computador que esteja a descarregar ficheiros tenha uma prioridade mais baixa que um computador portátil que esteja a exibir vídeo em direto, para garantir que o vídeo corre de forma suave, sem que os descarregamentos ocupem toda a largura de banda.",
	"All Devices": "Todos os Dispositivos",
	"Drag the device cards above to the Prioity boxes below.": "Arraste os cartões de dispositivo acima para as caixas de Prioridade abaixo.",
	"Highest": "O mais elevado",
	"Medium": "Média",
	
	// Firewall
	"Firewall Settings": "Definições de Firewall",
	"Here, you can set up various firewall features to protect your network from attacks. You can click on the DMZ, IPv4 Rules, and IPv6 Rules buttons to see the settings for that feature.": "Aqui pode configurar várias opções da firewall para proteger a sua rede de ataques. Pode clicar nos botões DMZ, Regras IPv4, e Regras IPv6 para ver as definições dessa funcionalidade.",
	"Application Level Gateway (ALG) Configuration": "Configuração de Gateway de Nível de Aplicação NAT (ALG)",
	"Enable SPI IPv4": "Ativar SPI IPv4",
	"Enable Anti-spoof Checking": "Ativar Verificação Anti-spoof",
	"IPv6 Simple Security": "Segurança Simples IPv6",
	"PPTP": "PPTP",
	"IPSec (VPN)": "IPSec (VPN)",
	"RTSP": "RTSP",
	"SIP": "SIP",
	"IPv4 Rules": "Regras IPv4",
	"IPv6 Rules": "Regras IPv6",
	"Firewall": "Firewall",
	"Enable DMZ Host": "Ativar Anfitrião DMZ",
	"DMZ IP Address": "Endereço IP da DMZ",
	"Security Check": "Verificação de Segurança",
	
	// Firewall IPv4, IPv6
	"The IPv4 rule section is an advance feature used to deny or allow traffic from passing through the device.": "A secção de regras IPv4 é uma função avançada para permitir ou recusar a passagem de tráfego através do dispositivo.",
	"The IPv6 rule section is an advance feature used to deny or allow traffic from passing through the device.": "A secção de regras IPv6 é uma função avançada para permitir ou recusar a passagem de tráfego através do dispositivo.",
	"Add Rules": "Adicionar Regras",
	"Name": "Nome",
	"Schedule": "Programa",
	"Create New Rule": "Criar Regra Nova",
	"Source IP Address Range": "Intervalo de Endereços IP de Origem",
	"Destination IP Address Range": "Intervalo de Endereços IP de Destino",
	"Port Range": "Intervalo de Portas",
	"Turn IPv4 Filtering OFF": "DESLIGAR Filtragem IPv4",
	"Turn IPv4 Filtering ON and ALLOW rules listed": "LIGAR Filtragem IPv4 e PERMITIR as regras listadas",
	"Turn IPv4 Filtering ON and DENY rules listed": "LIGAR Filtragem IPv4 e RECUSAR as regras listadas",
	"Turn IPv6 Filtering OFF": "DESLIGAR Filtragem IPv6",
	"Turn IPv6 Filtering ON and ALLOW rules listed": "LIGAR Filtragem IPv6 e PERMITIR as regras listadas",
	"Turn IPv6 Filtering ON and DENY rules listed": "LIGAR Filtragem IPv6 e RECUSAR as regras listadas",
	
	// Port Forwarding
	"Port Forwarding is used to open ports in your router and to redirect traffic to those ports to a specific device on your network. This may be needed for specific applications, games, or services. You can enter individual ports (80, 68, 888), port ranges (100-150), or in a mixed format (1020-5000, 689).": "O Encaminhamento de Portas é utilizado para abrir portas no seu router e para redirecionar o tráfego através dessas portas para um dispositivo específico na sua rede. Isto pode ser necessário para aplicações, jogos ou serviços específicos. Pode introduzir portas individuais (80, 68, 888), intervalos de portas (100-150), ou num formato misto (1020-5000, 689).",
	"Local IP": "IP Local",
	"TCP Port": "Porta TCP",
	"UDP Port": "Porta UDP",
	
	// Virtual Server
	"The Virtual Server option allows you to define a single public port on your router for redirection to an internal LAN IP Address and Private LAN port if required. This feature is useful for hosting online services such as FTP or Web Servers.": "A opção de Servidor Virtual permite que defina uma única porta pública do seu router para redirecionamento a um endereço LAN IP e a porta de LAN privada, se necessário. Esta opção é útil para alojar serviços on-line como Servidores FTP ou de Internet.",
	"Protocol": "Protocolo",
	"External Port": "Porta Externa",
	"Internal Port": "Porta Interna",
	"Protocol Number": "Protocol Number",
	
	// Website Filter
	"The Website Filter option allows you to set up a list of Web sites you would like to allow or deny through your network. To use this feature, you must also select the \"Apply Web Filter\" checkbox in the Access Control section.": "A opção Filtro de Sítios de Internet permite-lhe criar uma lista de sítios da Internet aos quais pretende permitir ou recusar o acesso à sua rede. Para utilizar esta funcionalidade, deve selecionar também a caixa de verificação \"Aplicar Filtro Web\" na secção Controlo de Acesso.",
	"DENY computers access to ONLY these sites": "RECUSA o acesso dos computadores APENAS a estes sítios da Internet",
	"ALLOW computers access to ONLY these sites": "PERMITE que os computadores acedam APENAS a estes sítios da Internet",
	"Website URL/Domain": "URL/Domínio do Sítio da Internet",
	
	// StaticRouter, StaticRouterIPv6
	"Static Routes": "Encaminhamento Estático",
	"This page allows you to define custom routes to define how data traffic is moved around your network.": "Esta página permite-lhe especificar caminhos personalizados que determinam como se movem os dados na sua rede.",
	"Destination IP": "IP de Destino",
	"Netmask": "Máscara de rede",
	"Gateway": "Gateway",
	"Matrix": "Matriz",
	"Interface": "Interface",
	"DestNetwork": "RedeDest",
	"PrefixLen": "LenPrefixo",
	
	// DynamicDNS
   	"Dynamic DNS (DDNS) allows you to use an easy to remember domain name such as www.[YourDomainName].com to reach your router\'s dynamically assigned IP address. This is useful when hosting a web, FTP, or game server, and allows you to reach your server no matter what your IP address has changed to. D-Link offers a free DDNS service that you can use through www.DLinkDDNS.com.": "O DNS Dinâmico (DDNS) permite-lhe utilizar um nome de domínio fácil de recordar tal como www.[OSeuNomedeDomínio].com para aceder ao endereço IP atribuído de forma dinâmica do seu router. Isto é útil quando é o anfitrião de um servidor da Internet, de FTP ou de jogos, e permite-lhe aceder ao seu servidor independentemente de qual for o seu endereço IP. A D-Link oferece um serviço DDNS gratuito que pode utilizar em www.DLinkDDNS.com.",
	"Server Address": "Endereço do Servidor",
	"Dynamic DNS": "DNS Dinâmico",
	"Enable Dynamic DNS": "Ativar DNS Dinâmico",
	"Select Server Name": "Selecionar Nome do Servidor",
	"Time Out": "Tempo Excedido",
	"IPv6 Address": "Endereço IPv6",
	"hours": "horas",
	
	// Time
	"Time & Schedule": "Hora e Programa",
	"Time": "Hora",
	"Time Confuguration": "Configuração de Hora",
	"Automatic Time Confuguration": "Configuração Automática de Hora",
	"Manual Time Confuguration": "Configuração Manual de Hora",
	"Date": "Data",
	"This page allows you to set the router\'s internal system clock. You can set the time manually, or automatically through a time server.": "Esta página permite-lhe configurar o relógio interno do sistema do router. Pode definir a hora de forma manual ou automática, através de um servidor de hora.",
	"System Time": "Hora do Sistema",
	"Time Zone": "Fuso Horário",
	"Enable Daylight Saving": "Ativar Hora de Verão",
	"Update Time Using an NTP Serevr": "Atualizar a Hora utilizando um Servidor NTP",
	"Year/ Month/ Day": "Ano/ Mês/ Dia",
	"Hour/ Minute": "Hora/ Minuto",
	"Day": "Dia",
	"Hour": "Horas",
	"Min": "Min",
	"Sec": "Seg",
	
	// Schedule
	"The Schedule configuration option is used to manage schedule rules for various firewall and parental control features.": "A opção Configuração de programas é utilizada para gerir as regras de programas para várias funções de controlo parental e de firewall.",
	"Monday": "Monday",
	"Tuesday": "Tuesday",
	"Wednesday": "Wednesday",
	"Thursday": "Thursday",
	"Friday": "Friday",
	"Saturday": "Saturday",
	"Sunday": "Sunday",
	"All Day": "All Day",
	"All Week": "All Week",
	"Always": "Always Enable",
	
	// System Log
	"System Log": "Registo do Sistema",
	"SysLog Settings": "Definições do Registo do Sistema",
	"This page allows you to enable logging of system events to a SysLog server, or to e-mail the log to you according to a schedule or when the log is full.": "Esta página permite-lhe ativar o registo de eventos do sistema num servidor de Registos do Sistema, ou o envio por correio eletrónico do registo segundo um programa ou quando o registo estiver cheio.",
	"SysLog Server IP Address": "Endereço IP do Servidor de Registo de Sistema",
	"Enable Logging to Syslog Server": "Ativar o registo no Servidor de Registos de Sistema",
	"E-mail Settings": "Configurações de E-mail",
	"E-mail Log When Full or On Schedule": "Envie registo por correio eletrónico quando Cheio ou quando Programado",
	"Enable E-mail Notification": "Ativar notificação por correio eletrónico",
	"From E-mail Address": "Do endereço de E-mail",
	"To E-mail Address": "Para o endereço de E-mail",
	"SMTP Server Address": "Endereço do Servidor SMTP",
	"SMTP Server Port": "Porta do Servidor SMTP",
	"Enable Authentication": "Ativar Autenticação",
	"Account Name": "Nome da Conta",
	"On Log Full": "Quando Registo estiver Cheio",
	"On Schedule": "Quando Programado",
	
	// System
	"System": "Sistema",
	"Save Configuration": "Guardar Configuração",
	"Restore Configuration From File": "Restabelecer a Configuração a partir de Ficheiro",
	"Restore Factory Default": "Restabelecer Predefinições de Fábrica",
	"Reboot": "Reiniciar",
	"This page lets you save your router\'s current settings to a file, restore your settings from a file, restore your router to factory default settings, or reboot the device. Please note that restoring the settings to the factory defaults will erase all settings, including any rules you have created.": "Esta página permite-lhe guardar as definições atuais do seu router num ficheiro, restabelecer as suas definições a partir de um ficheiro, restabelecer as predefinições de fábrica, ou reiniciar o dispositivo. Tenha em mente que restabelecer as definições para as predefinições de fábrica apagará todas as definições, incluindo quaisquer regras que tenha criado.",
	"Save Settings To Local Hard Drive": "Guardar as Definições no Disco Rígido Local",
	"Load Settings From Local Hard Drive": "Carregar as Definições a partir do Disco Rígido Local",
	"Restore To Factory Default Settings": "Repor as Definições de Fábrica",
	"Reboot The Device": "Reiniciar o Dispositivo",
	"Cancel": "Cancelar",
	"Are you sure you want to restore configuration file?": "Tem a certeza de que pretende restaurar o ficheiro de configuração?",
	"Do not close the page or power off the service until the restore configuration file is complete!": "Não feche a página ou desligue o serviço até que o restauro do ficheiro de configuração esteja concluído!",
	"Restore configuration file failed!": "O restauro do ficheiro de configuração falhou!",
	"Restore configuration file success!": "Restauro do ficheiro de configuração bem sucedido!",
	"Are you sure you want to reset the device?": "Tem a certeza de que pretende reiniciar o dispositivo?",
	"Rebooting": "Reiniciar",
	"Reboot success!": "Reiniciou com sucesso!",
	"Are you sure you want to reset the device to its factory default settings? This will cause current settings to be lost.": "Tem a certeza de que pretende restabelecer o dispositivo para os valores de fábrica? Isto fará com que perca as definições atuais.",
	"Restore to factory default success!": "Restabeleceu as predefinições de fábrica com sucesso!",
	"Select File": "Selecione Ficheiro",
	"Restore": "Restaurar",
	"Restore Factory Default": "Restabelecer Predefinições de Fábrica",
	
	// Admin
	"Admin": "Admin",
	"Admin Password": "Palavra-passe do Admin",
	"Administration": "Administração",
	"Use HTTPS": "Utilizar HTTPS",
	"The admin has read/write access and can change passwords, while the user has read-only access. By default there is no password configured. It is highly recommended that you create a password to keep your router secure.": "O administrador tem acesso a leitura/escrita e pode alterar as palavras-passe, enquanto que o utilizador tem apenas acesso a leitura. Por defeito, não há nenhuma palavra-passe configurada. É altamente recomendável que crie uma palavra-passe para manter o seu router seguro.",
	"Enable Graphical Authentication (CAPTCHA)": "Permitir Autenticação Gráfica (CAPTCHA)",
	"Enable HTTPS Server": "Ativar Servidor HTTPS",
	"Enable Remote Management": "Ativar Gestão Remota",
	"Remote Admin Port": "Porta Administração Remota",
	"Remote Admin Inbound Filter": "Filtro Interno do Administrador Remoto",
	
	// Update Firmware
	"Upgrade Firmware": "Atualizar o Firmware",
	"This page shows you your current firmware version and language pack, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below. If you are using a language pack, we recommend that you also get the latest version of the language pack when upgrading the firmware to ensure that any changes in the interface are shown correctly.": "Esta página mostra-lhe a versão de firmware e o pacote de idiomas atuais e permite-lhe procurar e descarregar novo firmware. Após descarregar o firmware, pode então atualizá-lo utilizando os botões abaixo. Se estiver a utilizar um pacote de idiomas, recomendamos que também obtenha a versão mais recente do pacote de idiomas quando atualizar o firmware para garantir que quaisquer alterações na interface são exibidas corretamente.",
	"Current Firmware Version": "Versão do Firmware Atual",
	"Current Firmware Date": "Data do Firmware Atual",
	"Current Language Pack": "Pacote de Idiomas Atual",
	"Download New Firmware": "Descarregar Novo Firmware",
	"Upgrade Firmware": "Atualizar o Firmware",
	"Add a Language Pack": "Adicionar um Pacote de Idiomas",
	"Upload": "Carregar",
	"Upgrade": "Atualizar",
	"Upgrading": "Upgrading",
	"Do you want to upgrade Firmware?": "Pretende atualizar o Firmware?",
	"Do not power off the device until the Firmware Upgrade is complete!": "Não feche a página ou desligue o serviço até que a Atualização de Firmware esteja concluída!",
	"Firmware Uploading": "A Carregar Firmware",
	"Firmware Upgrade failed!": "A Atualização de Firmware falhou!",
	"Firmware Upgrade success!": "Atualização do Firmware bem sucedida!",
	"Firmware Imformation": "Informações de Firmware",
	"New Firmware Version": "Nova Versão do Firmware",
	"New Firmware Date": "Data do Firmware Novo",
	"Check for New Firmware": "Verificar se existe Novo Firmware",
	"Language Pack Imformation": "Informações do Pacote de Idiomas",
	"Current Language Pack": "Pacote de Idiomas Atual",
	"Remove": "Remover",
	"Upgrade Manually": "Atualizar Manualmente",
	"Add a Language Pack": "Adicionar um Pacote de Idiomas",
	"Checking": "A verificar",
	"Retry": "Tentar novamente",
	"This firmware is the latest version.": "This firmware is the latest version.",
	"Downloading": "Downloading",
	"Please do not close the browser while the firmware is being downloaded!": "Please do not close the browser while the firmware is being downloaded!",
	
	// Statistic
	"Statistics": "Estatísticas",
	"This page gives you various statistics about data transmitted and received by your router through the Internet, on your wired network (LAN), and through your wireless networks.": "Esta página fornece-lhe várias estatísticas sobre os dados transmitidos e recebidos pelo seu router através da Internet, na sua rede com fios (LAN) e através das suas redes sem fios.",
	"Clear": "Limpar",
	"Information: Your browser is not support HTML5, please upgrade your browser.": "Informação: O seu explorador não suporta HTML5, atualize o seu explorador.",
	"Sent (Tx)": "Enviados (Tx)",
	"Received (Rx)": "Recebidos (Rx)",
	"Total Packets": "Total Packets",
	"Total Byte(s)": "Total Byte(s)",
	"Total Kbit(s)": "Total Kbit(s)",
	"Kbits/sec": "Kbits/sec",
	"Session": "Session"
}