{
	// Menu
	"Home": "Главная страница",
	"Settings": "Настройки",
	"Advanced": "Расширенные",
	"Management": "Управление",
	"Internet(WAN)": "Интернет",
	"Wireless(Wi-Fi)": "Беспроводная сеть",
	"Network(LAN)": "Сеть",
	"SharePort": "SharePort",
	"mydlink": "mydlink",
	"Firewall Setting": "Межсетевой экран",
	"Virtual Server": "Виртуальный сервер",
	"Port Forwarding": "Перенаправление портов",
	"Website Filter": "Фильтр Web-сайтов",
	"Static Route": "Статический маршрут",
	"Disabled": "Выключено",
	"Enabled": "Включено",
	
	// Genernal
	"There is unsaved data on this page. Do you want to abandon it?": "There is unsaved data on this page. Do you want to abandon it?",
	"Remaining": "Remaining",
	
	// Login
	"Model Name": "Название модели",
	"Hardware Version" : "Аппаратная версия",
	"Firmware Version" : "Версия ПО",
	"Language" : "Язык",
	"Admin Password": "Пароль администратора",
	"Log In" : "Войти",
	"To access your storage with SharePort Web Access," : "Чтобы получить доступ к хранилищу данных с помощью SharePort Web Access,",
	"click here." : "нажмите здесь.",
	"Invalid password, please try again.": "Некорректный пароль, пожалуйста, попробуйте еще раз.",
	"The Private Browsing feature of Safari is incompatible with this device's interface. You will need to disable Private Browsing to log in.": "Режим приватного просмотра в Safari несовместим с интерфейсом устройства. Необходимо выключить режим приватного просмотра, чтобы войти.",
	
	// Home
	"Current Status": "Текущий статус",
	"Click on any item in the diagram for more information.": "Нажмите на какой-либо элемент диаграммы для получения дополнительной информации.",
	"Setup Wizard": "Мастер настройки",
	"Router": "Маршрутизатор",
	"Internet": "Интернет",
	"LAN": "LAN",
	"Router IP Address": "IP-адрес маршрутизатора",
	"MAC Address": "MAC-адрес",
	"Wi-Fi 2.4GHz": "Wi-Fi 2.4 ГГц",
	"Wi-Fi 5GHz": "Wi-Fi 5 ГГц",
	"Guest Zone 2.4GHz": "Гостевая зона 2.4 ГГц",
	"Guest Zone 5GHz": "Гостевая зона 5 ГГц",
	"IP Address": "IP-адрес",
	"Subnet Mask": "Маска подсети",
	"Default Gateway": "Основной шлюз",
	"Available Space": "Доступный объем",
	"Total Space": "Общий объем",
	"Service Name": "Имя сервиса",
	"Ethernet Device": "Устройство Ethernet",
	"Wi-Fi Clients": "Wi-Fi клиенты",
	"USB Device": "USB-устройство",
	"USB Name": "Имя USB",
	"Status": "Статус",
	"Wi-Fi Name (SSID)": "Имя Wi-Fi (SSID)",
	"Password": "Пароль",
	"IPv6 Connection Type": "Тип соединения IPv6",
	"WAN IPv6 Address": "IPv6-адрес WAN",
	"Primary IPv6 DNS Server": "Предпочитаемый IPv6-адрес DNS",
	"Secondary IPv6 DNS Address": "Альтернативный IPv6-адрес DNS",
	"LAN IPv6 Link-Local Address": "IPv6-адрес Link-Local LAN",
	"DHCP-PD": "DHCP-PD",
	"IPv6 Network Assigned by DHCP-PD": "Сеть IPv6, назначенная DHCP-PD",
	"LAN IPv6 Address": "IPv6-адрес LAN",
	"Guest Zone": "Гостевая зона",
	"Connection Type": "Тип соединения  ",
	"Network Status": "Статус сети",
	"Connection Up Time": "Время соединения",
	"Primary DNS Server": "Предпочитаемый DNS-сервер",
	"Secondary DNS Server": "Альтернативный DNS-сервер",
	"SharePort": "SharePort",
	"Release": "Сбросить",
	"Renew": "Обновить",
	"Disconnect": "Отключить",
	"Connect": "Подключить",
	"Ignore": "Ignore",
	"Connected": "Connected",
	"Connecting": "Connecting",
	"Disconnected": "Disconnected",
	"DHCP": "Dynamic IP (DHCP)",
	"Static": "Static IP (Static)",
	"DHCPPPPoE": "Dynamic IP (PPPoE)",
	"StaticPPPoE": "Static IP (PPPoE)",
	"DynamicPPTP": "Dynamic IP (PPTP)",
	"StaticPPTP": "Static IP (PPTP)",
	"DynamicL2TP": "Dynamic IP (L2TP)",
	"StaticL2TP": "Static IP (L2TP)",
	"A new firmware is available! Do you want to download and upgrade the firmware?": "A new firmware is available! Do you want to download and upgrade the firmware?",
	"Your changes are being saved, and the device will need to reboot.": "Your changes are being saved, and the device will need to reboot.",
	"The Wi-Fi connection is not secure.": "The Wi-Fi connection is not secure.",
	"Secure your network.": "Secure your network.",
	
	// Wizard
	"Welcome": "Добро пожаловать",
	"This wizard will guide you through a step-by-step process to configure your new D-Link device.": "Этот мастер поможет произвести пошаговую настройку нового устройства D-Link.",
	"Step1: Install your device": "Шаг 1: Установите устройство",
	"Step2: Configure your Network and Wi-Fi settings": "Шаг 2: Настройте параметры сети и Wi-Fi",
	"Step3: Set your router password": "Шаг 3: Установите пароль маршрутизатора",
	"Step4: Set mydlink service": "Шаг 4: Установите сервис mydlink",
	"Your Device": "Ваше устройство",
	"Cable/xDSL Broadband Modem": "xDSL/кабельный модем",
	"DHCP Connection (Dynamic IP Address)": "DHCP-соединение (Динамический IP-адрес)",
	"Choose this if your Internet connection automatically provides you with an IP Address. Most Cable Modems use this type of connection.": "Выберите эту опцию, если при использовании Интернет-соединения IP-адрес присваивается автоматически. Большинство кабельных модемов используют данный тип соединения.",
	"Username/Password Connection (PPPoE)": "Имя пользователя/Пароль (PPPoE)",
	"Choose this option if your Internet connection reguires a username and passowrd to get online. Most DSL modems use this connection type of connection.": "Выберите эту опцию, если для установки Интернет-соединения требуются имя пользователя и пароль. Большинство DSL-модемов используют данный тип соединения.",
	"Static IP Address Connection": "Соединение типа Статический IP",
	"Choose this option if your Internet Setup Provider provided you with IP Address information that has to be manually configured.": "Выберите эту опцию, если провайдер предоставил информацию об IP-адресах, которые должны быть настроены вручную.",
	"Username": "Имя пользователя",
	"Gateway Address": "Адрес шлюза",
	"Primary DNS Address": "Предпочитаемый DNS-адрес",
	"Secondary DNS Address": "Альтернативный DNS-адрес",
	"2.4GHz Wi-Fi Network Name": "Имя сети Wi-Fi 2.4 ГГц",
	"5GHz Wi-Fi Network Name": "Имя сети Wi-Fi 5 ГГц",
	"The Wi-Fi Network Name is up to 32 characters. You will need to join your Wi-Fi network using this Network Name (SSID).": "В имени сети Wi-Fi должно использоваться не больше 32 символов. Это имя сети (SSID) потребуется для подключения к Вашей сети Wi-Fi.",
	"Wi-Fi Password": "Пароль Wi-Fi",
	"Copy to 5GHz": "Копировать в 5 ГГц",
	"2.4GHz Wi-Fi Password": "Пароль Wi-Fi 2.4 ГГц",
	"5GHz Wi-Fi Password": "Пароль Wi-Fi 5 ГГц",
	"The password must contain at least 8 characters. You will need to join your Wi-Fi network using this password.": "The password must contain at least 8 characters. You will need to join your Wi-Fi network using this password.",
	"Device Admin Password": "Пароль администратора устройства",
	"This device is mydlink-enabled, which allows you to remotely monitor and manage your network through the mydlink.com website, or through the mydlink mobile app.": "Это устройство поддерживает сервис mydlink, который обеспечивает возможность удаленного наблюдения и управления сетью через Web-сайт mydlink.com или с помощью мобильного приложения mydlink.",
	"You can register this device with your existing mydlink account. If you do not have one, you can create one now.": "Можно зарегистрировать это устройство с существующей учетной записью mydlink. Если учетная запись отсутствует, можно создать ее сейчас.",
	"Do you have an existing mydlink account": "У Вас есть учетная запись mydlink?",
	"Yes, I have a mydlink account": "Да, у меня есть учетная запись mydlink.",
	"No, I want to create a new mydlink account": "Нет, я хочу создать новую учетную запись mydlink.",
	"E-mail Address (Account Name)": "Адрес электронной почты (Имя учетной записи)",
	"First Name": "Имя",
	"Last Name": "Фамилия",
	"I accept the mydlink": "Я принимаю",
	"terms and conditions.": "условия соглашения mydlink.",
	"Connect to the Wi-Fi network from your mobile device or PC": "Подключиться к сети Wi-Fi с помощью мобильного устройства или компьютера",
	"1.Please go to Settings > Wi-fi, and choose": "1. Пожалуйста, перейдите в Настройки > Wi-Fi и выберите",
	"from the list of Wi-Fi network services.": "из списка один из сервисов сети Wi-Fi.",
	"2.Enter the password you just setup when prompted.": "2. Введите пароль, который был задан.",
	"Checking Internet connectivity": "Проверка подключения к Интернет",
	"Wi-Fi Client": "Wi-Fi клиент",
	"Save": "Сохранить",
	"Please wait": "Пожалуйста, подождите",
	"Configure Your Internet Connection": "Настройте Интернет-соединение",
	"Detecting Internet connection": "Определяется тип Интернет-соединения",
	"Install": "Установить",
	"Please plug one end of the Ethernet cable included with your device into the port labeled INTERNET on your device. Plug the other end of this cable into the Ethernet port on yourDSL or cable broadband modem, and power cycle the modem.": "Пожалуйста, подключите входящий в комплект поставки Ethernet-кабель к порту INTERNET на устройстве и к порту Ethernet на DSL/кабельном модеме.",
	"Please select your Internet connection type below": "Пожалуйста, выберите ниже тип Интернет-соединения",
	"PPPoE": "PPPoE",
	"To setup this Internet connection, you will need to have a User Name from your InternetService Provider. If you do not have this information, please contact your ISP.": "Чтобы установить данное Интернет-соединение, необходимо имя пользователя, полученное у провайдера. Если эта информация отсутствует, пожалуйста, обратитесь к провайдеру.",
	"Static IP": "Статический IP",
	"Dynamic IP (DHCP)": "Динамический IP (DHCP)",
	"To set up this conncetion you will need to have a complete list of IP information by your Internet Service Provider. If you have a Static IP connection and do not have this information, please contact your ISP.": "Для создания соединения типа Статический IP необходимо иметь полную информацию об IP-адресах провайдера. Свяжитесь с провайдером, если данная информация отсутствует.",
	"Wi-Fi Settings": "Настройки Wi-Fi",
	"To setup a Wi-Fi Network you will need to give your Wi-Fi Nerwork a Name(SSID) and Password.": "Чтобы установить сеть Wi-Fi, необходимо задать имя (SSID) и пароль сети Wi-Fi.",
	"By default, your new D-Link device does not have a password configured for administrator access to the Web-based configuration utility. To secure your new device, please create a password below.": "По умолчанию новое устройство D-Link не имеет пароля, заданного для доступа администратора к Web-утилите настройки. Чтобы защитить свое устройство, пожалуйста, задайте пароль ниже.",
	"Setup Complete": "Установка завершена",
	"Below is a summary of your Wi-Fi security and device password settings.Please take a note of your settings and save your configuration.": "Ниже указано подробное изложение настроек безопасности Wi-Fi и настроек пароля устройства. Пожалуйста, запишите эту информацию и сохраните настройки.",
	"Checking Your Internet connectivity": "Проверка Вашего подключения к Интернет",
	"Checking Internet connectivity": "Проверка подключения к Интернет",
	"mydlink Regristration": "Регистрация в mydlink",
	"Congratulations": "Поздравляем",
	"Congratulations,your device has been configured. You can now connect to your Wi-Fi network by using the new Wi-Fi Network Name and Password you created.": "Поздравляем, устройство настроено. Теперь можно подключиться к сети Wi-Fi, используя заданные имя и пароль сети Wi-Fi.",
	"Back": "Назад",
	"Next": "Далее",
	"Skip": "Пропустить",
	"Finish": "Завершить",
	"Registered": "Registered",
	"Unregistered": "Unregistered",
	
	// Ethernet, Wireless, Wireless_Guest
	"Wi-Fi Clients (Guest Zone)": "Wi-Fi клиенты (Гостевая зона)",
	"Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.",
	"Here, you can see a list of all devices connected through Wi-Fi. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Здесь можно увидеть список всех устройств, подключенных по Wi-Fi. Нажмите на устройство, чтобы просмотреть дополнительную информацию о нем, или нажмите на значок карандаша, чтобы задать устройству имя для его идентификации. Можно заблокировать доступ к сети устройству на постоянной основе или в соответствии с расписанием, используя раскрывающийся список блокирования.",
	"Vendor": "Производитель",
	"Reserve IP": "Зарезервировать IP-адрес",
	"Access": "Доступ",
	"Allowed": "Разрешен",
	"Blocked": "Заблокирован",
	
	// Internet > IPv4
	"Use this section to configure your Internet Connection type. There are several connection types to choose from Static IP, DHCP, PPPoE, PPTP, L2TP, and DS-Lite. If you are unsure of your connection method, please contact your Internet Service Provider. Note:  If using the PPPoE option, you will need to remove or disable any PPPoE client software on your computers.": "Используйте этот раздел для настройки типа Интернет-соединения. Можно выбрать один из следующих типов соединения: \"Статический IP\", DHCP, PPPoE, PPTP, L2TP и DS-Lite. Если тип соединения неизвестен, пожалуйста, обратитесь к провайдеру. Примечание:  Если используется тип соединения PPPoE, необходимо удалить или выключить на компьютерах любое клиентское программное обеспечение PPPoE.",
	"My Internet Connection is": "Мой тип Интернет-соединения",
	"Host Name": "Имя хоста",
	"Mac Address Clone": "Клонировать MAC-адрес",
	"PPTP IP Address": "IP-адрес PPTP",
	"PPTP Server IP Address": "IP-адрес сервера PPTP",
	"PPTP Subnet Mask": "Маска подсети PPTP",
	"PPTP Gateway IP Address": "IP-адрес шлюза PPTP",
	"L2TP IP Address": "IP-адрес L2TP",
	"L2TP Server IP Address": "IP-адрес сервера L2TP",
	"L2TP Subnet Mask": "Маска подсети L2TP",
	"L2TP Gateway IP Address": "IP-адрес шлюза L2TP",
	"MTU": "MTU",
	"Address Mode": "Режим адресации",
	"Reconnect Mode": "Режим повторного подключения",
	"Maximum Idle Time": "Максимальное время простоя",
	"DS-Lite Configuration": "Настройка DS-Lite",
	"DS-Lite DHCPv6 Option": "Опция DHCPv6 DS-Lite",
	"Manual Configuration": "Ручная настройка",
	"AFTR IPv6 Address": "IPv6-адрес AFTR",
	"B4 IPv4 Address": "IPv4-адрес B4",
	"WAN IPv6 Address": "IPv6-адрес WAN",
	"IPv6 WAN Default Gateway": "Основной шлюз IPv6 WAN",
	"Advanced Settings": "Расширенные настройки",
	"Manual": "Вручную",
	"Always on": "Всегда",
	"On demand": "По требованию",
	"Dynamic IP": "Dynamic IP",
	
	// Internet > IPv6
	"All of your IPv6 Internet and network connection details are displayed on this page.": "Вся подробная информация о Интернет-соединении IPv6 отображена на этой странице.",
	"Auto Detection": "Автоматическое определение",
	"Static IPv6": "Статический IPv6",
	"Auto Configuration (SLAAC/DHCPv6)": "Автоматическая настройка (SLAAC/DHCPv6)",
	"IPv6 in IPv4 Tunnel": "Туннель IPv6 в IPv4",
	"6to4": "6to4",
	"Local Connectivity Only": "Только возможность локального подключения",
	"Use Link-Local Address": "Использовать адрес Link-Local",
	"Subnet Prefix Length": "Длина префикса подсети",
	"PPPoE Session": "Сессия PPPoE",
	"Remote IPv4 Address": "Удаленный IPv4-адрес",
	"Remote IPv6 Address": "Удаленный IPv6-адрес",
	"Local IPv4 Address": "Локальный IPv4-адрес",
	"Local IPv6 Address": "Локальный IPv6-адрес",
	"6to4 Address": "Адрес 6to4",
	"6to4 Relay": "6to4 Relay",
	"Assign IPv6 Prefix": "Назначить префикс IPv6",
	"LAN IPv6 Link-Local Address": "IPv6-адрес Link-Local LAN",
	"IPv6 DNS SETTINGS": "НАСТРОЙКИ DNS IPv6",
	"LAN IPv6 ADDRESS SETTINGS": "НАСТРОЙКИ IPv6-АДРЕСА LAN",
	"LAN IPv6 Address": "IPv6-адрес LAN",
	"ADDRESS AUTOCONFIGURATION SETTINGS": "ПАРАМЕТРЫ АВТОНАСТРОЙКИ АДРЕСА",
	"Enable Automatic IPv6 Address Assignment": "Включить автоматическое назначение IPv6-адресов",
	"Enable Automatic DHCP-PD in LAN": "Включить автоматический DHCP-PD в LAN",
	"Autoconfiguration Type": "Тип автонастройки",
	"Enable DHCP-PD": "Включить DHCP-PD",
	"6RD MANUAL CONFIGURATION": "РУЧНАЯ НАСТРОЙКА 6rd",
	"Enable Hub and Spoke Mode": "Включить режим Hub and Spoke",
	"6rd Configuration": "Настройка 6rd",
	"6rd IPv6 Prefix": "Префикс IPv6 6rd",
	"6rd Border Relay IPv4 Address": "Border Relay IPv4-адрес 6rd",
	"IPv6 ULA SETTINGS": "Настройки IPv6 ULA",
	"Enable ULA": "Включить ULA",
	"Use Default ULA Prefix": "Использовать префикс ULA по умолчанию",
	"ULA Prefix": "Префикс ULA",
	"CURRENT IPv6 ULA SETTINGS": "ТЕКУЩИЕ НАСТРОЙКИ IPv6 ULA",
	"Current ULA Prefix": "Текущий префикс ULA",
	"LAN IPv6 ULA": "LAN IPv6 ULA",
	"minutes": "минуты",
	"DNS Type": "Тип DNS",
	"Obtain a DNS server address automatically": "Получить адрес DNS-сервера автоматически",
	"Use the following DNS address": "Использовать следующий DNS-адрес",
	"SLAAC+Stateless DHCP": "SLAAC + DHCP без сохранения состояния",
	"Stateful DHCPv6": "DHCPv6 с сохранением состояния",
	"6rd DHCPv4 Option": "Опция DHCPv4 6rd",
	"Share with IPv4": "Совместно использовать с IPv4",
	"Create a new session": "Создать новую сессию",
	"bytes": "bytes",
	"Router Advertisement Lifetime": "Router Advertisement Lifetime",
	"IPv6 Address Range (Start)": "IPv6 Address Range (Start)",
	"IPv6 Address Range (End)": "IPv6 Address Range (End)",
	"IPv6 Address Lifetime": "IPv6 Address Lifetime",
	
	// WiFi & Guest Zone
	"Security Mode": "Режим безопасности",
	"None": "Нет",
	"WPA-Personal": "WPA-Personal",
	"Auto": "Автоматический",
	"High": "Высокий",
	"Low": "Низкий",
	"802.11 Mode": "Режим 802.11",
	"Wi-Fi Channel": "Канал Wi-Fi",
	"Transmission Power": "Мощность передатчика",
	"Channel Width": "Ширина канала",
	"Visibility Status": "Статус видимости",
	"Visible": "Видимый",
	"Invisible": "Невидимый",
	"Mixed 802.11b/g": "Mixed 802.11b/g",
	"Mixed 802.11g/n": "Mixed 802.11g/n",
	"Mixed 802.11b/g/n": "Mixed 802.11b/g/n",
	"Auto 20/40 MHz": "Auto 20/40 МГц",
	"Mixed 802.11a and 802.11n": "Mixed 802.11a/n",
	"Use this section to configure the wireless settings for your D-Link Router. Please note that changes made on this section may also need to be duplicated on your Wireless Client.": "Используйте данный раздел, чтобы настроить параметры беспроводной сети для маршрутизатора D-Link. Пожалуйста, помните, что изменения, сделанные в данном разделе, также должны быть продублированы на беспроводном клиенте.",
	"This page lets you configure a Wi-Fi Guest Zone. Wi-Fi Guest Zones are Wi-Fi networks that are separate from your normal ones, and use different Wi-Fi Network Names and passwords. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless the Access Local Service option is enabled. Guest Zones are useful to give guests Internet access without allowing them to access your own devices on your network.": "На этой странице настраивается гостевая зона Wi-Fi. Гостевая зона Wi-Fi - это сеть Wi-Fi, которая отделена от обычной сети и использует другие имя и пароль сети Wi-Fi. Пользователи, подключенные к гостевой зоне, не могут обнаружить устройства в обычной сети и установить с ними связь кроме тех случаев, когда включена опция Доступ к локальному сервису. Гостевая зона полезна в том случае, когда гостям требуется предоставить доступ к Интернет, запретив им в то же время доступ к Вашим устройствам в сети.",
	"Internet Access Only": "Только доступ к Интернет",
	"Routing Between Zones": "Маршрутизация между зонами",
	"Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.": "Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.",
	"Your changes are being saved.": "Your changes are being saved.",
	
	// Network
	"Network": "Сеть",
	"Network Settings": "Настройки сети",
	"DHCP Server": "DHCP-сервер",
	"Use this page to configure the local network settings for your router, including the IP address you use to access this configuration interface. Please note that if you change this IP address, you will need to use the new IP to access this interface.": "Используйте эту страницу, чтобы настроить параметры локальной сети для маршрутизатора, включая IP-адрес, используемый для доступа к интерфейсу настройки. Пожалуйста, помните, что если изменить этот IP-адрес, необходимо использовать новый IP-адрес для доступа к этому интерфейсу.",
	"LAN IP Address": "IP-адрес LAN",
	"Device Name": "Имя устройства",
	"Local Domain Name": "Имя локального домена",
	"Enable DNS Relay": "Включить DNS Relay",
	"DHCP IP Address Range": "Диапазон IP-адресов DHCP",
	"DHCP Lease Time": "Время аренды DHCP",
	"Always Broadcast": "Постоянная широковещательная передача",
	"compatibility for some DHCP Clients": "(совместимость для некоторых DHCP-клиентов)",
	"If you changed the IP address of the router you will need to change the IP address in your browser before accessing the configuration website again.": "Если IP-адрес маршрутизатора был изменен, необходимо изменить IP-адрес в браузере перед тем, как снова получить доступ к Web-сайту настройки.",
	"The new settings have been saved.": "Новая конфигурация сохранена успешно.",
	"to": "to",
	
	// Advanced Network
	"Advanced Network": "Расширенные настройки сети",
	"Advanced Network settings allow you to configure some of the more advanced features of your router. It is recommended that you only change these settings if you are  familiar with them, or if you are specifically instructed to do so.": "Расширенные настройки сети позволяют настроить некоторые дополнительные функции маршрутизатора. Рекомендуется изменять эти настройки только в том случае, если они Вам знакомы, или Вы были проинформированы о том, как это сделать.",
	"UPnP": "UPnP",
	"WAN Port Speed": "Скорость на WAN-порте",
	"IPv4 Multicast Streams": "Многоадресные потоки IPv4",
	"IPv6 Multicast Streams": "Многоадресные потоки IPv6",
	"Auto (10/100/1000 Mbps)": "Автоматически (10/100/1000 Мбит/с)",
	
	// SharePort
	"SharePort": "SharePort",
	"DLNA (Digital Living Network Alliance) is the standard for the interoperability of Network Media Devices (NMDs). The user can enjoy multi-media applications (music, pictures and videos) on your network connected PC or media devices. Web File Access allows you to use a web browser to remotely access files stored on an SD card or USB storage drive plugged into the router.": "DLNA (Digital Living Network Alliance) - это стандарт, обеспечивающий совместную работу сетевых медиа-устройств (Network Media Devices (NMD)). Пользователь может работать с мультимедийными приложениями (музыка, изображения и видео) на подключенных к сети компьютерах или медиа-устройствах. Web-доступ к файлам позволяет использовать Web-браузер, чтобы получить удаленный доступ к файлам, хранящимся на SD-карте или USB-накопителе, подключенном к маршрутизатору.",
	"DLNA Media Server Configuration": "Настройка DLNA медиа-сервера",
	"DLNA Media Server": "DLNA медиа-сервер",
	"Web File Access": "Web-доступ к файлам",
	"Remote Access Port": "Порт удаленного доступа",
	"Remote HTTPS Port": "Порт удаленного HTTPS",
	"Enable Storage Remote Access": "Включить удаленный доступ HTTP к хранилищу данных",
	"Direct Links": "Прямые ссылки",
	"Local Access": "Локальный доступ",
	"SharePort Web Access": "Web-доступ SharePort",
	
	// SharePort CreateUser
	"\"Create User\" manage access to your storage devices or use the Guest account (guest/guest) to access the Guest Folder. After plugging in an SD card or USB storage drive, the new device will appear in the list with a link to it. You can then use this link to connect the drive and login with a user account.": "Создайте пользователя для управления доступом к устройствам хранения данных или используйте учетную запись гостя (guest/guest) для доступа к гостевой папке. После установки SD-карты или USB-накопителя новое устройство появится в списке со ссылкой на него. Затем можно использовать данную ссылку для подключения к накопителю и входа под учетной записью пользователя.",
	"Remote Access": "Удаленный доступ",
	"Create User": "Создать пользователя",
	"User Name": "Имя пользователя",
	"Access Path": "Путь доступа",
	"Permission": "Права доступа",
	"Edit": "Редактировать",
	"Delete": "Удалить",
	"Browse": "Обзор",
	"OK": "OK",
	"Create User": "Создать пользователя",
	"Create New User": "Создать нового пользователя",
	"Edit User Profile": "Редактировать профиль пользователя",
	"Folder": "Папка",
	"Select Folder": "Выбрать папку",
	"USB Device Name": "Имя USB-устройства",
	"Number of Device": "Номер устройства",
	
	// mydlink
	"Setting and registering your router with mydlink will allow you to use its mydlink cloud services features, including online access and management of your router through the mydlink portal website.": "Регистрация и настройка маршрутизатора в mydlink позволит воспользоваться функциями \"облачного\" сервиса mydlink, включая доступ и управление маршрутизатором в режиме онлайн через Web-сайт mydlink.",
	"mydlink Registration": "Регистрация в mydlink",
	"Sign Up": "Зарегистрироваться",
	"Sign In": "Войти",
	"Please enter your e-mail address and mydlink password.": "Пожалуйста, введите адрес электронной почты и пароль mydlink.",
	"You must accept the terms and conditions to continue.": "Необходимо принять условия соглашения, чтобы продолжить.",
	
	// QoS Engine
	"QoS Engine": "QoS Engine",
	"QoS prioritizes your network traffic so you can decide what devices should have priority over other devices. For example, you could set a computer that is downloading files to have lower priority than a laptop that is streaming movies to ensure that you can stream movies smoothly without downloads taking up all of your bandwidth.": "QoS приоритезирует сетевой трафик. Таким образом, можно определить, какие из устройств будут иметь приоритет. Например, можно задать компьютеру, скачивающему файлы, более низкий приоритет, чем ноутбуку, воспроизводящему потоковое видео, для того, чтобы скачиваемые файлы не занимали всю полосу пропускания, и потоковое видео воспроизводилось без задержек.",
	"All Devices": "Все устройства",
	"Drag the device cards above to the Prioity boxes below.": "Поместите карты устройств поверх нижерасположенных полей приоритетов.",
	"Highest": "Наивысший",
	"Medium": "Средний",
	
	// Firewall
	"Firewall Settings": "Настройки межсетевого экрана",
	"Here, you can set up various firewall features to protect your network from attacks. You can click on the DMZ, IPv4 Rules, and IPv6 Rules buttons to see the settings for that feature.": "Здесь можно настроить различные функции межсетевого экрана, чтобы защитить сеть от атак. Можно нажать на кнопки DMZ, Правила IPv4 и Правила IPv6, чтобы отобразить настройки для конкретной функции.",
	"Application Level Gateway (ALG) Configuration": "Настройка Application Level Gateway (ALG)",
	"Enable SPI IPv4": "Включить SPI IPv4",
	"Enable Anti-spoof Checking": "Включить анти-спуф проверку",
	"IPv6 Simple Security": "Простая защита IPv6",
	"PPTP": "PPTP",
	"IPSec (VPN)": "IPSec (VPN)",
	"RTSP": "RTSP",
	"SIP": "SIP",
	"IPv4 Rules": "Правила IPv4",
	"IPv6 Rules": "Правила IPv6",
	"Firewall": "Межсетевой экран",
	"Enable DMZ Host": "Включить DMZ-хост",
	"DMZ IP Address": "IP-адрес DMZ",
	"Security Check": "Проверка безопасности",
	
	// Firewall IPv4, IPv6
	"The IPv4 rule section is an advance feature used to deny or allow traffic from passing through the device.": "Раздел правил IPv4 является дополнительной функцией, используемой для того, чтобы запретить или разрешить прохождение трафика через устройство.",
	"The IPv6 rule section is an advance feature used to deny or allow traffic from passing through the device.": "Раздел правил IPv6 является дополнительной функцией, используемой для того, чтобы запретить или разрешить прохождение трафика через устройство.",
	"Add Rules": "Добавить правила",
	"Name": "Имя",
	"Schedule": "Расписание",
	"Create New Rule": "Создать новое правило",
	"Source IP Address Range": "Диапазон IP-адресов источника",
	"Destination IP Address Range": "Диапазон IP-адресов назначения",
	"Port Range": "Диапазон портов",
	"Turn IPv4 Filtering OFF": "ВЫКЛЮЧИТЬ фильтрацию IPv4",
	"Turn IPv4 Filtering ON and ALLOW rules listed": "ВКЛЮЧИТЬ фильтрацию IPv4 и РАЗРЕШИТЬ перечисленные правила",
	"Turn IPv4 Filtering ON and DENY rules listed": "ВКЛЮЧИТЬ фильтрацию IPv4 и ЗАПРЕТИТЬ перечисленные правила",
	"Turn IPv6 Filtering OFF": "ВЫКЛЮЧИТЬ фильтрацию IPv6",
	"Turn IPv6 Filtering ON and ALLOW rules listed": "ВКЛЮЧИТЬ фильтрацию IPv6 и РАЗРЕШИТЬ перечисленные правила",
	"Turn IPv6 Filtering ON and DENY rules listed": "ВКЛЮЧИТЬ фильтрацию IPv6 и ЗАПРЕТИТЬ перечисленные правила",
	
	// Port Forwarding
	"Port Forwarding is used to open ports in your router and to redirect traffic to those ports to a specific device on your network. This may be needed for specific applications, games, or services. You can enter individual ports (80, 68, 888), port ranges (100-150), or in a mixed format (1020-5000, 689).": "Перенаправление портов используется для того, чтобы открыть порты на маршрутизаторе и перенаправить трафик на эти порты и на определенное устройство в сети. Это может потребоваться для определенных приложений, игр или сервисов. Можно вводить отдельные порты (80, 68, 888), диапазон портов (100-150) или использовать смешанный формат (1020-5000, 689).",
	"Local IP": "Локальный IP-адрес",
	"TCP Port": "TCP-порт",
	"UDP Port": "UDP-порт",
	
	// Virtual Server
	"The Virtual Server option allows you to define a single public port on your router for redirection to an internal LAN IP Address and Private LAN port if required. This feature is useful for hosting online services such as FTP or Web Servers.": "Виртуальный сервер позволяет задать один публичный порт на маршрутизаторе для перенаправления на внутренний IP-адрес LAN и приватный LAN-порт, если требуется. Эта функция полезна для размещения онлайн-сервисов, таких как FTP или Web-серверы.",
	"Protocol": "Протокол",
	"External Port": "Внешний порт",
	"Internal Port": "Внутренний порт",
	"Protocol Number": "Protocol Number",
	
	// Website Filter
	"The Website Filter option allows you to set up a list of Web sites you would like to allow or deny through your network. To use this feature, you must also select the \"Apply Web Filter\" checkbox in the Access Control section.": "Фильтр Web-сайтов позволяет установить список Web-сайтов, посещение которых требуется разрешить или запретить. Чтобы использовать эту функцию, необходимо также отметить поле \"Применить Web-фильтр\" в разделе Контроль доступа.",
	"DENY computers access to ONLY these sites": "ЗАПРЕТИТЬ доступ компьютерам ТОЛЬКО к этим сайтам",
	"ALLOW computers access to ONLY these sites": "РАЗРЕШИТЬ доступ компьютерам ТОЛЬКО к этим сайтам",
	"Website URL/Domain": "URL-адрес Web-сайта/Домен",
	
	// StaticRouter, StaticRouterIPv6
	"Static Routes": "Статические маршруты",
	"This page allows you to define custom routes to define how data traffic is moved around your network.": "На этой странице можно задать пользовательские маршруты, определяющие, каким образом данные будут перемещаться по сети.",
	"Destination IP": "IP-адрес назначения",
	"Netmask": "Маска сети",
	"Gateway": "Шлюз",
	"Matrix": "Матрица",
	"Interface": "Интерфейс",
	"DestNetwork": "Сеть назначения",
	"PrefixLen": "Длина префикса",
	
	// DynamicDNS
   	"Dynamic DNS (DDNS) allows you to use an easy to remember domain name such as www.[YourDomainName].com to reach your router\'s dynamically assigned IP address. This is useful when hosting a web, FTP, or game server, and allows you to reach your server no matter what your IP address has changed to. D-Link offers a free DDNS service that you can use through www.DLinkDDNS.com.": "Dynamic DNS (DDNS) позволяет использовать легко запоминаемое доменное имя, например, www.[YourDomainName].com, чтобы попасть на IP-адрес, присваиваемый маршрутизатору динамически. Эта функция полезна при размещении Web, FTP или игрового сервера и позволяет достичь сервера независимо от того, какой IP-адрес он имеет в настоящий момент. D-Link предлагает бесплатный сервис DDNS, которым можно воспользоваться через www.DLinkDDNS.com.",
	"Server Address": "Адрес сервера",
	"Dynamic DNS": "Dynamic DNS",
	"Enable Dynamic DNS": "Включить Dynamic DNS",
	"Select Server Name": "Выбрать имя сервера",
	"Time Out": "Тайм-аут",
	"IPv6 Address": "IPv6-адрес",
	"hours": "часы",
	
	// Time
	"Time & Schedule": "Время и расписание",
	"Time": "Время",
	"Time Confuguration": "Настройка времени",
	"Automatic Time Confuguration": "Автоматическая настройка времени",
	"Manual Time Confuguration": "Ручная настройка времени",
	"Date": "Дата",
	"This page allows you to set the router\'s internal system clock. You can set the time manually, or automatically through a time server.": "На этой странице можно настроить системные часы маршрутизатора. Можно установить время вручную или автоматически через сервер времени.",
	"System Time": "Системное время",
	"Time Zone": "Часовой пояс",
	"Enable Daylight Saving": "Включить переход на летнее время",
	"Update Time Using an NTP Serevr": "Обновить время, используя NTP-сервер",
	"Year/ Month/ Day": "(Год/ Месяц/ День)",
	"Hour/ Minute": "(Час/ Минута)",
	"Day": "День",
	"Hour": "Час",
	"Min": "Мин.",
	"Sec": "Сек.",
	
	// Schedule
	"The Schedule configuration option is used to manage schedule rules for various firewall and parental control features.": "Настройка расписания используется, чтобы управлять правилами расписания для работы различных функций межсетевого экрана и родительского контроля.",
	"Monday": "Monday",
	"Tuesday": "Tuesday",
	"Wednesday": "Wednesday",
	"Thursday": "Thursday",
	"Friday": "Friday",
	"Saturday": "Saturday",
	"Sunday": "Sunday",
	"All Day": "All Day",
	"All Week": "All Week",
	"Always": "Always Enable",
	
	// System Log
	"System Log": "Системный журнал",
	"SysLog Settings": "Настройки системного журнала",
	"This page allows you to enable logging of system events to a SysLog server, or to e-mail the log to you according to a schedule or when the log is full.": "На этой странице можно включить ведение журнала событий системы на сервере системного журнала или отправить журнал по электронной почте в соответствии с расписанием или в случае, когда журнал заполнен.",
	"SysLog Server IP Address": "IP-адрес сервера системного журнала",
	"Enable Logging to Syslog Server": "Включить ведение журнала на сервере системного журнала",
	"E-mail Settings": "Настройки электронной почты",
	"E-mail Log When Full or On Schedule": "Отправить журнал по электронной почте, когда он заполнен, или по расписанию",
	"Enable E-mail Notification": "Включить уведомление по электронной почте",
	"From E-mail Address": "С адреса электронной почты",
	"To E-mail Address": "На адрес электронной почты",
	"SMTP Server Address": "На адрес SMTP-сервера",
	"SMTP Server Port": "Порт SMTP-сервера",
	"Enable Authentication": "Включить аутентификацию",
	"Account Name": "Имя учетной записи",
	"On Log Full": "Журнал заполнен",
	"On Schedule": "По расписанию",
	
	// System
	"System": "Система",
	"Save Configuration": "Сохранить конфигурацию",
	"Restore Configuration From File": "Восстановить конфигурацию из файла",
	"Restore Factory Default": "Восстановить заводские настройки",
	"Reboot": "Перезагрузить",
	"This page lets you save your router\'s current settings to a file, restore your settings from a file, restore your router to factory default settings, or reboot the device. Please note that restoring the settings to the factory defaults will erase all settings, including any rules you have created.": "На этой странице можно сохранить текущие настройки маршрутизатора в файл, восстановить настройки из файла, восстановить заводские настройки маршрутизатора или перезагрузить устройство. Пожалуйста, помните, что восстановление заводских настроек удалит все настройки, включая созданные правила.",
	"Save Settings To Local Hard Drive": "Сохранить настройки на локальный жесткий диск",
	"Load Settings From Local Hard Drive": "Загрузить настройки с локального жесткого диска",
	"Restore To Factory Default Settings": "Восстановить в заводские настройки",
	"Reboot The Device": "Перезагрузить устройство",
	"Cancel": "Отмена",
	"Are you sure you want to restore configuration file?": "Уверены, что хотите восстановить конфигурационный файл?",
	"Do not close the page or power off the service until the restore configuration file is complete!": "Не закрывайте страницу и не выключайте устройство до завершения процесса восстановления конфигурационного файла!",
	"Restore configuration file failed!": "Ошибка восстановления конфигурационного файла!",
	"Restore configuration file success!": "Конфигурационный файл успешно восстановлен!",
	"Are you sure you want to reset the device?": "Уверены, что хотите сбросить устройство к заводским настройкам?",
	"Rebooting": "Выполняется перезагрузка",
	"Reboot success!": "Перезагрузка выполнена успешно!",
	"Are you sure you want to reset the device to its factory default settings? This will cause current settings to be lost.": "Уверены, что хотите сбросить устройство к заводским настройкам? Текущие настройки будут утеряны.",
	"Restore to factory default success!": "Заводские настройки успешно восстановлены!",
	"Select File": "Выбрать файл",
	"Restore": "Восстановить",
	"Restore Factory Default": "Восстановить заводские настройки",
	
	// Admin
	"Admin": "Администратор",
	"Admin Password": "Пароль администратора",
	"Administration": "Администрирование",
	"Use HTTPS": "Использовать HTTPS",
	"The admin has read/write access and can change passwords, while the user has read-only access. By default there is no password configured. It is highly recommended that you create a password to keep your router secure.": "Администратор обладает правами чтения/записи и может изменять пароли, тогда как пользователь имеет только права чтения. По умолчанию заданный пароль отсутствует. Настоятельно рекомендуется создать пароль, чтобы обезопасить маршрутизатор.",
	"Enable Graphical Authentication (CAPTCHA)": "Включить графическую аутентификацию (CAPTCHA)",
	"Enable HTTPS Server": "Включить HTTPS-сервер",
	"Enable Remote Management": "Включить удаленное управление",
	"Remote Admin Port": "Порт удаленного администратора",
	"Remote Admin Inbound Filter": "Фильтр входящего трафика удаленного администратора",
	
	// Update Firmware
	"Upgrade Firmware": "Обновить программное обеспечение",
	"This page shows you your current firmware version and language pack, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below. If you are using a language pack, we recommend that you also get the latest version of the language pack when upgrading the firmware to ensure that any changes in the interface are shown correctly.": "На этой странице отображены версия текущего программного обеспечения и языковой пакет, а также здесь можно проверить наличие обновлений и загрузить новое ПО. После загрузки ПО можно выполнить его обновление, используя нижерасположенные кнопки. Если используется языковой пакет, рекомендуется также загрузить его последнюю версию, когда обновляется ПО, чтобы любые изменения в интерфейсе отображались корректно.",
	"Current Firmware Version": "Версия текущего программного обеспечения",
	"Current Firmware Date": "Дата текущего программного обеспечения",
	"Current Language Pack": "Текущий языковой пакет",
	"Download New Firmware": "Загрузить новое программное обеспечение",
	"Upgrade Firmware": "Обновить программное обеспечение",
	"Add a Language Pack": "Добавить языковой пакет",
	"Upload": "Выгрузить",
	"Upgrade": "Обновить",
	"Upgrading": "Upgrading",
	"Do you want to upgrade Firmware?": "Хотите обновить программное обеспечение?",
	"Do not power off the device until the Firmware Upgrade is complete!": "Не закрывайте страницу и не выключайте устройство до завершения процесса обновления программного обеспечения!",
	"Firmware Uploading": "Выполняется обновление программного обеспечения",
	"Firmware Upgrade failed!": "Ошибка обновления программного обеспечения!",
	"Firmware Upgrade success!": "Программное обеспечение успешно обновлено!",
	"Firmware Imformation": "Информация о программном обеспечении",
	"New Firmware Version": "Версия нового программного обеспечения",
	"New Firmware Date": "Дата нового программного обеспечения",
	"Check for New Firmware": "Проверить на наличие нового программного обеспечения",
	"Language Pack Imformation": "Информация о языковом пакете",
	"Current Language Pack": "Текущий языковой пакет",
	"Remove": "Удалить",
	"Upgrade Manually": "Обновить вручную",
	"Add a Language Pack": "Добавить языковой пакет",
	"Checking": "Выполняется проверка",
	"Retry": "Повторить",
	"This firmware is the latest version.": "This firmware is the latest version.",
	"Downloading": "Downloading",
	"Please do not close the browser while the firmware is being downloaded!": "Please do not close the browser while the firmware is being downloaded!",
	
	// Statistic
	"Statistics": "Статистика",
	"This page gives you various statistics about data transmitted and received by your router through the Internet, on your wired network (LAN), and through your wireless networks.": "На данной странице отображена разнообразная статистика об отправленных и полученных маршрутизатором данных через Интернет, по проводной сети (LAN) и по беспроводным сетям.",
	"Clear": "Очистить",
	"Information: Your browser is not support HTML5, please upgrade your browser.": "Информация: Web-браузер не поддерживает HTML5, пожалуйста, обновите браузер.",
	"Sent (Tx)": "Отправлено (Tx)",
	"Received (Rx)": "Получено (Rx)",
	"Total Packets": "Total Packets",
	"Total Byte(s)": "Total Byte(s)",
	"Total Kbit(s)": "Total Kbit(s)",
	"Kbits/sec": "Kbits/sec",
	"Session": "Session"
}