{
	// Menu
	"Home": "首页",
	"Settings": "设置",
	"Advanced": "高级",
	"Management": "管理",
	"Internet(WAN)": "网际网络",
	"Wireless(Wi-Fi)": "无线",
	"Network(LAN)": "网络",
	"SharePort": "SharePort",
	"mydlink": "mydlink",
	"Firewall Setting": "防火墙设置",
	"Virtual Server": "虚拟服务器",
	"Port Forwarding": "端口转发",
	"Website Filter": "站点过滤",
	"Static Route": "静态路由",
	"Disabled": "已禁用",
	"Enabled": "已启用",
	
	// Genernal
	"There is unsaved data on this page. Do you want to abandon it?": "There is unsaved data on this page. Do you want to abandon it?",
	"Remaining": "Remaining",
	
	// Login
	"Model Name": "型号名称",
	"Hardware Version": "硬件版本",
	"Firmware Version": "固件版本",
	"Language": "语言",
	"Admin Password": "管理员密码",
	"Log In": "登录",
	"To access your storage with SharePort Web Access,": "如要通过SharePort的Web访问方式访问您的存储设备，",
	"click here.": "请点击此处",
	"Invalid password, please try again.": "无效密码，请重试。",
	"The Private Browsing feature of Safari is incompatible with this device's interface. You will need to disable Private Browsing to log in.": "The Private Browsing feature of Safari is incompatible with this device's interface. You will need to disable Private Browsing to log in.",
	
	// Home
	"Current Status": "当前状态",
	"Click on any item in the diagram for more information.": "点击图标中的任意项，可获得更多信息。",
	"Setup Wizard": "设置向导",
	"Router": "路由器",
	"Internet": "Internet",
	"LAN": "LAN",
	"Router IP Address": "路由器IP地址",
	"MAC Address": "MAC地址",
	"Wi-Fi 2.4GHz": "Wi-Fi 2.4GHz",
	"Wi-Fi 5GHz": "Wi-Fi 5GHz",
	"Guest Zone 2.4GHz": "访客区2.4GHz",
	"Guest Zone 5GHz": "访客区5GHz",
	"IP Address": "IP地址",
	"Subnet Mask": "子网掩码",
	"Default Gateway": "默认网关",
	"Available Space": "可用空间",
	"Total Space": "总空间",
	"Service Name": "服务名",
	"Ethernet Device": "以太网设备",
	"Wi-Fi Clients": "Wi-Fi客户端",
	"USB Device": "USB设备",
	"USB Name": "USB名称",
	"Status": "状态",
	"Wi-Fi Name (SSID)": "Wi-Fi名称 (SSID)",
	"Password": "密码",
	"IPv6 Connection Type": "IPv6连接类型",
	"WAN IPv6 Address": "WAN IPv6地址",
	"Primary IPv6 DNS Server": "首选 IPv6 DNS服务器",
	"Secondary IPv6 DNS Address": "备用 IPv6 DNS地址",
	"LAN IPv6 Link-Local Address": "LAN IPv6链接本地地址",
	"DHCP-PD": "DHCP-PD",
	"IPv6 Network Assigned by DHCP-PD": "由DHCP-PD分配IPv6网络",
	"LAN IPv6 Address": "LAN IPv6地址",
	"Guest Zone": "访客区",
	"Connection Type": "连接类型",
	"Network Status": "网络状态",
	"Connection Up Time": "连接时间",
	"Primary DNS Server": "首选DNS服务器",
	"Secondary DNS Server": "备用DNS服务器",
	"SharePort": "SharePort",
	"Release": "释放",
	"Renew": "更新",
	"Disconnect": "断开",
	"Connect": "连接",
	"Ignore": "Ignore",
	"Connected": "Connected",
	"Connecting": "Connecting",
	"Disconnected": "Disconnected",
	"DHCP": "Dynamic IP (DHCP)",
	"Static": "Static IP (Static)",
	"DHCPPPPoE": "Dynamic IP (PPPoE)",
	"StaticPPPoE": "Static IP (PPPoE)",
	"DynamicPPTP": "Dynamic IP (PPTP)",
	"StaticPPTP": "Static IP (PPTP)",
	"DynamicL2TP": "Dynamic IP (L2TP)",
	"StaticL2TP": "Static IP (L2TP)",
	"A new firmware is available! Do you want to download and upgrade the firmware?": "A new firmware is available! Do you want to download and upgrade the firmware?",
	"Your changes are being saved, and the device will need to reboot.": "Your changes are being saved, and the device will need to reboot.",
	"The Wi-Fi connection is not secure.": "The Wi-Fi connection is not secure.",
	"Secure your network.": "Secure your network.",
	
	// Wizard
	"Welcome": "欢迎",
	"This wizard will guide you through a step-by-step process to configure your new D-Link device.": "该向导将指导您逐步地完成配置新的D-Link路由器。",
	"Step1: Install your device": "步骤1：安装您的设备",
	"Step2: Configure your Network and Wi-Fi settings": "步骤2：配置您的网络和Wi-Fi设置",
	"Step3: Set your router password": "步骤3：设置您的路由器的密码",
	"Step4: Set mydlink service": "步骤4：设置mydlink服务",
	"Your Device": "您的设备",
	"Cable/xDSL Broadband Modem": "线缆/xDSL宽带调制解调器",
	"DHCP Connection (Dynamic IP Address)": "DHCP连接 (动态IP地址)",
	"Choose this if your Internet connection automatically provides you with an IP Address. Most Cable Modems use this type of connection.": "如果Internet连接自动提供给您IP地址则选择此选项。大多数线缆调制解调器使用此类连接",
	"Username/Password Connection (PPPoE)": "用户名/密码连接 (PPPoE)",
	"Choose this option if your Internet connection reguires a username and passowrd to get online. Most DSL modems use this connection type of connection.": "如果Internet连接需要用输入用户名和密码，则选择此选项。多数DSL调制解调器使用此类连接。",
	"Static IP Address Connection": "静态IP地址连接",
	"Choose this option if your Internet Setup Provider provided you with IP Address information that has to be manually configured.": "如果Internet设置供应商提供给您需要手动配置的IP地址信息，则选择此选项。",
	"Username": "用户名",
	"Gateway Address": "网关地址",
	"Primary DNS Address": "首选DNS地址",
	"Secondary DNS Address": "备用DNS地址",
	"2.4GHz Wi-Fi Network Name": "2.4GHz Wi-Fi网络名",
	"5GHz Wi-Fi Network Name": "5GHz Wi-Fi网络名",
	"The Wi-Fi Network Name is up to 32 characters. You will need to join your Wi-Fi network using this Network Name (SSID).": "Wi-Fi网络名最多可使用32个字符。您需要使用该网络名 (SSID)加入您的Wi-Fi网络。",
	"Wi-Fi Password": "Wi-Fi密码",
	"Copy to 5GHz": "复制到5GHz",
	"2.4GHz Wi-Fi Password": "2.4GHz无线密码",
	"5GHz Wi-Fi Password": "5GHz无线密码",
	"The password must contain at least 8 characters. You will need to join your Wi-Fi network using this password.": "密码必须至少为8个字符。您需要使用该密码加入您的Wi-Fi网络。",
	"Device Admin Password": "设备管理员密码",
	"This device is mydlink-enabled, which allows you to remotely monitor and manage your network through the mydlink.com website, or through the mydlink mobile app.": "此设备支持mydlink功能，您可以通过mydlink.com网站或通过手机的mydlink app远程监控和管理您的网络。",
	"You can register this device with your existing mydlink account. If you do not have one, you can create one now.": "您可以将设备注册到现有的mydlink帐号下。如果您没有帐号，现在您可以新建一个。",
	"Do you have an existing mydlink account": "您有mydlink帐号吗？",
	"Yes, I have a mydlink account": "是的，我有mydlink帐户。",
	"No, I want to create a new mydlink account": "没有，我想注册一个新的mydlink帐户。",
	"E-mail Address (Account Name)": "E-mail地址 (帐户名)",
	"First Name": "名",
	"Last Name": "姓",
	"I accept the mydlink": "我接受mydlink",
	"terms and conditions.": "条款和条件。",
	"Connect to the Wi-Fi network from your mobile device or PC": "通过移动设备或个人计算机连接到Wi-Fi网络。",
	"1.Please go to Settings > Wi-fi, and choose": "1.请进入“设置> Wi-Fi”，并从",
	"from the list of Wi-Fi network services.": "Wi-Fi网络服务列表中进行选择。",
	"2.Enter the password you just setup when prompted.": "2.请输入刚才提示您设置的密码。",
	"Checking Internet connectivity": "检查Internet连接。",
	"Wi-Fi Client": "Wi-Fi客户端",
	"Save": "保存",
	"Please wait": "请等待",
	"Configure Your Internet Connection": "配置您的Internet连接",
	"Detecting Internet connection": "正在检测Internet连接",
	"Install": "安装",
	"Please plug one end of the Ethernet cable included with your device into the port labeled INTERNET on your device. Plug the other end of this cable into the Ethernet port on yourDSL or cable broadband modem, and power cycle the modem.": "请将路由器自带以太网线的一端插入到路由器背面标有INTERNET 的端口。将另一端插入DSL或有线宽带调制解调器的以太网端口。",
	"Please select your Internet connection type below": "请从下面选择Internet 连接类型",
	"PPPoE": "PPPoE",
	"To setup this Internet connection, you will need to have a User Name from your InternetService Provider. If you do not have this information, please contact your ISP.": "设置Internet类型，您需要从您的Internet服务提供商处获得用户名。您如果不知道这些信息，请联系ISP。",
	"Static IP": "静态IP",
	"Dynamic IP (DHCP)": "动态IP (DHCP)",
	"To set up this conncetion you will need to have a complete list of IP information by your Internet Service Provider. If you have a Static IP connection and do not have this information, please contact your ISP.": "您需要一张完整的相关IP信息表 (由Internet服务供应商提供)来建立此连接。如果您有一条静态IP连接，但是没有此信息，请联系您的ISP",
	"Wi-Fi Settings": "Wi-Fi设置",
	"To setup a Wi-Fi Network you will need to give your Wi-Fi Nerwork a Name(SSID) and Password.": "设置Wi-Fi网络，您需要提供Wi-Fi网络的名称 (SSID)和密码。",
	"By default, your new D-Link device does not have a password configured for administrator access to the Web-based configuration utility. To secure your new device, please create a password below.": "默认情况下，在新D-Link路由器上管理员无需密码即可访问到基于Web的配置工具。要确保新设备的安全，请在下面更改密码。",
	"Setup Complete": "设置完成",
	"Below is a summary of your Wi-Fi security and device password settings.Please take a note of your settings and save your configuration.": "下面概述了设备的Wi-Fi安全和密码设置。请记下您所做的设置并保存配置。",
	"Checking Your Internet connectivity": "检查您的Internet连接。",
	"Checking Internet connectivity": "检查Internet连接",
	"mydlink Regristration": "mydlink注册",
	"Congratulations": "恭喜！",
	"Congratulations,your device has been configured. You can now connect to your Wi-Fi network by using the new Wi-Fi Network Name and Password you created.": "恭喜！设备已配置完成。现在，您可以使用新建的Wi-Fi网络名称和密码连接到您的Wi-Fi网络了。",
	"Back": "返回",
	"Next": "下一步",
	"Skip": "跳过",
	"Finish": "完成",
	"Registered": "Registered",
	"Unregistered": "Unregistered",
	
	// Ethernet, Wireless, Wireless_Guest
	"Wi-Fi Clients (Guest Zone)": "Wi-Fi客户端 (访客区)",
	"Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.",
	"Here, you can see a list of all devices connected through Wi-Fi. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "此处，您可以看到通过Wi-Fi连接到网络的所有设备。单击设备，查看有关设备的更多信息；或者单击铅笔图标，为设备设置一个名称，以便识别。您可以点击“阻止”下拉框，始终或按时间表阻止某个设备访问您的网络。",
	"Vendor": "供应商",
	"Reserve IP": "保留IP",
	"Access": "访问",
	"Allowed": "允许",
	"Blocked": "阻止",
	
	// Internet > IPv4
	"Use this section to configure your Internet Connection type. There are several connection types to choose from Static IP, DHCP, PPPoE, PPTP, L2TP, and DS-Lite. If you are unsure of your connection method, please contact your Internet Service Provider. Note:  If using the PPPoE option, you will need to remove or disable any PPPoE client software on your computers.": "使用本节配置您 Internet连接类型。可供选择的连接类型包括以下几种:静态IP、DHCP、PPPoE、PPTP、L2TP和DS-Lite.如果您不能确定您的连接方式，请联系您的Internet服务供应商。请注意：如果使用PPPoE选项，您需要在您的计算机上移除或禁用任意PPPoE客户端软件。",
	"My Internet Connection is": "我的Internet连接是",
	"Host Name": "主机名",
	"Mac Address Clone": "复制MAC地址",
	"PPTP IP Address": "PPTP IP地址",
	"PPTP Server IP Address": "PPTP服务器IP地址",
	"PPTP Subnet Mask": "PPTP子网掩码",
	"PPTP Gateway IP Address": "PPTP网关IP地址",
	"L2TP IP Address": "L2TP IP地址",
	"L2TP Server IP Address": "L2TP服务器IP地址",
	"L2TP Subnet Mask": "L2TP子网掩码",
	"L2TP Gateway IP Address": "L2TP 网关IP地址",
	"MTU": "MTU",
	"Address Mode": "地址模式",
	"Reconnect Mode": "重新连接模式",
	"Maximum Idle Time": "最大闲置时间",
	"DS-Lite Configuration": "DS-Lite配置",
	"DS-Lite DHCPv6 Option": "DS-Lite DHCPv6 选项",
	"Manual Configuration": "手动配置",
	"AFTR IPv6 Address": "AFTR IPv6地址",
	"B4 IPv4 Address": "B4 IPv4地址",
	"WAN IPv6 Address": "WAN IPv6地址",
	"IPv6 WAN Default Gateway": "IPv6 WAN 默认网关",
	"Advanced Settings": "高级设置",
	"Manual": "手动",
	"Always on": "始终启用",
	"On demand": "按需",
	"Dynamic IP": "动态IP",
	
	// Internet > IPv6
	"All of your IPv6 Internet and network connection details are displayed on this page.": "此页显示所有的Internet和网络连接详细信息。",
	"Auto Detection": "自动探测",
	"Static IPv6": "静态IPv6",
	"Auto Configuration (SLAAC/DHCPv6)": "自动配置 (静态/DHCPv6)",
	"IPv6 in IPv4 Tunnel": "IPv6-in-IPv4隧道",
	"6to4": "6to4",
	"Local Connectivity Only": "仅本地连接",
	"Use Link-Local Address": "使用链接本地地址",
	"Subnet Prefix Length": "子网前缀长度：",
	"PPPoE Session": "PPPoE 会话",
	"Remote IPv4 Address": "远程IPv4地址",
	"Remote IPv6 Address": "远程IPv6地址",
	"Local IPv4 Address": "本地IPv4地址",
	"Local IPv6 Address": "本地IPv6地址",
	"6to4 Address": "6to4地址",
	"6to4 Relay": "6to4中继",
	"Assign IPv6 Prefix": "分配IPv6前缀",
	"LAN IPv6 Link-Local Address": "LAN IPv6链接本地地址",
	"IPv6 DNS SETTINGS": "IPv6 DNS设置",
	"LAN IPv6 ADDRESS SETTINGS": "LAN IPv6地址设置",
	"LAN IPv6 Address": "LAN IPv6地址",
	"ADDRESS AUTOCONFIGURATION SETTINGS": "地址自动配置设定",
	"Enable Automatic IPv6 Address Assignment": "启用自动IPv6地址分配",
	"Enable Automatic DHCP-PD in LAN": "启用LAN的自动DHCP-PD",
	"Autoconfiguration Type": "自动配置类型",
	"Enable DHCP-PD": "启用 DHCP-PD",
	"6RD MANUAL CONFIGURATION": "6RD手动配置",
	"Enable Hub and Spoke Mode": "启用Hub和Spoke模式",
	"6rd Configuration": "6rd 配置",
	"6rd IPv6 Prefix": "6rd IPv6前缀",
	"6rd Border Relay IPv4 Address": "6rd 边界中继 IPv4 地址",
	"IPv6 ULA SETTINGS": "IPv6 DLA设置",
	"Enable ULA": "启用ULA",
	"Use Default ULA Prefix": "使用默认ULA前缀",
	"ULA Prefix": "ULA前缀",
	"CURRENT IPv6 ULA SETTINGS": "当前IPv6 DLA设置",
	"Current ULA Prefix": "当前ULA前缀",
	"LAN IPv6 ULA": "LAN IPv6 ULA",
	"minutes": "分钟",
	"DNS Type": "DNS类型",
	"Obtain a DNS server address automatically": "自动获取DNS服务器地址",
	"Use the following DNS address": "使用下面的DNS服务器地址",
	"SLAAC+Stateless DHCP": "SLAAC+Staless DHCP",
	"Stateful DHCPv6": "全状态DHCPv6",
	"6rd DHCPv4 Option": "6rd DHCPv4 选项",
	"Share with IPv4": "同IPv4共享",
	"Create a new session": "创建新会话",
	"bytes": "bytes",
	"Router Advertisement Lifetime": "路由器存在时间",
	"IPv6 Address Range (Start)": "IPv6 Address Range (Start)",
	"IPv6 Address Range (End)": "IPv6 Address Range (End)",
	"IPv6 Address Lifetime": "IPv6 Address Lifetime",
	
	// WiFi & Guest Zone
	"Security Mode": "安全模式",
	"None": "无",
	"WPA-Personal": "WPA-Personal",
	"Auto": "自动",
	"High": "高",
	"Low": "低",
	"802.11 Mode": "802.11模式",
	"Wi-Fi Channel": "Wi-Fi信道",
	"Transmission Power": "传输功率",
	"Channel Width": "信道宽度",
	"Visibility Status": "可见状态",
	"Visible": "可见",
	"Invisible": "不可见",
	"Mixed 802.11b/g": "混合802.11b/g",
	"Mixed 802.11g/n": "混合802.11g/n",
	"Mixed 802.11b/g/n": "混合802.11b/g/n",
	"Auto 20/40 MHz": "自动20/100MHz",
	"Mixed 802.11a and 802.11n": "混合802.11a和802.11n",
	"Use this section to configure the wireless settings for your D-Link Router. Please note that changes made on this section may also need to be duplicated on your Wireless Client.": "使用本节配置您的D-Link路由器的无线设置。注意，在这部分所做的更改需要复制到您的无线客户端。",
	"This page lets you configure a Wi-Fi Guest Zone. Wi-Fi Guest Zones are Wi-Fi networks that are separate from your normal ones, and use different Wi-Fi Network Names and passwords. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless the Access Local Service option is enabled. Guest Zones are useful to give guests Internet access without allowing them to access your own devices on your network.": "在此页面，您可以配置Wi-Fi访客区。Wi-Fi访客区是独立于其它普通区域的Wi-Fi网络，它使用不同的Wi-Fi网络名称和密码。连接到访客区的用户无法进行通信或检测正常网络内的设备，除非启用“访问本地服务”项。访客可以使用访客区访问Internet，而不会访问网络内您自己的设备。",
	"Internet Access Only": "仅Internet访问",
	"Routing Between Zones": "区域间的路由",
	"Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.": "Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.",
	"Your changes are being saved.": "Your changes are being saved.",
	
	// Network
	"Network": "网络",
	"Network Settings": "网络设置",
	"DHCP Server": "DHCP服务器",
	"Use this page to configure the local network settings for your router, including the IP address you use to access this configuration interface. Please note that if you change this IP address, you will need to use the new IP to access this interface.": "根据本页面，为路由器配置本地网络设置，包括您用于访问本配置界面的IP地址。请注意：如果您更改了IP地址，您需要使用新的IP地址访问该界面。",
	"LAN IP Address": "LAN IP地址",
	"Device Name": "设备名",
	"Local Domain Name": "本地域名",
	"Enable DNS Relay": "启用DNS中继",
	"DHCP IP Address Range": "DHCP IP地址范围",
	"DHCP Lease Time": "DHCP租用时间",
	"Always Broadcast": "始终广播",
	"compatibility for some DHCP Clients": "兼容某些DHCP客户端",
	"If you changed the IP address of the router you will need to change the IP address in your browser before accessing the configuration website again.": "如果您更改了路由器的 IP地址，您再次访问配置站点之前，需要更改浏览器中的IP地址。",
	"The new settings have been saved.": "已保存新的设置。",
	"to": "to",
	
	// Advanced Network
	"Advanced Network": "高级网络",
	"Advanced Network settings allow you to configure some of the more advanced features of your router. It is recommended that you only change these settings if you are  familiar with them, or if you are specifically instructed to do so.": "通过高级网络设置，您可以为路由器配置更多高级功能中的部分功能。如果您不熟悉这些功能,或者没有经过相关的专门培训,建议不要更改这些设置。",
	"UPnP": "UPnP",
	"WAN Port Speed": "WAN端口速度",
	"IPv4 Multicast Streams": "IPv4组播流",
	"IPv6 Multicast Streams": "IPv6组播流",
	"Auto (10/100/1000 Mbps)": "Auto (10/100/1000 Mbps)",
	
	// SharePort
	"SharePort": "SharePort",
	"DLNA (Digital Living Network Alliance) is the standard for the interoperability of Network Media Devices (NMDs). The user can enjoy multi-media applications (music, pictures and videos) on your network connected PC or media devices. Web File Access allows you to use a web browser to remotely access files stored on an SD card or USB storage drive plugged into the router.": "DLNA (数字生活网络联盟)是一种有关网络多媒体设备 (NMD)互通性的标准。用户可以在网络中通过连接的PC或多媒体设备共享多媒体应用程序 (如音乐，图片和视频)。\"WEB文件访问\"允许用户使用WEB浏览器，远程访问插入路由器的SD卡或U盘中的文件。",
	"DLNA Media Server Configuration": "DLNA媒体服务器配置",
	"DLNA Media Server": "DLNA媒体服务器",
	"Web File Access": "启用文件访问",
	"Remote Access Port": "远程访问端口",
	"Remote HTTPS Port": "远程HTTPS端口",
	"Enable Storage Remote Access": "启用存储远程访问",
	"Direct Links": "直接链路",
	"Local Access": "本地访问",
	"SharePort Web Access": "SharePort Web访问",
	
	// SharePort CreateUser
	"\"Create User\" manage access to your storage devices or use the Guest account (guest/guest) to access the Guest Folder. After plugging in an SD card or USB storage drive, the new device will appear in the list with a link to it. You can then use this link to connect the drive and login with a user account.": "\"创建用户\"管理存储设备的访问，使用访客账户 (guest/guest)访问访客文件夹。插入SD卡或USB存储器后，带链接的新设备将出现在列表中。您可以使用此链接连接到驱动器，通过用户账户登录。",
	"Remote Access": "远程访问",
	"Create User": "创建用户",
	"User Name": "用户名",
	"Access Path": "访问路径",
	"Permission": "允许",
	"Edit": "编辑",
	"Delete": "删除",
	"Browse": "浏览",
	"OK": "确定",
	"Create User": "创建用户",
	"Create New User": "新建用户",
	"Edit User Profile": "编辑用户配置文件",
	"Folder": "文件夹",
	"Select Folder": "选择文件夹",
	"USB Device Name": "USB设备名",
	"Number of Device": "设备数量",
	
	// mydlink
	"Setting and registering your router with mydlink will allow you to use its mydlink cloud services features, including online access and management of your router through the mydlink portal website.": "通过mydlink设置和注册路由器后，您可以使用mydlink云服务功能，包括通过mydlink门户网站在线访问和管理路由器。",
	"mydlink Registration": "mydlink注册",
	"Sign Up": "注册",
	"Sign In": "登录",
	"Please enter your e-mail address and mydlink password.": "请输入您的邮件地址和mydlink密码。",
	"You must accept the terms and conditions to continue.": "您必须接受上述条款和条件才能继续。",
	
	// QoS Engine
	"QoS Engine": "QoS引擎",
	"QoS prioritizes your network traffic so you can decide what devices should have priority over other devices. For example, you could set a computer that is downloading files to have lower priority than a laptop that is streaming movies to ensure that you can stream movies smoothly without downloads taking up all of your bandwidth.": "通过QoS将排列出网络数据的优先级，以便您确定哪些设备具有高于其它设备的优先级。例如，您可以将正在下载文件的计算机的优先级设置成低于正播放在线电影的笔记本的优先级，确保您可以更流畅地观看影片，而不会让下载任务占用全部带宽。",
	"All Devices": "所有设备",
	"Drag the device cards above to the Prioity boxes below.": "将设备卡拖动至以下优先级框之上。",
	"Highest": "最高",
	"Medium": "中",
	
	// Firewall
	"Firewall Settings": "防火墙设置",
	"Here, you can set up various firewall features to protect your network from attacks. You can click on the DMZ, IPv4 Rules, and IPv6 Rules buttons to see the settings for that feature.": "此处，您可以设置各种防火墙功能，以保护您的网络免受攻击。您可以点击DMZ，IPv4规则和IPv6规则按钮，以查看该功能的设置。",
	"Application Level Gateway (ALG) Configuration": "应用等级网关(ALG)配置",
	"Enable SPI IPv4": "启用SPI IPv4",
	"Enable Anti-spoof Checking": "启用防欺骗检查",
	"IPv6 Simple Security": "IPv6简单安全功能",
	"PPTP": "PPTP",
	"IPSec (VPN)": "IPSec (VPN)",
	"RTSP": "RTSP",
	"SIP": "SIP",
	"IPv4 Rules": "IPv4规则",
	"IPv6 Rules": "IPv6规则",
	"Firewall": "防火墙",
	"Enable DMZ Host": "启用DMZ主机",
	"DMZ IP Address": "DMZ IP地址",
	"Security Check": "安全检查",
	
	// Firewall IPv4, IPv6
	"The IPv4 rule section is an advance feature used to deny or allow traffic from passing through the device.": "IPv4规则是一种高级功能，用于拒绝或允许流量通过设备。",
	"The IPv6 rule section is an advance feature used to deny or allow traffic from passing through the device.": "IPv6规则是一种高级功能，用于拒绝或允许流量通过设备。",
	"Add Rules": "添加规则",
	"Name": "名称",
	"Schedule": "调度",
	"Create New Rule": "新建规则",
	"Source IP Address Range": "源IP地址范围",
	"Destination IP Address Range": "目标IP地址范围",
	"Port Range": "端口范围",
	"Turn IPv4 Filtering OFF": "关闭IPv4过滤",
	"Turn IPv4 Filtering ON and ALLOW rules listed": "开启IPv4过滤，启用列表中的规则。",
	"Turn IPv4 Filtering ON and DENY rules listed": "开启Ipv4过滤，禁用列表中的规则。",
	"Turn IPv6 Filtering OFF": "关闭IPv6过滤",
	"Turn IPv6 Filtering ON and ALLOW rules listed": "开启IPv6过滤，启用列表中的规则。",
	"Turn IPv6 Filtering ON and DENY rules listed": "开启Ipv6过滤，禁用列表中的规则。",
	
	// Port Forwarding
	"Port Forwarding is used to open ports in your router and to redirect traffic to those ports to a specific device on your network. This may be needed for specific applications, games, or services. You can enter individual ports (80, 68, 888), port ranges (100-150), or in a mixed format (1020-5000, 689).": "端口转发功能用于开放路由器端口并将数据转发至网络内指定设备的端口上。这在某些特定应用、游戏或服务中可能会用到。您可以输入单个端口(80, 68, 888)，端口组(100-150)，或以混合(1020-5000,689)的方式输入。",
	"Local IP": "本地 IP",
	"TCP Port": "TCP端口",
	"UDP Port": "UDP端口",
	
	// Virtual Server
	"The Virtual Server option allows you to define a single public port on your router for redirection to an internal LAN IP Address and Private LAN port if required. This feature is useful for hosting online services such as FTP or Web Servers.": "通过虚拟服务器选项，您可以在路由器上定义单个端口用以重新定向一个内部LAN IP地址和专用LAN端口 (如要求的话)。此功能对于提供在线服务如FTP或Web服务器非常有用。",
	"Protocol": "协议",
	"External Port": "外部端口",
	"Internal Port": "内部端口",
	"Protocol Number": "Protocol Number",
	
	// Website Filter
	"The Website Filter option allows you to set up a list of Web sites you would like to allow or deny through your network. To use this feature, you must also select the \"Apply Web Filter\" checkbox in the Access Control section.": "通过站点过滤选项，可建立一个允许或拒绝通过您网络访问的站点列表。要启用此功能，您还必须在“访问控制”部分选择“应用Web过滤”复选框。",
	"DENY computers access to ONLY these sites": "仅拒绝计算机访问这些站点",
	"ALLOW computers access to ONLY these sites": "仅允许计算机访问这些站点",
	"Website URL/Domain": "站点URL/域",
	
	// StaticRouter, StaticRouterIPv6
	"Static Routes": "静态路由",
	"This page allows you to define custom routes to define how data traffic is moved around your network.": "在本页面，您可以自定义路由，以确定数据在您网络中的传输路径。",
	"Destination IP": "目的IP",
	"Netmask": "网络掩码",
	"Gateway": "应用层网关",
	"Matrix": "矩阵",
	"Interface": "接口",
	"DestNetwork": "目标网络",
	"PrefixLen": "前缀长度",
	
	// DynamicDNS
   	"Dynamic DNS (DDNS) allows you to use an easy to remember domain name such as www.[YourDomainName].com to reach your router\'s dynamically assigned IP address. This is useful when hosting a web, FTP, or game server, and allows you to reach your server no matter what your IP address has changed to. D-Link offers a free DDNS service that you can use through www.DLinkDDNS.com.": "通过动态DNS(DDNS)，您可以使用容易记住的域名，如www.[您的域名].com来访问动态分配的路由器IP地址。这对提供web，FTP或游戏服务器等在线服务非常有用，同时，不管您的IP地址是否更改，都可以访问到服务器。D-Link提供了免费的DDNS服务，您可以通过www.DLinkDDNS.com站点使用此服务。",
	"Server Address": "服务器地址",
	"Dynamic DNS": "动态DNS",
	"Enable Dynamic DNS": "启用动态DNS",
	"Select Server Name": "选择服务器名称",
	"Time Out": "超时",
	"IPv6 Address": "IPv6地址",
	"hours": "小时",
	
	// Time
	"Time & Schedule": "时间和计划",
	"Time": "时间",
	"Time Confuguration": "时间配置",
	"Automatic Time Confuguration": "自动时间配置",
	"Manual Time Confuguration": "自动时间配置",
	"Date": "日期",
	"This page allows you to set the router\'s internal system clock. You can set the time manually, or automatically through a time server.": "通过此页面，您可以设置路由器的内部系统时钟。您可以手动设置，也可以通过时间服务器自动设置。",
	"System Time": "系统时间",
	"Time Zone": "时区",
	"Enable Daylight Saving": "启用夏令时",
	"Update Time Using an NTP Serevr": "使用NTP服务器更新时间",
	"Year/ Month/ Day": "年/月/日",
	"Hour/ Minute": "时/分",
	"Day": "日",
	"Hour": "小时",
	"Min": "最小",
	"Sec": "秒",
	
	// Schedule
	"The Schedule configuration option is used to manage schedule rules for various firewall and parental control features.": "计划配置选项可用于管理各类防火墙和家长控制功能的计划规则。",
	"Monday": "Monday",
	"Tuesday": "Tuesday",
	"Wednesday": "Wednesday",
	"Thursday": "Thursday",
	"Friday": "Friday",
	"Saturday": "Saturday",
	"Sunday": "Sunday",
	"All Day": "All Day",
	"All Week": "All Week",
	"Always": "Always Enable",
	
	// System Log
	"System Log": "系统日志",
	"SysLog Settings": "SysLog设置",
	"This page allows you to enable logging of system events to a SysLog server, or to e-mail the log to you according to a schedule or when the log is full.": "在本页面，您可以为SysLog服务器启用“系统事件记录”功能，并按计划或在日志满时通过邮件将日志发送给您。",
	"SysLog Server IP Address": "SysLog服务器IP地址",
	"Enable Logging to Syslog Server": "启用登录SysLog服务器",
	"E-mail Settings": "电子邮件设置",
	"E-mail Log When Full or On Schedule": "日志满时或按照计划发送日志。",
	"Enable E-mail Notification": "启用电子邮件通知",
	"From E-mail Address": "发件人地址",
	"To E-mail Address": "收件人地址",
	"SMTP Server Address": "SMTP服务器地址",
	"SMTP Server Port": "SMTP服务器端口",
	"Enable Authentication": "启用认证",
	"Account Name": "账户名",
	"On Log Full": "日志已满",
	"On Schedule": "按计划",
	
	// System
	"System": "系统",
	"Save Configuration": "保存配置",
	"Restore Configuration From File": "从文件中恢复配置",
	"Restore Factory Default": "恢复出厂默认设置",
	"Reboot": "重启",
	"This page lets you save your router\'s current settings to a file, restore your settings from a file, restore your router to factory default settings, or reboot the device. Please note that restoring the settings to the factory defaults will erase all settings, including any rules you have created.": "在本页面，您可以保存路由器的当前设置至某个文件，从文件中恢复设置，将路由器恢复出厂默认设置，或者重启设备。请注意，恢复出厂默认设置将清除所有的设置，包括您创建的任何规则。",
	"Save Settings To Local Hard Drive": "保存设置到本地硬盘",
	"Load Settings From Local Hard Drive": "从本地硬盘加载设置",
	"Restore To Factory Default Settings": "恢复到出厂默认设置",
	"Reboot The Device": "重启设备",
	"Cancel": "取消",
	"Are you sure you want to restore configuration file?": "您确定要恢复配置文件吗？",
	"Do not close the page or power off the service until the restore configuration file is complete!": "在恢复配置文件完成之前，请勿关闭本页面或断开服务！",
	"Restore configuration file failed!": "恢复配置文件失败！",
	"Restore configuration file success!": "恢复配置文件成功！",
	"Are you sure you want to reset the device?": "您确定要重新启动设备吗？",
	"Rebooting": "重启中",
	"Reboot success!": "重启成功！",
	"Are you sure you want to reset the device to its factory default settings? This will cause current settings to be lost.": "您确定要将设备恢复到出厂设置吗？这将导致当前设置丢失。",
	"Restore to factory default success!": "恢复到出厂默认设置！",
	"Select File": "选择文件",
	"Restore": "恢复",
	"Restore Factory Default": "恢复出厂默认设置",
	
	// Admin
	"Admin": "管理员",
	"Admin Password": "管理员密码",
	"Administration": "管理",
	"Use HTTPS": "使用HTTPS",
	"The admin has read/write access and can change passwords, while the user has read-only access. By default there is no password configured. It is highly recommended that you create a password to keep your router secure.": "管理员有读/写访问和更改密码的权限，而用户仅具有只读访问权限。默认情况下此处没有配置密码。强烈推荐您创建密码以保证路由器的安全。",
	"Enable Graphical Authentication (CAPTCHA)": "启用图形验证 (CAPTCHA)",
	"Enable HTTPS Server": "启用HTTPS服务器",
	"Enable Remote Management": "启用远程管理",
	"Remote Admin Port": "远程管理端口",
	"Remote Admin Inbound Filter": "远程管理进站过滤",
	
	// Update Firmware
	"Upgrade Firmware": "升级固件",
	"This page shows you your current firmware version and language pack, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below. If you are using a language pack, we recommend that you also get the latest version of the language pack when upgrading the firmware to ensure that any changes in the interface are shown correctly.": "本页面将显示您当前的固件版本和语言包，您还可以查看是否有新版固件可供下载。下载完固件后，您可以点击以下按钮进行升级。如果您在使用语言包，我们建议您在升级固件的同时也下载最新版的语言包，以确保界面中的任何变化都能正确显示。",
	"Current Firmware Version": "当前固件版本",
	"Current Firmware Date": "当前固件日期",
	"Current Language Pack": "当前语言包",
	"Download New Firmware": "下载新版固件",
	"Upgrade Firmware": "升级固件",
	"Add a Language Pack": "添加语言包",
	"Upload": "上传",
	"Upgrade": "升级",
	"Upgrading": "升级中",
	"Do you want to upgrade Firmware?": "你要升级固件吗？",
	"Do not power off the device until the Firmware Upgrade is complete!": "在固件升级完成之前，请勿关闭本页面或断开服务！",
	"Firmware Uploading": "固件上传",
	"Firmware Upgrade failed!": "固件升级失败！",
	"Firmware Upgrade success!": "固件升级成功！",
	"Firmware Imformation": "固件信息",
	"New Firmware Version": "新固件版本",
	"New Firmware Date": "新版固件日期",
	"Check for New Firmware": "查看是否有新固件",
	"Language Pack Imformation": "语言包信息",
	"Current Language Pack": "当前语言包",
	"Remove": "移除",
	"Upgrade Manually": "手动升级",
	"Add a Language Pack": "添加语言包",
	"Checking": "检查中",
	"Retry": "重试",
	"This firmware is the latest version.": "This firmware is the latest version.",
	"Downloading": "下载中",
	"Please do not close the browser while the firmware is being downloaded!": "Please do not close the browser while the firmware is being downloaded!",
	
	// Statistic
	"Statistics": "统计数据",
	"This page gives you various statistics about data transmitted and received by your router through the Internet, on your wired network (LAN), and through your wireless networks.": "本页面显示了使用路由器经Internet、有线网络 (LAN)和无线网络收发的数据的相关统计信息。",
	"Clear": "清除",
	"Information: Your browser is not support HTML5, please upgrade your browser.": "信息：您的浏览器不支持HTML5，请升级浏览器。",
	"Sent (Tx)": "已发送 (Tx)",
	"Received (Rx)": "已接收 (Rx)",
	"Total Packets": "Total Packets",
	"Total Byte(s)": "Total Byte(s)",
	"Total Kbit(s)": "Total Kbit(s)",
	"Kbits/sec": "Kbits/sec",
	"Session": "Session",
	
	//DAP1320B
	//general
	"Extended Wi-Fi" : "扩展Wi-Fi",
	"SCAN": "搜寻",
	"Uplink Router": "上行路由器",
	"Wireless Mode": "无线模式",
	"Scanning":"正在扫描",
	"Connect to another uplink router":"连接至另一上行路由器",
	"Select":"選擇",
	"Repeater":"中繼站",
	"Password Length":"金鑰長度",
	"Authentication":"證明",
	"DNS Server":"DNS伺服器",
	"Network Settings": "網路設定",
	"Network Status":"网络状态",
	"Connection Up Time":"向上连接时间",
	"Subnet Prefix Length":"子網路前置碼(Subnet Prefix Length)",
	"The device is not connected to an uplink router, click &quot;Next&quot; to find available Wi-Fi networks.":"此裝置尚未與任何路由器建立連線。按&quot;下一步&quot;來搜尋可使用的Wi-Fi網路。",
	"A password is required to join":"连接需要密码",
	"Wi-Fi Network Name (SSID)":"Wi-Fi网络名称（SSID）",
	"Network Name(SSID)":"",
	
	
	//page
	"Use this section to configure the Wi-Fi Network you would like your DAP-1320b to connect to. Use Site Survey to scan available Wi-Fi networks and select the Wi-Fi Network you would like your DAP-1320b to connect to. Enter the Password of the Wi-Fi Network you selected and click Save.": "使用此部分来配置您要您的DAP-1320b连接至的Wi-Fi网络。使用“站点检测”来扫描可用的Wi-Fi网络并您要您的DAP-1320b连接至的Wi-Fi网络。输入您选择的Wi-Fi网络的密码并单击“保存”按钮。",
	"Use this section to configure the wireless settings for your D-Link Extender. Please note that changes made on this section may also need to be duplicated on your Wireless Client.":"請在此介面設定您D-Link無線基地台的無線參數。注意: 您於此所做的變更皆有可能需要設定於您的無線使用端。",
	"Use this section to configure the internal network settings of your Extender. Device Name allows you to configure this device more easily when your network using TCP/IP protocol. You can enter the device name of the Extender into your web browser to access the instead of IP address for configuration. Recommend to change the device name if there're more than one D-Link devices within the subnet. ":"使用這個功能表選單以組態設定您無線網路基地台 AP 的內部網路設定。 當您的網路使用 TCP/IP 通信協定時，裝置名稱 (NetBIOS 名稱) 可讓您更輕鬆地組態設定這台裝置。您可以輸入這台無線網路基地台的裝置名稱到您的網頁瀏覽器用以替代 IP 位址以進行組態設定。如果在這個子網域上有超過一台以上的 D-Link 裝置，建議您變更此裝置名稱。",
	"The admin password is used to log in to this configuration interface. It is highly recommended that you create a password to keep your router secure.":"管理員密碼使用於登入管理介面。建議您設定一個密碼來確保網路的安全。",
	"This page shows you your current firmware version, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below.":"此介面顯示了目前使用中的韌體版本和語言包並且讓您可於線上檢查新版韌體。下載韌體後，您將可以使用以下的按紐來更新。如果您有使用語言包，建議您也取得最新的語言包版本來確保所有參數和選項顯示正確。",



	"This page gives you various statistics about data transmitted and received by your AP through the internet, and through your wireless networks.":"此頁面提供您一些基地台已接收或已傳送的數據。",
	//Wizard
	//wizard title
	"WI-FI CONNECTION SETUP WIZARD":"無線網路連線設定精靈",
	"SELECT CONFIGURATION METHOD":"選擇無線網路的設定方式",
	"SELECT WI-FI NETWORK":"選擇無線網路",
	"ENTER WIFI PASSWORD":"輸入無線網路密碼",
	"PLEASE ENTER THE SETTINGS FOR THE EXTENDED NETWORK":"請輸入延伸網路的設定",
	"SETUP COMPLETE":"設定完成",
	"DEVICE NAME SETUP":"裝置名稱設定",
	
	
	"Wi-Fi Network Name":"無線網路名稱",
	"Extended Wi-Fi Network Name":"延伸網路名稱",
	"Extended Wi-Fi Password":"延伸的無線網路 密碼",
	"This wizard is designed to assist you in your Wi-Fi network setup. It will guide you through step-by step instructions on how to set up your Wi-Fi network and how to make it secure.":"設定精靈將幫助您完成無線網路相關設定。它將一步一步的引導您操作如何正確的設定無線網路和安全性設定。",
	"Select this option if your wireless device supports WPS(Wi-Fi Protected Setup)": "若您的無線裝置支援WPS(Wi-Fi Protected Setup)請選擇此項目",
	"Select this option if you want to setup your network manually":"如果您要手動設定網路的話，請選擇這個項目。",
	"Please enter Wi-Fi Password to establish wireless connection" : "請輸入無線網路密碼以建立無線連結",
	"Between 8 and 63 characters": "8~63個英文或數字",
	"Give Your Extended Wi-Fi Network(SSID) a Name":"為您的Wi-Fi中繼網路建立一個名稱",
	"Give Your Extended Wi-Fi Network a Password":"為您的Wi-Fi中繼網路建立一個密碼",
	"Using up to 32 characters":"最多32個英文或數字",
	"Use the same Wi-Fi Network Name for the Extended Network.":"延伸網路請用相同的無線網路名稱。",
	"Please Take a note of the following summary of your Wi-Fi Security setting for furture reference":"請記下以下無線安全設定，已供未來無線設備連結時參考。",
	//network setting ipv6
	"IPv4 Device Management Interface":"IPv4裝置管理介面",
	"Choose a IPv4 provisioning mechanism to be used by the device.":"請選擇基地台將使用的IPv4配置機制",
	"IPv6 Device Management Interface":"IPv6裝置管理介面",
	"Choose a IPv6 provisioning mechanism to be used by the device.":"請選擇基地台將使用的IPv6配置機制",
	"Obtain a DNS server address automatically or enter a specific DNS server address.":"自動取得一個DNS伺服器位址或輸入一個特定的DNS伺服器位址。",
	"Autoconfiguration (SLAAC/DHCPv6)":"自動設定 (SLAAC/DHCPv6)",
	"Obtain IPV6 Servers automatically.":"自動取得IPv6 DNS伺服器",
	"Use the following IPv6 DNS Servers.":"使用下列IPv6 DNS伺服器",
	"My IPv6 Connection is":"我的IPv6連線為",
	"My LAN Connection is":"我的區域網路連線是",
	"The LAN IPv6 Link-Local Address is the IPv6 Address that you use to access the Web-based management interface.":"LAN IPv6 Link-Local位址是您用來連線到網路管理界面時所使用的IPv6位址",
	"LAN IPv6 Link-Local Address":"區域網路IPv6 區域間連線位址",
	"Enter the IPv6 address information that you would like to use to access the Web-based management interface.":"輸入您想用來存取網頁管理介面的IPv6位址資訊。"
	
	
}