{
	// Menu
	"Home": "首頁",
	"Settings": "基本設定",
	"Advanced": "進階設定",
	"Management": "系統管理",
	"Internet(WAN)": "網際網路",
	"Wireless(Wi-Fi)": "無線網路",
	"Network(LAN)": "區域網路",
	"SharePort": "SharePort",
	"mydlink": "mydlink",
	"Firewall Setting": "防火牆設定",
	"Virtual Server": "虛擬伺服器",
	"Port Forwarding": "連接埠轉送",
	"Website Filter": "網站篩選器",
	"Static Route": "固定路由",
	"Disabled": "關閉",
	"Enabled": "啟用",
	
	// Genernal
	"There is unsaved data on this page. Do you want to abandon it?": "此頁面尚有未儲存的資料，您確定要放棄修改嗎？",
	"Remaining": "剩餘",
	
   	// Login
	"Model Name": "裝置名稱",
	"Hardware Version": "硬體版本",
	"Firmware Version": "韌體版本",
	"Language": "語言",
	"Admin Password": "管理員密碼",
	"Log In": "登入",
	"To access your storage with SharePort Web Access,": "使用 SharePort 連結到您的儲存裝置，",
	"click here.": "請點選此處",
	"Invalid password, please try again.": "錯誤的密碼，請重新輸入。",
	"The Private Browsing feature of Safari is incompatible with this device's interface. You will need to disable Private Browsing to log in.": "請將您的瀏覽器切換成非私密瀏覽模式再進行登入",
	
	// Home
	"Current Status": "網路組態",
	"Click on any item in the diagram for more information.": "點選網路拓樸中的任何一個物件，以了解更多詳細資訊。",
	"Setup Wizard": "設定精靈",
	"Router": "路由器裝置",
	"Internet": "網際網路",
	"LAN": "區域網路",
	"Router IP Address": "IP 位址",
	"MAC Address": "MAC 位址",
	"Wi-Fi 2.4GHz": "無線網路 (2.4GHz)",
	"Wi-Fi 5GHz": "無線網路 (5GHz)",
	"Guest Zone 2.4GHz": "訪客區無線網路 (2.4GHz)",
	"Guest Zone 5GHz": "訪客區無線網路 (5GHz)",
	"IP Address": "IP 位址",
	"Subnet Mask": "子網域遮罩",
	"Default Gateway": "預設閘道器",
	"Available Space": "可用空間",
	"Total Space": "總共空間",
	"Service Name": "服務名稱",
	"Ethernet Device": "有線裝置",
	"Wi-Fi Clients": "無線網路用戶端",
	"USB Device": "USB 裝置",
	"USB Name": "USB 名稱",
	"Status": "狀態",
	"Wi-Fi Name (SSID)": "無線網路名稱 (SSID)",
	"Password": "密碼",
	"IPv6 Connection Type": "IPv6 網路連線類型",
	"WAN IPv6 Address": "WAN IPv6 Address",
	"Primary IPv6 DNS Server": "IPv6 主要 DNS 伺服器",
	"Secondary IPv6 DNS Address": "IPv6 輔助 DNS 伺服器",
	"LAN IPv6 Link-Local Address": "LAN IPv6 Link-Local Address",
	"DHCP-PD": "DHCP-PD",
	"IPv6 Network Assigned by DHCP-PD": "IPv6 Network Assigned by DHCP-PD",
	"LAN IPv6 Address": "LAN IPv6 Address",
	"Guest Zone": "訪客區",
	"Connection Type": "網路連線類型",
	"Network Status": "網際網路狀態",
	"Connection Up Time": "連線時間",
	"Primary DNS Server": "主要 DNS 伺服器",
	"Secondary DNS Server": "輔助 DNS 伺服器",
	"SharePort": "SharePort",
	"Release": "釋放",
	"Renew": "更新",
	"Disconnect": "斷線",
	"Connect": "連線",
	"Ignore": "忽略",
	"Connected": "已連線",
	"Connecting": "連接中",
	"Disconnected": "已斷線",
	"DHCP": "動態 IP (DHCP)",
	"Static": "固定 IP (Static)",
	"DHCPPPPoE": "動態 IP (PPPoE)",
	"StaticPPPoE": "固定 IP (PPPoE)",
	"DynamicPPTP": "動態 IP (PPTP)",
	"StaticPPTP": "固定 IP (PPTP)",
	"DynamicL2TP": "動態 IP (L2TP)",
	"StaticL2TP": "固定 IP (L2TP)",
	"A new firmware is available! Do you want to download and upgrade the firmware?": "有新韌體可供下載！您想下載並更新韌體嗎？",
	"Your changes are being saved, and the device will need to reboot.": "設定已經儲存，裝置將重新啟動。",
	"The Wi-Fi connection is not secure.": "無線網路連線不安全",
	"Secure your network.": "為您的無線網路設置密碼",
	
	// Wizard
	"Welcome": "歡迎",
	"This wizard will guide you through a step-by-step process to configure your new D-Link device.": "這個精靈將引導您經過逐步的步驟以組態設定您的新 D-Link 路由器並連上網際網路。",
	"Step1: Install your device": "步驟1：安裝您的裝置",
	"Step2: Configure your Network and Wi-Fi settings": "步驟2：設定您的網路及無線網路",
	"Step3: Set your router password": "步驟3：設定密碼",
	"Step4: Set mydlink service": "步驟4：設定 mydlink 服務",
	"Your Device": "您的裝置",
	"Cable/xDSL Broadband Modem": "Cable/xDSL Broadband Modem",
	"DHCP Connection (Dynamic IP Address)": "DHCP 連線 (動態 IP 位址)",
	"Choose this if your Internet connection automatically provides you with an IP Address. Most Cable Modems use this type of connection.": "如果您的網際網路連線自動提供您 IP 位址，請選擇此選項。大多數 DSL 數據機使用這種連線方式。",
	"Username/Password Connection (PPPoE)": "使用者名稱 / 密碼 連線 (PPPoE)",
	"Choose this option if your Internet connection reguires a username and passowrd to get online. Most DSL modems use this connection type of connection.": "如果您的網際網路連線需要帳號及密碼以進行連線，請選擇此選項。大多數 DSL 數據機使用這種連線方式。",
	"Static IP Address Connection": "固定 IP 位址連線",
	"Choose this option if your Internet Setup Provider provided you with IP Address information that has to be manually configured.": "如果您的「網際網路設定供應商」提供您需要手動加以組態設定的 IP 位址資訊，請選擇此選項。",
	"Username": "使用者名稱",
	"Gateway Address": "閘道器 IP 位址",
	"Primary DNS Address": "主要 DNS 伺服器",
	"Secondary DNS Address": "輔助 DNS 伺服器",
	"2.4GHz Wi-Fi Network Name": "無線網路名稱 (2.4GHz)",
	"5GHz Wi-Fi Network Name": "無線網路名稱 (5GHz)",
	"The Wi-Fi Network Name is up to 32 characters. You will need to join your Wi-Fi network using this Network Name (SSID).": "無線網路名稱長度最多可達 32 個字元。",
	"Wi-Fi Password": "無線網路密碼",
	"Copy to 5GHz": "複製密碼至 5GHz",
	"2.4GHz Wi-Fi Password": "無線網路密碼 (2.4GHz)",
	"5GHz Wi-Fi Password": "無線網路密碼 (5GHz)",
	"The password must contain at least 8 characters. You will need to join your Wi-Fi network using this password.": "無線網路密碼長度需介於 8 到 63 個字元之間。",
	"Device Admin Password": "管理員密碼",
	"This device is mydlink-enabled, which allows you to remotely monitor and manage your network through the mydlink.com website, or through the mydlink mobile app.": "此路由器為支援mydlink服務的設備，mydlink為D-Link免費提供的雲端服務，透過此路由器的設定網頁註冊後，您可至mydlink網站，或透過行動裝置使用mydlink Lite App來管理和查看您的路由器。",
	"You can register this device with your existing mydlink account. If you do not have one, you can create one now.": "您可以使用已註冊的 mydlink 帳戶，若尚未註冊則可在此建立一個新帳戶。",
	"Do you have an existing mydlink account": "是否已建立 mydlink 帳號",
	"Yes, I have a mydlink account": "是的，我有 mydlink 帳號",
	"No, I want to create a new mydlink account": "沒有，我要建立新的 mydlink 帳號",
	"E-mail Address (Account Name)": "E-mail (帳號名稱)",
	"First Name": "名字",
	"Last Name": "姓",
	"I accept the mydlink": "我同意 mydlink",
	"terms and conditions.": "相關條款與規章",
	"Connect to the Wi-Fi network from your mobile device or PC": "透過您的行動裝置或電腦連線至無線網路",
	"1.Please go to Settings > Wi-fi, and choose": "1. 請於無線網路列表中，選擇",
	"from the list of Wi-Fi network services.": "來進行連線",
	"2.Enter the password you just setup when prompted.": "2. 輸入您所設定的無線網路密碼",
	"Checking Internet connectivity": "確認網路連接狀況",
	"Wi-Fi Client": "無線網路用戶端",
	"Save": "儲存",
	"Please wait": "請稍後",
	"Configure Your Internet Connection": "設定您的網際網路連線",
	"Detecting Internet connection": "檢查網路連線中",
	"Install": "安裝",
	"Please plug one end of the Ethernet cable included with your device into the port labeled INTERNET on your device. Plug the other end of this cable into the Ethernet port on yourDSL or cable broadband modem, and power cycle the modem.": "請將網路線的一端連線到路由器的 Internet 埠，另一端連接到數據機或設在牆壁的網路埠。",
	"Please select your Internet connection type below": "請從下列清單中選擇您的網際網路類型：",
	"PPPoE": "設定帳號密碼與連線 (PPPoE)",
	"To setup this Internet connection, you will need to have a User Name from your InternetService Provider. If you do not have this information, please contact your ISP.": "要設定連線，您將需要由您網際網路服務供應商所提供的帳號與密碼。如果您沒有此項資訊，請洽您的ISP。",
	"Static IP": "固定 IP",
	"Dynamic IP (DHCP)": "動態 IP (DHCP)",
	"To set up this conncetion you will need to have a complete list of IP information by your Internet Service Provider. If you have a Static IP connection and do not have this information, please contact your ISP.": "要設定這個連線，您將需要您的網際網路服務供應商所提供的完整 IP 資訊清單。如果您有固定 IP 連線而沒有這項資訊，請洽您的ISP。",
	"Wi-Fi Settings": "設定無線網路",
	"To setup a Wi-Fi Network you will need to give your Wi-Fi Nerwork a Name(SSID) and Password.": "賦予您的無線網路名稱以及密碼",
	"By default, your new D-Link device does not have a password configured for administrator access to the Web-based configuration utility. To secure your new device, please create a password below.": "在新的路由器中，管理員密碼預設為空白。 強烈建議您建立密碼以保持您路由器的安全。",
	"Setup Complete": "設定完成",
	"Below is a summary of your Wi-Fi security and device password settings.Please take a note of your settings and save your configuration.": "以下為您無線網路安全設定的詳細摘要。請印出這一頁或將此資訊寫在紙張上，以讓您可以在您的無線網路用戶端配接器上設定正確的參數值。",
	"Checking Your Internet connectivity": "檢查您的網際網路連接狀態",
	"Checking Internet connectivity": "檢查網際網路連接中",
	"mydlink Regristration": "註冊 mydlink",
	"Congratulations": "恭喜",
	"Congratulations,your device has been configured. You can now connect to your Wi-Fi network by using the new Wi-Fi Network Name and Password you created.": "恭喜！您的路由器已經設定完成。 您現在可以透過您所設定的無線網路進行連線。",
	"Back": "上一步",
	"Next": "下一步",
	"Skip": "略過",
	"Finish": "完成",
	"Registered": "已註冊",
	"Unregistered": "尚未註冊",
	
	// Ethernet, Wireless, Wireless_Guest
	"Wi-Fi Clients (Guest Zone)": "無線網路用戶端 (訪客區)",
	"Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.",
	"Here, you can see a list of all devices connected through Wi-Fi. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "在此顯示連線到無線網路的所有裝置，您可以點選裝置來瀏覽詳細資訊，或點選鉛筆圖示來設定裝置名稱以方便辨認。",
	"Vendor": "製造商",
	"Reserve IP": "IP 位址保留",
	"Access": "存取",
	"Allowed": "允許",
	"Blocked": "禁止",
	
	// Internet > IPv4
	"Use this section to configure your Internet Connection type. There are several connection types to choose from Static IP, DHCP, PPPoE, PPTP, L2TP, and DS-Lite. If you are unsure of your connection method, please contact your Internet Service Provider. Note:  If using the PPPoE option, you will need to remove or disable any PPPoE client software on your computers.": "使用這個功能表選單以組態設定您網際網路的連線方式。 有幾種連線方式可供選擇：固定IP、DHCP、PPPoE、PPTP及L2TP。 如果您不確定您的連線方式，請洽詢您的網際網路服務供應商。",
	"My Internet Connection is": "我的網際網路連線是",
	"Host Name": "主機名稱",
	"Mac Address Clone": "複製 Mac 位址",
	"PPTP IP Address": "PPTP IP 位址",
	"PPTP Server IP Address": "PPTP 伺服器 IP 位址",
	"PPTP Subnet Mask": "PPTP 子網域遮罩",
	"PPTP Gateway IP Address": "PPTP 閘道 IP 位址",
	"L2TP IP Address": "L2TP IP 位址",
	"L2TP Server IP Address": "L2TP 伺服器 IP 位址",
	"L2TP Subnet Mask": "L2TP 子網域遮罩",
	"L2TP Gateway IP Address": "L2TP 閘道 IP 位址",
	"MTU": "最大傳輸單元",
	"Address Mode": "位址模式",
	"Reconnect Mode": "重新連線模式",
	"Maximum Idle Time": "最大閒置時間",
	"DS-Lite Configuration": "DS-Lite 設定",
	"DS-Lite DHCPv6 Option": "DS-Lite DHCPv6 選項",
	"Manual Configuration": "手動設定",
	"AFTR IPv6 Address": "AFTR IPv6 位址",
	"B4 IPv4 Address": "B4 IPv4 位址",
	"WAN IPv6 Address": "廣域網路 (WAN) IPv6 位址",
	"IPv6 WAN Default Gateway": "IPv6 WAN 預設閘道",
	"Advanced Settings": "進階設定",
	"Manual": "手動",
	"Always on": "一直打開",
	"On demand": "依需求",
	"Dynamic IP": "動態 IP",
	
	// Internet > IPv6
	"All of your IPv6 Internet and network connection details are displayed on this page.": "此功能表選單以組態設定您的 IPv6 連線形式。 如果您不確定您的連線方式，請洽詢您的網際網路服務供應商。",
	"Auto Detection": "自動偵測",
	"Static IPv6": "靜態的 IPv6",
	"Auto Configuration (SLAAC/DHCPv6)": "自動設定 (SLAAC/DHCPv6)",
	"IPv6 in IPv4 Tunnel": "IPv6 在 IPv4 隧道裡",
	"6to4": "IPv6 到 IPv4",
	"Local Connectivity Only": "僅用區域間連線",
	"Use Link-Local Address": "使用連結本機位址",
	"Subnet Prefix Length": "子網域前置碼長度",
	"PPPoE Session": "PPPoE 工作階段",
	"Remote IPv4 Address": "遠端 IPv4 位址",
	"Remote IPv6 Address": "遠端 IPv6 位址",
	"Local IPv4 Address": "區域 IPv4 位址",
	"Local IPv6 Address": "區域 IPv6 位址",
	"6to4 Address": "IPv6 到 IPv4 位址轉換",
	"6to4 Relay": "6to4 轉送",
	"Assign IPv6 Prefix": "IPv6 字首派發",
	"LAN IPv6 Link-Local Address": "區域網路 IPv6 連結 - 本機位址",
	"IPv6 DNS SETTINGS": "IPv6 DNS 設定",
	"LAN IPv6 ADDRESS SETTINGS": "區域網路 (LAN) IPv6 位址設定",
	"LAN IPv6 Address": "區域網路 (LAN) IPv6 位址",
	"ADDRESS AUTOCONFIGURATION SETTINGS": "位址自動設置",
	"Enable Automatic IPv6 Address Assignment": "啟用 IPv6 位址自動指派",
	"Enable Automatic DHCP-PD in LAN": "啟用 LAN 上的自動 DHCP-PD",
	"Autoconfiguration Type": "自動設定組態方式",
	"Enable DHCP-PD": "啟用 DHCP-PD",
	"6RD MANUAL CONFIGURATION": "6rd 手動設置",
	"Enable Hub and Spoke Mode": "啟用 Hub 和 Spoke 模式",
	"6rd Configuration": "6rd 設置",
	"6rd IPv6 Prefix": "6rd IPv6 字首",
	"6rd Border Relay IPv4 Address": "6rd Border Relay IPv4 位址",
	"IPv6 ULA SETTINGS": "IPv6 ULA 設定",
	"Enable ULA": "啟用 ULA",
	"Use Default ULA Prefix": "使用預設的 ULA 字首",
	"ULA Prefix": "ULA 字首",
	"CURRENT IPv6 ULA SETTINGS": "目前的 ULA 設定",
	"Current ULA Prefix": "目前的 ULA 字首",
	"LAN IPv6 ULA": "LAN IPv6 ULA",
	"minutes": "分鐘",
	"DNS Type": "DNS 類型",
	"Obtain a DNS server address automatically": "自動取得 IPv6 DNS 伺服器",
	"Use the following DNS address": "使用下列 IPv6 DNS 伺服器",
	"SLAAC+Stateless DHCP": "SLAAC+無狀態 DHCP",
	"Stateful DHCPv6": "全狀態 DHCPv6",
	"6rd DHCPv4 Option": "6rd DHCPv4 選項",
	"Share with IPv4": "與 IPv4 共享",
	"Create a new session": "建立新的工作程序",
	"bytes": "位元組",
	"Router Advertisement Lifetime": "路由器廣告壽命",
	"IPv6 Address Range (Start)": "IPv6 位址範圍 (起始)",
	"IPv6 Address Range (End)": "IPv6 位址範圍 (結尾)",
	"IPv6 Address Lifetime": "IPv6 位址存活時間",
	
	// WiFi & Guest Zone
	"Security Mode": "安全性加密方式",
	"None": "無加密",
	"WPA-Personal": "WPA-個人",
	"Auto": "自動",
	"High": "高",
	"Low": "低",
	"802.11 Mode": "802.11 模式",
	"Wi-Fi Channel": "頻道",
	"Transmission Power": "傳輸強度",
	"Channel Width": "頻道寬度",
	"Visibility Status": "可見狀態",
	"Visible": "顯示",
	"Invisible": "隱藏",
	"Mixed 802.11b/g": "混合 802.11b/g",
	"Mixed 802.11g/n": "混合 802.11g/n",
	"Mixed 802.11b/g/n": "混合 802.11b/g/n",
	"Auto 20/40 MHz": "自動 20/40 MHz",
	"Mixed 802.11a and 802.11n": "混和 802.11a/n",
	"Use this section to configure the wireless settings for your D-Link Router. Please note that changes made on this section may also need to be duplicated on your Wireless Client.": "使用此功能表選單為您的 D-Link 路由器的無線網路設定進行組態設定。 請注意在這個功能表選單裡所進行的變更也必須在您的無線網路用戶端上重複操作。 要保障您的隱私權，您可以設定無線網路安全性功能。 無線網路安全性是很重要的，它可以保護資料傳輸安全性。 本路由器支援4種無線安全性：WEP、僅WPA、僅WPA2，與WPA/WPA2(自動偵測)。",
	"This page lets you configure a Wi-Fi Guest Zone. Wi-Fi Guest Zones are Wi-Fi networks that are separate from your normal ones, and use different Wi-Fi Network Names and passwords. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless the Access Local Service option is enabled. Guest Zones are useful to give guests Internet access without allowing them to access your own devices on your network.": "在此頁面可更改訪客區的無線設定。訪客區為獨立的無線區域，與內部網路分隔開以確保網路的隱私與安全，除非將「允許存取區域網路」項目設為啟用，否則無法與內部的網路裝置互通。",
	"Internet Access Only": "啟用區域內路由",
	"Routing Between Zones": "區域內路由",
	"Your changes are being saved. When reconnectiong to this device, please use the new Wi-Fi name and password you created.": "您的設定將被儲存。當重新連線到此裝置時，請使用您所設定的無線網路名稱及密碼來進行連線。",
	"Your changes are being saved.": "您的設定將被儲存。",
	
	// Network
	"Network": "網路",
	"Network Settings": "路由器設定",
	"DHCP Server": "DHCP 伺服器設定",
	"Use this page to configure the local network settings for your router, including the IP address you use to access this configuration interface. Please note that if you change this IP address, you will need to use the new IP to access this interface.": "使用此功能表選單調整您路由器的內部網路設定，並且也可設定內建 DHCP 伺服器以指派 IP 位址到您網路上的電腦。 在此所設定的 IP 位指示您用來使用網頁式管理介面的 IP 位址。 如果您在這個功能表選單變更 IP 位址，您可能需要調整您個人電腦的網路設定以再次使用此網路。",
	"LAN IP Address": "路由器 IP 位址",
	"Device Name": "主機名稱",
	"Local Domain Name": "本機的網域名稱",
	"Enable DNS Relay": "啟用 DNS 中繼 (Relay)",
	"DHCP IP Address Range": "DHCP IP 位址範圍",
	"DHCP Lease Time": "DHCP 租用時間",
	"Always Broadcast": "總是廣播",
	"compatibility for some DHCP Clients": "(僅相容於某些 DHCP 用戶端)",
	"If you changed the IP address of the router you will need to change the IP address in your browser before accessing the configuration website again.": "如果您變更了路由器的 IP 位址，您將需要在使用組態設定網頁之前在瀏覽器裡變更 IP 位址。",
	"The new settings have been saved.": "新的設定已經儲存。",
	"to": "至",
	
	// Advanced Network
	"Advanced Network": "進階網路",
	"Advanced Network settings allow you to configure some of the more advanced features of your router. It is recommended that you only change these settings if you are  familiar with them, or if you are specifically instructed to do so.": "這個選項可讓使用者變更區域網路(LAN)設定，我們不建議從出廠預設值變更這些參數設定。變更這些參數設定可能會影響到您網路的效能。",
	"UPnP": "啟用 UPnP IGD",
	"WAN Port Speed": "廣域網路連接埠速率",
	"IPv4 Multicast Streams": "啟動 IPv4 多點廣播串流",
	"IPv6 Multicast Streams": "啟動 IPv6 多點廣播串流",
	"Auto (10/100/1000 Mbps)": "自動 (10/100/1000 Mbps)",
	
	// SharePort
	"SharePort": "SharePort",
	"DLNA (Digital Living Network Alliance) is the standard for the interoperability of Network Media Devices (NMDs). The user can enjoy multi-media applications (music, pictures and videos) on your network connected PC or media devices. Web File Access allows you to use a web browser to remotely access files stored on an SD card or USB storage drive plugged into the router.": "DLNA (Digital Living Network Alliance) 是 Network Media Devices (NMDs) 的互用性標準。 用戶可在您的網路連線電腦或媒體裝置上享受多媒體應用 (音樂、照片和錄影)。",
	"DLNA Media Server Configuration": "媒體伺服器(DLNA)設定",
	"DLNA Media Server": "媒體伺服器(DLNA)",
	"Web File Access": "啟用 SharePort 網頁存取",
	"HTTP Access Port": "HTTP 存取通訊埠",
	"HTTPS Access Port": "HTTPS 存取通訊埠",
	"Enable Storage Remote Access": "允許遠端存取",
	"Direct Links": "SharePort 存取連結",
	"Local Access": "內部存取",
	"SharePort Web Access": "SharePort 網頁存取",
	
	// SharePort CreateUser
	"\"Create User\" manage access to your storage devices or use the Guest account (guest/guest) to access the Guest Folder. After plugging in an SD card or USB storage drive, the new device will appear in the list with a link to it. You can then use this link to connect the drive and login with a user account.": "設定和管理存取儲存裝置或使用訪客帳戶(guest/guest)來存取訪客資料夾的使用者。路由器插入SD卡或USB儲存裝置後，儲存裝置的名稱和存取連結會顯示在清單內，您可以點選連結來開啟存取網頁。",
	"Remote Access": "遠端存取",
	"Create User": "建立使用者",
	"User Name": "使用者名稱",
	"Access Path": "存取路徑",
	"Permission": "權限",
	"Edit": "編輯",
	"Delete": "刪除",
	"Browse": "瀏覽",
	"OK": "確定",
	"Create User": "新增使用者",
	"Create New User": "建立新使用者",
	"Edit User Profile": "編輯使用者設定檔",
	"Folder": "目錄",
	"Select Folder": "選擇目錄",
	"USB Device Name": "USB 裝置名稱",
	"Number of Device": "裝置數量",
	
	// mydlink
	"Setting and registering your router with mydlink will allow you to use its mydlink cloud services features, including online access and management of your router through the mydlink portal website.": "設定或註冊 mydlink 服務可讓您使用 D-Link 免費提供的雲端服務，透過此路由器註冊後您可透過 mydlink 平台來遠端管理或查看您的路由器。",
	"mydlink Registration": "mydlink 註冊",
	"Sign Up": "註冊",
	"Sign In": "登入",
	"Please enter your e-mail address and mydlink password.": "請輸入您的電子郵件位址及 mydlink 密碼",
	"You must accept the terms and conditions to continue.": "您必須勾選接受 mydlink 服務條款才能繼續註冊程序",
	
	// QoS Engine
	"QoS Engine": "QoS 引擎",
	"QoS prioritizes your network traffic so you can decide what devices should have priority over other devices. For example, you could set a computer that is downloading files to have lower priority than a laptop that is streaming movies to ensure that you can stream movies smoothly without downloads taking up all of your bandwidth.": "您可以利用此項目來設定 QoS 引擎。此功能藉由確保您遊戲流量的優先權高於其他如 FTP 或 Web 服務網路流量的方式來改善您線上遊戲的經驗。 要獲得最佳的效能，請使用自動分類項目來自動為您的應用程式設定優先權。",
	"All Devices": "裝置清單",
	"Drag the device cards above to the Prioity boxes below.": "拖曳卡片至下方欄位以設定其優先權",
	"Highest": "最高",
	"Medium": "一般",
	
	// Firewall
	"Firewall Settings": "防火牆設定",
	"Here, you can set up various firewall features to protect your network from attacks. You can click on the DMZ, IPv4 Rules, and IPv6 Rules buttons to see the settings for that feature.": "在這裡您可以設定不同的防火牆功能，保護您的網路避免遭受攻擊。",
	"Application Level Gateway (ALG) Configuration": "應用程式層級閘道器 (ALG) 設定",
	"Enable SPI IPv4": "啟動 SPI",
	"Enable Anti-spoof Checking": "啟動防止假冒位址封包入侵檢查",
	"IPv6 Simple Security": "IPv6 Simple Security",
	"PPTP": "PPTP",
	"IPSec (VPN)": "IPSec (VPN)",
	"RTSP": "RTSP",
	"SIP": "SIP",
	"IPv4 Rules": "IPv4 規則",
	"IPv6 Rules": "IPv6 規則",
	"Firewall": "防火牆",
	"Enable DMZ Host": "啟用 DMZ",
	"DMZ IP Address": "DMZ IP 位址",
	"Security Check": "安全性",
	
	// Firewall IPv4, IPv6
	"The IPv4 rule section is an advance feature used to deny or allow traffic from passing through the device.": "防火牆設置可用來允許或拒絕流量通過裝置。",
	"The IPv6 rule section is an advance feature used to deny or allow traffic from passing through the device.": "防火牆設置可用來允許或拒絕流量通過裝置。",
	"Add Rules": "新增規則",
	"Name": "名稱",
	"Schedule": "排程",
	"Create New Rule": "建立新的規則",
	"Source IP Address Range": "來源 IP 位址範圍",
	"Destination IP Address Range": "目的 IP 位址範圍",
	"Port Range": "連接埠範圍",
	"Turn IPv4 Filtering OFF": "關閉",
	"Turn IPv4 Filtering ON and ALLOW rules listed": "允許下列清單進行存取",
	"Turn IPv4 Filtering ON and DENY rules listed": "禁止下列清單進行存取",
	"Turn IPv6 Filtering OFF": "關閉",
	"Turn IPv6 Filtering ON and ALLOW rules listed": "允許下列清單進行存取",
	"Turn IPv6 Filtering ON and DENY rules listed": "禁止下列清單進行存取",
	
	// Port Forwarding
	"Port Forwarding is used to open ports in your router and to redirect traffic to those ports to a specific device on your network. This may be needed for specific applications, games, or services. You can enter individual ports (80, 68, 888), port ranges (100-150), or in a mixed format (1020-5000, 689).": "這個選項是用來在您的路由器上開啟多重連接埠，並且重新導向資料流經這些連接埠以連接到您網路上的一台個人電腦。",
	"Local IP": "區域 IP 位址",
	"TCP Port": "TCP 連接埠",
	"UDP Port": "UDP 連接埠",
	
	// Virtual Server
	"The Virtual Server option allows you to define a single public port on your router for redirection to an internal LAN IP Address and Private LAN port if required. This feature is useful for hosting online services such as FTP or Web Servers.": "「虛擬伺服器」選項可讓您在需要的時候於路由器上定義一個單一公開連接埠以供重新導向到一個內部的區域網路 LAN IP 位址以及私人的區域網路連接埠。這個功能在架設線上服務(像是FTP或是網站伺服器)的主機時，非常有用。",
	"Protocol": "通訊協定",
	"External Port": "外部連接埠",
	"Internal Port": "內部連接埠",
	"Protocol Number": "連接埠編號",
	
	// Website Filter
	"The Website Filter option allows you to set up a list of Web sites you would like to allow or deny through your network. To use this feature, you must also select the \"Apply Web Filter\" checkbox in the Access Control section.": "網站篩選功能可讓您建立一個允許/拒絕使用者存取的網站清單。",
	"DENY computers access to ONLY these sites": "禁止電腦存取下列清單中的網站",
	"ALLOW computers access to ONLY these sites": "僅允許電腦存取下列清單中的網站",
	"Website URL/Domain": "網址/網域",
	
	// StaticRouter, StaticRouterIPv6
	"Static Routes": "固定路由表",
	"This page allows you to define custom routes to define how data traffic is moved around your network.": "路由選項可讓您定義到特定目的地的固定路由路徑。",
	"Destination IP": "目的 IP 位址",
	"Netmask": "網路遮罩",
	"Gateway": "閘道器",
	"Matrix": "公制",
	"Interface": "介面",
	"DestNetwork": "目的 IP 位址",
	"PrefixLen": "前置字長度",
	
	// DynamicDNS
   	"Dynamic DNS (DDNS) allows you to use an easy to remember domain name such as www.[YourDomainName].com to reach your router\'s dynamically assigned IP address. This is useful when hosting a web, FTP, or game server, and allows you to reach your server no matter what your IP address has changed to. D-Link offers a free DDNS service that you can use through www.DLinkDDNS.com.": "動態 DNS 功能可讓您以所購買的網域名稱 (www.whateveryournameis.com) 搭配您所被動態賦予的 IP 位址架設伺服器主機 (網頁、FTP、遊戲伺服器等 ...)。 大多數的寬頻網網際網路服務供應商會動態指派 (變動的) IP 位址。 透過 DDNS 服務供應商，您的朋友可以輸入您的主機名稱以連接上您的遊戲伺服器，不論您的 IP 位址是什麼。",
	"Server Address": "伺服器位址",
	"Dynamic DNS": "動態DNS",
	"Enable Dynamic DNS": "開啟動態DNS",
	"Select Server Name": "選擇伺服器名稱",
	"Time Out": "逾時",
	"IPv6 Address": "IPv6 位址",
	"hours": "小時",
	
	// Time
	"Time & Schedule": "時間與排程",
	"Time Confuguration": "日期和時間組態設定",
	"Time": "時間",
	"Automatic Time Confuguration": "自動日期和時間組態設定",
	"Manual Time Confuguration": "手動日期和時間組態設定",
	"Date": "日期",
	"This page allows you to set the router\'s internal system clock. You can set the time manually, or automatically through a time server.": "日期與時間的組態設定選項可讓您設定、更新、與維持在內部系統時鐘上的正確時間。從這個功能表選單，您可以設定您所位於的時區並且設定網路時間通訊協定 (NTP:Network Time) 伺服器。日光節約時間也可設定為當需要時可調整時間。",
	"System Time": "時間",
	"Time Zone": "時區",
	"Enable Daylight Saving": "啟用日光節約時間",
	"Update Time Using an NTP Serevr": "透過 NTP 伺服器更新時間",
	"Year/ Month/ Day": "(年/月/日)",
	"Hour/ Minute": "(小時/分鐘)",
	"Day": "天",
	"Hour": "時",
	"Min": "分",
	"Sec": "秒",
	
	// Schedule
	"The Schedule configuration option is used to manage schedule rules for various firewall and parental control features.": "排程設定選項是用來管理\"WAN\"、\"無線網路\"、\"通訊埠轉發\"及\"虛擬伺服器\"的排程規則。",
	"Monday": "星期一",
	"Tuesday": "星期二",
	"Wednesday": "星期三",
	"Thursday": "星期四",
	"Friday": "星期五",
	"Saturday": "星期六",
	"Sunday": "星期日",
	"All Day": "整天",
	"All Week": "整週",
	"Always": "一直開啟",
	
	// System Log
	"System Log": "系統日誌",
	"SysLog Settings": "系統日誌設定",
	"This page allows you to enable logging of system events to a SysLog server, or to e-mail the log to you according to a schedule or when the log is full.": "日誌記錄可顯示發生在路由器上的活動。",
	"SysLog Server IP Address": "系統日誌伺服器 IP 位址",
	"Enable Logging to Syslog Server": "啟用紀錄功能到系統日誌伺服器",
	"E-mail Settings": "電子郵件設定",
	"E-mail Log When Full or On Schedule": "記錄檔滿了或記錄檔到期請用電子郵件將記錄檔寄出",
	"Enable E-mail Notification": "啟用電子郵件通知",
	"From E-mail Address": "從電子郵件位址",
	"To E-mail Address": "收信人電子郵件位址",
	"SMTP Server Address": "SMTP 伺服器位址",
	"SMTP Server Port": "SMTP 伺服器通訊埠",
	"Enable Authentication": "啟用驗證",
	"Account Name": "帳號名稱",
	"On Log Full": "紀錄已滿",
	"On Schedule": "排程",
	
	// System
	"System": "系統",
	"Save Configuration": "儲存設定",
	"Restore Configuration From File": "從文件中恢復設置",
	"Restore Factory Default": "復原成出廠預設值",
	"Reboot": "重新啟動",
	"This page lets you save your router\'s current settings to a file, restore your settings from a file, restore your router to factory default settings, or reboot the device. Please note that restoring the settings to the factory defaults will erase all settings, including any rules you have created.": "一旦組態設定好這台路由器，您可以儲存此組態設定檔案到您的硬碟上。 您也可以選擇載入組態設定檔，或復原回存出廠預設設定。",
	"Save Settings To Local Hard Drive": "儲存到本機硬碟",
	"Load Settings From Local Hard Drive": "從本機硬碟載入設定",
	"Restore To Factory Default Settings": "復原到出廠預設值設定",
	"Reboot The Device": "重新啟動此裝置",
	"Cancel": "取消",
	"Are you sure you want to restore configuration file?": "是否要回復設定？",
	"Do not close the page or power off the service until the restore configuration file is complete!": "回復中，請勿關閉此頁面或是電源。",
	"Restore configuration file failed!": "回復失敗！",
	"Restore configuration file success!": "回復成功！",
	"Are you sure you want to reset the device?": "是否要重新啟動裝置？",
	"Rebooting": "重新啟動中",
	"Reboot success!": "裝置已重新啟動完畢！",
	"Are you sure you want to reset the device to its factory default settings? This will cause current settings to be lost.": "是否要回復到原廠設定值？這將會消除目前的設定。",
	"Restore to factory default success!": "裝置已回復到原廠預設值！",
	"Select File": "選擇檔案",
	"Restore": "回復",
	"Restore Factory Default": "回復到原廠預設值",
	
	// Admin
	"Admin": "管理員",
	"Admin Password": "管理員密碼",
	"Administration": "管理",
	"Use HTTPS": "使用 HTTPS",
	"The admin has read/write access and can change passwords, while the user has read-only access. By default there is no password configured. It is highly recommended that you create a password to keep your router secure.": "管理員具有讀/寫權限並且可變更密碼。預設並無設定密碼，強烈建議您建立密碼以保持路由器的安全。",
	"Enable Graphical Authentication (CAPTCHA)": "允許圖形化驗證",
	"Enable HTTPS Server": "啟用 HTTPS 伺服器",
	"Enable Remote Management": "啟用遠端管理",
	"Remote Admin Port": "遠端管理員連接埠",
	"Remote Admin Inbound Filter": "遠端管理連入篩選器",
	
	// Update Firmware
	"Upgrade Firmware": "韌體更新",
	"This page shows you your current firmware version and language pack, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below. If you are using a language pack, we recommend that you also get the latest version of the language pack when upgrading the firmware to ensure that any changes in the interface are shown correctly.": "這裡會顯示您目前的韌體與語言套件的版本，並允許您檢查並下載升級檔案。",
	"Current Firmware Version": "目前的韌體版本",
	"Current Firmware Date": "目前韌體日期",
	"Current Language Pack": "語言套件",
	"Download New Firmware": "新韌體下載",
	"Upgrade Firmware": "韌體更新",
	"Add a Language Pack": "更新語言套件",
	"Upload": "上傳",
	"Upgrade": "韌體更新",
	"Upgrading": "韌體更新中",
	"Do you want to upgrade Firmware?": "是否要更新韌體？",
	"Do not power off the device until the Firmware Upgrade is complete!": "更新中，請勿將裝置的電源關閉。",
	"Firmware Uploading": "檔案上傳中",
	"Firmware Upgrade failed!": "更新韌體失敗！",
	"Firmware Upgrade success!": "更新韌體完成！",
	"Firmware Imformation": "韌體資訊",
	"New Firmware Version": "新韌體版本",
	"New Firmware Date": "新韌體日期",
	"Check for New Firmware": "檢查新韌體",
	"Language Pack Imformation": "語言套件資訊",
	"Current Language Pack": "目前的語言套件",
	"Remove": "移除",
	"Upgrade Manually": "手動更新",
	"Add a Language Pack": "新增語言套件",
	"Checking": "檢查中",
	"Retry": "重試",
	"This firmware is the latest version.": "目前的韌體為最新版本。",
	"Downloading": "下載中",
	"Please do not close the browser while the firmware is being downloaded!": "下載韌體中，請勿關閉此頁面！",
	
	// Statistic
	"Statistics": "統計",
	"This page gives you various statistics about data transmitted and received by your router through the Internet, on your wired network (LAN), and through your wireless networks.": "流量統計會顯示經由此裝置的接收與傳送封包。",
	"Clear": "清除",
	"Information: Your browser is not support HTML5, please upgrade your browser.": "資訊：您的瀏覽器不支援 HTML5，請更新您的瀏覽器。",
	"Sent (Tx)": "傳送",
	"Received (Rx)": "接收",
	"Total Packets": "總計封包數",
	"Total Byte(s)": "總計 Byte",
	"Total Kbit(s)": "總計 KByte",
	"Kbits/sec": "傳輸速率(kbps)",
	"Session": "連接數",

	//DAP1320B
	//general
	"Extended Wi-Fi" : "延伸的無線網路",
	"SCAN": "掃描",
	"Uplink Router": "連線路由器",
	"Wireless Mode": "無線網路模式",
	"Scanning":"掃描中",
	"Connect to another uplink router":"連線至其他路由器",
	"Select":"選擇",
	"Repeater":"中繼",
	"Password Length":"金鑰長度",
	"Authentication":"證明",
	"DNS Server":"DNS伺服器",
	"Network Settings": "網路設定",
	"Network Status":"網路狀態",
	"Connection Up Time":"裝置連線時間",
	"Subnet Prefix Length":"子網路前置碼(Subnet Prefix Length)",
	"The device is not connected to an uplink router, click &quot;Next&quot; to find available Wi-Fi networks.":"此裝置尚未與任何路由器建立連線。按&quot;下一步&quot;來搜尋可使用的Wi-Fi網路。",
	"A password is required to join":"如需加入請輸入密碼",
	//page
	"Use this section to configure the Wi-Fi Network you would like your DAP-1320b to connect to. Use Site Survey to scan available Wi-Fi networks and select the Wi-Fi Network you would like your DAP-1320b to connect to. Enter the Password of the Wi-Fi Network you selected and click Save.": "請在此介面設定您希望DAP-1320b建立連線的Wi-Fi網路。使用掃描功能將可以搜尋可讓DAP-1320b建立連線的Wi-Fi網路。選取Wi-Fi網路後請輸入該網路的無線金鑰，然後再按下儲存。",
	"Use this section to configure the wireless settings for your D-Link Extender. Please note that changes made on this section may also need to be duplicated on your Wireless Client.":"請在此介面設定您D-Link無線基地台的無線參數。注意: 您於此所做的變更皆有可能需要設定於您的無線使用端。",
	"Use this section to configure the internal network settings of your Extender. Device Name allows you to configure this device more easily when your network using TCP/IP protocol. You can enter the device name of the Extender into your web browser to access the instead of IP address for configuration. Recommend to change the device name if there're more than one D-Link devices within the subnet. ":"使用這個功能表選單以組態設定您無線網路基地台 AP 的內部網路設定。 當您的網路使用 TCP/IP 通信協定時，裝置名稱 (NetBIOS 名稱) 可讓您更輕鬆地組態設定這台裝置。您可以輸入這台無線網路基地台的裝置名稱到您的網頁瀏覽器用以替代 IP 位址以進行組態設定。如果在這個子網域上有超過一台以上的 D-Link 裝置，建議您變更此裝置名稱。",
	"The admin password is used to log in to this configuration interface. It is highly recommended that you create a password to keep your router secure.":"管理員密碼使用於登入管理介面。建議您設定一個密碼來確保網路的安全。",
	"This page shows you your current firmware version, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below.":"此介面顯示了目前使用中的韌體版本和語言包並且讓您可於線上檢查新版韌體。下載韌體後，您將可以使用以下的按紐來更新。如果您有使用語言包，建議您也取得最新的語言包版本來確保所有參數和選項顯示正確。",



	"This page gives you various statistics about data transmitted and received by your AP through the internet, and through your wireless networks.":"此頁面提供您一些基地台已接收或已傳送的數據。",
	//Wizard
	//wizard title
	"WI-FI CONNECTION SETUP WIZARD":"無線網路連線設定精靈",
	"SELECT CONFIGURATION METHOD":"選擇無線網路的設定方式",
	"SELECT WI-FI NETWORK":"選擇無線網路",
	"ENTER WIFI PASSWORD":"輸入無線網路密碼",
	"PLEASE ENTER THE SETTINGS FOR THE EXTENDED NETWORK":"請輸入延伸網路的設定",
	"SETUP COMPLETE":"設定完成",
	"DEVICE NAME SETUP":"裝置名稱設定",
	
	
	"Wi-Fi Network Name":"無線網路名稱",
	"Extended Wi-Fi Network Name":"延伸網路名稱",
	"Extended Wi-Fi Password":"延伸的無線網路 密碼",
	"This wizard is designed to assist you in your Wi-Fi network setup. It will guide you through step-by step instructions on how to set up your Wi-Fi network and how to make it secure.":"設定精靈將幫助您完成無線網路相關設定。它將一步一步的引導您操作如何正確的設定無線網路和安全性設定。",
	"Select this option if your wireless device supports WPS(Wi-Fi Protected Setup)": "若您的無線裝置支援WPS(Wi-Fi Protected Setup)請選擇此項目",
	"Select this option if you want to setup your network manually":"如果您要手動設定網路的話，請選擇這個項目。",
	"Please enter Wi-Fi Password to establish wireless connection" : "請輸入無線網路密碼以建立無線連結",
	"Between 8 and 63 characters": "8~63個英文或數字",
	"Give Your Extended Wi-Fi Network(SSID) a Name":"為您的Wi-Fi中繼網路建立一個名稱",
	"Give Your Extended Wi-Fi Network a Password":"為您的Wi-Fi中繼網路建立一個密碼",
	"Using up to 32 characters":"最多32個英文或數字",
	"Use the same Wi-Fi Network Name for the Extended Network.":"延伸網路請用相同的無線網路名稱。",
	"Please Take a note of the following summary of your Wi-Fi Security setting for furture reference":"請記下以下無線安全設定，已供未來無線設備連結時參考。",
	//network setting ipv6
	"IPv4 Device Management Interface":"IPv4裝置管理介面",
	"Choose a IPv4 provisioning mechanism to be used by the device.":"請選擇基地台將使用的IPv4配置機制",
	"IPv6 Device Management Interface":"IPv6裝置管理介面",
	"Choose a IPv6 provisioning mechanism to be used by the device.":"請選擇基地台將使用的IPv6配置機制",
	"Obtain a DNS server address automatically or enter a specific DNS server address.":"自動取得一個DNS伺服器位址或輸入一個特定的DNS伺服器位址。",
	"Autoconfiguration (SLAAC/DHCPv6)":"自動設定 (SLAAC/DHCPv6)",
	"Obtain IPV6 Servers automatically.":"自動取得IPv6 DNS伺服器",
	"Use the following IPv6 DNS Servers.":"使用下列IPv6 DNS伺服器",
	"My IPv6 Connection is":"我的IPv6連線為",
	"My LAN Connection is":"我的區域網路連線是",
	"The LAN IPv6 Link-Local Address is the IPv6 Address that you use to access the Web-based management interface.":"LAN IPv6 Link-Local位址是您用來連線到網路管理界面時所使用的IPv6位址",
	"LAN IPv6 Link-Local Address":"區域網路IPv6 區域間連線位址",
	"Enter the IPv6 address information that you would like to use to access the Web-based management interface.":"輸入您想用來存取網頁管理介面的IPv6位址資訊。"
	
	}